def main():
    K = int(input())
    S = input()[:-1]
    T = input()[:-1]
    #print(K)
    #print(S)
    #print(T)
    #print(S[0:4])
    #print(S[4])
    #print(T[0:4])
    #print(T[4])
    #print(S[0:4].count('1'))
    #print(S[0:4].count('2'))
    #print(S[0:4].count('3'))
    #print(S[0:4].count('4'))
    #print(S[0:4].count('5'))
    #print(S[0:4].count('6'))
    #print(S[0:4].count('7'))
    #print(S[0:4].count('8'))
    #print(S[0:4].count('9'))
    #print(T[0:4].count('1'))
    #print(T[0:4].count('2'))
    #print(T[0:4].count('3'))
    #print(T[0:4].count('4'))
    #print(T[0:4].count('5'))
    #print(T[0:4].count('6'))
    #print(T[0:4].count('7'))
    #print(T[0:4].count('8'))
    #print(T[0:4].count('9'))
    #print(S[0:4].count('1') + T[0:4].count('1'))
    #print(S[0:4].count('2') + T[0:4].count('2'))
    #print(S[0:4].count('3') + T[0:4].count('3'))
    #print(S[0:4].count('4') + T[0:4].count('4'))
    #print(S[0:4].count('5') + T[0:4].count('5'))
    #print(S[0:4].count('6') + T[0:4].count('6'))
    #print(S[0:4].count('7') + T[0:4].count('7'))
    #print(S[0:4].count('8') + T[0:4].count('8'))
    #print

if __name__ == '__main__':
    main()