def main():
    K = int(input())
    S = input()
    T = input()
    S = S[:-1]
    T = T[:-1]
    SD = [0]*10
    TD = [0]*10
    for i in range(4):
        SD[int(S[i])] += 1
        TD[int(T[i])] += 1
    #print(SD)
    #print(TD)
    #print(S)
    #print(T)
    #print(SD)
    #print(TD)
    #print(S)
    #print(T)
    #print(SD)
    #print(TD)
    #print(S)
    #print(T)
    #print(SD)
    #print(TD)
    #print(S)
    #print(T)
    #print(SD)
    #print(TD)
    #print(S)
    #print(T)
    #print(SD)
    #print(TD)
    #print(S)
    #print(T)
    #print(SD)
    #print(TD)
    #print(S)
    #print(T)
    #print(SD)
    #print(TD)
    #print(S)
    #print(T)
    #print(SD)
    #print(TD)
    #print(S)
    #print(T)
    #print(SD)
    #print(TD)
    #print(S)
    #print(T)
    #print(SD)
    #print(TD)
    #print(S)
    #print(T)
    #print(SD)
    #print(TD)
    #print(S)
    #print(T)
    #print(SD)
    #print(TD)
    #print(S)
    #print(T)
    #print(SD)
    #print(TD)
    #print(S)
    #print(T)
    #print(SD)
    #print(TD)
    #print(S)
    #print(T)
    #print(SD)
    #print(TD)
    #print(S)
    #print(T)
    #print(SD)
    #print(TD)
    #print(S)
    #print(T)
    #print(SD)
    #print(TD)
    #print(S)
    #print(T)
    #print(SD)
    #print(TD)
    #print(S)
    #print(T)
    #print(SD)

if __name__ == '__main__':
    main()