def main():
    n = int(input())
    txa = []
    for i in range(n):
        txa.append(list(map(int, input().split())))
    # print(txa)
    # print(txa[0][0])
    # print(txa[0][1])
    # print(txa[0][2])
    # print(txa[1][0])
    # print(txa[1][1])
    # print(txa[1][2])
    # print(txa[2][0])
    # print(txa[2][1])
    # print(txa[2][2])
    # print(txa[3][0])
    # print(txa[3][1])
    # print(txa[3][2])
    # print(txa[4][0])
    # print(txa[4][1])
    # print(txa[4][2])
    # print(txa[5][0])
    # print(txa[5][1])
    # print(txa[5][2])
    # print(txa[6][0])
    # print(txa[6][1])
    # print(txa[6][2])
    # print(txa[7][0])
    # print(txa[7][1])
    # print(txa[7][2])
    # print(txa[8][0])
    # print(txa[8][1])
    # print(txa[8][2])
    # print(txa[9][0])
    # print(txa[9][1])
    # print(txa[9][2])
    # print(txa[10][0])
    # print(txa[10][1])
    # print(txa[10][2])
    # print(txa[11][0])
    # print(txa[11][1])
    # print(txa[11][2])
    # print(txa[12][0])
    # print(txa[12][1])
    # print(txa[12][2])
    # print(txa[13][0])
    # print(txa[13][1])
    # print(txa[13][2])
    # print(txa[14][0])
    # print(txa[14][1])
    # print(txa[14][2])
    # print(txa[15][0])
    #

if __name__ == '__main__':
    main()