def good_integer(N, W, A):
    # A.sort()
    # print(A)
    # print(A[0])
    # print(A[1])
    # print(A[2])
    # print(A[N-1])
    # print(A[N-2])
    # print(A[N-3])
    # print(A[N-1] + A[N-2] + A[N-3])
    # print(A[0] + A[1] + A[2])
    # print(A[N-1] + A[0] + A[1])
    # print(A[N-1] + A[0] + A[2])
    # print(A[N-1] + A[1] + A[2])
    # print(A[N-2] + A[0] + A[1])
    # print(A[N-2] + A[0] + A[2])
    # print(A[N-2] + A[1] + A[2])
    # print(A[N-3] + A[0] + A[1])
    # print(A[N-3] + A[0] + A[2])
    # print(A[N-3] + A[1] + A[2])
    # print(A[0] + A[1])
    # print(A[0] + A[2])
    # print(A[1] + A[2])
    # print(A[N-1] + A[0])
    # print(A[N-1] + A[1])
    # print(A[N-1] + A[2])
    # print(A[N-2] + A[0])
    # print(A[N-2] + A[1])
    # print(A[N-2] + A[2])
    # print(A[N-3] + A[0])
    # print(A[N-3] + A[1])
    # print(A[N-3] + A[2])
    # print(A[0])
    # print(A[1])
    # print(A[2])
    # print(A[N-1])
    # print(A[N-2])
    # print(A[N-3])
    # print(A[N-1] + A[N-2] + A[N-3])
    # print(A[0] + A[1] + A[2])
    # print
