def main():
    # Take input from stdin
    input_str = input()
    input_arr = input_str.split(" ")
    H = int(input_arr[0])
    W = int(input_arr[1])
    #print("H = ", H, " W = ", W)
    #print("input_str = ", input_str)
    #print("input_arr = ", input_arr)
    #print("input_arr[0] = ", input_arr[0])
    #print("input_arr[1] = ", input_arr[1])
    #print("input_arr[2] = ", input_arr[2])
    #print("input_arr[3] = ", input_arr[3])
    #print("input_arr[4] = ", input_arr[4])
    #print("input_arr[5] = ", input_arr[5])
    #print("input_arr[6] = ", input_arr[6])
    #print("input_arr[7] = ", input_arr[7])
    #print("input_arr[8] = ", input_arr[8])
    #print("input_arr[9] = ", input_arr[9])
    #print("input_arr[10] = ", input_arr[10])
    #print("input_arr[11] = ", input_arr[11])
    #print("input_arr[12] = ", input_arr[12])
    #print("input_arr[13] = ", input_arr[13])
    #print("input_arr[14] = ", input_arr[14])
    #print("input_arr[15] = ", input_arr[15])
    #print("input_arr[16] = ", input_arr[16])
    #print("input_arr[17] = ", input_arr[17])
    #print("input_arr[18] = ", input_arr[18])
    #print("input_arr[19] = ", input_arr[19])
    #print("input_arr[20] = ", input_arr[20])
    #print("input_arr[21] = ", input_arr[21])
    #print("input_arr[22] = ", input_arr[22])
    #print("input_arr[23] = ", input_arr[23])
    #print("input_arr[24] = ", input_arr[24])
    #print("input_arr[25] = ", input_arr[25])
    #print("input

if __name__ == '__main__':
    main()