def main():
    N, M = map(int, input().split())
    #print(N, M)
    #print(type(N), type(M))
    #print((N, M))
    #print(type((N, M)))
    #print(type((N, M)[0]))
    #print(type((N, M)[1]))
    #print(type((N, M)[0]) is int)
    #print(type((N, M)[1]) is int)
    #print(type((N, M)[0]) is str)
    #print(type((N, M)[1]) is str)
    #print(type((N, M)[0]) is float)
    #print(type((N, M)[1]) is float)
    #print(type((N, M)[0]) is bool)
    #print(type((N, M)[1]) is bool)
    #print(type((N, M)[0]) is list)
    #print(type((N, M)[1]) is list)
    #print(type((N, M)[0]) is tuple)
    #print(type((N, M)[1]) is tuple)
    #print(type((N, M)[0]) is set)
    #print(type((N, M)[1]) is set)
    #print(type((N, M)[0]) is dict)
    #print(type((N, M)[1]) is dict)
    #print(type((N, M)[0]) is complex)
    #print(type((N, M)[1]) is complex)
    #print(type((N, M)[0]) is bytes)
    #print(type((N, M)[1]) is bytes)
    #print(type((N, M)[0]) is bytearray)
    #print(type((N, M)[1]) is bytearray)
    #print(type((N, M)[0]) is memoryview)
    #print(type((N, M)[1]) is memoryview)
    #print(type((N, M)[0]) is None)
    #print(type((N, M)[1]) is None)
    #print(type((N, M)[0]) is Ellipsis)
    #print(type((N, M)[1]) is Ellipsis)
    #print(type((N, M)[0]) is NotImplemented)
    #print(type((N, M)[1]) is NotImplemented)
    #print(type((N,

if __name__ == '__main__':
    main()