def main():
    N, C = map(int, input().split())
    ABC = [list(map(int, input().split())) for _ in range(N)]
    ABC.sort(key=lambda x: x[0])
    #print(ABC)
    #print(C)
    #print(N)
    #print(ABC)
    #print(ABC[0])
    #print(ABC[1])
    #print(ABC[2])
    #print(ABC[3])
    #print(ABC[4])
    #print(ABC[0][0])
    #print(ABC[0][1])
    #print(ABC[0][2])
    #print(ABC[1][0])
    #print(ABC[1][1])
    #print(ABC[1][2])
    #print(ABC[2][0])
    #print(ABC[2][1])
    #print(ABC[2][2])
    #print(ABC[3][0])
    #print(ABC[3][1])
    #print(ABC[3][2])
    #print(ABC[4][0])
    #print(ABC[4][1])
    #print(ABC[4][2])
    #print(ABC[0][0] < ABC[1][0])
    #print(ABC[0][0] < ABC[2][0])
    #print(ABC[0][0] < ABC[3][0])
    #print(ABC[0][0] < ABC[4][0])
    #print(ABC[1][0] < ABC[2][0])
    #print(ABC[1][0] < ABC[3][0])
    #print(ABC[1][0] < ABC[4][0])
    #print(ABC[2][0] < ABC[3][0])
    #print(ABC[2][0] < ABC[4][0])
    #print(ABC[3][0] < ABC[4][0])
    #print(ABC[0][0] < ABC[1][0] < ABC[2][0] < ABC[3][0] < ABC[4][0])
    #print(ABC[0][1] < ABC[1][1] < ABC[2][1] < ABC[3][1] < ABC[4][1
