def main():
    n,q = map(int, input().split())
    ab = [[0]*2 for i in range(n-1)]
    for i in range(n-1):
        ab[i][0],ab[i][1] = map(int, input().split())
    px = [[0]*2 for i in range(q)]
    for i in range(q):
        px[i][0],px[i][1] = map(int, input().split())
    #print(px)
    #print(ab)
    #print(n,q)
    #print(ab[0][0])
    #print(ab[0][1])
    #print(ab[1][0])
    #print(ab[1][1])
    #print(ab[2][0])
    #print(ab[2][1])
    #print(px[0][0])
    #print(px[0][1])
    #print(px[1][0])
    #print(px[1][1])
    #print(px[2][0])
    #print(px[2][1])
    #print(px[3][0])
    #print(px[3][1])
    #print(px[4][0])
    #print(px[4][1])
    #print(px[5][0])
    #print(px[5][1])
    #print(px[6][0])
    #print(px[6][1])
    #print(px[7][0])
    #print(px[7][1])
    #print(px[8][0])
    #print(px[8][1])
    #print(px[9][0])
    #print(px[9][1])
    #print(px[10][0])
    #print(px[10][1])
    #print(px[11][0])
    #print(px[11][1])
    #print(px[12][0])
    #print(px[12][1])
    #print(px[13][0])
    #print(px[13][1])
    #print(px[14][0])
    #print(px[14][1])
    #print(px[15][0])
    #print(px[15][1])
    #print(px[16][0])
    #print(px[16][1])
    #print(px[17][0])
    #print(px[17][1])
    #print(px[18][0])
    #

if __name__ == '__main__':
    main()