def main():
    n = int(input())
    edges = []
    for i in range(n-1):
        edge = list(map(int, input().split()))
        edges.append(edge)
    edges.sort(key=lambda x:x[2])
    # print(edges)
    # print(edges[0][2])
    # print(edges[1][2])
    # print(edges[n-2][2])
    # print(edges[n-3][2])
    # print(edges[n-4][2])
    # print(edges[n-5][2])
    # print(edges[n-6][2])
    # print(edges[n-7][2])
    # print(edges[n-8][2])
    # print(edges[n-9][2])
    # print(edges[n-10][2])
    # print(edges[n-11][2])
    # print(edges[n-12][2])
    # print(edges[n-13][2])
    # print(edges[n-14][2])
    # print(edges[n-15][2])
    # print(edges[n-16][2])
    # print(edges[n-17][2])
    # print(edges[n-18][2])
    # print(edges[n-19][2])
    # print(edges[n-20][2])
    # print(edges[n-21][2])
    # print(edges[n-22][2])
    # print(edges[n-23][2])
    # print(edges[n-24][2])
    # print(edges[n-25][2])
    # print(edges[n-26][2])
    # print(edges[n-27][2])
    # print(edges[n-28][2])
    # print(edges[n-29][2])
    # print(edges[n-30][2])
    # print(edges[n-31][2])
    # print(edges[n-32][2])
    # print(edges[n-33][2])
    # print(edges[n-34][2])
    # print(edges[n-35][2])
    # print(edges[n-36][2])
    # print(edges[n-37][2])
    # print(edges[n-38][2])
    # print(edges[n-39][2])
    # print(edges[n-40][2])
    # print(edges[n-41][2])
    # print(edges[n-42][2])
    # print(edges[n-43][2])
    # print(edges[n-44][2])

if __name__ == '__main__':
    main()