def main():
    N, Q = map(int, input().split())
    A = [0] * Q
    B = [0] * Q
    T = [0] * Q
    for i in range(Q):
        T[i], A[i], B[i] = map(int, input().split())
    #print("N", N)
    #print("Q", Q)
    #print("A", A)
    #print("B", B)
    #print("T", T)
    #print("A[0]", A[0])
    #print("B[0]", B[0])
    #print("T[0]", T[0])
    #print("A[1]", A[1])
    #print("B[1]", B[1])
    #print("T[1]", T[1])
    #print("A[2]", A[2])
    #print("B[2]", B[2])
    #print("T[2]", T[2])
    #print("A[3]", A[3])
    #print("B[3]", B[3])
    #print("T[3]", T[3])
    #print("A[4]", A[4])
    #print("B[4]", B[4])
    #print("T[4]", T[4])
    #print("A[5]", A[5])
    #print("B[5]", B[5])
    #print("T[5]", T[5])
    #print("A[6]", A[6])
    #print("B[6]", B[6])
    #print("T[6]", T[6])
    #print("A[7]", A[7])
    #print("B[7]", B[7])
    #print("T[7]", T[7])
    #print("A[8]", A[8])
    #print("B[8]", B[8])
    #print("T[8]", T[8])
    #print("A[9]", A[9])
    #print("B[9]", B[9])
    #print("T[9]", T[9])
    #print("A[10]", A[10])
    #print("B[10]", B[10])
    #print("T[10]", T[

if __name__ == '__main__':
    main()