def main():
    N = int(input())
    MOD = 10**9+7
    # A, C, G, T
    # AGC, ACG, GAC, AGGC, AAGC, AGAC, AGTC, AGCC, AGCT, AGCG
    # AGC, ACG, GAC, AGGC, AAGC, AGAC, AGTC, AGCC, AGCT, AGCG
    # AGC, ACG, GAC, AGGC, AAGC, AGAC, AGTC, AGCC, AGCT, AGCG
    # AGC, ACG, GAC, AGGC, AAGC, AGAC, AGTC, AGCC, AGCT, AGCG
    # AGC, ACG, GAC, AGGC, AAGC, AGAC, AGTC, AGCC, AGCT, AGCG
    # AGC, ACG, GAC, AGGC, AAGC, AGAC, AGTC, AGCC, AGCT, AGCG
    # AGC, ACG, GAC, AGGC, AAGC, AGAC, AGTC, AGCC, AGCT, AGCG
    # AGC, ACG, GAC, AGGC, AAGC, AGAC, AGTC, AGCC, AGCT, AGCG
    # AGC, ACG, GAC, AGGC, AAGC, AGAC, AGTC, AGCC, AGCT, AGCG
    # AGC, ACG, GAC, AGGC, AAGC, AGAC, AGTC, AGCC, AGCT, AGCG
    # AGC, ACG, GAC, AGGC, AAGC, AGAC, AGTC, AGCC, AGCT, AGCG
    # AGC, ACG, GAC, AGGC, AAGC, AGAC, AGTC, AGCC, AGCT, AGCG
    # AGC, ACG, GAC, AGGC, AAGC, AGAC, AGTC, AGCC, AGCT, AGCG
    # AGC, ACG, GAC, AGGC, AAGC, AGAC, AGTC, AGCC, AGCT, AGCG
    # AGC, ACG, GAC

if __name__ == '__main__':
    main()