def solve(n, m, q, w, v, x, l, r):
    #print(n, m, q, w, v, x, l, r)
    #print(w)
    #print(v)
    #print(x)
    #print(l)
    #print(r)
    #print('-----------------------------')
    #print(n, m, q, w, v, x, l, r)
    #print(w)
    #print(v)
    #print(x)
    #print(l)
    #print(r)
    #print('-----------------------------')
    #print(n, m, q, w, v, x, l, r)
    #print(w)
    #print(v)
    #print(x)
    #print(l)
    #print(r)
    #print('-----------------------------')
    #print(n, m, q, w, v, x, l, r)
    #print(w)
    #print(v)
    #print(x)
    #print(l)
    #print(r)
    #print('-----------------------------')
    #print(n, m, q, w, v, x, l, r)
    #print(w)
    #print(v)
    #print(x)
    #print(l)
    #print(r)
    #print('-----------------------------')
    #print(n, m, q, w, v, x, l, r)
    #print(w)
    #print(v)
    #print(x)
    #print(l)
    #print(r)
    #print('-----------------------------')
    #print(n, m, q, w, v, x, l, r)
    #print(w)
    #print(v)
    #print(x)
    #print(l)
    #print(r)
    #print('-----------------------------')
    #print(n, m, q, w, v, x, l, r)
    #print(w)
    #print(v)
    #print(x)
    #print(l)
    #print(r)
    #print('-----------------------------')
    #print(n, m, q, w, v, x, l, r)
    #print(w)
    #print(v)
    #print(x)
    #print(l)
    #print(r)
    #print('-----------------------------')
    #print(n, m, q, w, v, x, l, r)
    #print(w)

if __name__ == '__main__':
    solve()