def main():
    N,M = map(int, input().split())
    #print(N,M)
    A = [[0 for i in range(M)] for j in range(N)]
    #print(A)
    for i in range(N):
        A[i] = list(map(int, input().split()))
        #print(A[i])
    #print(A)
    #print(A[0][0])
    #print(A[0][1])
    #print(A[0][2])
    #print(A[0][3])
    #print(A[1][0])
    #print(A[1][1])
    #print(A[1][2])
    #print(A[1][3])
    #print(A[2][0])
    #print(A[2][1])
    #print(A[2][2])
    #print(A[2][3])
    #print(A[3][0])
    #print(A[3][1])
    #print(A[3][2])
    #print(A[3][3])
    #print(A[4][0])
    #print(A[4][1])
    #print(A[4][2])
    #print(A[4][3])
    #print(A[5][0])
    #print(A[5][1])
    #print(A[5][2])
    #print(A[5][3])
    #print(A[6][0])
    #print(A[6][1])
    #print(A[6][2])
    #print(A[6][3])
    #print(A[7][0])
    #print(A[7][1])
    #print(A[7][2])
    #print(A[7][3])
    #print(A[8][0])
    #print(A[8][1])
    #print(A[8][2])
    #print(A[8][3])
    #print(A[9][0])
    #print(A[9][1])
    #print(A[9][2])
    #print(A[9][3])
    #print(A[10][0])
    #print(A[10][1])
    #print(A[10][2])
    #print(A[10][3])
    #print(A[11][0])
    #print(A[11][1])
    #print(A[11][2])
    #print(A[

if __name__ == '__main__':
    main()