def main():
    N, X, Y = map(int, input().split())
    #print(N, X, Y)
    #print("N={}, X={}, Y={}".format(N, X, Y))
    #print("N="+str(N)+", X="+str(X)+", Y="+str(Y))
    #print("N={}, X={}, Y={}".format(N, X, Y))
    #print("N="+str(N)+", X="+str(X)+", Y="+str(Y))
    #print("N={}, X={}, Y={}".format(N, X, Y))
    #print("N="+str(N)+", X="+str(X)+", Y="+str(Y))
    #print("N={}, X={}, Y={}".format(N, X, Y))
    #print("N="+str(N)+", X="+str(X)+", Y="+str(Y))
    #print("N={}, X={}, Y={}".format(N, X, Y))
    #print("N="+str(N)+", X="+str(X)+", Y="+str(Y))
    #print("N={}, X={}, Y={}".format(N, X, Y))
    #print("N="+str(N)+", X="+str(X)+", Y="+str(Y))
    #print("N={}, X={}, Y={}".format(N, X, Y))
    #print("N="+str(N)+", X="+str(X)+", Y="+str(Y))
    #print("N={}, X={}, Y={}".format(N, X, Y))
    #print("N="+str(N)+", X="+str(X)+", Y="+str(Y))
    #print("N={}, X={}, Y={}".format(N, X, Y))
    #print("N="+str(N)+", X="+str(X)+", Y="+str(Y))
    #print("N={}, X={}, Y={}".format(N, X, Y))
    #print("N="+str(N)+", X="+str(X)+", Y="+str(Y))
    #print("N={}, X={}, Y={}".format(N, X, Y))
    #print("N="+str(N)+", X="+str(X)+", Y="+str(Y))
    #print("N={}, X={}, Y={}".format(N, X, Y))
    #print("N="+str(N)+", X="+str(X)+", Y="+str(Y))
    #print("N={}, X
