def main():
    N, K = map(int, input().split())
    R, S, P = map(int, input().split())
    T = input()
    #print(N, K, R, S, P, T)
    #N, K, R, S, P = 5, 2, 8, 7, 6
    #T = 'rsrpr'
    #N, K, R, S, P = 7, 1, 100, 10, 1
    #T = 'ssssppr'
    #N, K, R, S, P = 30, 5, 325, 234, 123
    #T = 'rspsspspsrpspsppprpsprpspsppprpr'
    #print(N, K, R, S, P, T)
    #print(len(T))
    #print(T[0])
    #print(T[1])
    #print(T[2])
    #print(T[3])
    #print(T[4])
    #print(T[5])
    #print(T[6])
    #print(T[7])
    #print(T[8])
    #print(T[9])
    #print(T[10])
    #print(T[11])
    #print(T[12])
    #print(T[13])
    #print(T[14])
    #print(T[15])
    #print(T[16])
    #print(T[17])
    #print(T[18])
    #print(T[19])
    #print(T[20])
    #print(T[21])
    #print(T[22])
    #print(T[23])
    #print(T[24])
    #print(T[25])
    #print(T[26])
    #print(T[27])
    #print(T[28])
    #print(T[29])
    #print(T[30])
    #print(T[31])
    #print(T[32])
    #print(T[33])
    #print(T[34])
    #print(T[35])
    #print(T[36])
    #print(T[37])
    #print(T[38])
    #print(T[39])
    #print(T[40])
    #print(T[41])
    #print(T[42])
    #print(T[43])
