def main():
    n, k = map(int, input().split())
    s = input()
    #print(n, k, s)
    #n, k = 6, 1
    #s = 'LRLRRL'
    #n, k = 13, 3
    #s = 'LRRLRLRRLLR'
    #n, k = 10, 1
    #s = 'LLLLLRRRRRR'
    #n, k = 9, 2
    #s = 'RRRLRLL'
    #n, k = 9, 1
    #s = 'RRRLRLL'
    #n, k = 9, 0
    #s = 'RRRLRLL'
    #n, k = 9, 3
    #s = 'RRRLRLL'
    #n, k = 9, 4
    #s = 'RRRLRLL'
    #n, k = 9, 5
    #s = 'RRRLRLL'
    #n, k = 9, 6
    #s = 'RRRLRLL'
    #n, k = 9, 7
    #s = 'RRRLRLL'
    #n, k = 9, 8
    #s = 'RRRLRLL'
    #n, k = 9, 9
    #s = 'RRRLRLL'
    #n, k = 9, 10
    #s = 'RRRLRLL'
    #n, k = 9, 11
    #s = 'RRRLRLL'
    #n, k = 9, 12
    #s = 'RRRLRLL'
    #n, k = 9, 13
    #s = 'RRRLRLL'
    #n, k = 9, 14
    #s = 'RRRLRLL'
    #n, k = 9, 15
    #s = 'RRRLRLL'
    #n, k = 9, 16
    #s = 'RRRLRLL'
    #n, k = 9, 17
    #s = 'RRRLRLL'
    #n, k =
