def main():
    H,W,N = map(int,input().split())
    A = []
    B = []
    for i in range(N):
        a,b = map(int,input().split())
        A.append(a)
        B.append(b)
    # print(A)
    # print(B)
    # print(H,W,N)
    # print(A,B)
    # print(type(A),type(B))
    # print(type(H),type(W),type(N))
    # print(type(A[0]),type(B[0]))
    # print(len(A),len(B))
    # print(A[0],B[0])
    # print(A[0],B[0])
    # print(A[1],B[1])
    # print(A[2],B[2])
    # print(A[3],B[3])
    # print(A[4],B[4])
    # print(A[5],B[5])
    # print(A[6],B[6])
    # print(A[7],B[7])
    # print(A[8],B[8])
    # print(A[9],B[9])
    # print(A[10],B[10])
    # print(A[11],B[11])
    # print(A[12],B[12])
    # print(A[13],B[13])
    # print(A[14],B[14])
    # print(A[15],B[15])
    # print(A[16],B[16])
    # print(A[17],B[17])
    # print(A[18],B[18])
    # print(A[19],B[19])
    # print(A[20],B[20])
    # print(A[21],B[21])
    # print(A[22],B[22])
    # print(A[23],B[23])
    # print(A[24],B[24])
    # print(A[25],B[25])
    # print(A[26],B[26])
    # print(A[27],B[27])
    # print(A[28],B[28])
    # print(A[29],B[29])
    # print(A[30],B[30])
    # print(A[31],B[31])
    # print(A[32],B[32])
    # print(A[33],B[33])

if __name__ == '__main__':
    main()