def print_all_numbers(N):
    # N=11
    # N=0
    # N=576461302059761664
    # N=576461302059761664
    N = int(N)
    # print(N)
    # print(bin(N))
    N_bin = bin(N)
    # print(N_bin)
    N_bin = N_bin[2:]
    # print(N_bin)
    N_bin = N_bin[::-1]
    # print(N_bin)
    N_bin_list = list(N_bin)
    # print(N_bin_list)
    N_bin_list_len = len(N_bin_list)
    # print(N_bin_list_len)
    # print(N_bin_list)
    # print(N_bin_list_len)
    # print(N_bin_list_len)
    # print(N_bin_list[0])
    # print(N_bin_list[1])
    # print(N_bin_list[2])
    # print(N_bin_list[3])
    # print(N_bin_list[4])
    # print(N_bin_list[5])
    # print(N_bin_list[6])
    # print(N_bin_list[7])
    # print(N_bin_list[8])
    # print(N_bin_list[9])
    # print(N_bin_list[10])
    # print(N_bin_list[11])
    # print(N_bin_list[12])
    # print(N_bin_list[13])
    # print(N_bin_list[14])
    # print(N_bin_list[15])
    # print(N_bin_list[16])
    # print(N_bin_list[17])
    # print(N_bin_list[18])
    # print(N_bin_list[19])
    # print(N_bin_list[20])
    # print(N_bin_list[21])
    # print(N_bin_list[22])
    # print(N_bin_list[23])
    # print(N_bin_list[24])
    # print(N_bin_list[25])
    # print(N_bin_list[26])
    # print(N_bin_list[27])
    # print(N_bin_list[28])
    # print(N_bin_list[29])
    # print(N_bin_list[30])
    # print(N_bin_list[31])
    # print(N_bin_list[32])
    # print(N_bin_list[33])
    # print(N_bin_list[34])
    # print(N_bin_list[35])
    # print(N_bin_list[36])
    # print(N_bin_list[37])
