def main():
    N, M = map(int, input().split())
    bridge = []
    for i in range(M):
        bridge.append(list(map(int, input().split())))
    bridge.sort()
    #print(bridge)
    #print(N, M)
    #print(bridge[0][0])
    #print(bridge[0][1])
    #print(bridge[1][0])
    #print(bridge[1][1])
    #print(bridge[2][0])
    #print(bridge[2][1])
    #print(bridge[3][0])
    #print(bridge[3][1])
    #print(bridge[4][0])
    #print(bridge[4][1])
    #print(bridge[5][0])
    #print(bridge[5][1])
    #print(bridge[6][0])
    #print(bridge[6][1])
    #print(bridge[7][0])
    #print(bridge[7][1])
    #print(bridge[8][0])
    #print(bridge[8][1])
    #print(bridge[9][0])
    #print(bridge[9][1])
    #print(bridge[10][0])
    #print(bridge[10][1])
    #print(bridge[11][0])
    #print(bridge[11][1])
    #print(bridge[12][0])
    #print(bridge[12][1])
    #print(bridge[13][0])
    #print(bridge[13][1])
    #print(bridge[14][0])
    #print(bridge[14][1])
    #print(bridge[15][0])
    #print(bridge[15][1])
    #print(bridge[16][0])
    #print(bridge[16][1])
    #print(bridge[17][0])
    #print(bridge[17][1])
    #print(bridge[18][0])
    #print(bridge[18][1])
    #print(bridge[19][0])
    #print(bridge[19][1])
    #print(bridge[20][0])
    #print(bridge[20][1])
    #print(bridge[21][0])
    #print(bridge[21][1])
    #print(bridge[22
