def main():
    H, W = list(map(int, input().split()))
    S = [list(map(str, input())) for _ in range(H)]
    #print(S)
    #print(S[0][0])
    #print(S[0][1])
    #print(S[1][0])
    #print(S[1][1])
    #print(S[2][0])
    #print(S[2][1])
    #print(S[0][0] == '#')
    #print(S[0][1] == '#')
    #print(S[1][0] == '#')
    #print(S[1][1] == '#')
    #print(S[2][0] == '#')
    #print(S[2][1] == '#')
    #print(S[0][0] == '.' and S[0][1] == '.' and S[1][0] == '.' and S[1][1] == '.')
    #print(S[0][0] == '.' and S[0][1] == '.' and S[1][0] == '.' and S[1][1] == '.' and S[2][0] == '.' and S[2][1] == '.')
    #print(S[0][0] == '#' and S[0][1] == '#' and S[1][0] == '#' and S[1][1] == '#')
    #print(S[0][0] == '#' and S[0][1] == '#' and S[1][0] == '#' and S[1][1] == '#' and S[2][0] == '#' and S[2][1] == '#')
    #print(S[0][0] == '#' and S[0][1] == '.' and S[1][0] == '#' and S[1][1] == '.')
    #print(S[0][0] == '.' and S[0][1] == '#' and S[1][0] == '.' and S[1][1] == '#')
    #print(S[0][0] == '#' and S[0][1] == '.' and S[1][0] == '.' and S[1][1] == '#')
    #print(S[0][0] == '.' and S[0][1] == '#' and S[1][0] == '#'
