def solve():
    N, K = map(int, input().split())
    S = input()
    #print(N, K, S)
    #print(S[0])
    #print(S[-1])
    #print(S[0] == S[-1])
    #print(S[0] == S[-1] == 'L')
    #print(S[0] == S[-1] == 'R')
    #print(S[0] == S[-1] == 'R' or S[0] == S[-1] == 'L')
    #print(S[0] == S[-1] == 'L' or S[0] == S[-1] == 'R')
    #print(S[0] == S[-1] == 'L' or S[0] == S[-1] == 'R' or (S[0] == 'R' and S[-1] == 'L'))
    #print(S[0] == S[-1] == 'L' or S[0] == S[-1] == 'R' or (S[0] == 'R' and S[-1] == 'L') or (S[0] == 'L' and S[-1] == 'R'))
    #print(S[0] == S[-1] == 'L' or S[0] == S[-1] == 'R' or (S[0] == 'R' and S[-1] == 'L') or (S[0] == 'L' and S[-1] == 'R') or (S[0] == S[-1] == 'R' and S[0] == S[-1] == 'L'))
    #print(S[0] == S[-1] == 'L' or S[0] == S[-1] == 'R' or (S[0] == 'R' and S[-1] == 'L') or (S[0] == 'L' and S[-1] == 'R') or (S[0] == S[-1] == 'R' and S[0] == S[-1] == 'L') or (S[0] == S[-1] == 'R' and S[0] == S[-1] == 'R'))
    #print(S[0] == S[-1] == '
