def main():
    n, k = map(int, input().split())
    d = []
    a = []
    for i in range(k):
        d.append(int(input()))
        a.append(list(map(int, input().split())))
    # print(d)
    # print(a)
    # print(n)
    # print(k)
    # print(len(d))
    # print(len(a))
    # print(len(a[0]))
    # print(a[0][0])
    # print(a[0][1])
    # print(a[1][0])
    # print(a[1][1])
    # print(a[1][2])
    # print(a[2][0])
    # print(a[2][1])
    # print(a[2][2])
    # print(a[2][3])
    # print(a[2][4])
    # print(a[2][5])
    # print(d[0])
    # print(d[1])
    # print(d[2])
    # print(d[3])
    # print(d[4])
    # print(d[5])
    # print(d[6])
    # print(d[7])
    # print(d[8])
    # print(d[9])
    # print(d[10])
    # print(d[11])
    # print(d[12])
    # print(d[13])
    # print(d[14])
    # print(d[15])
    # print(d[16])
    # print(d[17])
    # print(d[18])
    # print(d[19])
    # print(d[20])
    # print(d[21])
    # print(d[22])
    # print(d[23])
    # print(d[24])
    # print(d[25])
    # print(d[26])
    # print(d[27])
    # print(d[28])
    # print(d[29])
    # print(d[30])
    # print(d[31])
    # print(d[32])
    # print(d[33])
    # print(d[34])
    # print(d[35])
    # print(d[36])
    # print(d[37])
    # print(d[38])
    # print(d[39])
    # print(d[40])
    # print(d[41])
    # print(d[42])
    # print(d[43])
    # print(d[44])

if __name__ == '__main__':
    main()