def main():
    n, m = map(int, input().split())
    #print(n, m)
    #print(type(n), type(m))
    #print(type(n), type(m))
    #print(n, m)
    #print(type(n), type(m))
    #print(type(n), type(m))
    #print(n, m)
    #print(type(n), type(m))
    #print(type(n), type(m))
    #print(n, m)
    #print(type(n), type(m))
    #print(type(n), type(m))
    #print(n, m)
    #print(type(n), type(m))
    #print(type(n), type(m))
    #print(n, m)
    #print(type(n), type(m))
    #print(type(n), type(m))
    #print(n, m)
    #print(type(n), type(m))
    #print(type(n), type(m))
    #print(n, m)
    #print(type(n), type(m))
    #print(type(n), type(m))
    #print(n, m)
    #print(type(n), type(m))
    #print(type(n), type(m))
    #print(n, m)
    #print(type(n), type(m))
    print(type(n), ty

if __name__ == '__main__':
    main()