def main():
    H, W = map(int, input().split())
    C_h, C_w = map(int, input().split())
    D_h, D_w = map(int, input().split())
    S = [list(input()) for _ in range(H)]
    #print(H, W, C_h, C_w, D_h, D_w)
    #print(S)
    S[C_h-1][C_w-1] = 0
    S[D_h-1][D_w-1] = 0
    #print(S)
    #print()
    #print(S)
    #print()
    #print(S[0][0])
    #print(S[0][1])
    #print(S[0][2])
    #print(S[0][3])
    #print(S[0][4])
    #print(S[1][0])
    #print(S[1][1])
    #print(S[1][2])
    #print(S[1][3])
    #print(S[1][4])
    #print(S[2][0])
    #print(S[2][1])
    #print(S[2][2])
    #print(S[2][3])
    #print(S[2][4])
    #print(S[3][0])
    #print(S[3][1])
    #print(S[3][2])
    #print(S[3][3])
    #print(S[3][4])
    #print()
    #print(S[0])
    #print(S[1])
    #print(S[2])
    #print(S[3])
    #print()
    #print(S[0][0])
    #print(S[1][0])
    #print(S[2][0])
    #print(S[3][0])
    #print(S[4][0])
    #print(S[0][1])
    #print(S[1][1])
    #print(S[2][1])
    #print(S[3][1])
    #print(S[4][1])
    #print(S[0][2])
    #print(S[1][2])
    #print(S[2][2])
    #print(S[3][2])
    #print(S[4][2])
    #print(S[0][3])
    #print(S[1][3])
    #

if __name__ == '__main__':
    main()