def solve():
    N = int(input())
    T = []
    K = []
    A = []
    for i in range(N):
        t_k_a = input().split()
        T.append(int(t_k_a[0]))
        K.append(int(t_k_a[1]))
        A.append([int(a) for a in t_k_a[2:]])
    # print(N, T, K, A)
    # print(T)
    # print(K)
    # print(A)
    # print(A[0])
    # print(A[1])
    # print(A[2])
    # print(A[3])
    # print(A[4])
    # print(A[5])
    # print(A[6])
    # print(A[7])
    # print(A[8])
    # print(A[9])
    # print(A[10])
    # print(A[11])
    # print(A[12])
    # print(A[13])
    # print(A[14])
    # print(A[15])
    # print(A[16])
    # print(A[17])
    # print(A[18])
    # print(A[19])
    # print(A[20])
    # print(A[21])
    # print(A[22])
    # print(A[23])
    # print(A[24])
    # print(A[25])
    # print(A[26])
    # print(A[27])
    # print(A[28])
    # print(A[29])
    # print(A[30])
    # print(A[31])
    # print(A[32])
    # print(A[33])
    # print(A[34])
    # print(A[35])
    # print(A[36])
    # print(A[37])
    # print(A[38])
    # print(A[39])
    # print(A[40])
    # print(A[41])
    # print(A[42])
    # print(A[43])
    # print(A[44])
    # print(A[45])
    # print(A[46])
    # print(A[47])
    # print(A[48])
    # print(A[49])
    # print(A[50])
    # print(A[51])
    # print(A[52])
    # print(A[53])
    # print(A[54])
    # print(A[55])
    # print(A[56])
    #

if __name__ == '__main__':
    solve()