def solve():
    N,K = map(int,input().split())
    t = []
    d = []
    for i in range(N):
        t_i,d_i = map(int,input().split())
        t.append(t_i)
        d.append(d_i)
    sushi = []
    for i in range(N):
        sushi.append([d[i],t[i]])
    sushi.sort(reverse=True)
    #print(sushi)
    #print(sushi[0][0])
    #print(sushi[0][1])
    #print(sushi[1][0])
    #print(sushi[1][1])
    #print(sushi[2][0])
    #print(sushi[2][1])
    #print(sushi[3][0])
    #print(sushi[3][1])
    #print(sushi[4][0])
    #print(sushi[4][1])
    #print(sushi[5][0])
    #print(sushi[5][1])
    #print(sushi[6][0])
    #print(sushi[6][1])
    #print(sushi[7][0])
    #print(sushi[7][1])
    #print(sushi[8][0])
    #print(sushi[8][1])
    #print(sushi[9][0])
    #print(sushi[9][1])
    #print(sushi[10][0])
    #print(sushi[10][1])
    #print(sushi[11][0])
    #print(sushi[11][1])
    #print(sushi[12][0])
    #print(sushi[12][1])
    #print(sushi[13][0])
    #print(sushi[13][1])
    #print(sushi[14][0])
    #print(sushi[14][1])
    #print(sushi[15][0])
    #print(sushi[15][1])
    #print(sushi[16][0])
    #print(sushi[16][1])
    #print(sushi[17][0])
    #print(sushi[17][1])
    #print(sushi[18][0])
    #print(sushi[18][1])
    #print(sushi[19][0])
    #print(sushi[19][1])
    #print(sushi[20][0])
    #print(sushi[
