def main():
    N, L, R = map(int, input().split())
    A = list(map(int, input().split()))
    #print(N, L, R)
    #print(A)
    #print(N, L, R, A)
    #print("N=", N, "L=", L, "R=", R, "A=", A)
    #print("N=", N, "L=", L, "R=", R, "A=", A)
    #print("N=", N, "L=", L, "R=", R, "A=", A)
    #print("N=", N, "L=", L, "R=", R, "A=", A)
    #print("N=", N, "L=", L, "R=", R, "A=", A)
    #print("N=", N, "L=", L, "R=", R, "A=", A)
    #print("N=", N, "L=", L, "R=", R, "A=", A)
    #print("N=", N, "L=", L, "R=", R, "A=", A)
    #print("N=", N, "L=", L, "R=", R, "A=", A)
    #print("N=", N, "L=", L, "R=", R, "A=", A)
    #print("N=", N, "L=", L, "R=", R, "A=", A)
    #print("N=", N, "L=", L, "R=", R, "A=", A)
    #print("N=", N, "L=", L, "R=", R, "A=", A)
    #print("N=", N, "L=", L, "R=", R, "A=", A)
    #print("N=", N, "L=", L, "R=", R, "A=", A)
    #print("N=", N, "L=", L, "R=", R, "A=", A)
    #print("N=", N, "L=", L, "R=", R, "A=", A)
    #print("N=", N, "L=", L, "R=", R, "A=", A)
    #print("N=", N, "L=", L, "R=", R, "A=", A)
    #print("N=", N, "L=",

if __name__ == '__main__':
    main()