def main():
    H, W = map(int, input().split())
    S = [input() for _ in range(H)]
    T = [input() for _ in range(H)]
    S = [list(s) for s in S]
    T = [list(t) for t in T]
    #print(S)
    #print(T)
    #print(S[0][0])
    #print(S[0][1])
    #print(S[1][0])
    #print(S[1][1])
    #print(S[2][0])
    #print(S[2][1])
    #print(S[0])
    #print(S[1])
    #print(S[2])
    #print(T[0])
    #print(T[1])
    #print(T[2])
    #print(S[0][0])
    #print(S[0][1])
    #print(S[1][0])
    #print(S[1][1])
    #print(S[2][0])
    #print(S[2][1])
    #print(S[0])
    #print(S[1])
    #print(S[2])
    #print(T[0])
    #print(T[1])
    #print(T[2])
    #print(S[0][0])
    #print(S[0][1])
    #print(S[1][0])
    #print(S[1][1])
    #print(S[2][0])
    #print(S[2][1])
    #print(S[0])
    #print(S[1])
    #print(S[2])
    #print(T[0])
    #print(T[1])
    #print(T[2])
    #print(S[0][0])
    #print(S[0][1])
    #print(S[1][0])
    #print(S[1][1])
    #print(S[2][0])
    #print(S[2][1])
    #print(S[0])
    #print(S[1])
    #print(S[2])
    #print(T[0])
    #print(T[1])
    #print(T[2])
    #print(S[0][0])
    #print(S[0][1])
    #print(S[1][0])
    #print(S[1][1])
    #print(S[2][0

if __name__ == '__main__':
    main()