def main():
    s = input()
    print(s)
    print(s.count('('))
    print(s.count(')'))
    print(s.count('a'))
    print(s.count('b'))
    print(s.count('c'))
    print(s.count('d'))
    print(s.count('e'))
    print(s.count('f'))
    print(s.count('g'))
    print(s.count('h'))
    print(s.count('i'))
    print(s.count('j'))
    print(s.count('k'))
    print(s.count('l'))
    print(s.count('m'))
    print(s.count('n'))
    print(s.count('o'))
    print(s.count('p'))
    print(s.count('q'))
    print(s.count('r'))
    print(s.count('s'))
    print(s.count('t'))
    print(s.count('u'))
    print(s.count('v'))
    print(s.count('w'))
    print(s.count('x'))
    print(s.count('y'))
    print(s.count('z'))

if __name__ == '__main__':
    main()