def main():
    # 读入数据
    N, M = map(int, input().split())
    # print(N, M)
    # print(type(N), type(M))
    # print(type(N), type(M))
    # print(N, M)
    # print(type(N), type(M))
    # print(type(N), type(M))
    # print(N, M)
    # print(type(N), type(M))
    # print(type(N), type(M))
    # print(N, M)
    # print(type(N), type(M))
    # print(type(N), type(M))
    # print(N, M)
    # print(type(N), type(M))
    # print(type(N), type(M))
    # print(N, M)
    # print(type(N), type(M))
    # print(type(N), type(M))
    # print(N, M)
    # print(type(N), type(M))
    # print(type(N), type(M))
    # print(N, M)
    # print(type(N), type(M))
    # print(type(N), type(M))
    # print(N, M)
    # print(type(N), type(M))
    # print(type(N), type(M))
    # print(N, M)
    # print(type(N), type(M))
    # print(type(N), type(M))
    # print(N, M)
    # print(type(N), type(M))
    # print(type(N), type(M))
    K = []
    A = []
    for i in range(N):
        temp = list(map(int, input().split()))
        K.append(temp[0])
        A.append(temp[1:])
    # print(K)
    # print(A)
    # print(type(K))
    # print(type(A))
    # print(K[0])
    # print(A[0])
    # print(type(K[0]))
    # print(type(A[0]))
    # print(K[1])
    # print(A[1])
    # print(type(K[1]))
    # print(type(A[1]))
    # print(K[2])
    # print(A[2])
    # print(type(K[2]))
    # print(type(A[2]))
    # print(K[3])
    # print(A[3])
    # print(type(K[3]))
    # print(type(A[3]))
    # print(K[4])
    # print(A[4])
    # print(type(K[4]))
