def main():
    # 读入数据
    n, m = map(int, input().split())
    #print(n, m)
    #print(type(n), type(m))
    #print(type(n), type(m))
    #print("n = %d, m = %d" % (n, m))
    #print("n = %s, m = %s" % (n, m))
    #print("n = %s, m = %s" % (type(n), type(m)))
    #print("n = %d, m = %d" % (type(n), type(m)))
    #print("n = %d, m = %d" % (str(n), str(m)))
    #print("n = %s, m = %s" % (str(n), str(m)))
    #print("n = %s, m = %s" % (str(type(n)), str(type(m))))
    #print("n = %d, m = %d" % (str(type(n)), str(type(m))))
    #print("n = %s, m = %s" % (str(n), str(m)))
    #print("n = %d, m = %d" % (n, m))
    #print("n = %s, m = %s" % (str(n), str(m)))
    #print("n = %d, m = %d" % (n, m))
    #print("n = %s, m = %s" % (str(n), str(m)))
    #print("n = %d, m = %d" % (n, m))
    #print("n = %s, m = %s" % (str(n), str(m)))
    #print("n = %d, m = %d" % (n, m))
    #print("n = %s, m = %s" % (str(n), str(m)))
    #print("n = %d, m = %d" % (n, m))
    #print("n = %s, m = %s" % (str(n), str(m)))
    #print("n = %d, m = %d" % (n, m))
    #print("n = %s, m = %s" % (str(n), str(m)))
    #print("
