def main():
    N = int(input())
    a = []
    for i in range(N):
        a.append(list(map(int, input().split())))
    #print(a)
    #print(N)
    #print(a[0][0])
    #print(a[0][0])
    #print(a[1][0])
    #print(a[2][0])
    #print(a[3][0])
    #print(a[0][1])
    #print(a[0][2])
    #print(a[0][3])
    #print(a[1][1])
    #print(a[2][2])
    #print(a[3][3])
    #print(a[1][2])
    #print(a[2][3])
    #print(a[1][3])
    #print(a[2][1])
    #print(a[3][2])
    #print(a[3][1])
    #print(a[1][1])
    #print(a[2][2])
    #print(a[3][3])
    #print(a[1][2])
    #print(a[2][3])
    #print(a[1][3])
    #print(a[2][1])
    #print(a[3][2])
    #print(a[3][1])
    #print(a[1][1])
    #print(a[2][2])
    #print(a[3][3])
    #print(a[1][2])
    #print(a[2][3])
    #print(a[1][3])
    #print(a[2][1])
    #print(a[3][2])
    #print(a[3][1])
    #print(a[1][1])
    #print(a[2][2])
    #print(a[3][3])
    #print(a[1][2])
    #print(a[2][3])
    #print(a[1][3])
    #print(a[2][1])
    #print(a[3][2])
    #print(a[3][1])
    #print(a[1][1])
    #print(a[2][2])
    #print(a[3][3])
    #print(a[1][2])
    #print(a[2][3])
    #print(a[1][3])
    #print(a[2][1])

if __name__ == '__main__':
    main()