def main():
    N,W = map(int,input().split())
    people = []
    for i in range(N):
        people.append(list(map(int,input().split())))
    people.sort(key=lambda x:x[0])
    people.sort(key=lambda x:x[1])
    #print(people)
    #print('N:',N)
    #print('W:',W)
    #print('people:',people)
    #print('people[0][0]:',people[0][0])
    #print('people[0][1]:',people[0][1])
    #print('people[0][2]:',people[0][2])
    #print('people[1][0]:',people[1][0])
    #print('people[1][1]:',people[1][1])
    #print('people[1][2]:',people[1][2])
    #print('people[2][0]:',people[2][0])
    #print('people[2][1]:',people[2][1])
    #print('people[2][2]:',people[2][2])
    #print('people[3][0]:',people[3][0])
    #print('people[3][1]:',people[3][1])
    #print('people[3][2]:',people[3][2])
    #print('people[4][0]:',people[4][0])
    #print('people[4][1]:',people[4][1])
    #print('people[4][2]:',people[4][2])
    #print('people[5][0]:',people[5][0])
    #print('people[5][1]:',people[5][1])
    #print('people[5][2]:',people[5][2])
    #print('people[6][0]:',people[6][0])
    #print('people[6][1]:',people[6][1])
    #print('people[6][2]:',people[6][2])
    #print('people[7][0]:',people[7][0])
    #print('people[7][1]:',people[7][1])
    #print('people[7][2]:',people[7][2])
    #print('people[8][0
