def main():
    H, W = map(int, input().split())
    A = [list(map(int, input().split())) for _ in range(H)]
    #print(A)
    #print(H)
    #print(W)
    #print(A)
    #print(len(A))
    #print(len(A[0]))
    #print(A[0][0])
    #print(A[0][1])
    #print(A[0][2])
    #print(A[1][0])
    #print(A[1][1])
    #print(A[1][2])
    #print(A[2][0])
    #print(A[2][1])
    #print(A[2][2])
    #print(A[0])
    #print(A[1])
    #print(A[2])
    
    #print(A[0][0])
    #print(A[1][0])
    #print(A[2][0])
    #print(A[0][1])
    #print(A[1][1])
    #print(A[2][1])
    #print(A[0][2])
    #print(A[1][2])
    #print(A[2][2])
    
    #print(A[0][0])
    #print(A[1][0])
    #print(A[2][0])
    #print(A[0][1])
    #print(A[1][1])
    #print(A[2][1])
    #print(A[0][2])
    #print(A[1][2])
    #print(A[2][2])
    
    #print(A[0][0])
    #print(A[1][0])
    #print(A[2][0])
    #print(A[0][1])
    #print(A[1][1])
    #print(A[2][1])
    #print(A[0][2])
    #print(A[1][2])
    #print(A[2][2])
    
    #print(A[0][0])
    #print(A[1][0])
    #print(A[2][0])
    #print(A[0][1])
    #print(A[1][1])
    #print(A[2][1])
    #print(A[0][2])
    #print(A[1][2])
    #print(A[2][2])
    
    #print

if __name__ == '__main__':
    main()