def main():
    N, Q = map(int, input().split())
    S = input()
    l = []
    r = []
    for i in range(Q):
        l_i, r_i = map(int, input().split())
        l.append(l_i)
        r.append(r_i)
    #print(N, Q)
    #print(S)
    #print(l)
    #print(r)
    #print(S[2:3])
    #print(S[3:7])
    #print(S[2:7])
    #print(S[1:8])
    #print(S[0:8])
    #print(S[2:3] == 'A')
    #print(S[3:7] == 'AC')
    #print(S[2:7] == 'AC')
    #print(S[1:8] == 'AC')
    #print(S[0:8] == 'AC')
    #print(S[2:3] == 'A' and S[3:7] == 'AC')
    #print(S[2:7] == 'AC')
    #print(S[1:8] == 'AC')
    #print(S[0:8] == 'AC')
    #print(S[2:3] == 'A' and S[3:7] == 'AC')
    #print(S[2:7] == 'AC')
    #print(S[1:8] == 'AC')
    #print(S[0:8] == 'AC')
    #print(S[2:3] == 'A' and S[3:7] == 'AC')
    #print(S[2:7] == 'AC')
    #print(S[1:8] == 'AC')
    #print(S[0:8] == 'AC')
    #print(S[2:3] == 'A' and S[3:7] == 'AC')
    #print(S[2:7] == 'AC')
    #print(S[1:8] == 'AC')
    #print(S[0:8] == 'AC')
    #print(S[2:3] == 'A' and S[3:7] == 'AC')
    #print(S[2:7] == 'AC')
    #print(S[1:8] == 'AC')
    #print(S[0
