def main():
    n, k = map(int, input().split())
    A = list(map(int, input().split()))
    A.sort()
    #print(A)
    #print(n, k)
    #print(A)
    #print(A[0])
    #print(A[n-1])
    #print(A[0]*A[n-1])
    #print(A[1])
    #print(A[n-2])
    #print(A[1]*A[n-2])
    #print(A[2])
    #print(A[n-3])
    #print(A[2]*A[n-3])
    #print(A[3])
    #print(A[n-4])
    #print(A[3]*A[n-4])
    #print(A[4])
    #print(A[n-5])
    #print(A[4]*A[n-5])
    #print(A[5])
    #print(A[n-6])
    #print(A[5]*A[n-6])
    #print(A[6])
    #print(A[n-7])
    #print(A[6]*A[n-7])
    #print(A[7])
    #print(A[n-8])
    #print(A[7]*A[n-8])
    #print(A[8])
    #print(A[n-9])
    #print(A[8]*A[n-9])
    #print(A[9])
    #print(A[n-10])
    #print(A[9]*A[n-10])
    #print(A[10])
    #print(A[n-11])
    #print(A[10]*A[n-11])
    #print(A[11])
    #print(A[n-12])
    #print(A[11]*A[n-12])
    #print(A[12])
    #print(A[n-13])
    #print(A[12]*A[n-13])
    #print(A[13])
    #print(A[n-14])
    #print(A[13]*A[n-14])
    #print(A[14])
    #print(A[n-15])
    #print(A[14]*A[n-15])
    #print(A[15])
    #print(A[n-16])
    #print(A[15]*A[n-16])
    #print(A[16])
    #print(A[n-17])
    #print(A[16]*

if __name__ == '__main__':
    main()