def main():
    A = int(input())
    B = int(input())
    C = int(input())
    D = int(input())
    E = int(input())
    #print(A, B, C, D, E)
    a = [A, B, C, D, E]
    #print(a)
    b = list(map(lambda x: x % 10, a))
    #print(b)
    c = list(map(lambda x: 10 if x == 0 else x, b))
    #print(c)
    d = list(map(lambda x, y: x - y, c, b))
    #print(d)
    e = list(map(lambda x, y: x + y, a, d))
    #print(e)
    print(max(e))
main()
