def main():
    N, C = map(int, input().split())
    #print(N, C)
    A = []
    B = []
    C = []
    for i in range(N):
        a, b, c = map(int, input().split())
        A.append(a)
        B.append(b)
        C.append(c)
    #print(A, B, C)
    #print(type(A[0]))
    #print(type(B[0]))
    #print(type(C[0]))
    #print(type(N))
    #print(type(C))
    #print(type(A))
    #print(type(B))
    #print(type(N))
    #print(type(C))
    #print(type(A))
    #print(type(B))
    #print(type(C))
    #print(type(N))
    #print(type(C))
    #print(type(A))
    #print(type(B))
    #print(type(C))
    #print(type(N))
    #print(type(C))
    #print(type(A))
    #print(type(B))
    #print(type(C))
    #print(type(N))
    #print(type(C))
    #print(type(A))
    #print(type(B))
    #print(type(C))
    #print(type(N))
    #print(type(C))
    #print(type(A))
    #print(type(B))
    #print(type(C))
    #print(type(N))
    #print(type(C))
    #print(type(A))
    #print(type(B))
    #print(type(C))
    #print(type(N))
    #print(type(C))
    #print(type(A))
    #print(type(B))
    #print(type(C))
    #print(type(N))
    #print(type(C))
    #print(type(A))
    #print(type(B))
    #print(type(C))
    #print(type(N))
    #print(type(C))
    #print(type(A))
    #print(type(B))
    #print(type(C))
    #print(type(N))
    #print(type(C))
    #print(type(A))
    #print(type(B))
    #print(type(C))
    #print(type(N))
    #print(type(C))
    #print(type(A))
    #print(type(B))
    #print(type(C))
    #print(type(N))
    #print(type(C))
    #print(type(A))
    #print(type(B))
    #print(type(C))
    #print(type(N))
    #print(type(C))

if __name__ == '__main__':
    main()