def main():
    N, Q = map(int, input().split())
    tree = [[] for _ in range(N)]
    for _ in range(N-1):
        a, b = map(int, input().split())
        tree[a-1].append(b-1)
        tree[b-1].append(a-1)
    #print(tree)
    #print()
    #print(tree[0])
    #print(tree[1])
    #print(tree[2])
    #print(tree[3])
    #print(tree[4])
    #print(tree[5])
    #print()
    #print("tree[0] = ", tree[0])
    #print("tree[1] = ", tree[1])
    #print("tree[2] = ", tree[2])
    #print("tree[3] = ", tree[3])
    #print("tree[4] = ", tree[4])
    #print("tree[5] = ", tree[5])
    #print("len(tree[0]) = ", len(tree[0]))
    #print("len(tree[1]) = ", len(tree[1]))
    #print("len(tree[2]) = ", len(tree[2]))
    #print("len(tree[3]) = ", len(tree[3]))
    #print("len(tree[4]) = ", len(tree[4]))
    #print("len(tree[5]) = ", len(tree[5]))
    #print("tree[0][0] = ", tree[0][0])
    #print("tree[0][1] = ", tree[0][1])
    #print("tree[1][0] = ", tree[1][0])
    #print("tree[2][0] = ", tree[2][0])
    #print("tree[3][0] = ", tree[3][0])
    #print("tree[4][0] = ", tree[4][0])
    #print("tree[5][0] = ", tree[5][0])
    #print("tree[0][0] = ", tree[0][0])
    #print("tree[0][1] = ", tree[0][1])
    #print("tree[1][0] = ", tree[1][0])
    #print("tree[2][0] = ", tree[2][0])

if __name__ == '__main__':
    main()