def main():
    S = input()
    K = int(input())
    #print(S)
    #print(K)
    #print(S.find('X',0,len(S)))
    #print(S.find('X',1,len(S)))
    #print(S.find('X',2,len(S)))
    #print(S.find('X',3,len(S)))
    #print(S.find('X',4,len(S)))
    #print(S.find('X',5,len(S)))
    #print(S.find('X',6,len(S)))
    #print(S.find('X',7,len(S)))
    #print(S.find('X',8,len(S)))
    #print(S.find('X',9,len(S)))
    #print(S.find('X',10,len(S)))
    #print(S.find('X',11,len(S)))
    #print(S.find('X',12,len(S)))
    #print(S.find('X',13,len(S)))
    #print(S.find('X',14,len(S)))
    #print(S.find('X',15,len(S)))
    #print(S.find('X',16,len(S)))
    #print(S.find('X',17,len(S)))
    #print(S.find('X',18,len(S)))
    #print(S.find('X',19,len(S)))
    #print(S.find('X',20,len(S)))
    #print(S.find('X',21,len(S)))
    #print(S.find('X',22,len(S)))
    #print(S.find('X',23,len(S)))
    #print(S.find('X',24,len(S)))
    #print(S.find('X',25,len(S)))
    #print(S.find('X',26,len(S)))
    #print(S.find('X',27,len(S)))
    #print(S.find('X',28,len(S)))
    #print(S.find('X',29,len(S)))
    #print(S.find('X',30,len(S)))
    #print(S.find('X',31,len(S)))
    #print(S.find('X',32,len(S)))
    #print(S.find('X',33,len(S)))
    #print(S.find('X',34,len(S)))
    #print(S.find('X',35,len(S)))
    #print(S.find('X',36,len(S)))
    #print(S.find('X',37,len(S)))
    #print(S.find('X',38,len(S)))
    #print(S.find('X',39

if __name__ == '__main__':
    main()