def main():
    n,x,y = map(int,input().split())
    #print(n,x,y)
    #print(type(n),type(x),type(y))
    #print(type(n))
    #print(type(x))
    #print(type(y))
    #print(n,x,y)
    #print(type(n),type(x),type(y))
    #print(type(n))
    #print(type(x))
    #print(type(y))
    #print(n,x,y)
    #print(type(n),type(x),type(y))
    #print(type(n))
    #print(type(x))
    #print(type(y))
    #print(n,x,y)
    #print(type(n),type(x),type(y))
    #print(type(n))
    #print(type(x))
    #print(type(y))
    #print(n,x,y)
    #print(type(n),type(x),type(y))
    #print(type(n))
    #print(type(x))
    #print(type(y))
    #print(n,x,y)
    #print(type(n),type(x),type(y))
    #print(type(n))
    #print(type(x))
    #print(type(y))
    #print(n,x,y)
    #print(type(n),type(x),type(y))
    #print(type(n))
    #print(type(x))
    #print(type(y))
    #print(n,x,y)
    #print(type(n),type(x),type(y))
    #print(type(n))
    #print(type(x))
    #print(type(y))

if __name__ == '__main__':
    main()