def paint(n, a, b, p, q, r, s):
    #print(n, a, b, p, q, r, s)
    #print([max(1-a,1-b), min(n-a,n-b)])
    #print([max(1-a,b-n), min(n-a,b-1)])
    #print([max(1-a,1-b), min(n-a,n-b)])
    #print([max(1-a,b-n), min(n-a,b-1)])
    #print([max(1-a,1-b), min(n-a,n-b)])
    #print([max(1-a,b-n), min(n-a,b-1)])
    #print([max(1-a,1-b), min(n-a,n-b)])
    #print([max(1-a,b-n), min(n-a,b-1)])
    #print([max(1-a,1-b), min(n-a,n-b)])
    #print([max(1-a,b-n), min(n-a,b-1)])
    #print([max(1-a,1-b), min(n-a,n-b)])
    #print([max(1-a,b-n), min(n-a,b-1)])
    #print([max(1-a,1-b), min(n-a,n-b)])
    #print([max(1-a,b-n), min(n-a,b-1)])
    #print([max(1-a,1-b), min(n-a,n-b)])
    #print([max(1-a,b-n), min(n-a,b-1)])
    #print([max(1-a,1-b), min(n-a,n-b)])
    #print([max(1-a,b-n), min(n-a,b-1)])
    #print([max(1-a,1-b), min(n-a,n-b)])
    #print([max(1-a,b-n), min(n-a,b-1)])
    
    #print([max(1-a,1-b), min(n-a,n-b)])
    #print([max(1-a,b-n), min(n-a,b-1)])
    #print([max(1-a,1-b), min(n-a,n-b)])
    #print([max(1-a,b-n), min(n-a,b-1)])
    
    #print([max(1-a,1-b), min(n-a,n-b)])
    #print([max(1-a,b-n), min(n-a,b-
