def f(n):
    if n==0:
        return 0
    if n==1:
        return 1
    if n==2:
        return 1
    if n==3:
        return 2
    if n==4:
        return 1
    if n==5:
        return 2
    if n==6:
        return 1
    if n==7:
        return 1
    if n==8:
        return 2
    if n==9:
        return 3
    if n==10:
        return 2
    if n==11:
        return 1
    if n==12:
        return 2
    if n==13:
        return 3
    if n==14:
        return 2
    if n==15:
        return 3
    if n==16:
        return 1
    if n==17:
        return 2
    if n==18:
        return 3
    if n==19:
        return 4
    if n==20:
        return 3
    if n==21:
        return 2
    if n==22:
        return 3
    if n==23:
        return 4
    if n==24:
        return 3
    if n==25:
        return 2
    if n==26:
        return 3
    if n==27:
        return 4
    if n==28:
        return 3
    if n==29:
        return 2
    if n==30:
        return 3
    if n==31:
        return 4
    if n==32:
        return 2
    if n==33:
        return 3
    if n==34:
        return 4
    if n==35:
        return 5
    if n==36:
        return 4
    if n==37:
        return 3
    if n==38:
        return 4
    if n==39:
        return 5
    if n==40:
        return 4
    if n==41:
        return 3
    if n==42:
        return 4
    if n==43:
        return 5
    if n==44:
        return 4
    if
