def main():
    N,M = map(int, input().split())
    s = []
    c = []
    for i in range(M):
        s_i, c_i = map(int, input().split())
        s.append(s_i)
        c.append(c_i)
    #print(N,M,s,c)
    #从最小值开始
    for i in range(10**(N-1), 10**N):
        #print("i=",i)
        #print("i=",i)
        #print("str(i)=",str(i))
        #print("len(str(i))=",len(str(i)))
        #print("N=",N)
        if len(str(i)) == N:
            #print("len(str(i))=",len(str(i)))
            #print("N=",N)
            #print("i=",i)
            #print("str(i)=",str(i))
            #print("len(str(i))=",len(str(i)))
            #print("N=",N)
            #print("i=",i)
            #print("str(i)=",str(i))
            #print("len(str(i))=",len(str(i)))
            #print("N=",N)
            #print("i=",i)
            #print("str(i)=",str(i))
            #print("len(str(i))=",len(str(i)))
            #print("N=",N)
            #print("i=",i)
            #print("str(i)=",str(i))
            #print("len(str(i))=",len(str(i)))
            #print("N=",N)
            #print("i=",i)
            #print("str(i)=",str(i))
            #print("len(str(i))=",len(str(i)))
            #print("N=",N)
            #print("i=",i)
            #print("str(i)=",str(i))
            #print("len(str(i))=",len(str(i)))
            #print("N=",N)
            #print("i=",i)
            #print("str(i)=",str(i))
            #print("len(str(i))=",len(str(i)))
            #print("N=",N)
            #print("i=",i)
            #print("str(i)=",str(i))
            #print("len(str(i))=",len(str(i)))
            #print("N=",N)
            #print("i=",i)
            #print("str(i)

if __name__ == '__main__':
    main()