def main():
    n = int(input())
    print("%04d" % n)
    # print('{0:04d}'.format(n))
    # print('{:04d}'.format(n))
    # print(f"{n:04d}")
    # print(f"{n:0>4}")
    # print(format(n, '04d'))
    # print(format(n, '0>4'))
    # print(format(n, '04'))
    # print(format(n, '0>4'))
    # print(format(n, '04d'))
    # print(format(n, '0>4d'))
    # print(format(n, '04d'))
    # print(format(n, '0>4d'))
    # print(format(n, '04d'))
    # print(format(n, '0>4d'))
    # print(format(n, '04d'))
    # print(format(n, '0>4d'))
    # print(format(n, '04d'))
    # print(format(n, '0>4d'))
    # print(format(n, '04d'))
    # print(format(n, '0>4d'))
    # print(format(n, '04d'))
    # print(format(n, '0>4d'))
    # print(format(n, '04d'))
    # print(format(n, '0>4d'))
    # print(format(n, '04d'))
    # print(format(n, '0>4d'))

if __name__ == '__main__':
    main()