def main():
    s = input()
    # print(s)
    # print(s[0])
    # print(s[1])
    # print(s[2])
    # print(s[3])
    # print(s[4])
    # print(s[5])
    # print(s[6])
    # print(len(s))
    # print(s[0] == s[6])
    # print(s[1] == s[5])
    # print(s[2] == s[4])
    # print(s[3] == s[3])
    # print(s[0] == s[6] and s[1] == s[5] and s[2] == s[4] and s[3] == s[3])
    # print(s[0] == s[6] and s[1] == s[5] and s[2] == s[4])
    # print(s[0] == s[6] and s[1] == s[5])
    # print(s[0] == s[6])
    # print(s[0] == s[6] and s[1] == s[5] and s[2] == s[4] and s[3] == s[3])
    # print(s[0] == s[6] and s[1] == s[5] and s[2] == s[4])
    # print(s[0] == s[6] and s[1] == s[5])
    # print(s[0] == s[6])
    # print(s[0] == s[6])
    # print(s[1] == s[5])
    # print(s[2] == s[4])
    # print(s[3] == s[3])
    # print(s[0] == s[6] and s[1] == s[5] and s[2] == s[4] and s[3] == s[3])
    # print(s[0] == s[6] and s[1] == s[5] and s[2] == s[4])
    # print(s[0] == s[6] and s[1] == s[5])
    # print(s[0] == s[6])
    # print(s[0] == s[6] and
