def main():
    N = int(input())
    A = list(map(int, input().split()))
    A.sort()
    # print(A)
    # print(len(A))
    # print(A[len(A)-1])
    # print(A[len(A)-2])
    # print(A[len(A)-3])
    # print(A[len(A)-4])
    # print(A[len(A)-5])
    # print(A[len(A)-6])
    # print(A[len(A)-7])
    # print(A[len(A)-8])
    # print(A[len(A)-9])
    # print(A[len(A)-10])
    # print(A[len(A)-11])
    # print(A[len(A)-12])
    # print(A[len(A)-13])
    # print(A[len(A)-14])
    # print(A[len(A)-15])
    # print(A[len(A)-16])
    # print(A[len(A)-17])
    # print(A[len(A)-18])
    # print(A[len(A)-19])
    # print(A[len(A)-20])
    # print(A[len(A)-21])
    # print(A[len(A)-22])
    # print(A[len(A)-23])
    # print(A[len(A)-24])
    # print(A[len(A)-25])
    # print(A[len(A)-26])
    # print(A[len(A)-27])
    # print(A[len(A)-28])
    # print(A[len(A)-29])
    # print(A[len(A)-30])
    # print(A[len(A)-31])
    # print(A[len(A)-32])
    # print(A[len(A)-33])
    # print(A[len(A)-34])
    # print(A[len(A)-35])
    # print(A[len(A)-36])
    # print(A[len(A)-37])
    # print(A[len(A)-38])
    # print(A[len(A)-39])
    # print(A[len(A)-40])
    # print(A[len(A)-41])
    # print(A[len(A)-42])
    # print(A[len(A)-43])
    # print(A[len(A)-44])
    # print(A[len(A)-45])
    # print(A[len(A)-46])
    # print(A[len(A)-47])
    # print(A[len(A)-48])
    # print(A[len(A)-49])
    # print(A[len(A)-50])
    # print(A[len(A)-51])
    # print(A[len(A)-

if __name__ == '__main__':
    main()