def main():
    L, Q = map(int, input().split())
    #L = 5
    #Q = 3
    #c = [2, 1, 2]
    #x = [2, 3, 2]
    c = []
    x = []
    for i in range(Q):
        c_i, x_i = map(int, input().split())
        c.append(c_i)
        x.append(x_i)
    #print(c)
    #print(x)
    #print("L =", L)
    #print("Q =", Q)
    #print("c =", c)
    #print("x =", x)
    #print("")
    #print("L =", L)
    #print("Q =", Q)
    #print("c =", c)
    #print("x =", x)
    #print("")
    #print("")
    #print("L =", L)
    #print("Q =", Q)
    #print("c =", c)
    #print("x =", x)
    #print("")
    #print("")
    #print("L =", L)
    #print("Q =", Q)
    #print("c =", c)
    #print("x =", x)
    #print("")
    #print("")
    #print("L =", L)
    #print("Q =", Q)
    #print("c =", c)
    #print("x =", x)
    #print("")
    #print("")
    #print("L =", L)
    #print("Q =", Q)
    #print("c =", c)
    #print("x =", x)
    #print("")
    #print("")
    #print("L =", L)
    #print("Q =", Q)
    #print("c =", c)
    #print("x =", x)
    #print("")
    #print("")
    #print("L =", L)
    #print("Q =", Q)
    #print("c =", c)
    #print("x =", x)
    #print("")
    #print("")
    #print("L =", L)
    #print("Q =", Q)
    #print("c =", c)
    #print("x =", x)
    #print("")
    #print("")
    #print("L =", L)
    #print("Q =", Q)
    #print("c =", c)
    #print("x =",
