def main():
    h = [int(x) for x in input().split()]
    w = [int(x) for x in input().split()]
    print(h, w)
    # print('h1', h[0])
    # print('h2', h[1])
    # print('h3', h[2])
    # print('w1', w[0])
    # print('w2', w[1])
    # print('w3', w[2])
    # print('-----------')
    # print('h1+h2+h3', h[0]+h[1]+h[2])
    # print('w1+w2+w3', w[0]+w[1]+w[2])
    # print('-----------')
    # print('h1+h2', h[0]+h[1])
    # print('h2+h3', h[1]+h[2])
    # print('-----------')
    # print('w1+w2', w[0]+w[1])
    # print('w2+w3', w[1]+w[2])
    # print('-----------')
    # print('h1+h2+h3', h[0]+h[1]+h[2])
    # print('w1+w2+w3', w[0]+w[1]+w[2])
    # print('-----------')
    # print('h1+h2', h[0]+h[1])
    # print('h2+h3', h[1]+h[2])
    # print('-----------')
    # print('w1+w2', w[0]+w[1])
    # print('w2+w3', w[1]+w[2])
    # print('-----------')
    # print('h1+h2+h3', h[0]+h[1]+h[2])
    # print('w1+w2+w3', w[0]+w[1]+w[2])
    # print('-----------')
    # print('h1+h2', h[0]+h[1])
    # print('h2+h3', h[1]+h[2])
    # print('h1+h3', h[0]+h[2])
    # print('-----------')
    # print('w1+w2', w[0]+w[1])
    #
