def main():
    n,m,x = map(int,input().split())
    c = []
    a = []
    for i in range(n):
        c.append(list(map(int,input().split())))
    for i in range(n):
        a.append(c[i][1:])
    c = [c[i][0] for i in range(n)]
    print(c)
    print(a)
    #print(n,m,x)
    #print(c)
    #print(a)
    #print(a[0])
    #print(a[0][0])
    #print(a[0][1])
    #print(a[0][2])
    #print(a[1][0])
    #print(a[1][1])
    #print(a[1][2])
    #print(a[2][0])
    #print(a[2][1])
    #print(a[2][2])
    #print(a[3][0])
    #print(a[3][1])
    #print(a[3][2])
    #print(a[4][0])
    #print(a[4][1])
    #print(a[4][2])
    #print(a[5][0])
    #print(a[5][1])
    #print(a[5][2])
    #print(a[6][0])
    #print(a[6][1])
    #print(a[6][2])
    #print(a[7][0])
    #print(a[7][1])
    #print(a[7][2])
    #print(a[8][0])
    #print(a[8][1])
    #print(a[8][2])
    #print(a[9][0])
    #print(a[9][1])
    #print(a[9][2])
    #print(a[10][0])
    #print(a[10][1])
    #print(a[10][2])
    #print(a[11][0])
    #print(a[11][1])
    #print(a[11][2])
    #print(a[12][0])
    #print(a[12][1])
    #print(a[12][2])
    #print(a[13][0])
    #print(a[13][1])
    #print(a[13][2])
    #print(a[14][0])
    #print(a[14][1])
    #print(a
