def main():
    Q = int(input())
    queries = []
    for i in range(Q):
        queries.append(input().split())
    #print(queries)
    #print(queries[0][0])
    #print(queries[0][1])
    #print(queries[1][0])
    #print(queries[1][1])
    #print(queries[2][0])
    #print(queries[3][0])
    #print(queries[3][1])
    #print(queries[4][0])
    #print(queries[5][0])
    #print(queries[6][0])
    #print(queries[7][0])
    #print(queries[8][0])
    #print(queries[9][0])
    #print(queries[10][0])
    #print(queries[11][0])
    #print(queries[12][0])
    #print(queries[13][0])
    #print(queries[14][0])
    #print(queries[15][0])
    #print(queries[16][0])
    #print(queries[17][0])
    #print(queries[18][0])
    #print(queries[19][0])
    #print(queries[20][0])
    #print(queries[21][0])
    #print(queries[22][0])
    #print(queries[23][0])
    #print(queries[24][0])
    #print(queries[25][0])
    #print(queries[26][0])
    #print(queries[27][0])
    #print(queries[28][0])
    #print(queries[29][0])
    #print(queries[30][0])
    #print(queries[31][0])
    #print(queries[32][0])
    #print(queries[33][0])
    #print(queries[34][0])
    #print(queries[35][0])
    #print(queries[36][0])
    #print(queries[37][0])
    #print(queries[38][0])
    #print(queries[39][0])
    #print(queries[40][0])
    #print(queries[41][0])
    #print(queries[42][0])
    #print(queries[43][

if __name__ == '__main__':
    main()