def main():
    n,k = map(int,input().split())
    r,s,p = map(int,input().split())
    t = input()
    #print(n,k,r,s,p,t)
    #print(type(n),type(k),type(r),type(s),type(p),type(t))
    #print(len(t))
    #print(type(len(t)))
    #print(t[0])
    #print(type(t[0]))
    #print(t[0] == 'r')
    #print(type(t[0] == 'r'))
    #print(t[0] == 'r' and t[1] == 's')
    #print(type(t[0] == 'r' and t[1] == 's'))
    #print(t[0] == 'r' and t[1] == 's' and t[2] == 'r')
    #print(type(t[0] == 'r' and t[1] == 's' and t[2] == 'r'))
    #print(t[0] == 'r' and t[1] == 's' and t[2] == 'r' and t[3] == 'p')
    #print(type(t[0] == 'r' and t[1] == 's' and t[2] == 'r' and t[3] == 'p'))
    #print(t[0] == 'r' and t[1] == 's' and t[2] == 'r' and t[3] == 'p' and t[4] == 's')
    #print(type(t[0] == 'r' and t[1] == 's' and t[2] == 'r' and t[3] == 'p' and t[4] == 's'))
    #print(t[0] == 'r' and t[1] == 's' and t[2] == 'r' and t[3] == 'p' and t[4] == 's' and t[5] == 's')
    #print(type(t[0] == 'r' and t[1] == 's' and t[2] == 'r' and t[3] == 'p' and t[4] == 's' and t[5] == 's'))
    #print(t[
