def main():
    N = int(input())
    A = list(map(int, input().split()))
    B = list(map(int, input().split()))
    C = list(map(int, input().split()))
    #print(A)
    #print(B)
    #print(C)
    #print(N)
    #print(len(A))
    #print(len(B))
    #print(len(C))
    #print(A[0])
    #print(A[1])
    #print(A[2])
    #print(B[0])
    #print(B[1])
    #print(B[2])
    #print(C[0])
    #print(C[1])
    #print(C[2])
    #print(A[0] == B[C[0]])
    #print(A[0] == B[C[1]])
    #print(A[0] == B[C[2]])
    #print(A[1] == B[C[0]])
    #print(A[1] == B[C[1]])
    #print(A[1] == B[C[2]])
    #print(A[2] == B[C[0]])
    #print(A[2] == B[C[1]])
    #print(A[2] == B[C[2]])
    #print(A[0] == B[C[0]] or A[0] == B[C[1]] or A[0] == B[C[2]])
    #print(A[1] == B[C[0]] or A[1] == B[C[1]] or A[1] == B[C[2]])
    #print(A[2] == B[C[0]] or A[2] == B[C[1]] or A[2] == B[C[2]])
    #print(A[0] == B[C[0]] or A[0] == B[C[1]] or A[0] == B[C[2]] or A[1] == B[C[0]] or A[1] == B[C[1]] or A[1] == B[C[2]] or A[2] == B[C[0]] or A[2] == B[C[1]] or A[2] == B[C[2]])
    #print(A[0] == B[C[0]])
    #print(A[0] == B[C[1]])
    #print(A[0] == B
