def main():
    A, B = map(int, input().split())
    if A*6 < B or A > B:
        print("No")
    else:
        print("Yes")
main()
A, B = map(int, input().split())
print("YNeos"[A*6<B or A>B::2])
A, B = map(int, input().split())
print('YNeos'[A*6<B or A>B::2])
A, B = map(int, input().split())
print("YNeos"[A*6<B or A>B::2])
A, B = map(int, input().split())
print("YNeos"[A*6<B or A>B::2])
A, B = map(int, input().split())
print("YNeos"[A*6<B or A>B::2])
A, B = map(int, input().split())
print("YNeos"[A*6<B or A>B::2])
A, B = map(int, input().split())
print("YNeos"[A*6<B or A>B::2])
A, B = map(int, input().split())
print("YNeos"[A*6<B or A>B::2])
A, B = map(int, input().split())
print("YNeos"[A*6<B or A>B::2])
A, B = map(int, input().split())
print("YNeos"[A*6<B or A>B::2])
A, B = map(int, input().split())
print("YNeos"[A*6<B or A>B::2])
A, B = map(int, input().split())
print("YNeos"[A*6<B or A>B::2])
A, B = map(int, input().split())
print("YNeos"[A*6<B or A>B::2])
A, B = map(int, input().split())
print("YNeos"[A*6<B or A>B::2])
A, B = map(int, input().split())
print("YNeos"[A*6<B or A>B::2])
A, B = map(int, input().split())
print("YNeos"[A*6<B or A>B::2])
A, B = map(int, input().split())
print("YNeos"[A*6<B or A>B::2])
