def main():
    H, W, N = map(int, input().split())
    #print(H, W, N)
    #print(type(H), type(W), type(N))
    #print(H, W, N)
    #print(type(H), type(W), type(N))
    #print(H, W, N)
    #print(type(H), type(W), type(N))
    #print(H, W, N)
    #print(type(H), type(W), type(N))
    #print(H, W, N)
    #print(type(H), type(W), type(N))
    #print(H, W, N)
    #print(type(H), type(W), type(N))
    #print(H, W, N)
    #print(type(H), type(W), type(N))
    #print(H, W, N)
    #print(type(H), type(W), type(N))
    #print(H, W, N)
    #print(type(H), type(W), type(N))
    #print(H, W, N)
    #print(type(H), type(W), type(N))
    A = []
    B = []
    for i in range(N):
        a, b = map(int, input().split())
        A.append(a)
        B.append(b)
    #print(A)
    #print(B)
    #print(type(A))
    #print(type(B))
    #print(type(A[0]))
    #print(type(B[0]))
    #print(A[0])
    #print(B[0])
    #print(type(A[1]))
    #print(type(B[1]))
    #print(A[1])
    #print(B[1])
    #print(type(A[2]))
    #print(type(B[2]))
    #print(A[2])
    #print(B[2])
    #print(type(A[3]))
    #print(type(B[3]))
    #print(A[3])
    #print(B[3])
    #print(type(A[4]))
    #print(type(B[4]))
    #print(A[4])
    #print(B[4])
    #print(type(A[5]))
    #print(type(B[5]))
    #print(A[5])
    #print(B[5])
    #print(type(A[6]))
    #print(type(B[6]))
    #print(A[6])
    #print(B[6])
    #print(type(A
