def main():
    N, X, Y = map(int, input().split())
    X -= 1
    Y -= 1
    if X > Y:
        X, Y = Y, X
    edges = []
    for _ in range(N-1):
        a, b = map(int, input().split())
        edges.append((a-1, b-1))
    #print(edges)
    #print(X, Y)
    #print(N, X, Y)
    #print(edges)
    #print(X, Y)
    #print(N, X, Y)
    #print(edges)
    #print(X, Y)
    #print(N, X, Y)
    #print(edges)
    #print(X, Y)
    #print(N, X, Y)
    #print(edges)
    #print(X, Y)
    #print(N, X, Y)
    #print(edges)
    #print(X, Y)
    #print(N, X, Y)
    #print(edges)
    #print(X, Y)
    #print(N, X, Y)
    #print(edges)
    #print(X, Y)
    #print(N, X, Y)
    #print(edges)
    #print(X, Y)
    #print(N, X, Y)
    #print(edges)
    #print(X, Y)
    #print(N, X, Y)
    #print(edges)
    #print(X, Y)
    #print(N, X, Y)
    #print(edges)
    #print(X, Y)
    #print(N, X, Y)
    #print(edges)
    #print(X, Y)
    #print(N, X, Y)
    #print(edges)
    #print(X, Y)
    #print(N, X, Y)
    #print(edges)
    #print(X, Y)
    #print(N, X, Y)
    #print(edges)
    #print(X, Y)
    #print(N, X, Y)
    #print(edges)
    #print(X, Y)
    #print(N, X, Y)
    #print(edges)
    #print(X, Y)
    #print(N, X, Y)
    #print(edges)
    #print(X, Y)
    #print(N, X, Y)
    #print(edges)
    #print(X, Y)
    #print(N, X, Y)

if __name__ == '__main__':
    main()