def get_value(s):
    value = 0
    for i in range(len(s)):
        value += (ord(s[i])-ord('A')+1)*pow(26,len(s)-i-1)
    return value
# print(get_value('A'))
# print(get_value('B'))
# print(get_value('Z'))
# print(get_value('AA'))
# print(get_value('AB'))
# print(get_value('AZ'))
# print(get_value('BA'))
# print(get_value('BB'))
# print(get_value('ZZ'))
# print(get_value('AAA'))
# print(get_value('AAB'))
# print(get_value('AAZ'))
# print(get_value('ABA'))
# print(get_value('ABB'))
# print(get_value('ABZ'))
# print(get_value('ACA'))
# print(get_value('ACB'))
# print(get_value('ACZ'))
# print(get_value('AZZ'))
# print(get_value('BAA'))
# print(get_value('BAB'))
# print(get_value('BAZ'))
# print(get_value('BBA'))
# print(get_value('BBB'))
# print(get_value('BBZ'))
# print(get_value('BZZ'))
# print(get_value('ZAA'))
# print(get_value('ZAB'))
# print(get_value('ZAZ'))
# print(get_value('ZZZ'))
# print(get_value('AAAA'))
# print(get_value('AAAB'))
# print(get_value('AAAZ'))
# print(get_value('AABA'))
# print(get_value('AABB'))
# print(get_value('AABZ'))
# print(get_value('AACA'))
# print(get_value('AACB'))
# print(get_value('AACZ'))
# print(get_value('AAZZ'))
# print(get_value('ABAA'))
# print(get_value('ABAB'))
# print(get_value('ABAZ'))
# print(get_value('ABBA'))
# print(get_value('ABBB'))
# print(get_value('ABAZ'))
# print(get_value('ABBA'))
# print(get_value('ABBB'))
# print(get_value('ABZZ'))
# print(get_value('ACAA'))
# print(get_value('ACAB'))
# print(get_value('ACAZ'))
# print(get_value('ACBA'))
# print(get_value('ACBB'))
# print(get_value('ACBZ'))
# print(get_value('ACZA'))
# print(get_value('ACZB'))
# print(get_value('ACZZ'))
# print

if __name__ == '__main__':
    get_value()