def calculate():
    N,M = map(int,input().split())
    A = []
    B = []
    for i in range(N):
        a,b = map(int,input().split())
        A.append(a)
        B.append(b)
    #print(A)
    #print(B)
    #print(N)
    #print(M)
    #print(type(N))
    #print(type(M))
    #print(type(A))
    #print(type(B))
    #print(len(A))
    #print(len(B))
    #print(type(A[0]))
    #print(type(B[0]))
    #print(sum(B))
    if sum(B) < M:
        print("输入有误")
        return
    #print("输入正确")
    #print("开始计算")
    #print("先计算最便宜的，然后再计算最贵的")
    #print("A中最便宜的")
    #print(min(A))
    #print("B中最便宜的")
    #print(min(B))
    #print("A中最贵的")
    #print(max(A))
    #print("B中最贵的")
    #print(max(B))
    #print("A中最便宜的")
    #print(min(A))
    #print("B中最贵的")
    #print(max(B))
    #print("A中最贵的")
    #print(max(A))
    #print("B中最便宜的")
    #print(min(B))
    #print("A中最便宜的")
    #print(min(A))
    #print("B中最便宜的")
    #print(min(B))
    #print("A中最贵的")
    #print(max(A))
    #print("B中最贵的")
    #print(max(B))
    #print("A中最便宜的")
    #print(min(A))
    #print("B中最贵的")
    #print(max(B))
    #print("A中最贵的")
    #print(max(A))
    #print("B中最便宜的")
    #print(min(B))
    #print("A中最便宜的")
    #print(min(A))
    #print("B中最便宜

if __name__ == '__main__':
    calculate()