def main():
    N = int(input())
    #print(N)
    T = []
    X = []
    A = []
    for i in range(N):
        t, x, a = map(int, input().split())
        T.append(t)
        X.append(x)
        A.append(a)
        #print(T, X, A)
    #print(T, X, A)
    #print(len(T))
    #print(len(X))
    #print(len(A))
    #print(T[0])
    #print(X[0])
    #print(A[0])
    #print(T[1])
    #print(X[1])
    #print(A[1])
    #print(T[2])
    #print(X[2])
    #print(A[2])
    #print(T[3])
    #print(X[3])
    #print(A[3])
    #print(T[4])
    #print(X[4])
    #print(A[4])
    #print(T[5])
    #print(X[5])
    #print(A[5])
    #print(T[6])
    #print(X[6])
    #print(A[6])
    #print(T[7])
    #print(X[7])
    #print(A[7])
    #print(T[8])
    #print(X[8])
    #print(A[8])
    #print(T[9])
    #print(X[9])
    #print(A[9])
    #print(T[0])
    #print(T[1])
    #print(T[2])
    #print(T[3])
    #print(T[4])
    #print(T[5])
    #print(T[6])
    #print(T[7])
    #print(T[8])
    #print(T[9])
    #print(X[0])
    #print(X[1])
    #print(X[2])
    #print(X[3])
    #print(X[4])
    #print(X[5])
    #print(X[6])
    #print(X[7])
    #print(X[8])
    #print(X[9])
    #print(A[0])
    #print(A[1])
    #print(A[2])
    #print(A[3])
    #print(A[4])
    #print(A[5])
    #print(A[6])
    #print(A

if __name__ == '__main__':
    main()