def main():
    N, M = map(int, input().split())
    k = []
    a = []
    for i in range(M):
        k.append(int(input()))
        a.append(list(map(int, input().split())))
    # print(k)
    # print(a)
    # print(N, M)
    # print(a[0][0])
    # print(a[1][0])
    # print(a[0][1])
    # print(a[1][1])
    # print(a[0][2])
    # print(a[1][2])
    # print(a[0][3])
    # print(a[1][3])
    # print(a[0][4])
    # print(a[1][4])
    # print(a[0][5])
    # print(a[1][5])
    # print(a[0][6])
    # print(a[1][6])
    # print(a[0][7])
    # print(a[1][7])
    # print(a[0][8])
    # print(a[1][8])
    # print(a[0][9])
    # print(a[1][9])
    # print(a[0][10])
    # print(a[1][10])
    # print(a[0][11])
    # print(a[1][11])
    # print(a[0][12])
    # print(a[1][12])
    # print(a[0][13])
    # print(a[1][13])
    # print(a[0][14])
    # print(a[1][14])
    # print(a[0][15])
    # print(a[1][15])
    # print(a[0][16])
    # print(a[1][16])
    # print(a[0][17])
    # print(a[1][17])
    # print(a[0][18])
    # print(a[1][18])
    # print(a[0][19])
    # print(a[1][19])
    # print(a[0][20])
    # print(a[1][20])
    # print(a[0][21])
    # print(a[1][21])
    # print(a[0][22])
    # print(a[1][22])
    # print(a[0][23])
    # print(a[1][23])
    # print(a[

if __name__ == '__main__':
    main()