def main():
    N = int(input())
    A = list(map(int, input().split()))
    Q = int(input())
    query = [input().split() for i in range(Q)]
    #print(N, A, Q, query)
    #print(query[0][0])
    #print(query[0][1])
    #print(query[0][2])
    #print(query[1][0])
    #print(query[1][1])
    #print(query[1][2])
    #print(query[2][0])
    #print(query[2][1])
    #print(query[2][2])
    #print(query[3][0])
    #print(query[3][1])
    #print(query[3][2])
    #print(query[4][0])
    #print(query[4][1])
    #print(query[4][2])
    #print(query[5][0])
    #print(query[5][1])
    #print(query[5][2])
    #print(query[6][0])
    #print(query[6][1])
    #print(query[6][2])
    #print(query[7][0])
    #print(query[7][1])
    #print(query[7][2])
    #print(query[8][0])
    #print(query[8][1])
    #print(query[8][2])
    #print(query[9][0])
    #print(query[9][1])
    #print(query[9][2])
    #print(query[10][0])
    #print(query[10][1])
    #print(query[10][2])
    #print(query[11][0])
    #print(query[11][1])
    #print(query[11][2])
    #print(query[12][0])
    #print(query[12][1])
    #print(query[12][2])
    #print(query[13][0])
    #print(query[13][1])
    #print(query[13][2])
    #print(query[14][0])
    #print(query[14][1])
    #print(query[14][2])
    #print(query[15][0])
    #print(query[15][1])
    #print(query[15][2])
    #print(query[16][0])
    #print(query[16][1])
