def main():
    n, k, d = map(int, input().split())
    A = list(map(int, input().split()))
    #print(n, k, d)
    #print(A)
    print("n:", n)
    print("k:", k)
    print("d:", d)
    print("A:", A)
    #print("A[0]:", A[0])
    #print("A[1]:", A[1])
    #print("A[2]:", A[2])
    #print("A[3]:", A[3])
    S = []
    for i in range(k):
        S.append(A[i])
    print("S:", S)
    #print("S[0]:", S[0])
    #print("S[1]:", S[1])
    #print("S[2]:", S[2])
    #print("S[3]:", S[3])
    #print("S[4]:", S[4])
    #print("S[5]:", S[5])
    #print("S[6]:", S[6])
    #print("S[7]:", S[7])
    #print("S[8]:", S[8])
    #print("S[9]:", S[9])
    #print("S[10]:", S[10])
    #print("S[11]:", S[11])
    #print("S[12]:", S[12])
    #print("S[13]:", S[13])
    #print("S[14]:", S[14])
    #print("S[15]:", S[15])
    #print("S[16]:", S[16])
    #print("S[17]:", S[17])
    #print("S[18]:", S[18])
    #print("S[19]:", S[19])
    #print("S[20]:", S[20])
    #print("S[21]:", S[21])
    #print("S[22]:", S[22])
    #print("S[23]:", S[23])
    #print("S[24]:", S[24])
    #print("S[25]:", S[25])
    #print("S[26]:", S[26])
    #print("

if __name__ == '__main__':
    main()