def main():
    N,M = map(int,input().split())
    A = [0] * M
    B = [0] * M
    for i in range(M):
        A[i],B[i] = map(int,input().split())
    #print(N,M,A,B)
    #print(A)
    #print(B)
    #print(A[0])
    #print(B[0])
    #print(A[1])
    #print(B[1])
    #print(A[2])
    #print(B[2])
    #print(A[3])
    #print(B[3])
    #print(A[4])
    #print(B[4])
    #print(A[5])
    #print(B[5])
    #print(A[6])
    #print(B[6])
    #print(A[7])
    #print(B[7])
    #print(A[8])
    #print(B[8])
    #print(A[9])
    #print(B[9])
    #print(A[10])
    #print(B[10])
    #print(A[11])
    #print(B[11])
    #print(A[12])
    #print(B[12])
    #print(A[13])
    #print(B[13])
    #print(A[14])
    #print(B[14])
    #print(A[15])
    #print(B[15])
    #print(A[16])
    #print(B[16])
    #print(A[17])
    #print(B[17])
    #print(A[18])
    #print(B[18])
    #print(A[19])
    #print(B[19])
    #print(A[20])
    #print(B[20])
    #print(A[21])
    #print(B[21])
    #print(A[22])
    #print(B[22])
    #print(A[23])
    #print(B[23])
    #print(A[24])
    #print(B[24])
    #print(A[25])
    #print(B[25])
    #print(A[26])
    #print(B[26])
    #print(A[27])
    #print(B[27])
    #print(A[28])
    #print(B[28])
    #print(A[29])
    #print(B[29])
    #print(A[30])
    #print(B

if __name__ == '__main__':
    main()