def main():
    N = int(input())
    T = []
    A = []
    for i in range(N):
        t, k, *a = map(int, input().split())
        T.append(t)
        A.append(a)
    #print(T)
    #print(A)
    #print(T[0])
    #print(A[0][0])
    #print(A[0][1])
    #print(A[0][2])
    #print(A[0][3])
    #print(A[0][4])
    #print(A[0][5])
    #print(T[1])
    #print(A[1][0])
    #print(A[1][1])
    #print(A[1][2])
    #print(A[1][3])
    #print(A[1][4])
    #print(A[1][5])
    #print(T[2])
    #print(A[2][0])
    #print(A[2][1])
    #print(A[2][2])
    #print(A[2][3])
    #print(A[2][4])
    #print(A[2][5])
    #print(T[3])
    #print(A[3][0])
    #print(A[3][1])
    #print(A[3][2])
    #print(A[3][3])
    #print(A[3][4])
    #print(A[3][5])
    #print(T[4])
    #print(A[4][0])
    #print(A[4][1])
    #print(A[4][2])
    #print(A[4][3])
    #print(A[4][4])
    #print(A[4][5])
    #print(T[5])
    #print(A[5][0])
    #print(A[5][1])
    #print(A[5][2])
    #print(A[5][3])
    #print(A[5][4])
    #print(A[5][5])
    #print(T[6])
    #print(A[6][0])
    #print(A[6][1])
    #print(A[6][2])
    #print(A[6][3])
    #print(A[6][4])
    #print(A[6][5])
    #print(T[7])
    #print(A[7][0

if __name__ == '__main__':
    main()