def main():
    A,B,C = map(int,input().split())
    #print(A,B,C)
    #print(type(A),type(B),type(C))
    #print(A+B+C)
    #print(type(A+B+C))
    #print(A/(A+B+C))
    #print(type(A/(A+B+C)))
    #print(1/(A/(A+B+C)))
    #print(type(1/(A/(A+B+C))))
    #print(1/(A/(A+B+C))+1/(B/(A+B+C))+1/(C/(A+B+C)))
    #print(type(1/(A/(A+B+C))+1/(B/(A+B+C))+1/(C/(A+B+C))))
    #print((A+B+C)/A+(A+B+C)/B+(A+B+C)/C)
    #print(type((A+B+C)/A+(A+B+C)/B+(A+B+C)/C))
    #print((A+B+C)/A+(A+B+C)/B+(A+B+C)/C-3)
    #print(type((A+B+C)/A+(A+B+C)/B+(A+B+C)/C-3))
    #print((A+B+C)/A+(A+B+C)/B+(A+B+C)/C-3+3)
    #print(type((A+B+C)/A+(A+B+C)/B+(A+B+C)/C-3+3))
    #print((A+B+C)/A+(A+B+C)/B+(A+B+C)/C-3+3-3)
    #print(type((A+B+C)/A+(A+B+C)/B+(A+B+C)/C-3+3-3))
    #print((A+B+C)/A+(A+B+C)/B+(A+B+C)/C-3+3-3+3)
    #print(type((A+B+C)/A+(A+B+C)/B+(A+B+C)/C-3+3-3+3))
    #print((A+B+C)/A+(A+B+C)/B+(A+B+C)/C-3+3-3+3-3)
    #print(type((A+B+C)/A+(A+B+C)/B+(A+B+C)/C-3+3-3+3-3))
    #print((A+B+C)/A+(A+B+C)/B+(A+B+C)/C-
