def main():
    x = input()
    n = int(input())
    s = []
    for i in range(n):
        s.append(input())
    #print(x)
    #print(n)
    #print(s)
    order = []
    for i in range(len(x)):
        order.append(x[i])
    #print(order)
    order.sort()
    #print(order)
    #print(order.index('z'))
    #print(order.index('a'))
    #print(order.index('b'))
    #print(order.index('c'))
    #print(order.index('d'))
    #print(order.index('e'))
    #print(order.index('f'))
    #print(order.index('g'))
    #print(order.index('h'))
    #print(order.index('i'))
    #print(order.index('j'))
    #print(order.index('k'))
    #print(order.index('l'))
    #print(order.index('m'))
    #print(order.index('n'))
    #print(order.index('o'))
    #print(order.index('p'))
    #print(order.index('q'))
    #print(order.index('r'))
    #print(order.index('s'))
    #print(order.index('t'))
    #print(order.index('u'))
    #print(order.index('v'))
    #print(order.index('w'))
    #print(order.index('x'))
    #print(order.index('y'))
    #print(order.index('z'))
    #print(order.index('a'))
    #print(order.index('b'))
    #print(order.index('c'))
    #print(order.index('d'))
    #print(order.index('e'))
    #print(order.index('f'))
    #print(order.index('g'))
    #print(order.index('h'))
    #print(order.index('i'))
    #print(order.index('j'))
    #print(order.index('k'))
    #print(order.index('l'))
    #print(order.index('m'))
    #print(order.index('n'))
    #print(order.index('o'))
    #print(order.index('p'))
    #print(order.index('q'))
    #print(order.index('r'))
    #print(order.index('s'))
    #print(order.index('t'))
    #print(order.index('u'))
    #print(order.index('v'))
    #print(order.index('w'))
    #print(order.index('x'))
    #print(order.index('y'))
    #print(order.index('z'))
