def main():
    s = input()
    s_len = len(s)
    # print(s_len)
    # print(s)
    # print(s[0])
    # print(s[s_len-1])
    # print(type(s))
    # print(type(s[0]))
    # print(type(s[s_len-1]))
    # print("s[0] = ", s[0])
    # print("s[s_len-1] = ", s[s_len-1])
    # print("s[0] = ", int(s[0]))
    # print("s[s_len-1] = ", int(s[s_len-1]))
    # print("s[0] = ", type(int(s[0])))
    # print("s[s_len-1] = ", type(int(s[s_len-1])))
    # print("s[0] = ", int(s[0]) * 10)
    # print("s[s_len-1] = ", int(s[s_len-1]) * 10)
    # print("s[0] = ", type(int(s[0]) * 10))
    # print("s[s_len-1] = ", type(int(s[s_len-1]) * 10))
    # print("s[0] = ", int(s[0]) * 100)
    # print("s[s_len-1] = ", int(s[s_len-1]) * 100)
    # print("s[0] = ", type(int(s[0]) * 100))
    # print("s[s_len-1] = ", type(int(s[s_len-1]) * 100))
    # print("s[0] = ", int(s[0]) * 1000)
    # print("s[s_len-1] = ", int(s[s_len-1]) * 1000)
    # print("s[0] = ", type(int(s[0]) * 1000))
    # print("s[s_len-1] = ", type(int(s[s_len-1]) * 1000))
    # print("s[0] = ", int(s[0]) * 10000)
    # print("s[s_len-1] = ", int(s[s_len-1]) * 10000)
    # print("s[0] = ", type(int(s[0]) * 10000))
    # print("s

if __name__ == '__main__':
    main()