def main():
    N = int(input())
    x_y = [list(map(int, input().split())) for _ in range(N)]
    x_y.sort()
    x_y = tuple(map(tuple, x_y))
    x_y = list(x_y)
    #print(x_y)
    #print(len(x_y))
    #print(x_y[0])
    #print(x_y[0][0])
    #print(x_y[0][1])
    #print(x_y[1])
    #print(x_y[1][0])
    #print(x_y[1][1])
    #print(x_y[2])
    #print(x_y[2][0])
    #print(x_y[2][1])
    #print(x_y[3])
    #print(x_y[3][0])
    #print(x_y[3][1])
    #print(x_y[4])
    #print(x_y[4][0])
    #print(x_y[4][1])
    #print(x_y[5])
    #print(x_y[5][0])
    #print(x_y[5][1])
    #print(x_y[6])
    #print(x_y[6][0])
    #print(x_y[6][1])
    #print(x_y[7])
    #print(x_y[7][0])
    #print(x_y[7][1])
    #print(x_y[8])
    #print(x_y[8][0])
    #print(x_y[8][1])
    #print(x_y[9])
    #print(x_y[9][0])
    #print(x_y[9][1])
    #print(x_y[10])
    #print(x_y[10][0])
    #print(x_y[10][1])
    #print(x_y[11])
    #print(x_y[11][0])
    #print(x_y[11][1])
    #print(x_y[12])
    #print(x_y[12][0])
    #print(x_y[12][1])
    #print(x_y[13])
    #print(x_y[13][0])
    #print(x_y[13][1])
    #print(x_y[14])
    #print(x_y[14][0])
    #print(x_y[14][1])
    #print(x_y[15])
    #print(x_y[15][

if __name__ == '__main__':
    main()