def main():
    n, s = map(int, input().split())
    cards = []
    for i in range(n):
        a, b = map(int, input().split())
        cards.append((a, b))
    # print(cards)
    # print(n, s)
    # print(cards[0][0])
    # print(cards[0][1])
    # print(cards[1][0])
    # print(cards[1][1])
    # print(cards[2][0])
    # print(cards[2][1])
    # print(cards[3][0])
    # print(cards[3][1])
    # print(cards[4][0])
    # print(cards[4][1])
    # print(cards[0][0])
    # print(cards[0][1])
    # print(cards[1][0])
    # print(cards[1][1])
    # print(cards[2][0])
    # print(cards[2][1])
    # print(cards[3][0])
    # print(cards[3][1])
    # print(cards[4][0])
    # print(cards[4][1])
    # print(cards[0][0])
    # print(cards[0][1])
    # print(cards[1][0])
    # print(cards[1][1])
    # print(cards[2][0])
    # print(cards[2][1])
    # print(cards[3][0])
    # print(cards[3][1])
    # print(cards[4][0])
    # print(cards[4][1])
    # print(cards[0][0])
    # print(cards[0][1])
    # print(cards[1][0])
    # print(cards[1][1])
    # print(cards[2][0])
    # print(cards[2][1])
    # print(cards[3][0])
    # print(cards[3][1])
    # print(cards[4][0])
    # print(cards[4][1])
    # print(cards[0][0])
    # print(cards[0][1])
    # print(cards[1][0])
    # print(cards[1][1])
    # print(cards[2][0])
    # print(cards[2][1])
    # print(cards[3][0])
    # print(cards[3][1])
    # print(cards[4][0])
    #
