def main():
    n, m = map(int, input().split())
    a = list(map(int, input().split()))
    a.sort()
    #print(a)
    #print("a[0]:", a[0])
    #print("a[0] % m:", a[0] % m)
    #print("m - a[0]:", m - a[0])
    #print("m - a[0] % m:", m - a[0] % m)
    #print("m - a[0] % m:", (m - a[0] % m) % m)
    #print("m - a[0] % m:", (m - a[0] % m) % m)
    #print("a[0] + m - a[0] % m:", a[0] + (m - a[0] % m))
    #print("a[0] + m - a[0] % m:", (a[0] + (m - a[0] % m)) % m)
    #print("a[1]:", a[1])
    #print("a[1] % m:", a[1] % m)
    #print("m - a[1]:", m - a[1])
    #print("m - a[1] % m:", m - a[1] % m)
    #print("m - a[1] % m:", (m - a[1] % m) % m)
    #print("m - a[1] % m:", (m - a[1] % m) % m)
    #print("a[1] + m - a[1] % m:", a[1] + (m - a[1] % m))
    #print("a[1] + m - a[1] % m:", (a[1] + (m - a[1] % m)) % m)
    #print("a[2]:", a[2])
    #print("a[2] % m:", a[2] % m)
    #print("m - a[2]:", m - a[2])
    #print("m - a[2] % m:", m - a[2] % m)
    #print("m - a[2] % m

if __name__ == '__main__':
    main()