def main():
    N,M = map(int,input().split())
    A = list(map(int,input().split()))
    A.sort()
    #print(A)
    #print(N,M)
    #print(A)
    #print("-------------")
    #print("A[0] = ",A[0])
    #print("A[1] = ",A[1])
    #print("A[2] = ",A[2])
    #print("A[3] = ",A[3])
    #print("A[4] = ",A[4])
    #print("A[5] = ",A[5])
    #print("A[6] = ",A[6])
    #print("A[7] = ",A[7])
    #print("A[8] = ",A[8])
    #print("A[9] = ",A[9])
    #print("A[10] = ",A[10])
    #print("A[11] = ",A[11])
    #print("A[12] = ",A[12])
    #print("A[13] = ",A[13])
    #print("A[14] = ",A[14])
    #print("A[15] = ",A[15])
    #print("A[16] = ",A[16])
    #print("A[17] = ",A[17])
    #print("A[18] = ",A[18])
    #print("A[19] = ",A[19])
    #print("-------------")
    #print("A[0]%M = ",A[0]%M)
    #print("A[1]%M = ",A[1]%M)
    #print("A[2]%M = ",A[2]%M)
    #print("A[3]%M = ",A[3]%M)
    #print("A[4]%M = ",A[4]%M)
    #print("A[5]%M = ",A[5]%M)
    #print("A[6]%M = ",A[6]%M)
    #print("A[7]%M = ",A[7]%M)
    #print("A[8]%M = ",A[8]%M)
    #print("A[9]%M = ",A[

if __name__ == '__main__':
    main()