def main():
    n = int(input())
    s = [input() for _ in range(n)]
    t = [input() for _ in range(n)]
    # print(s)
    # print(t)
    # print(s[0])
    # print(s[0][0])
    # print(s[0][1])
    # print(s[0][2])
    # print(s[0][3])
    # print(s[0][4])
    # print(s[1])
    # print(s[1][0])
    # print(s[1][1])
    # print(s[1][2])
    # print(s[1][3])
    # print(s[1][4])
    # print(s[2])
    # print(s[2][0])
    # print(s[2][1])
    # print(s[2][2])
    # print(s[2][3])
    # print(s[2][4])
    # print(s[3])
    # print(s[3][0])
    # print(s[3][1])
    # print(s[3][2])
    # print(s[3][3])
    # print(s[3][4])
    # print(s[4])
    # print(s[4][0])
    # print(s[4][1])
    # print(s[4][2])
    # print(s[4][3])
    # print(s[4][4])
    # print(t[0])
    # print(t[0][0])
    # print(t[0][1])
    # print(t[0][2])
    # print(t[0][3])
    # print(t[0][4])
    # print(t[1])
    # print(t[1][0])
    # print(t[1][1])
    # print(t[1][2])
    # print(t[1][3])
    # print(t[1][4])
    # print(t[2])
    # print(t[2][0])
    # print(t[2][1])
    # print(t[2][2])
    # print(t[2][3])
    # print(t[2][4])
    # print(t[3])
    # print(t[3][0])
    # print(t[3][1])
    # print(t[3][2])
    # print(t[3][3

if __name__ == '__main__':
    main()