def main():
    n = int(input())
    edge = []
    for i in range(n-1):
        u, v, w = map(int, input().split())
        edge.append([u, v, w])
    edge.sort(key=lambda x:x[2])
    #print(edge)
    #print(edge[0])
    #print(edge[0][2])
    #print(edge[0][0])
    #print(edge[0][1])
    #print(edge[1])
    #print(edge[1][2])
    #print(edge[1][0])
    #print(edge[1][1])
    #print(edge[2])
    #print(edge[2][2])
    #print(edge[2][0])
    #print(edge[2][1])
    #print(edge[3])
    #print(edge[3][2])
    #print(edge[3][0])
    #print(edge[3][1])
    #print(edge[4])
    #print(edge[4][2])
    #print(edge[4][0])
    #print(edge[4][1])
    #print(edge[5])
    #print(edge[5][2])
    #print(edge[5][0])
    #print(edge[5][1])
    #print(edge[6])
    #print(edge[6][2])
    #print(edge[6][0])
    #print(edge[6][1])
    #print(edge[7])
    #print(edge[7][2])
    #print(edge[7][0])
    #print(edge[7][1])
    #print(edge[8])
    #print(edge[8][2])
    #print(edge[8][0])
    #print(edge[8][1])
    #print(edge[9])
    #print(edge[9][2])
    #print(edge[9][0])
    #print(edge[9][1])
    #print(edge[10])
    #print(edge[10][2])
    #print(edge[10][0])
    #print(edge[10][1])
    #print(edge[11])
    #print(edge[11][2])
    #print(edge[11][0])
    #print(edge[11][1])
    #print(edge[12])
    #print(edge[12][2])
    #print(edge[12][0])
    #print(edge[12][
