def main():
    n = int(input())
    a = list(map(int, input().split()))
    a.sort()
    a.reverse()
    #print(a)
    #print(len(a))
    count = 0
    for i in range(len(a)):
        #print(a[i])
        #print(i)
        #print(len(a))
        #print("i",i)
        #print("len",len(a))
        #print("a[i]",a[i])
        #print("a[i+1]",a[i+1])
        #print("a[i+2]",a[i+2])
        #print("a[i+3]",a[i+3])
        #print("a[i+4]",a[i+4])
        #print("a[i+5]",a[i+5])
        #print("a[i+6]",a[i+6])
        #print("a[i+7]",a[i+7])
        #print("a[i+8]",a[i+8])
        #print("a[i+9]",a[i+9])
        #print("a[i+10]",a[i+10])
        #print("a[i+11]",a[i+11])
        #print("a[i+12]",a[i+12])
        #print("a[i+13]",a[i+13])
        #print("a[i+14]",a[i+14])
        #print("a[i+15]",a[i+15])
        #print("a[i+16]",a[i+16])
        #print("a[i+17]",a[i+17])
        #print("a[i+18]",a[i+18])
        #print("a[i+19]",a[i+19])
        #print("a[i+20]",a[i+20])
        #print("a[i+21]",a[i+21])
        #print("a[i+22]",a[i+22])
        #print("a[i+23]",a[i+23])
        #print("a[i+24]",a[i+24])
        #print("a[i+25]",a[i+25])
        #print("a[i+26]",a[i+26])
        #print("a[i+27]",a[i+27])
        #print("a[i+28]",a[i+28])
        #print("a[i+29]",a[i+
