def main():
    n, k = map(int, input().split())
    a = list(map(int, input().split()))
    maxa = max(a)
    maxa_bin = bin(maxa)[2:]
    maxa_bin_len = len(maxa_bin)
    k_bin = bin(k)[2:]
    k_bin_len = len(k_bin)
    # print(k_bin)
    # print(maxa_bin)
    # print(k_bin_len)
    # print(maxa_bin_len)
    # print(maxa_bin_len - k_bin_len)
    if maxa_bin_len - k_bin_len > 0:
        for i in range(maxa_bin_len - k_bin_len):
            k_bin = '0' + k_bin
    # print(k_bin)
    # print(maxa_bin)
    # print(k_bin_len)
    # print(maxa_bin_len)
    # print(maxa_bin_len - k_bin_len)
    # print(k_bin)
    # print(maxa_bin)
    # print(k_bin_len)
    # print(maxa_bin_len)
    # print(maxa_bin_len - k_bin_len)
    # print(k_bin)
    # print(maxa_bin)
    # print(k_bin_len)
    # print(maxa_bin_len)
    # print(maxa_bin_len - k_bin_len)
    # print(k_bin)
    # print(maxa_bin)
    # print(k_bin_len)
    # print(maxa_bin_len)
    # print(maxa_bin_len - k_bin_len)
    # print(k_bin)
    # print(maxa_bin)
    # print(k_bin_len)
    # print(maxa_bin_len)
    # print(maxa_bin_len - k_bin_len)
    # print(k_bin)
    # print(maxa_bin)
    # print(k_bin_len)
    # print(maxa_bin_len)
    # print(maxa_bin_len - k_bin_len)
    # print(k_bin)
    # print(maxa_bin)
    # print(k_bin_len)
    # print(maxa_bin_len)
    # print(maxa_bin_len - k_bin_len)
    # print(k_bin)
    # print(maxa_bin)
    # print(k_bin_len)
    # print(maxa_bin_len)
    # print(maxa_bin_len - k_bin_len)
    # print(k_bin)
    # print(maxa_bin)
    # print(k_bin_len)
    # print(maxa_bin_len)

if __name__ == '__main__':
    main()