def main():
    n, k = map(int, input().split())
    a = list(map(int, input().split()))
    a = [i - 1 for i in a]
    #print(a)
    #print(n, k)
    #print(a)
    #print(a[0])
    #print(a[a[0]])
    #print(a[a[a[0]]])
    #print(a[a[a[a[0]]]])
    #print(a[a[a[a[a[0]]]]])
    #print(a[a[a[a[a[a[0]]]]]])
    #print(a[a[a[a[a[a[a[0]]]]]]])
    #print(a[a[a[a[a[a[a[a[0]]]]]]]])
    #print(a[a[a[a[a[a[a[a[a[0]]]]]]]]])
    #print(a[a[a[a[a[a[a[a[a[a[0]]]]]]]]]])
