def main():
    n = int(input())
    #n = 576461302059761664
    #n = 11
    #n = 0
    #n = 1
    #print(bin(n))
    #print(bin(n)[2:])
    #print(len(bin(n)[2:]))
    #print(bin(n).count('1'))
    #print(bin(n).count('0'))
    #print(bin(n).count('1') + bin(n).count('0'))
    #print(bin(n).count('1'))
    #print(bin(n).count('0'))
    #print(bin(n).count('1') + bin(n).count('0'))
    #print(bin(n).count('1'))
    #print(bin(n).count('0'))
    #print(bin(n).count('1') + bin(n).count('0'))
    #print(bin(n).count('1'))
    #print(bin(n).count('0'))
    #print(bin(n).count('1') + bin(n).count('0'))
    #print(bin(n).count('1'))
    #print(bin(n).count('0'))
    #print(bin(n).count('1') + bin(n).count('0'))
    #print(bin(n).count('1'))
    #print(bin(n).count('0'))
    #print(bin(n).count('1') + bin(n).count('0'))
    #print(bin(n).count('1'))
    #print(bin(n).count('0'))
    #print(bin(n).count('1') + bin(n).count('0'))
    #print(bin(n).count('1'))
    #print(bin(n).count('0'))
    #print(bin(n).count('1') + bin(n).count('0'))
    #print(bin(n).count('1'))
    #print(bin(n).count('0'))
    #print(bin(n).count('1') + bin(n).count('0'))
    #print('')
    #print(bin(n).count('1'))
    #print(bin(n).count('0'))
    #print(bin(n).count('1') + bin(n).count('0'))
    #print('')
    #print(bin(n).count('1'))
    #print(bin(n).count('0'))
    #print(bin(n).count('1') + bin(n).count('0'))
    #print('')
    #

if __name__ == '__main__':
    main()