def main():
    N = int(input())
    X = []
    Y = []
    P = []
    for i in range(N):
        x,y,p = map(int,input().split())
        X.append(x)
        Y.append(y)
        P.append(p)
    #print(X)
    #print(Y)
    #print(P)
    #print(N)
    #print(X[0])
    #print(Y[0])
    #print(P[0])
    #print(X[1])
    #print(Y[1])
    #print(P[1])
    #print(X[2])
    #print(Y[2])
    #print(P[2])
    #print(X[3])
    #print(Y[3])
    #print(P[3])
    #print(X[4])
    #print(Y[4])
    #print(P[4])
    #print(X[5])
    #print(Y[5])
    #print(P[5])
    #print(X[6])
    #print(Y[6])
    #print(P[6])
    #print(X[7])
    #print(Y[7])
    #print(P[7])
    #print(X[8])
    #print(Y[8])
    #print(P[8])
    #print(X[9])
    #print(Y[9])
    #print(P[9])
    #print(X[10])
    #print(Y[10])
    #print(P[10])
    #print(X[11])
    #print(Y[11])
    #print(P[11])
    #print(X[12])
    #print(Y[12])
    #print(P[12])
    #print(X[13])
    #print(Y[13])
    #print(P[13])
    #print(X[14])
    #print(Y[14])
    #print(P[14])
    #print(X[15])
    #print(Y[15])
    #print(P[15])
    #print(X[16])
    #print(Y[16])
    #print(P[16])
    #print(X[17])
    #print(Y[17])
    #print(P[17])
    #print(X[18])
    #print(Y[18])
    #print(P[18])
    #print(X[19])
    #print(Y[19])
    #print(P[19])
    #print(X[20])

if __name__ == '__main__':
    main()