def main():
    S = input()
    S = S.replace('ww','w w')
    S = S.replace('vv','v v')
    S = S.replace('wv','w v')
    S = S.replace('vw','v w')
    S = S.replace('vv','v v')
    S = S.replace('ww','w w')
    S = S.replace('wv','w v')
    S = S.replace('vw','v w')
    S = S.replace('vv','v v')
    S = S.replace('ww','w w')
    S = S.replace('wv','w v')
    S = S.replace('vw','v w')
    S = S.replace('vv','v v')
    S = S.replace('ww','w w')
    S = S.replace('wv','w v')
    S = S.replace('vw','v w')
    S = S.replace('vv','v v')
    S = S.replace('ww','w w')
    S = S.replace('wv','w v')
    S = S.replace('vw','v w')
    S = S.replace('vv','v v')
    S = S.replace('ww','w w')
    S = S.replace('wv','w v')
    S = S.replace('vw','v w')
    S = S.replace('vv','v v')
    S = S.replace('ww','w w')
    S = S.replace('wv','w v')
    S = S.replace('vw','v w')
    S = S.replace('vv','v v')
    S = S.replace('ww','w w')
    S = S.replace('wv','w v')
    S = S.replace('vw','v w')
    S = S.replace('vv','v v')
    print(len(S))

if __name__ == '__main__':
    main()