def main():
    n,k = map(int,input().split())
    a = list(map(int,input().split()))
    #print(n,k,a)
    #print(bin(k)[2:])
    #print(bin(a[0])[2:])
    #print(bin(a[1])[2:])
    #print(bin(a[2])[2:])
    #print(bin(a[3])[2:])
    #print(bin(a[4])[2:])
    #print(bin(a[5])[2:])
    #print(bin(a[6])[2:])
    #print(bin(a[7])[2:])
    #print(bin(a[8])[2:])
    #print(bin(a[9])[2:])
    #print(bin(a[10])[2:])
    #print(bin(a[11])[2:])
    #print(bin(a[12])[2:])
    #print(bin(a[13])[2:])
    #print(bin(a[14])[2:])
    #print(bin(a[15])[2:])
    #print(bin(a[16])[2:])
    #print(bin(a[17])[2:])
    #print(bin(a[18])[2:])
    #print(bin(a[19])[2:])
    #print(bin(a[20])[2:])
    #print(bin(a[21])[2:])
    #print(bin(a[22])[2:])
    #print(bin(a[23])[2:])
    #print(bin(a[24])[2:])
    #print(bin(a[25])[2:])
    #print(bin(a[26])[2:])
    #print(bin(a[27])[2:])
    #print(bin(a[28])[2:])
    #print(bin(a[29])[2:])
    #print(bin(a[30])[2:])
    #print(bin(a[31])[2:])
    #print(bin(a[32])[2:])
    #print(bin(a[33])[2:])
    #print(bin(a[34])[2:])
    #print(bin(a[35])[2:])
    #print(bin(a[36])[2:])
    #print(bin(a[37])[2:])
    #print(bin(a[38])[2:])
    #print(bin(a[39])[2:])
    #print(bin(a[40])[2:])
    #print(bin(a[41])[2:])
    #print(bin(a[42])[2:])
    #print(bin(a[43])[2:])
    #print(bin(a[44])[2:])
    #print(bin(a[45])[2:])
    #print

if __name__ == '__main__':
    main()