def main():
    L, Q = map(int, input().split())
    X = [0] * (Q + 1)
    for i in range(1, Q + 1):
        c, x = map(int, input().split())
        X[i] = x
    X.sort()
    #print(X)
    #print(L)
    #print(Q)
    #print(X)
    #print(X[1])
    #print(X[2])
    #print(X[3])
    #print(X[4])
    #print(X[5])
    #print(X[6])
    #print(X[7])
    #print(X[8])
    #print(X[9])
    #print(X[10])
    #print(X[11])
    #print(X[12])
    #print(X[13])
    #print(X[14])
    #print(X[15])
    #print(X[16])
    #print(X[17])
    #print(X[18])
    #print(X[19])
    #print(X[20])
    #print(X[21])
    #print(X[22])
    #print(X[23])
    #print(X[24])
    #print(X[25])
    #print(X[26])
    #print(X[27])
    #print(X[28])
    #print(X[29])
    #print(X[30])
    #print(X[31])
    #print(X[32])
    #print(X[33])
    #print(X[34])
    #print(X[35])
    #print(X[36])
    #print(X[37])
    #print(X[38])
    #print(X[39])
    #print(X[40])
    #print(X[41])
    #print(X[42])
    #print(X[43])
    #print(X[44])
    #print(X[45])
    #print(X[46])
    #print(X[47])
    #print(X[48])
    #print(X[49])
    #print(X[50])
    #print(X[51])
    #print(X[52])
    #print(X[53])
    #print(X[54])
    #print(X[55])
    #print(X[56])
    #print(X[57])
    #print(X[58])
    #print(X[59])
    #print(X

if __name__ == '__main__':
    main()