def main():
    N = int(input())
    A = []
    B = []
    for i in range(N):
        a,b = [int(i) for i in input().split()]
        A.append(a)
        B.append(b)
    #print(A)
    #print(B)
    #print(N)
    #print("Hello World")
    #print(A)
    #print(B)
    #print(N)
    #print("Hello World")
    #print(A)
    #print(B)
    #print(N)
    #print("Hello World")
    #print(A)
    #print(B)
    #print(N)
    #print("Hello World")
    #print(A)
    #print(B)
    #print(N)
    #print("Hello World")
    #print(A)
    #print(B)
    #print(N)
    #print("Hello World")
    #print(A)
    #print(B)
    #print(N)
    #print("Hello World")
    #print(A)
    #print(B)
    #print(N)
    #print("Hello World")
    #print(A)
    #print(B)
    #print(N)
    #print("Hello World")
    #print(A)
    #print(B)
    #print(N)
    #print("Hello World")
    #print(A)
    #print(B)
    #print(N)
    #print("Hello World")
    #print(A)
    #print(B)
    #print(N)
    #print("Hello World")
    #print(A)
    #print(B)
    #print(N)
    #print("Hello World")
    #print(A)
    #print(B)
    #print(N)
    #print("Hello World")
    #print(A)
    #print(B)
    #print(N)
    #print("Hello World")
    #print(A)
    #print(B)
    #print(N)
    #print("Hello World")
    #print(A)
    #print(B)
    #print(N)
    #print("Hello World")
    #print(A)
    #print(B)
    #print(N)
    #print("Hello World")
    #print(A)
    #print(B)
    #print(N)
    #print("Hello World")
    #print(A)
    #print(B)
    #print(N)
    #print("Hello World")
