def main():
  n,x,y = map(int,input().split())
  edge = [[] for _ in range(n+1)]
  for _ in range(n-1):
    u,v = map(int,input().split())
    edge[u].append(v)
    edge[v].append(u)
  #print(edge)
  #xからyへのパスを探す
  #dfsで探索
  #print(edge[x])
  #print(edge[y])
  #print(edge[x][0])
  #print(edge[y][0])
  #print(edge[edge[x][0]])
  #print(edge[edge[y][0]])
  #print(edge[edge[y][0]][0])
  #print(edge[edge[y][0]][1])
  #print(edge[edge[y][0]][2])
  #print(edge[edge[y][0]][3])
  #print(edge[edge[y][0]][4])
  #print(edge[edge[y][0]][5])
  #print(edge[edge[y][0]][6])
  #print(edge[edge[y][0]][7])
  #print(edge[edge[y][0]][8])
  #print(edge[edge[y][0]][9])
  #print(edge[edge[y][0]][10])
  #print(edge[edge[y][0]][11])
  #print(edge[edge[y][0]][12])
  #print(edge[edge[y][0]][13])
  #print(edge[edge[y][0]][14])
  #print(edge[edge[y][0]][15])
  #print(edge[edge[y][0]][16])
  #print(edge[edge[y][0]][17])
  #print(edge[edge[y][0]][18])
  #print(edge[edge[y][0]][19])
  #print(edge[edge[y][0]][20])
  #print(edge[edge[y][0]][21])
  #print(edge[edge[y][0]][22])
  #print(edge[edge[y][0]][23])
  #print(edge[edge[y][0]][24])
  #print(edge[edge[y][0]][25])
  #print(edge[edge[y][0]][26])
  #print(edge[edge[y][0]][27])
  #print(edge[edge[y][0]][28])
  #print(edge[edge[y][0]][29])
  #print(edge[edge[y][0]][30])
  #print(edge[edge[y][0]][31])
  #print(edge[edge[y][0]][32])
  #print(edge[edge
