def main():
    N, M = map(int, input().split())
    #print(N, M)
    K = []
    A = []
    for i in range(M):
        k = int(input())
        K.append(k)
        a = list(map(int, input().split()))
        A.append(a)
    #print(K)
    #print(A)
    #print(N, M, K, A)
    #print(N, M, K, A)
    #print(K)
    #print(A)
    #print(N, M, K, A)
    #print(N, M, K, A)
    #print(K)
    #print(A)
    #print(N, M, K, A)
    #print(N, M, K, A)
    #print(K)
    #print(A)
    #print(N, M, K, A)
    #print(N, M, K, A)
    #print(K)
    #print(A)
    #print(N, M, K, A)
    #print(N, M, K, A)
    #print(K)
    #print(A)
    #print(N, M, K, A)
    #print(N, M, K, A)
    #print(K)
    #print(A)
    #print(N, M, K, A)
    #print(N, M, K, A)
    #print(K)
    #print(A)
    #print(N, M, K, A)
    #print(N, M, K, A)
    #print(K)
    #print(A)
    #print(N, M, K, A)
    #print(N, M, K, A)
    #print(K)
    #print(A)
    #print(N, M, K, A)
    #print(N, M, K, A)
    #print(K)
    #print(A)
    #print(N, M, K, A)
    #print(N, M, K, A)
    #print(K)
    #print(A)
    #print(N, M, K, A)
    #print(N, M, K, A)
    #print(K)
    #print(A)
    #print(N, M, K, A)
    #print(N, M, K, A)
    #print(K)
    #print(A)
    #print(N, M, K, A)

if __name__ == '__main__':
    main()