def main():
    k = int(input())
    #print(k)
    #print(type(k))
    #print(bin(k))
    #print(type(bin(k)))
    #print(bin(k)[2:])
    #print(type(bin(k)[2:]))
    #print(len(bin(k)[2:]))
    #print(type(len(bin(k)[2:])))
    #print(bin(k)[2:].count('0'))
    #print(type(bin(k)[2:].count('0')))
    #print(bin(k)[2:].count('2'))
    #print(type(bin(k)[2:].count('2')))
    #print(bin(k)[2:].count('0') + bin(k)[2:].count('2'))
    #print(type(bin(k)[2:].count('0') + bin(k)[2:].count('2')))
    #print(bin(k)[2:].count('0') + bin(k)[2:].count('2') == len(bin(k)[2:]))
    #print(type(bin(k)[2:].count('0') + bin(k)[2:].count('2') == len(bin(k)[2:])))
    #print(bin(k)[2:].count('0') + bin(k)[2:].count('2') == len(bin(k)[2:]) and bin(k)[2:].count('2') == 1)
    #print(type(bin(k)[2:].count('0') + bin(k)[2:].count('2') == len(bin(k)[2:]) and bin(k)[2:].count('2') == 1))
    #print(bin(k)[2:].count('0') + bin(k)[2:].count('2') == len(bin(k)[2:]) and bin(k)[2:].count('2') == 1 and bin(k)[2:].count('0') == 0)
    #print(type(bin(k)[2:].count('0') + bin(k)[2:].count('2') == len(bin(k)[2:]) and bin(k)[2:].count('2') == 1 and bin(k)[2:].count('0') == 0))
    #print(bin(k)[2:].count('0') + bin(k)[2:].count('2') == len(bin(k)[2:]) and bin(k)[2:].count('2') == 1 and bin(k)[2:].count('0') == 0 and k % 2 == 0)
    #print(type(bin(k)[2:].

if __name__ == '__main__':
    main()