def main():
    H, W, K = map(int, input().split())
    #print(H, W, K)
    #print(type(H), type(W), type(K))
    #print(H, W, K)
    #print(type(H), type(W), type(K))
    #print(H, W, K)
    #print(type(H), type(W), type(K))
    #print(H, W, K)
    #print(type(H), type(W), type(K))
    #print(H, W, K)
    #print(type(H), type(W), type(K))
    #print(H, W, K)
    #print(type(H), type(W), type(K))
    #print(H, W, K)
    #print(type(H), type(W), type(K))
    #print(H, W, K)
    #print(type(H), type(W), type(K))
    #print(H, W, K)
    #print(type(H), type(W), type(K))
