def problem211_c():
    #读取输入
    s = input()
    #print(s)
    #print(len(s))
    #print(s[0])
    #print(ord(s[0]))
    #print(chr(ord(s[0])+1))
    #print(chr(ord(s[0])-1))
    #print(ord('a'))
    #print(ord('z'))
    #print(ord('A'))
    #print(ord('Z'))
    #print(ord('0'))
    #print(ord('9'))
    #print(ord(' '))
    #print(ord('\\'))
    #print(ord('`'))
    #print(ord('{'))
    #print(ord('~'))
    #print(ord('!'))
    #print(ord('@'))
    #print(ord('#'))
    #print(ord('$'))
    #print(ord('%'))
    #print(ord('^'))
    #print(ord('&'))
    #print(ord('*'))
    #print(ord('('))
    #print(ord(')'))
    #print(ord('-'))
    #print(ord('_'))
    #print(ord('+'))
    #print(ord('='))
    #print(ord('['))
    #print(ord(']'))
    #print(ord('|'))
    #print(ord(';'))
    #print(ord(':'))
    #print(ord

if __name__ == '__main__':
    problem211_c()