def main():
    n = int(input())
    x, y = map(int, input().split())
    a = []
    b = []
    for i in range(n):
        ai, bi = map(int, input().split())
        a.append(ai)
        b.append(bi)
    #print(a)
    #print(b)
    #print(x)
    #print(y)
    #print(n)
    #print(len(a))
    #print(len(b))
    #print(len(a) == len(b))
    #print(len(a) == n)
    #print(len(b) == n)
    #print(len(a) == len(b) == n)
    #print(len(a) == len(b) == n == True)
    #print(len(a) == len(b) == n == True == True)
    #print(len(a) == len(b) == n == True == True == True)
    #print(len(a) == len(b) == n == True == True == True == True)
    #print(len(a) == len(b) == n == True == True == True == True == True)
    #print(len(a) == len(b) == n == True == True == True == True == True == True)
    #print(len(a) == len(b) == n == True == True == True == True == True == True == True)
    #print(len(a) == len(b) == n == True == True == True == True == True == True == True == True)
    #print(len(a) == len(b) == n == True == True == True == True == True == True == True == True == True)
    #print(len(a) == len(b) == n == True == True == True == True == True == True == True == True == True == True)
    #print(len(a) == len(b) == n == True == True == True == True == True == True == True == True == True == True == True)
    #print(len(a) == len(b) == n == True == True == True == True == True == True == True == True == True == True == True == True)
    #print(len(a) == len(b) == n == True == True == True == True == True == True == True == True == True == True == True == True == True)
    #print(len(a) == len(b) == n ==
