def main():
    n, k = map(int, input().split())
    p = list(map(int, input().split()))
    # print(n, k, p)
    # print(len(p))
    # print(p[0])
    # print(p[n-1])
    # print(p[n])
    # print(p[n+1])
    # print(p[n+2])
    # print(p[n-1])
    # print(p[n-1] - 1)
    # print(p[n-1] - 2)
    # print(p[n-1] - 3)
    # print(p[n-1] - 4)
    # print(p[n-1] - 5)
    # print(p[n-1] - 6)
    # print(p[n-1] - 7)
    # print(p[n-1] - 8)
    # print(p[n-1] - 9)
    # print(p[n-1] - 10)
    # print(p[n-1] - 11)
    # print(p[n-1] - 12)
    # print(p[n-1] - 13)
    # print(p[n-1] - 14)
    # print(p[n-1] - 15)
    # print(p[n-1] - 16)
    # print(p[n-1] - 17)
    # print(p[n-1] - 18)
    # print(p[n-1] - 19)
    # print(p[n-1] - 20)
    # print(p[n-1] - 21)
    # print(p[n-1] - 22)
    # print(p[n-1] - 23)
    # print(p[n-1] - 24)
    # print(p[n-1] - 25)
    # print(p[n-1] - 26)
    # print(p[n-1] - 27)
    # print(p[n-1] - 28)
    # print(p[n-1] - 29)
    # print(p[n-1] - 30)
    # print(p[n-1] - 31)
    # print(p[n-1] - 32)
    # print(p[n-1] - 33)
    # print(p[n-1] - 34)
    # print(p[n-1

if __name__ == '__main__':
    main()