def main():
    N, K = map(int, input().split())
    P = list(map(int, input().split()))
    # print(N, K, P)
    # print(P.index(1))
    # print(P.index(2))
    # print(P.index(3))
    # print(P.index(4))
    # print(P.index(5))
    # print(P.index(6))
    # print(P.index(7))
    # print(P.index(8))
    # print(P.index(9))
    # print(P.index(10))
    # print(P.index(11))
    # print(P.index(12))
    # print(P.index(13))
    # print(P.index(14))
    # print(P.index(15))
    # print(P.index(16))
    # print(P.index(17))
    # print(P.index(18))
    # print(P.index(19))
    # print(P.index(20))
    # print(P.index(21))
    # print(P.index(22))
    # print(P.index(23))
    # print(P.index(24))
    # print(P.index(25))
    # print(P.index(26))
    # print(P.index(27))
    # print(P.index(28))
    # print(P.index(29))
    # print(P.index(30))
    # print(P.index(31))
    # print(P.index(32))
    # print(P.index(33))
    # print(P.index(34))
    # print(P.index(35))
    # print(P.index(36))
    # print(P.index(37))
    # print(P.index(38))
    # print(P.index(39))
    # print(P.index(40))
    # print(P.index(41))
    # print(P.index(42))
    # print(P.index(43))
    # print(P.index(44))
    # print(P.index(45))
    # print(P.index(46))
    # print(P.index(47))
    # print(P.index(48))
    # print(P.index(49))
    # print(P.index(50))
    # print(P.index(51))
    # print(P.index(52))
    # print(P.index(53))
    # print(P.index(54))
    # print(P.index(55))
    # print(P.index(56))
    # print(P.index(57))
    # print(P.index(58))
    #

if __name__ == '__main__':
    main()