def main():
    N = int(input())
    A = int(input())
    B = int(input())
    C = int(input())
    D = int(input())
    E = int(input())
    #print(N,A,B,C,D,E)
    #print("N:{}".format(N))
    #print("A:{}".format(A))
    #print("B:{}".format(B))
    #print("C:{}".format(C))
    #print("D:{}".format(D))
    #print("E:{}".format(E))
    #print("N:{}".format(N))
    #print("A:{}".format(A))
    #print("B:{}".format(B))
    #print("C:{}".format(C))
    #print("D:{}".format(D))
    #print("E:{}".format(E))
    #print("N:{}".format(N))
    #print("A:{}".format(A))
    #print("B:{}".format(B))
    #print("C:{}".format(C))
    #print("D:{}".format(D))
    #print("E:{}".format(E))
    #print("N:{}".format(N))
    #print("A:{}".format(A))
    #print("B:{}".format(B))
    #print("C:{}".format(C))
    #print("D:{}".format(D))
    #print("E:{}".format(E))
    #print("N:{}".format(N))
    #print("A:{}".format(A))
    #print("B:{}".format(B))
    #print("C:{}".format(C))
    #print("D:{}".format(D))
    #print("E:{}".format(E))
    #print("N:{}".format(N))
    #print("A:{}".format(A))
    #print("B:{}".format(B))
    #print("C:{}".format(C))
    #print("D:{}".format(D))
    #print("E:{}".format(E))
    #print("N:{}".format(N))
    #print("A:{}".format(A))
    #print("B:{}".format(B))
    #print("C:{}".format(C))
    #print("D:{}".format(D))
    #print("E:{}".format(E))
    #print("N:{}".format(N))
    #print("A:{}".format(A))
    #print("B:{}".format(B))
    #
