def main():
    h,w = map(int,input().split())
    c = []
    for i in range(h):
        c.append(input())
    print(c)
    print(h,w)
    print(c[0][0])
    #print(c[0][1])
    #print(c[0][2])
    #print(c[0][3])
    #print(c[1][0])
    #print(c[1][1])
    #print(c[1][2])
    #print(c[1][3])
    #print(c[2][0])
    #print(c[2][1])
    #print(c[2][2])
    #print(c[2][3])
    #print(c[3][0])
    #print(c[3][1])
    #print(c[3][2])
    #print(c[3][3])
    #print(c[4][0])
    #print(c[4][1])
    #print(c[4][2])
    #print(c[4][3])
    #print(c[5][0])
    #print(c[5][1])
    #print(c[5][2])
    #print(c[5][3])
    #print(c[6][0])
    #print(c[6][1])
    #print(c[6][2])
    #print(c[6][3])
    #print(c[7][0])
    #print(c[7][1])
    #print(c[7][2])
    #print(c[7][3])
    #print(c[8][0])
    #print(c[8][1])
    #print(c[8][2])
    #print(c[8][3])
    #print(c[9][0])
    #print(c[9][1])
    #print(c[9][2])
    #print(c[9][3])
    #print(c[10][0])
    #print(c[10][1])
    #print(c[10][2])
    #print(c[10][3])
    #print(c[11][0])
    #print(c[11][1])
    #print(c[11][2])
    #print(c[11][3])
    #print(c[12][0])
    #print(c[12][1])
    #print(c[12][2])
    #print(c[

if __name__ == '__main__':
    main()