def resolve():
    N,W = map(int, input().split())
    A = []
    for i in range(N):
        A.append(list(map(int, input().split())))
    A.sort()
    #print(A)
    #print("A[0][0] = ", A[0][0])
    #print("A[0][1] = ", A[0][1])
    #print("A[0][2] = ", A[0][2])
    #print("A[1][0] = ", A[1][0])
    #print("A[1][1] = ", A[1][1])
    #print("A[1][2] = ", A[1][2])
    #print("A[0][0] = ", A[0][0])
    #print("A[0][1] = ", A[0][1])
    #print("A[0][2] = ", A[0][2])
    #print("A[1][0] = ", A[1][0])
    #print("A[1][1] = ", A[1][1])
    #print("A[1][2] = ", A[1][2])
    #print("A[0][0] = ", A[0][0])
    #print("A[0][1] = ", A[0][1])
    #print("A[0][2] = ", A[0][2])
    #print("A[1][0] = ", A[1][0])
    #print("A[1][1] = ", A[1][1])
    #print("A[1][2] = ", A[1][2])
    #print("A[0][0] = ", A[0][0])
    #print("A[0][1] = ", A[0][1])
    #print("A[0][2] = ", A[0][2])
    #print("A[1][0] = ", A[1][0])
    #print("A[1][1] = ", A[1][1])
    #print("A[1][2] = ", A[1][2])
    #print("A[0][0] = ", A[0][0])
    #print("A
