def main():
    N, W = map(int, input().split())
    STP = [list(map(int, input().split())) for _ in range(N)]
    #print(N)
    #print(W)
    #print(STP)
    #s = [0] * 200001
    #t = [0] * 200001
    #p = [0] * 200001
    #for i in range(N):
    #    s[i], t[i], p[i] = map(int, input().split())
    #print(s)
    #print(t)
    #print(p)
    #print("test")
    #print(STP[0][0])
    #print(STP[0][1])
    #print(STP[0][2])
    #print(STP[1][0])
    #print(STP[1][1])
    #print(STP[1][2])
    #print(STP[2][0])
    #print(STP[2][1])
    #print(STP[2][2])
    #print(STP[3][0])
    #print(STP[3][1])
    #print(STP[3][2])
    #print("test")
    #print(STP[0])
    #print("test")
    #print(STP[0][0])
    #print(STP[0][1])
    #print(STP[0][2])
    #print("test")
    #print(STP[0][0])
    #print(STP[0][1])
    #print(STP[0][2])
    #print("test")
    #print(STP[0][0])
    #print(STP[0][1])
    #print(STP[0][2])
    #print("test")
    #print(STP[0][0])
    #print(STP[0][1])
    #print(STP[0][2])
    #print("test")
    #print(STP[0][0])
    #print(STP[0][1])
    #print(STP[0][2])
    #print("test")
    #print(STP[0][0])
    #print(STP[0][1])
    #print(STP[0][2])
    #print("test")
    #print(STP[0][0])
