def main():
    N, M = map(int, input().split())
    A = []
    B = []
    for i in range(M):
        a, b = map(int, input().split())
        A.append(a)
        B.append(b)
    #print("A: ", A)
    #print("B: ", B)
    #print("N: ", N)
    #print("M: ", M)
    #print("A: ", A)
    #print("B: ", B)
    #print("N: ", N)
    #print("M: ", M)
    #print("A: ", A)
    #print("B: ", B)
    #print("N: ", N)
    #print("M: ", M)
    #print("A: ", A)
    #print("B: ", B)
    #print("N: ", N)
    #print("M: ", M)
    #print("A: ", A)
    #print("B: ", B)
    #print("N: ", N)
    #print("M: ", M)
    #print("A: ", A)
    #print("B: ", B)
    #print("N: ", N)
    #print("M: ", M)
    #print("A: ", A)
    #print("B: ", B)
    #print("N: ", N)
    #print("M: ", M)
    #print("A: ", A)
    #print("B: ", B)
    #print("N: ", N)
    #print("M: ", M)
    #print("A: ", A)
    #print("B: ", B)
    #print("N: ", N)
    #print("M: ", M)
    #print("A: ", A)
    #print("B: ", B)
    #print("N: ", N)
    #print("M: ", M)
    #print("A: ", A)
    #print("B: ", B)
    #print("N: ", N)
    #print("M: ", M)
    print("N: ", N)
    print("M: ", M)
    print("A: ", A)
    print("B: ", B)
    print("N: ", N)
    print("M: ", M)
    print("A:
