def main():
    N = int(input())
    data = [list(map(int, input().split())) for _ in range(N - 1)]
    data.sort(key=lambda x: x[2])
    # print(data)
    # print(N)
    # print(data)
    # print(data[0][1])
    # print(data[0][2])
    # print(data[0][0])
    # print(data[1][1])
    # print(data[1][2])
    # print(data[1][0])
    # print(data[2][1])
    # print(data[2][2])
    # print(data[2][0])
    # print(data[3][1])
    # print(data[3][2])
    # print(data[3][0])
    # print(data[4][1])
    # print(data[4][2])
    # print(data[4][0])
    # print(data[5][1])
    # print(data[5][2])
    # print(data[5][0])
    # print(data[6][1])
    # print(data[6][2])
    # print(data[6][0])
    # print(data[7][1])
    # print(data[7][2])
    # print(data[7][0])
    # print(data[8][1])
    # print(data[8][2])
    # print(data[8][0])
    # print(data[9][1])
    # print(data[9][2])
    # print(data[9][0])
    # print(data[10][1])
    # print(data[10][2])
    # print(data[10][0])
    # print(data[11][1])
    # print(data[11][2])
    # print(data[11][0])
    # print(data[12][1])
    # print(data[12][2])
    # print(data[12][0])
    # print(data[13][1])
    # print(data[13][2])
    # print(data[13][0])
    # print(data[14][1])
    # print(data[14][2])
    # print(data[14][0])
    # print(data[15][1])
    # print(data[15][2])
    # print(data[15][0])
    # print(data[16][1])
    # print(data

if __name__ == '__main__':
    main()