def isReachable(N, M, T, A, XY):
    #print("N, M, T, A, XY", N, M, T, A, XY)
    #print("N: ", N)
    #print("M: ", M)
    #print("T: ", T)
    #print("A: ", A)
    #print("XY: ", XY)
    #print("A[0]: ", A[0])
    #print("A[1]: ", A[1])
    #print("A[2]: ", A[2])
    #print("A[3]: ", A[3])
    #print("XY[0][0]: ", XY[0][0])
    #print("XY[0][1]: ", XY[0][1])
    #print("XY[1][0]: ", XY[1][0])
    #print("XY[1][1]: ", XY[1][1])
    #print("XY[2][0]: ", XY[2][0])
    #print("XY[2][1]: ", XY[2][1])
    #print("XY[3][0]: ", XY[3][0])
    #print("XY[3][1]: ", XY[3][1])
    #print("XY[4][0]: ", XY[4][0])
    #print("XY[4][1]: ", XY[4][1])
    #print("XY[5][0]: ", XY[5][0])
    #print("XY[5][1]: ", XY[5][1])
    #print("XY[6][0]: ", XY[6][0])
    #print("XY[6][1]: ", XY[6][1])
    #print("XY[7][0]: ", XY[7][0])
    #print("XY[7][1]: ", XY[7][1])
    #print("XY[8][0]: ", XY[8][0])
    #print("XY[8][1]: ", XY[8][1])
    #print("XY[9][0]: ", XY[9][0])
    #print("XY[9][1]: ", XY[9][1])
    #print("XY[10][0]: ", XY[10][0])
    #print("XY[10][1
