def solve():
    N,K = map(int,input().split())
    A = list(map(int,input().split()))
    A.sort()
    #print(A)
    #print(N,K)
    #print(A)
    #print(len(A))
    #print(((N*(N-1))//2))
    #print(((N*(N-1))//2)-K)
    #print(A[((N*(N-1))//2)-K])
    #print(A[0]*A[1])
    #print(A[N-1]*A[N-2])
    #print(A[0]*A[N-1])
    #print(A[0]*A[N-2])
    #print(A[1]*A[N-1])
    #print(A[1]*A[N-2])
    #print(A[0]*A[1])
    #print(A[1]*A[2])
    #print(A[N-1]*A[N-2])
    #print(A[N-2]*A[N-3])
    #print(A[0]*A[1])
    #print(A[1]*A[2])
    #print(A[2]*A[3])
    #print(A[3]*A[4])
    #print(A[N-1]*A[N-2])
    #print(A[N-2]*A[N-3])
    #print(A[N-3]*A[N-4])
    #print(A[N-4]*A[N-5])
    #print(A[0]*A[1])
    #print(A[1]*A[2])
    #print(A[2]*A[3])
    #print(A[3]*A[4])
    #print(A[4]*A[5])
    #print(A[N-1]*A[N-2])
    #print(A[N-2]*A[N-3])
    #print(A[N-3]*A[N-4])
    #print(A[N-4]*A[N-5])
    #print(A[N-5]*A[N-6])
    #print(A[0]*A[1])
    #print(A[1]*A[2])
    #print(A[2]*A[3])
    #print(A[3]*A[4])
    #print(A[4]*A[5])
    #print(A[5]*A[6])
    #print(A[N-

if __name__ == '__main__':
    solve()