def main():
    N, M = map(int, input().split())
    #print(N, M)
    #print(type(N), type(M))
    #print(N)
    #print(M)
    #print(type(N))
    #print(type(M))
    #print(N, M)
    #print(type(N), type(M))
    #print(N)
    #print(M)
    #print(type(N))
    #print(type(M))
    #print(N, M)
    #print(type(N), type(M))
    #print(N)
    #print(M)
    #print(type(N))
    #print(type(M))
    #print(N, M)
    #print(type(N), type(M))
    #print(N)
    #print(M)
    #print(type(N))
    #print(type(M))
    #print(N, M)
    #print(type(N), type(M))
    #print(N)
    #print(M)
    #print(type(N))
    #print(type(M))
    #print(N, M)
    #print(type(N), type(M))
    #print(N)
    #print(M)
    #print(type(N))
    #print(type(M))
    #print(N, M)
    #print(type(N), type(M))
    #print(N)
    #print(M)
    #print(type(N))
    #print(type(M))
    #print(N, M)
    #print(type(N), type(M))
    #print(N)
    #print(M)
    #print(type(N))
    #print(type(M))
    #print(N, M)
    #print(type(N), type(M))
    #print(N)
    #print(M)
    #print(type(N))
    #print(type(M))
    #print(N, M)
    #print(type(N), type(M))
    #print(N)
    #print(M)
    #prin
