def main():
    N,M = map(int,input().split())
    #print(N,M)
    #print(type(N),type(M))
    #print(type(input().split()))
    #print(input().split())
    #print(type(map(int,input().split())))
    #print(map(int,input().split()))
    #print(type(list(map(int,input().split()))))
    #print(list(map(int,input().split())))
    #print(type([list(map(int,input().split()))]))
    #print([list(map(int,input().split()))])
    #print(type([list(map(int,input().split())) for i in range(M)]))
    #print([list(map(int,input().split())) for i in range(M)])
    #print(type([list(map(int,input().split())) for i in range(M)][0]))
    #print([list(map(int,input().split())) for i in range(M)][0])
    #print(type([list(map(int,input().split())) for i in range(M)][0][0]))
    #print([list(map(int,input().split())) for i in range(M)][0][0])
    #print(type([[list(map(int,input().split())) for i in range(M)][0][0] for j in range(M)]))
    #print([[list(map(int,input().split())) for i in range(M)][0][0] for j in range(M)])
    #print(type([[list(map(int,input().split())) for i in range(M)][0][0] for j in range(M)][0]))
    #print([[list(map(int,input().split())) for i in range(M)][0][0] for j in range(M)][0])
    #print(type([[list(map(int,input().split())) for i in range(M)][0][0] for j in range(M)][0][0]))
    #print([[list(map(int,input().split())) for i in range(M)][0][0] for j in range(M)][0][0])
    #print(type([[list(map(int,input().split())) for i in range(M)][0][0] for j in range(M)][0][1]))
    #print([[list(map(int,input().split())) for i in range(M)][0][0] for j in range(M)][0][1])
    #print(type([[list(map(int,input().split())) for i in range(M)][0][0] for j in range(M)][0][2]))
