def main():
    N = int(input())
    X = []
    Y = []
    for i in range(N):
        x, y = map(int, input().split())
        X.append(x)
        Y.append(y)
    # print(X)
    # print(Y)
    # print(N)
    # print(math.factorial(N))
    # print(2**N)
    # print(N**N)
    # print(N**2)
    # print(N**3)
    # print(N**4)
    # print(N**5)
    # print(N**6)
    # print(N**7)
    # print(N**8)
    # print(2**N)
    # print(N**N)
    # print(N**2)
    # print(N**3)
    # print(N**4)
    # print(N**5)
    # print(N**6)
    # print(N**7)
    # print(N**8)
    # print(2**N)
    # print(N**N)
    # print(N**2)
    # print(N**3)
    # print(N**4)
    # print(N**5)
    # print(N**6)
    # print(N**7)
    # print(N**8)
    # print(2**N)
    # print(N**N)
    # print(N**2)
    # print(N**3)
    # print(N**4)
    # print(N**5)
    # print(N**6)
    # print(N**7)
    # print(N**8)
    # print(2**N)
    # print(N**N)
    # print(N**2)
    # print(N**3)
    # print(N**4)
    # print(N**5)
    # print(N**6)
    # print(N**7)
    # print(N**8)
    # print(2**N)
    # print(N**N)
    # print(N**2)
    # print(N**3)
    # print(N**4)
    # print(N**5)
    # print(N**6)
    # print(N**7)
    # print(N**8)
    # print(2**N)
    # print(N**N)
    # print(N**2)
    # print(N**3)
    # print(N**4)
    # print(N**5)
    # print(N**

if __name__ == '__main__':
    main()