def main():
    N = int(input())
    edges = []
    for i in range(N-1):
        a, b = map(int, input().split())
        edges.append((a, b))
    #print(edges)
    #print(N)
    #print(edges[0][0])
    #print(edges[0][1])
    #print(edges[1][0])
    #print(edges[1][1])
    #print(edges[2][0])
    #print(edges[2][1])
    #print(edges[3][0])
    #print(edges[3][1])
    #print(edges[4][0])
    #print(edges[4][1])
    #print(edges[5][0])
    #print(edges[5][1])
    #print(edges[6][0])
    #print(edges[6][1])
    #print(edges[7][0])
    #print(edges[7][1])
    #print(edges[8][0])
    #print(edges[8][1])
    #print(edges[9][0])
    #print(edges[9][1])
    #print(edges[10][0])
    #print(edges[10][1])
    #print(edges[11][0])
    #print(edges[11][1])
    #print(edges[12][0])
    #print(edges[12][1])
    #print(edges[13][0])
    #print(edges[13][1])
    #print(edges[14][0])
    #print(edges[14][1])
    #print(edges[15][0])
    #print(edges[15][1])
    #print(edges[16][0])
    #print(edges[16][1])
    #print(edges[17][0])
    #print(edges[17][1])
    #print(edges[18][0])
    #print(edges[18][1])
    #print(edges[19][0])
    #print(edges[19][1])
    #print(edges[20][0])
    #print(edges[20][1])
    #print(edges[21][0])
    #print(edges[21][1])
    #print(edges[22][0])
    #print(edges[22][1])
    #print(edges[23][0])
    #print(edges[23][1])
    #print(edges[24][0])
    #print(edges[24][1

if __name__ == '__main__':
    main()