def main():
    N = int(input())
    # print(N)
    # print(type(N))
    # print(100)
    # print(type(100))
    # print(999)
    # print(type(999))
    if N >= 100 and N <= 999:
        # print("OK")
        # print(N)
        # print(type(N))
        # print(100)
        # print(type(100))
        # print(999)
        # print(type(999))
        # print(N)
        # print(type(N))
        # print(100)
        # print(type(100))
        # print(999)
        # print(type(999))
        # print(N)
        # print(type(N))
        # print(100)
        # print(type(100))
        # print(999)
        # print(type(999))
        # print(N)
        # print(type(N))
        # print(100)
        # print(type(100))
        # print(999)
        # print(type(999))
        # print(N)
        # print(type(N))
        # print(100)
        # print(type(100))
        # print(999)
        # print(type(999))
        # print(N)
        # print(type(N))
        # print(100)
        # print(type(100))
        # print(999)
        # print(type(999))
        # print(N)
        # print(type(N))
        # print(100)
        # print(type(100))
        # print(999)
        # print(type(999))
        # print(N)
        # print(type(N))
        # print(100)
        # print(type(100))
        # print(999)
        # print(type(999))
        for i in range(N,1000):
            # print(i)
            # print(type(i))
            # print(100)
            # print(type(100))
            # print(999)
            # print(type(999))
            # print(i)
            # print(type(i))
            # print(100)
            # print(type(100))
            # print(999)
            # print(type(999))
            if i % 111 == 0:
                print(i)
                break
    else:
        print("ERROR")
        print(N)
        print(type(N))
        print(100)
        print(type(100))
        print(999)
        print(type(999))
