def main():
    n, k = map(int, input().split())
    a = list(map(int, input().split()))
    a_s = sorted(a)
    # print(a_s)
    # print(n, k)
    # print(a)
    # print(a_s)
    # print(a_s[0])
    # print(a_s[1])
    # print(a_s[2])
    # print(a_s[3])
    # print(a_s[4])
    # print(a_s[5])
    # print(a_s[6])
    # print(a_s[7])
    # print(a_s[8])
    # print(a_s[9])
    # print(a_s[10])
    # print(a_s[11])
    # print(a_s[12])
    # print(a_s[13])
    # print(a_s[14])
    # print(a_s[15])
    # print(a_s[16])
    # print(a_s[17])
    # print(a_s[18])
    # print(a_s[19])
    # print(a_s[20])
    # print(a_s[21])
    # print(a_s[22])
    # print(a_s[23])
    # print(a_s[24])
    # print(a_s[25])
    # print(a_s[26])
    # print(a_s[27])
    # print(a_s[28])
    # print(a_s[29])
    # print(a_s[30])
    # print(a_s[31])
    # print(a_s[32])
    # print(a_s[33])
    # print(a_s[34])
    # print(a_s[35])
    # print(a_s[36])
    # print(a_s[37])
    # print(a_s[38])
    # print(a_s[39])
    # print(a_s[40])
    # print(a_s[41])
    # print(a_s[42])
    # print(a_s[43])
    # print(a_s[44])
    # print(a_s[45])
    # print(a_s[46])
    # print(a_s[47])
    # print(a_s[48])
    # print(a_s[49])
    # print(a_s[50])
    # print(a_s[51])
    # print(a_s[52])
    # print(a_s[53])
    # print(a_s[54])
    # print(a

if __name__ == '__main__':
    main()