def main():
    N, Q = map(int, input().split())
    S = input()
    #print(N, Q)
    #print(S)
    #print(S[3:7])
    #print(S[2:3])
    #print(S[1:8])
    #print(S[0:8])
    #print(S[0:7])
    #print(S[0:6])
    #print(S[0:5])
    #print(S[0:4])
    #print(S[0:3])
    #print(S[0:2])
    #print(S[0:1])
    #print(S[0:0])
    #print(S[0:8].count('AC'))
    #print(S[0:7].count('AC'))
    #print(S[0:6].count('AC'))
    #print(S[0:5].count('AC'))
    #print(S[0:4].count('AC'))
    #print(S[0:3].count('AC'))
    #print(S[0:2].count('AC'))
    #print(S[0:1].count('AC'))
    #print(S[0:0].count('AC'))
    #print(S[1:8].count('AC'))
    #print(S[2:3].count('AC'))
    #print(S[3:7].count('AC'))
    #print(S[0:8].count('AC'))
    #print(S[0:7].count('AC'))
    #print(S[0:6].count('AC'))
    #print(S[0:5].count('AC'))
    #print(S[0:4].count('AC'))
    #print(S[0:3].count('AC'))
    #print(S[0:2].count('AC'))
    #print(S[0:1].count('AC'))
    #print(S[0:0].count('AC'))
    #print(S[1:8].count('AC'))
    #print(S[2:3].count('AC'))
    #print(S[3:7].count('AC'))
    #print(S[0:8].count('AC'))
    #print(S[0:7].count('AC'))
    #print(S[0:6].count('AC'))
    #print(S[0:5].count

if __name__ == '__main__':
    main()