def main():
    h,w = map(int,input().split())
    a = []
    for i in range(h):
        a.append(list(input()))
    #print(a)
    #print(a[0][0])
    #print(a[0][1])
    #print(a[1][0])
    #print(a[1][1])
    #print(a[2][0])
    #print(a[2][1])
    #print(a[0][2])
    #print(a[1][2])
    #print(a[2][2])
    #print(a[0][0])
    #print(a[1][0])
    #print(a[2][0])
    #print(a[0][1])
    #print(a[1][1])
    #print(a[2][1])
    #print(a[0][2])
    #print(a[1][2])
    #print(a[2][2])
    #print(a[0][0])
    #print(a[0][1])
    #print(a[0][2])
    #print(a[1][0])
    #print(a[1][1])
    #print(a[1][2])
    #print(a[2][0])
    #print(a[2][1])
    #print(a[2][2])
    #print(a[0][0])
    #print(a[0][1])
    #print(a[0][2])
    #print(a[1][0])
    #print(a[1][1])
    #print(a[1][2])
    #print(a[2][0])
    #print(a[2][1])
    #print(a[2][2])
    #print(a[0][0])
    #print(a[0][1])
    #print(a[0][2])
    #print(a[1][0])
    #print(a[1][1])
    #print(a[1][2])
    #print(a[2][0])
    #print(a[2][1])
    #print(a[2][2])
    #print(a[0][0])
    #print(a[0][1])
    #print(a[0][2])
    #print(a[1][0])
    #print(a[1][1])
    #print(a[1][2])
    #print(a[2][

if __name__ == '__main__':
    main()