def solve():
    N = int(input())
    XY = [list(map(int,input().split())) for _ in range(N)]
    #print(N,XY)
    #print(XY[0][0])
    #print(XY[0][1])
    #print(XY[1][0])
    #print(XY[1][1])
    #print(XY[2][0])
    #print(XY[2][1])
    #print(XY[3][0])
    #print(XY[3][1])
    #print(XY[4][0])
    #print(XY[4][1])
    #print(XY[0][0])
    #print(XY[0][1])
    #print(XY[1][0])
    #print(XY[1][1])
    #print(XY[2][0])
    #print(XY[2][1])
    #print(XY[3][0])
    #print(XY[3][1])
    #print(XY[4][0])
    #print(XY[4][1])
    #print(XY[5][0])
    #print(XY[5][1])
    #print(XY[6][0])
    #print(XY[6][1])
    #print(XY[7][0])
    #print(XY[7][1])
    #print(XY[0][0])
    #print(XY[0][1])
    #print(XY[1][0])
    #print(XY[1][1])
    #print(XY[2][0])
    #print(XY[2][1])
    #print(XY[3][0])
    #print(XY[3][1])
    #print(XY[4][0])
    #print(XY[4][1])
    #print(XY[5][0])
    #print(XY[5][1])
    #print(XY[6][0])
    #print(XY[6][1])
    #print(XY[7][0])
    #print(XY[7][1])
    #print(XY[8][0])
    #print(XY[8][1])
    #print(XY[9][0])
    #print(XY[9][1])
    #print(XY[10][

if __name__ == '__main__':
    solve()