def main():
    N = int(input())
    A = []
    B = []
    for n in range(N):
        a, b = map(int, input().split())
        A.append(a)
        B.append(b)
    #print(A)
    #print(B)
    #print(A[0])
    #print(B[0])
    #print(A[0] + B[0])
    #print(A[0] - B[0])
    #print(abs(A[0] - B[0]))
    #print(A[0] - B[0] < 0)
    #print(A[0] - B[0] > 0)
    #print(A[0] - B[0] == 0)
    #print(A[0] - B[0] < 0)
    #print(A[0] - B[0] > 0)
    #print(A[0] - B[0] == 0)
    #print(A[0] - B[0] < 0)
    #print(A[0] - B[0] > 0)
    #print(A[0] - B[0] == 0)
    #print(A[0] - B[0] < 0)
    #print(A[0] - B[0] > 0)
    #print(A[0] - B[0] == 0)
    #print(A[0] - B[0] < 0)
    #print(A[0] - B[0] > 0)
    #print(A[0] - B[0] == 0)
    #print(A[0] - B[0] < 0)
    #print(A[0] - B[0] > 0)
    #print(A[0] - B[0] == 0)
    #print(A[0] - B[0] < 0)
    #print(A[0] - B[0] > 0)
    #print(A[0] - B[0] == 0)
    #print(A[0] - B[0] < 0)
    #print(A[0] - B[0] > 0)
    #print(A[0] - B[0] == 0)
    #print(A[0] - B[

if __name__ == '__main__':
    main()