def main():
    H, W, N = map(int, input().split())
    A = []
    B = []
    for i in range(N):
        a, b = map(int, input().split())
        A.append(a)
        B.append(b)
    #print(A)
    #print(B)
    #print(H)
    #print(W)
    #print(N)
    #print("")
    #print(max(A))
    #print(max(B))
    #print("")
    #print(min(A))
    #print(min(B))
    #print("")
    #print(max(A) - min(A) + 1)
    #print(max(B) - min(B) + 1)
    #print("")
    #print(H - (max(A) - min(A) + 1))
    #print(W - (max(B) - min(B) + 1))
    #print("")
    #print(max(H - (max(A) - min(A) + 1), W - (max(B) - min(B) + 1)))
    #print("")
    #print(max(H - (max(A) - min(A) + 1), W - (max(B) - min(B) + 1)) - min(H - (max(A) - min(A) + 1), W - (max(B) - min(B) + 1)))
    #print("")
    #print(max(H - (max(A) - min(A) + 1), W - (max(B) - min(B) + 1)) - min(H - (max(A) - min(A) + 1), W - (max(B) - min(B) + 1)) + 1)
    #print("")
    #print(max(H - (max(A) - min(A) + 1), W - (max(B) - min(B) + 1)) - min(H - (max(A) - min(A) + 1), W - (max(B) - min(B) + 1)) + 1)
    #print("")
    #print(max(H - (max(A) - min(A) + 1), W - (max(B) - min(B) + 1)) - min(H - (max(A) - min(A) + 1), W - (max(B) - min(B) + 1)) + 1
