def main():
    N, K = map(int, input().split())
    C = list(map(int, input().split()))
    #print(N, K)
    #print(C)
    #print(len(C))
    #print(C[0])
    #print(C[0:K])
    #print(set(C[0:K]))
    #print(len(set(C[0:K])))
    #print(C[0:K-1])
    #print(set(C[0:K-1]))
    #print(len(set(C[0:K-1])))
    #print(C[1:K])
    #print(set(C[1:K]))
    #print(len(set(C[1:K])))
    #print(C[1:K+1])
    #print(set(C[1:K+1]))
    #print(len(set(C[1:K+1])))
    #print(C[2:K+2])
    #print(set(C[2:K+2]))
    #print(len(set(C[2:K+2])))
    #print(C[3:K+3])
    #print(set(C[3:K+3]))
    #print(len(set(C[3:K+3])))
    #print(C[4:K+4])
    #print(set(C[4:K+4]))
    #print(len(set(C[4:K+4])))
    #print(C[5:K+5])
    #print(set(C[5:K+5]))
    #print(len(set(C[5:K+5])))
    #print(C[6:K+6])
    #print(set(C[6:K+6]))
    #print(len(set(C[6:K+6])))
    #print(C[7:K+7])
    #print(set(C[7:K+7]))
    #print(len(set(C[7:K+7])))
    #print(C[8:K+8])
    #print(set(C[8:K+8]))
    #print(len(set(C[8:K+8])))
    #print(C[9:K+9])
    #print(set(C[9:K+9]))
    #print(len(set(C[9:K+9])))
    #print(C[10:K+10])
    #print(set(C[10:K+10]))
    #print(len(set(C[
