def main():
    N, X = map(int, input().split())
    AB = [list(map(int, input().split())) for _ in range(N)]
    A = [AB[i][0] for i in range(N)]
    B = [AB[i][1] for i in range(N)]
    # print(N, X, A, B)
    # print(AB)
    # print(A)
    # print(B)
    # print(type(N), type(X), type(A), type(B))
    # print(type(AB))
    # print(type(AB[0]))
    # print(type(AB[0][0]))
    # print(type(AB[0][1]))
    # print(AB[0][0])
    # print(AB[0][1])
    # print(AB[1][0])
    # print(AB[1][1])
    # print(AB[2][0])
    # print(AB[2][1])
    # print(AB[3][0])
    # print(AB[3][1])
    # print(AB[4][0])
    # print(AB[4][1])
    # print(AB[5][0])
    # print(AB[5][1])
    # print(AB[6][0])
    # print(AB[6][1])
    # print(AB[7][0])
    # print(AB[7][1])
    # print(AB[8][0])
    # print(AB[8][1])
    # print(AB[9][0])
    # print(AB[9][1])
    # print(X, X+1, X+2, X+3, X+4, X+5, X+6, X+7, X+8, X+9)
    # print(X, X+1, X+2, X+3, X+4, X+5, X+6, X+7, X+8, X+9)
    # print(A[0], A[1], A[2], A[3], A[4], A[5], A[6], A[7], A[8], A[9])
    # print(A[0], A[1], A[2], A[3], A[4], A[5], A[6], A[
