def main():
    s = input()
    s = s.replace("?", "0")
    s = s.replace("A", "1")
    s = s.replace("B", "2")
    s = s.replace("C", "3")
    s = s.replace("0", "ABC")
    s = s.replace("1", "BC")
    s = s.replace("2", "AC")
    s = s.replace("3", "AB")
    print(s.count("ABC") % (10 ** 9 + 7))
