def main():
    N = int(input())
    X = []
    Y = []
    for i in range(N):
        x,y = map(int,input().split())
        X.append(x)
        Y.append(y)
    #print(X)
    #print(Y)
    #print(len(X))
    #print(len(Y))
    #print(X[0])
    #print(Y[0])
    #print(X[0] - Y[0])
    #print(X[0] + Y[0])
    #print(X[1] - Y[1])
    #print(X[1] + Y[1])
    #print(X[2] - Y[2])
    #print(X[2] + Y[2])
    #print(X[3] - Y[3])
    #print(X[3] + Y[3])
    #print(X[4] - Y[4])
    #print(X[4] + Y[4])
    #print(X[5] - Y[5])
    #print(X[5] + Y[5])
    #print(X[6] - Y[6])
    #print(X[6] + Y[6])
    #print(X[7] - Y[7])
    #print(X[7] + Y[7])
    #print(X[8] - Y[8])
    #print(X[8] + Y[8])
    #print(X[9] - Y[9])
    #print(X[9] + Y[9])
    #print(X[10] - Y[10])
    #print(X[10] + Y[10])
    #print(X[11] - Y[11])
    #print(X[11] + Y[11])
    #print(X[12] - Y[12])
    #print(X[12] + Y[12])
    #print(X[13] - Y[13])
    #print(X[13] + Y[13])
    #print(X[14] - Y[14])
    #print(X[14] + Y[14])
    #print(X[15] - Y[15])
    #print(X[15] + Y[15])
    #print(X[16] - Y[16])
    #print(X[16] + Y[16])
    #print(X[17] - Y[17])

if __name__ == '__main__':
    main()