def main():
    n,a,b = map(int,input().split())
    p,q,r,s = map(int,input().split())
    #print(n,a,b,p,q,r,s)
    #print("n = ",n)
    #print("a = ",a)
    #print("b = ",b)
    #print("p = ",p)
    #print("q = ",q)
    #print("r = ",r)
    #print("s = ",s)
    #print("p-q = ",p-q)
    #print("r-s = ",r-s)
    #print("p-q+1 = ",p-q+1)
    #print("r-s+1 = ",r-s+1)
    #print("p-q+1 * r-s+1 = ",(p-q+1) * (r-s+1))
    #print("n * n = ",n * n)
    #print("3 * 10^5 = ",3 * 10**5)
    #print("n*n = ",n*n)
    #print("3*10**5 = ",3*10**5)
    #print("(p-q+1) * (r-s+1) <= 3 * 10**5 = ",(p-q+1) * (r-s+1) <= 3 * 10**5)
    #print("(p-q+1) * (r-s+1) <= 3 * 10**5 = ",(p-q+1) * (r-s+1) <= 3 * 10**5)
    #print("(p-q+1) * (r-s+1) <= 3 * 10**5 = ",(p-q+1) * (r-s+1) <= 3 * 10**5)
    #print("(p-q+1) * (r-s+1) <= 3 * 10**5 = ",(p-q+1) * (r-s+1) <= 3 * 10**5)
    #print("(p-q+1) * (r-s+1) <= 3 * 10**5 = ",(p-q+1) * (r-s+1) <= 3 * 10**5)
    #print("(p-q+1) * (r-s+1) <= 3 *

if __name__ == '__main__':
    main()