def main():
    N, A, B = map(int, input().split())
    P, Q, R, S = map(int, input().split())
    #print(N, A, B)
    #print(P, Q, R, S)
    #print("N={}, A={}, B={}".format(N, A, B))
    #print("P={}, Q={}, R={}, S={}".format(P, Q, R, S))
    #print("N={}, A={}, B={}".format(type(N), type(A), type(B)))
    #print("P={}, Q={}, R={}, S={}".format(type(P), type(Q), type(R), type(S)))
    #print("N={}, A={}, B={}".format(type(N), type(A), type(B)))
    #print("P={}, Q={}, R={}, S={}".format(type(P), type(Q), type(R), type(S)))
    #print("N={}, A={}, B={}".format(N, A, B))
    #print("P={}, Q={}, R={}, S={}".format(P, Q, R, S))
    #print("N={}, A={}, B={}".format(type(N), type(A), type(B)))
    #print("P={}, Q={}, R={}, S={}".format(type(P), type(Q), type(R), type(S)))
    #print("N={}, A={}, B={}".format(N, A, B))
    #print("P={}, Q={}, R={}, S={}".format(P, Q, R, S))
    #print("N={}, A={}, B={}".format(type(N), type(A), type(B)))
    #print("P={}, Q={}, R={}, S={}".format(type(P), type(Q), type(R), type(S)))
    #print("N={}, A={}, B={}".format(N, A, B))
    #print("P={}, Q={}, R={}, S={}".format(P, Q, R, S))
    #print("N={}, A={}, B={}".format(type(N), type(A), type(B)))
    #print("P={}, Q={}, R={}, S={}".format(type(P), type(Q), type(R), type(S)))
    #print("N={}, A={}, B={}".format(N, A, B))
    #print("P={}, Q={}, R={}, S={}".format(P, Q, R, S))
    #print("N={}, A={}, B={}".format(type

if __name__ == '__main__':
    main()