def main():
    N, W = map(int, input().split())
    #print(N, W)
    #print(type(N), type(W))
    #print(type(N))
    #print(type(W))
    #print(N, W)
    #print(type(N), type(W))
    #print(type(N))
    #print(type(W))
    #print(N, W)
    #print(type(N), type(W))
    #print(type(N))
    #print(type(W))
    #print(N, W)
    #print(type(N), type(W))
    #print(type(N))
    #print(type(W))
    #print(N, W)
    #print(type(N), type(W))
    #print(type(N))
    #print(type(W))
    #print(N, W)
    #print(type(N), type(W))
    #print(type(N))
    #print(type(W))
    #print(N, W)
    #print(type(N), type(W))
    #print(type(N))
    #print(type(W))
    #print(N, W)
    #print(type(N), type(W))
    #print(type(N))
    #print(type(W))
    #print(N, W)
    #print(type(N), type(W))
    #print(type(N))
    #print(type(W))
    S = []
    T = []
    P = []
    for i in range(N):
        s, t, p = map(int, input().split())
        S.append(s)
        T.append(t)
        P.append(p)
    #print(S)
    #print(T)
    #print(P)
    #print(type(S))
    #print(type(T))
    #print(type(P))
    #print(S[0])
    #print(T[0])
    #print(P[0])
    #print(type(S[0]))
    #print(type(T[0]))
    #print(type(P[0]))
    #print(S[1])
    #print(T[1])
    #print(P[1])
    #print(type(S[1]))
    #print(type(T[1]))
    #print(type(P[1]))
    #print(S[2])
    #print(T[2])
    #print(P[2])
    #print(type(S[2]))
    #print(type(T[2]))
    #print(type(P[2]))
    #print(S[3])
    #print(T[3])
    #print(P

if __name__ == '__main__':
    main()