def main():
    N,W = map(int,input().split())
    #print(N,W)
    STP = [list(map(int,input().split())) for i in range(N)]
    #print(STP)
    #STP = sorted(STP,key=lambda x: x[0])
    #print(STP)
    #STP = sorted(STP,key=lambda x: x[1])
    #print(STP)
    #STP = sorted(STP,key=lambda x: x[2])
    #print(STP)
    #STP = sorted(STP,key=lambda x: x[0])
    #print(STP)
    #STP = sorted(STP,key=lambda x: x[1])
    #print(STP)
    #STP = sorted(STP,key=lambda x: x[2])
    #print(STP)
    STP = sorted(STP,key=lambda x: x[1])
    #print(STP)
    STP = sorted(STP,key=lambda x: x[0])
    #print(STP)
    #STP = sorted(STP,key=lambda x: x[2])
    #print(STP)
    #STP = sorted(STP,key=lambda x: x[1])
    #print(STP)
    #STP = sorted(STP,key=lambda x: x[0])
    #print(STP)
    #STP = sorted(STP,key=lambda x: x[2])
    #print(STP)
    #STP = sorted(STP,key=lambda x: x[1])
    #print(STP)
    #STP = sorted(STP,key=lambda x: x[0])
    #print(STP)
    #STP = sorted(STP,key=lambda x: x[2])
    #print(STP)
    #STP = sorted(STP,key=lambda x: x[1])
    #print(STP)
    #STP = sorted(STP,key=lambda x: x[0])
    #print(STP)
    #STP = sorted(STP,key=lambda x: x[2])
    #print(STP)
    #STP = sorted(STP,key=lambda x: x[1])
    #print(STP)
    #STP = sorted(STP,key=lambda x: x[0])
    #print(STP)
    #STP = sorted(STP,key=lambda x: x[2])
    #print(ST

if __name__ == '__main__':
    main()