def main():
    n, m = map(int, input().split())
    cakes = []
    for i in range(n):
        cakes.append(list(map(int, input().split())))
    # print(cakes)
    # print(n, m)
    # print(cakes[0][0])
    max_value = 0
    for i in range(2**3):
        # print(bin(i))
        # print(bin(i)[2:].zfill(3))
        # print(list(bin(i)[2:].zfill(3)))
        cake_list = list(bin(i)[2:].zfill(3))
        # print(cake_list)
        # print(cake_list[0])
        # print(cake_list[1])
        # print(cake_list[2])
        # print(cakes[0][0])
        # print(cakes[0][1])
        # print(cakes[0][2])
        # print(cakes[1][0])
        # print(cakes[1][1])
        # print(cakes[1][2])
        # print(cakes[2][0])
        # print(cakes[2][1])
        # print(cakes[2][2])
        # print(cakes[3][0])
        # print(cakes[3][1])
        # print(cakes[3][2])
        # print(cakes[4][0])
        # print(cakes[4][1])
        # print(cakes[4][2])
        # print(cake_list[0])
        # print(cake_list[1])
        # print(cake_list[2])
        # print(cakes[0][0] * int(cake_list[0]))
        # print(cakes[0][1] * int(cake_list[1]))
        # print(cakes[0][2] * int(cake_list[2]))
        # print(cakes[1][0] * int(cake_list[0]))
        # print(cakes[1][1] * int(cake_list[1]))
        # print(cakes[1][2] * int(cake_list[2]))
        # print(cakes[2][0] * int(cake_list[0]))
        # print(cakes[2][1] * int(cake_list[1]))
        # print(cakes[2][2] * int(cake_list[2]))
        # print
