def main():
    N, M = map(int, input().split())
    A = [0] * M
    B = [0] * M
    for i in range(M):
        A[i], B[i] = map(int, input().split())
    #print("N, M = ", N, M)
    #print("A = ", A)
    #print("B = ", B)
    #print("A[0] = ", A[0])
    #print("B[0] = ", B[0])
    #print("A[1] = ", A[1])
    #print("B[1] = ", B[1])
    #print("A[2] = ", A[2])
    #print("B[2] = ", B[2])
    #print("A[3] = ", A[3])
    #print("B[3] = ", B[3])
    #print("A[4] = ", A[4])
    #print("B[4] = ", B[4])
    #print("A[5] = ", A[5])
    #print("B[5] = ", B[5])
    #print("A[6] = ", A[6])
    #print("B[6] = ", B[6])
    #print("A[7] = ", A[7])
    #print("B[7] = ", B[7])
    #print("A[8] = ", A[8])
    #print("B[8] = ", B[8])
    #print("A[9] = ", A[9])
    #print("B[9] = ", B[9])
    #print("A[10] = ", A[10])
    #print("B[10] = ", B[10])
    #print("A[11] = ", A[11])
    #print("B[11] = ", B[11])
    #print("A[12] = ", A[12])
    #print("B[12] = ", B[12])
    #print("A[13] = ", A[13])
    #print("B[13] = ", B[13])
    #print("A[14] = ", A[14])
    #print("B[14] =

if __name__ == '__main__':
    main()