def main():
    h, w, rs, cs = map(int, input().split())
    n = int(input())
    r = []
    c = []
    for i in range(n):
        a, b = map(int, input().split())
        r.append(a)
        c.append(b)
    q = int(input())
    d = []
    l = []
    for i in range(q):
        a, b = input().split()
        d.append(a)
        l.append(int(b))
    #print(h, w, rs, cs)
    #print(n)
    #print(r)
    #print(c)
    #print(q)
    #print(d)
    #print(l)
    #print(h, w, rs, cs)
    #print(n)
    #print(r)
    #print(c)
    #print(q)
    #print(d)
    #print(l)
    #print(h, w, rs, cs)
    #print(n)
    #print(r)
    #print(c)
    #print(q)
    #print(d)
    #print(l)
    #print(h, w, rs, cs)
    #print(n)
    #print(r)
    #print(c)
    #print(q)
    #print(d)
    #print(l)
    #print(h, w, rs, cs)
    #print(n)
    #print(r)
    #print(c)
    #print(q)
    #print(d)
    #print(l)
    #print(h, w, rs, cs)
    #print(n)
    #print(r)
    #print(c)
    #print(q)
    #print(d)
    #print(l)
    #print(h, w, rs, cs)
    #print(n)
    #print(r)
    #print(c)
    #print(q)
    #print(d)
    #print(l)
    #print(h, w, rs, cs)
    #print(n)
    #print(r)
    #print(c)
    #print(q)
    #print(d)
    #print(l)
    #print(h, w, rs, cs)
    #print(n)
    #print(r)
    #print(c)
    #print(q)
    #print(d)
    #print(l)
