def main():
    L, Q = map(int, input().split())
    cuts = []
    for i in range(Q):
        cuts.append(list(map(int, input().split())))
    #print(cuts)
    #print(cuts[0][0])
    #print(cuts[0][1])
    #print(len(cuts))
    #print(cuts[1][0])
    #print(cuts[1][1])
    #print(cuts[2][0])
    #print(cuts[2][1])
    #print(cuts[3][0])
    #print(cuts[3][1])
    #print(cuts[4][0])
    #print(cuts[4][1])
    #print(cuts[5][0])
    #print(cuts[5][1])
    #print(cuts[6][0])
    #print(cuts[6][1])
    #print(cuts[7][0])
    #print(cuts[7][1])
    #print(cuts[8][0])
    #print(cuts[8][1])
    #print(cuts[9][0])
    #print(cuts[9][1])
    #print(cuts[10][0])
    #print(cuts[10][1])
    #print(cuts[11][0])
    #print(cuts[11][1])
    #print(cuts[12][0])
    #print(cuts[12][1])
    #print(cuts[13][0])
    #print(cuts[13][1])
    #print(cuts[14][0])
    #print(cuts[14][1])
    #print(cuts[15][0])
    #print(cuts[15][1])
    #print(cuts[16][0])
    #print(cuts[16][1])
    #print(cuts[17][0])
    #print(cuts[17][1])
    #print(cuts[18][0])
    #print(cuts[18][1])
    #print(cuts[19][0])
    #print(cuts[19][1])
    #print(cuts[20][0])
    #print(cuts[20][1])
    #print(cuts[21][0])
    #print(cuts[21][1])
    #print(cuts[22][0])

if __name__ == '__main__':
    main()