def main():
    n,m=map(int,input().split())
    x=list(map(int,input().split()))
    c,y=[],[]
    for i in range(m):
        c_,y_=map(int,input().split())
        c.append(c_)
        y.append(y_)
    # print(n,m,x,c,y)
    # print(len(x),len(c),len(y))
    # print(x)
    # print(c)
    # print(y)
    # print(len(x))
    # print(len(c))
    # print(len(y))
    # print(len(x))
    # print(len(c))
    # print(len(y))
    # print(x[0:3])
    # print(x[3:6])
    # print(x[0:2])
    # print(x[2:3])
    # print(x[3:5])
    # print(x[5:6])
    # print(x[0:1])
    # print(x[1:1])
    # print(x[2:2])
    # print(x[3:3])
    # print(x[4:4])
    # print(x[5:5])
    # print(x[6:6])
    # print(x[0:0])
    # print(x[1:0])
    # print(x[2:0])
    # print(x[3:0])
    # print(x[4:0])
    # print(x[5:0])
    # print(x[6:0])
    # print(x[0:1])
    # print(x[1:2])
    # print(x[2:3])
    # print(x[3:4])
    # print(x[4:5])
    # print(x[5:6])
    # print(x[6:7])
    # print(x[0:2])
    # print(x[2:3])
    # print(x[3:5])
    # print(x[5:6])
    # print(x[0:3])
    # print(x[3:6])
    # print(x[0:1])
    # print(x[1:1])
    # print(x[2:2])
    # print(x[3:3])
    # print(x[4:4])
    # print(x[5:5])
    # print(x[6:6])
    # print(x[0:0])
    # print(x

if __name__ == '__main__':
    main()