def main():
    n, m = map(int, input().split())
    x = [int(x) for x in input().split()]
    c = []
    y = []
    for i in range(m):
        c_y = [int(x) for x in input().split()]
        c.append(c_y[0])
        y.append(c_y[1])
    #print(n, m)
    #print(x)
    #print(c)
    #print(y)
    #print(x[0])
    #print(c[0])
    #print(y[0])
    #print(x[1])
    #print(c[1])
    #print(y[1])
    #print(x[2])
    #print(c[2])
    #print(y[2])
    #print(x[3])
    #print(c[3])
    #print(y[3])
    #print(x[4])
    #print(c[4])
    #print(y[4])
    #print(x[5])
    #print(c[5])
    #print(y[5])
    #print(x[6])
    #print(c[6])
    #print(y[6])
    #print(x[7])
    #print(c[7])
    #print(y[7])
    #print(x[8])
    #print(c[8])
    #print(y[8])
    #print(x[9])
    #print(c[9])
    #print(y[9])
    #print(x[10])
    #print(c[10])
    #print(y[10])
    #print(x[11])
    #print(c[11])
    #print(y[11])
    #print(x[12])
    #print(c[12])
    #print(y[12])
    #print(x[13])
    #print(c[13])
    #print(y[13])
    #print(x[14])
    #print(c[14])
    #print(y[14])
    #print(x[15])
    #print(c[15])
    #print(y[15])
    #print(x[16])
    #print(c[16])
    #print(y[16])
    #print(x[17])
    #print(c[17])
    #print(y[17])
    #print(x[18])
    #print(c[18])
    #print(y[18])
    #print(x[

if __name__ == '__main__':
    main()