def main():
    k = int(input())
    s = input()
    t = input()
    #print(k, s, t)
    s = s.replace('#', '')
    t = t.replace('#', '')
    #print(k, s, t)
    s = list(map(int, s))
    t = list(map(int, t))
    #print(k, s, t)
    s.sort()
    t.sort()
    #print(k, s, t)
    s = ''.join(map(str, s))
    t = ''.join(map(str, t))
    #print(k, s, t)
    #print(s > t)
    #print(s, t)
    #print(s[0:4], t[0:4])
    #print(s[0:4] > t[0:4])
    #print(s[0:4] < t[0:4])
    #print(int(s[0:4]) > int(t[0:4]))
    #print(int(s[0:4]) < int(t[0:4]))
    #print(int(s[0:4]) == int(t[0:4]))
    #print(s[0:4] > t[0:4])
    #print(s[0:4] < t[0:4])
    #print(s[0:4] == t[0:4])
    #print(s[0:4] > t[0:4])
    #print(s[0:4] < t[0:4])
    #print(s[0:4] == t[0:4])
    #print(s[0:4] > t[0:4])
    #print(s[0:4] < t[0:4])
    #print(s[0:4] == t[0:4])
    #print(s[0:4] > t[0:4])
    #print(s[0:4] < t[0:4])
    #print(s[0:4] == t[0:4])
    #print(s[0:4] > t[0:4])
    #print(s[0:4] < t[0:4])
    #print(s[0:4] == t[0:4])
    #print(s[0:4] > t[0:4])
    #print(s
