def main():
    N, M = map(int, input().split())
    X = sorted(list(map(int, input().split())))
    if N >= M:
        print(0)
        return
    #print(X)
    #print(N, M)
    #print(X[0], X[-1])
    #print(X[-1] - X[0])
    #print(X[1], X[-1])
    #print(X[-1] - X[1])
    #print(X[0], X[-2])
    #print(X[-2] - X[0])
    #print(X[0], X[-1])
    #print(X[-1] - X[0])
    #print(X[0], X[-1])
    #print(X[-1] - X[0])
    #print(X[0], X[-1])
    #print(X[-1] - X[0])
    #print(X[0], X[-1])
    #print(X[-1] - X[0])
    #print(X[0], X[-1])
    #print(X[-1] - X[0])
    #print(X[0], X[-1])
    #print(X[-1] - X[0])
    #print(X[0], X[-1])
    #print(X[-1] - X[0])
    #print(X[0], X[-1])
    #print(X[-1] - X[0])
    #print(X[0], X[-1])
    #print(X[-1] - X[0])
    #print(X[0], X[-1])
    #print(X[-1] - X[0])
    #print(X[0], X[-1])
    #print(X[-1] - X[0])
    #print(X[0], X[-1])
    #print(X[-1] - X[0])
    #print(X[0], X[-1])
    #print(X[-1] - X[0])
    #print(X[0], X[-1])
    #print(X[-1] - X[0])
    #print(X[0], X[-1])
    #print(X[-1] - X[0])
    #print(X[0], X[-1])
    #print(X[-1] - X[0])
    #print(X[0], X[-1])
