def main():
    N, M = map(int, input().split())
    A = list(map(int, input().split()))
    A.sort()
    #print(N, M)
    #print(A)
    #print(A[0])
    #print(A[-1])
    #print(A[0]*A[-1])
    #print(M//(A[0]*A[-1]))
    #print(M//(A[0]*A[-1])+1)
    #print(M//(A[0]*A[-1])-1)
    #print(M//(A[0]*A[-1])-2)
    #print(M//(A[0]*A[-1])-3)
    #print(M//(A[0]*A[-1])-4)
    #print(M//(A[0]*A[-1])-5)
    #print(M//(A[0]*A[-1])-6)
    #print(M//(A[0]*A[-1])-7)
    #print(M//(A[0]*A[-1])-8)
    #print(M//(A[0]*A[-1])-9)
    #print(M//(A[0]*A[-1])-10)
    #print(M//(A[0]*A[-1])-11)
    #print(M//(A[0]*A[-1])-12)
    #print(M//(A[0]*A[-1])-13)
    #print(M//(A[0]*A[-1])-14)
    #print(M//(A[0]*A[-1])-15)
    #print(M//(A[0]*A[-1])-16)
    #print(M//(A[0]*A[-1])-17)
    #print(M//(A[0]*A[-1])-18)
    #print(M//(A[0]*A[-1])-19)
    #print(M//(A[0]*A[-1])-20)
    #print(M//(A[0]*A[-1])-21)
    #print(M//(A[0]*A[-1])-22)
    #print(M//(A[0]*A[-1])-23)
    #print(M//(A[0]*A[-1])-24)
    #print(M//(A[0]*A[-1])-25)
    #print(M//(A[0]*A[-1])-26)
    #print(M//(A[0]*A[-1])-27)

if __name__ == '__main__':
    main()