def main():
    N,M = map(int,input().split())
    A = []
    B = []
    for i in range(M):
        a,b = map(int,input().split())
        A.append(a)
        B.append(b)
    #print(A)
    #print(B)
    #print(N)
    #print(M)
    #print(N)
    #print(M)
    #print(A)
    #print(B)
    #print(N)
    #print(M)
    #print(N)
    #print(M)
    #print(A)
    #print(B)
    #print(N)
    #print(M)
    #print(N)
    #print(M)
    #print(A)
    #print(B)
    #print(N)
    #print(M)
    #print(N)
    #print(M)
    #print(A)
    #print(B)
    #print(N)
    #print(M)
    #print(N)
    #print(M)
    #print(A)
    #print(B)
    #print(N)
    #print(M)
    #print(N)
    #print(M)
    #print(A)
    #print(B)
    #print(N)
    #p

if __name__ == '__main__':
    main()