def main():
    N, W = map(int, input().split())
    A = list(map(int, input().split()))
    A.sort()
    # print(A)
    # print(N, W)
    # print(A)
    # print(A[0], A[1], A[2])
    # print(A[0] + A[1] + A[2] <= W)
    # print(A[0] + A[1] <= W)
    # print(A[0] + A[2] <= W)
    # print(A[1] + A[2] <= W)
    # print(A[0] <= W)
    # print(A[1] <= W)
    # print(A[2] <= W)
    # print(A[0] + A[1] + A[2])
    # print(A[0] + A[1])
    # print(A[0] + A[2])
    # print(A[1] + A[2])
    # print(A[0])
    # print(A[1])
    # print(A[2])
    # print(A[0] + A[1] + A[2] <= W)
    # print(A[0] + A[1] <= W)
    # print(A[0] + A[2] <= W)
    # print(A[1] + A[2] <= W)
    # print(A[0] <= W)
    # print(A[1] <= W)
    # print(A[2] <= W)
    # print(A[0] + A[1] + A[2])
    # print(A[0] + A[1])
    # print(A[0] + A[2])
    # print(A[1] + A[2])
    # print(A[0])
    # print(A[1])
    # print(A[2])
    # print()
    # print(A[0] + A[1] + A[2] <= W)
    # print(A[0] + A[1] <= W)
    # print(A[0] + A[2] <= W)
    # print(A[1] + A[2] <= W)
    # print(A[0] <= W)
    # print(A[1] <= W)
    # print(A[2] <= W)
    #

if __name__ == '__main__':
    main()