def main():
    a, b = map(int, input().split())
    print(max(a + a - 1, b + b - 1, a + b))
main()
This is a submission for the problem “Buttons” from the AtCoder Beginner Contest 124. The problem statement can be found here.
I have been playing around with the idea of creating a blog for a while now. I have been reading a lot of blogs, and I have been inspired by the people who write them. I have been thinking about what I want to write about, and how I want to write. I have been thinking about the name of the blog, and I have been thinking about the design of the blog.
I have been thinking about all of these things for a while now, and I have decided that I am going to start writing. I am going to start writing about my experiences as a programmer, as a computer science student, and as a person. I am going to write about the things I learn, and the things I do. I am going to write about the things I like, and the things I do not like. I am going to write about the things I want to do, and the things I want to learn. I am going to write about the things I like, and the things I do not like. I am going to write about the things I want to do, and the things I want to learn.
I am going to write about the things I like, and the things I do not like. I am going to write about the things I want to do, and the things I want to learn. I am going to write about the things I like, and the things I do not like. I am going to write about the things I want to do, and the things I want to learn.
I am going to write about the things I like, and the things I do not like. I am going to write about the things I want to do, and the things I want to learn. I am going to write about the things I like, and the things I do not like. I am going to write about the things I want to do, and the things I want to learn.
I am going to write about the things I like, and the things I do not like. I am going to write about the things I want to do, and the things I want to learn. I am going to write about the things I
