def main():
    H,W = map(int,input().split())
    C = [input() for _ in range(H)]
    print(C)
    print(H,W)
    print(C[0][0])
    print(C[0][1])
    print(C[1][0])
    print(C[1][1])
    print(C[0][W-1])
    print(C[H-1][0])
    print(C[H-1][W-1])
    print(C[0][W-1])
    print(C[H-1][0])
    print(C[H-1][W-1])
    print(C[0][W-1])
    print(C[H-1][0])
    print(C[H-1][W-1])
    print(C[0][W-1])
    print(C[H-1][0])
    print(C[H-1][W-1])
    print(C[0][W-1])
    print(C[H-1][0])
    print(C[H-1][W-1])
    print(C[0][W-1])
    print(C[H-1][0])
    print(C[H-1][W-1])
    print(C[0][W-1])
    print(C[H-1][0])
    print(C[H-1][W-1])
    print(C[0][W-1])
    print(C[H-1][0])
    print(C[H-1][W-1])
    print(C[0][W-1])
    print(C[H-1][0])
    print(C[H-1][W-1])
    print(C[0][W-1])
    print(C[H-1][0])
    print(C[H-1][W-1])

if __name__ == '__main__':
    main()