def isConvex(A, B, C, D):
    # A, B, C, D = (Ax, Ay), (Bx, By), (Cx, Cy), (Dx, Dy)
    # A->B->C->D->A
    # A->C->B->D->A
    # A->D->C->B->A
    # A->B->C->D->A
    # A->C->B->D->A
    # A->D->C->B->A
    # A->B->D->C->A
    # A->C->D->B->A
    # A->D->B->C->A
    # A->B->C->D->A
    # A->C->B->D->A
    # A->D->C->B->A
    # A->B->D->C->A
    # A->C->D->B->A
    # A->D->B->C->A
    # A->B->C->D->A
    # A->C->B->D->A
    # A->D->C->B->A
    # A->B->D->C->A
    # A->C->D->B->A
    # A->D->B->C->A
    # A->B->C->D->A
    # A->C->B->D->A
    # A->D->C->B->A
    # A->B->D->C->A
    # A->C->D->B->A
    # A->D->B->C->A
    # A->B->C->D->A
    # A->C->B->D->A
    # A->D->C->B->A
    # A->B->D->C->A
    # A->C->D->B->A
    # A->D->B->C->A
    # A->B->C->D->A
    # A->C->B->D->A
    # A->D->C->B->A
    # A->B->D->C->A
    # A->C->D->B->A
