def main():
    n, m = map(int, input().split())
    edges = []
    for _ in range(m):
        edges.append(tuple(map(int, input().split())))
    edges.sort(key=lambda x: x[1])
    edges.sort(key=lambda x: x[0])
    #print(edges)
    #print(n, m)
    #print(edges)
    #print(edges[0])
    #print(edges[1])
    #print(edges[2])
    #print(edges[3])
    #print(edges[4])
    #print(edges[5])
    #print(edges[6])
    #print(edges[7])
    #print(edges[8])
    #print(edges[9])
    #print(edges[10])
    #print(edges[11])
    #print(edges[12])
    #print(edges[13])
    #print(edges[14])
    #print(edges[15])
    #print(edges[16])
    #print(edges[17])
    #print(edges[18])
    #print(edges[19])
    #print(edges[20])
    #print(edges[21])
    #print(edges[22])
    #print(edges[23])
    #print(edges[24])
    #print(edges[25])
    #print(edges[26])
    #print(edges[27])
    #print(edges[28])
    #print(edges[29])
    #print(edges[30])
    #print(edges[31])
    #print(edges[32])
    #print(edges[33])
    #print(edges[34])
    #print(edges[35])
    #print(edges[36])
    #print(edges[37])
    #print(edges[38])
    #print(edges[39])
    #print(edges[40])
    #print(edges[41])
    #print(edges[42])
    #print(edges[43])
    #print(edges[44])
    #print(edges[45])
    #print(edges[46])
    #print(edges[47])
    #print(edges[48])
    #print(edges[49])
    #print(edges[50])
    #print(edges[51])
    #print(edges[52])
    #print(edges[53])
    #print(edges[54])
    #print(edges[55])
    #print(edges[56])
    #print(edges[57])
    #print(edges[58])
    #print(edges[59])
    #print(edges[
