def main():
    N, C = map(int, input().split())
    #print(N,C)
    #print(type(N),type(C))
    a = []
    b = []
    c = []
    for i in range(N):
        a_i, b_i, c_i = map(int, input().split())
        a.append(a_i)
        b.append(b_i)
        c.append(c_i)
    #print(a)
    #print(b)
    #print(c)
    #print(type(a))
    #print(type(b))
    #print(type(c))
    #print(len(a))
    #print(len(b))
    #print(len(c))
    #print(a[0])
    #print(b[0])
    #print(c[0])
    #print(type(a[0]))
    #print(type(b[0]))
    #print(type(c[0]))
    #print(a[1])
    #print(b[1])
    #print(c[1])
    #print(type(a[1]))
    #print(type(b[1]))
    #print(type(c[1]))
    #print(a[2])
    #print(b[2])
    #print(c[2])
    #print(type(a[2]))
    #print(type(b[2]))
    #print(type(c[2]))
    #print(a[3])
    #print(b[3])
    #print(c[3])
    #print(type(a[3]))
    #print(type(b[3]))
    #print(type(c[3]))
    #print(a[4])
    #print(b[4])
    #print(c[4])
    #print(type(a[4]))
    #print(type(b[4]))
    #print(type(c[4]))
    #print(a[5])
    #print(b[5])
    #print(c[5])
    #print(type(a[5]))
    #print(type(b[5]))
    #print(type(c[5]))
    #print(a[6])
    #print(b[6])
    #print(c[6])
    #print(type(a[6]))
    #print(type(b[6]))
    #print(type(c[6]))
    #print(a[7])
    #print(b[7])
    #print(c[7])
    #print(type(a[7]))
    #print(type(b[7]))
    #print(type(c[7]))
    #print(a[8

if __name__ == '__main__':
    main()