def main():
    N, M, Q = map(int, input().split())
    AB = []
    CD = []
    for i in range(Q):
        a, b, c, d = map(int, input().split())
        AB.append([a, b])
        CD.append([c, d])
    # print(AB)
    # print(CD)
    # print(N, M, Q)
    # print(AB[1][0])
    # print(CD[1][0])
    # print(AB[2][0])
    # print(CD[2][0])
    # print(AB[3][0])
    # print(CD[3][0])
    # print(AB[4][0])
    # print(CD[4][0])
    # print(AB[5][0])
    # print(CD[5][0])
    # print(AB[6][0])
    # print(CD[6][0])
    # print(AB[7][0])
    # print(CD[7][0])
    # print(AB[8][0])
    # print(CD[8][0])
    # print(AB[9][0])
    # print(CD[9][0])
    # print(AB[10][0])
    # print(CD[10][0])
    # print(AB[11][0])
    # print(CD[11][0])
    # print(AB[12][0])
    # print(CD[12][0])
    # print(AB[13][0])
    # print(CD[13][0])
    # print(AB[14][0])
    # print(CD[14][0])
    # print(AB[15][0])
    # print(CD[15][0])
    # print(AB[16][0])
    # print(CD[16][0])
    # print(AB[17][0])
    # print(CD[17][0])
    # print(AB[18][0])
    # print(CD[18][0])
    # print(AB[19][0])
    # print(CD[19][0])
    # print(AB[20][0])
    # print(CD[20][0])
    # print(AB[21][0])
    # print(CD[

if __name__ == '__main__':
    main()