def main():
    #n = int(input())
    #s = input()
    #s = list(input().split())
    #a = list(map(int, input().split()))
    #n, m = list(map(int, input().split()))
    n, k = list(map(int, input().split()))
    a = list(map(int, input().split()))
    #b = [list(map(int, input().split())) for i in range(n)]
    #b = [list(input().split()) for i in range(n)]
    #b = [input() for i in range(n)]
    #b = [list(map(int, list(input()))) for i in range(n)]
    #print(a)
    #print(b)
    #print(c)
    #print(d)
    #print(e)
    #print(f)
    #print(g)
    #print(h)
    #print(i)
    #print(j)
    #print(k)
    #print(l)
    #print(m)
    #print(n)
    #print(o)
    #print(p)
    #print(q)
    #print(r)
    #print(s)
    #print(t)
    #print(u)
    #print(v)
    #print(w)
    #print(x)
    #print(y)
    #print(z)
    #print(a)
    #print(b)
    #print(c)
    #print(d)
    #print(e)
    #print(f)
    #print(g)
    #print(h)
    #print(i)
    #print(j)
    #print(k)
    #print(l)
    #print(m)
    #print(n)
    #print(o)
    #print(p)
    #print(q)
    #print(r)
    #print(s)
    #print(t)
    #print(u)
    #print(v)
    #print(w)
    #print(x)
    #print(y)
    #print(z)
    #print(a)
    #print(b)
    #print(c)
    #print(d)
    #print(e)
    #print(f)
    #print(g)
    #print(h)
    #print(i)
    #print(j)
    #print(k)
    #print(l)
    #print(m)
    #print(n)
    #print(o)
    #print(p)
    #print(q)
    #print(r)
    #print(s)
    #print(t)

if __name__ == '__main__':
    main()