def main():
    n = int(input())
    a = list(map(int, input().split()))
    #print(n)
    #print(a)
    a.sort()
    #print(a)
    #print(a[0])
    #print(a[n-1])
    #print(a[n-1] - a[0])
    #print(a[n-1] - a[0] + 1)
    #print(len(a))
    #print(len(set(a)))
    #print(set(a))
    #print(sorted(list(set(a))))
    #print(sorted(list(set(a)))[1])
    #print(sorted(list(set(a)))[2])
    #print(sorted(list(set(a)))[3])
    #print(sorted(list(set(a)))[4])
    #print(sorted(list(set(a)))[5])
    #print(sorted(list(set(a)))[6])
    #print(sorted(list(set(a)))[7])
    #print(sorted(list(set(a)))[8])
    #print(sorted(list(set(a)))[9])
    #print(sorted(list(set(a)))[10])
    #print(sorted(list(set(a)))[11])
    #print(sorted(list(set(a)))[12])
    #print(sorted(list(set(a)))[13])
    #print(sorted(list(set(a)))[14])
    #print(sorted(list(set(a)))[15])
    #print(sorted(list(set(a)))[16])
    #print(sorted(list(set(a)))[17])
    #print(sorted(list(set(a)))[18])
    #print(sorted(list(set(a)))[19])
    #print(sorted(list(set(a)))[20])
    #print(sorted(list(set(a)))[21])
    #print(sorted(list(set(a)))[22])
    #print(sorted(list(set(a)))[23])
    #print(sorted(list(set(a)))[24])
    #print(sorted(list(set(a)))[25])
    #print(sorted(list(set(a)))[26])
    #print(sorted(list(set(a)))[27])
    #print(sorted(list(set(a)))[28])
    #print(sorted(list(set(a)))[29])
    #print(sorted(list(set(a)))[30])
    #print(sorted(list(set(a)))[31])
    #print(sorted(list(set(a)))[32])
    #print(sorted(list(set(a)))[33])
    #print(sorted(list(set(a)))[34])
    #print(sorted(list(set(a)))[35])
    #print(sorted(list
