def solve():
    n,k=map(int,input().split())
    a=list(map(int,input().split()))
    a.sort()
    #print(a)
    #print('a[0]=',a[0])
    #print('a[-1]=',a[-1])
    #print('a[0]*a[1]=',a[0]*a[1])
    #print('a[-1]*a[-2]=',a[-1]*a[-2])
    #print('a[0]*a[-1]=',a[0]*a[-1])
    #print('a[0]*a[1]=',a[0]*a[1])
    #print('a[-1]*a[-2]=',a[-1]*a[-2])
    #print('a[0]*a[-1]=',a[0]*a[-1])
    #print('a[0]*a[1]=',a[0]*a[1])
    #print('a[-1]*a[-2]=',a[-1]*a[-2])
    #print('a[0]*a[-1]=',a[0]*a[-1])
    #print('a[0]*a[1]=',a[0]*a[1])
    #print('a[-1]*a[-2]=',a[-1]*a[-2])
    #print('a[0]*a[-1]=',a[0]*a[-1])
    #print('a[0]*a[1]=',a[0]*a[1])
    #print('a[-1]*a[-2]=',a[-1]*a[-2])
    #print('a[0]*a[-1]=',a[0]*a[-1])
    #print('a[0]*a[1]=',a[0]*a[1])
    #print('a[-1]*a[-2]=',a[-1]*a[-2])
    #print('a[0]*a[-1]=',a[0]*a[-1])
    #print('a[0]*a[1]=',a[0]*a[1])
    #print('a[-1]*a[-2]=',a[-1]*a[-2])
    #print('a[0]*a[-1]=',a[0]*a[-1])
    #print

if __name__ == '__main__':
    solve()