def main():
    N, M = map(int, input().split())
    X = list(map(int, input().split()))
    X.sort()
    #print(X)
    #print(N, M)
    #print(X)
    #座標の差を求める
    #X[i+1] - X[i]を求める
    #print(X[1] - X[0])
    #print(X[2] - X[1])
    #print(X[3] - X[2])
    #print(X[4] - X[3])
    #print(X[5] - X[4])
    #print(X[6] - X[5])
    #print(X[7] - X[6])
    #上記の結果をリストに格納する
    #差分のリスト
    #print(X[1] - X[0])
    #print(X[2] - X[1])
    #print(X[3] - X[2])
    #print(X[4] - X[3])
    #print(X[5] - X[4])
    #print(X[6] - X[5])
    #print(X[7] - X[6])
    #print(X[8] - X[7])
    #print(X[9] - X[8])
    #print(X[10] - X[9])
    #print(X[1] - X[0])
    #print(X[2] - X[1])
    #print(X[3] - X[2])
    #print(X[4] - X[3])
    #print(X[5] - X[4])
    #print(X[6] - X[5])
    #print(X[7] - X[6])
    #print(X[8] - X[7])
    #print(X[9] - X[8])
    #print(X[10] - X[9])
    #print(X[11] - X[10])
    #print(X[12] - X[11])
    #print(X[13] - X[12])
    #print(X[14] - X[13])
    #print(X[15] - X[14])
    #print(X[16] - X[15])

if __name__ == '__main__':
    main()