def main():
    n = int(input())
    s = [input() for i in range(n)]
    #print(n,s)
    #print(s[0])
    #print(s[0] == "AND")
    #print(s[0] == "OR")
    #print(s[1] == "AND")
    #print(s[1] == "OR")
    #print(s[2] == "AND")
    #print(s[2] == "OR")
    #print(s[3] == "AND")
    #print(s[3] == "OR")
    #print(s[4] == "AND")
    #print(s[4] == "OR")
    #print(s[5] == "AND")
    #print(s[5] == "OR")
    #print(s[6] == "AND")
    #print(s[6] == "OR")
    #print(s[7] == "AND")
    #print(s[7] == "OR")
    #print(s[8] == "AND")
    #print(s[8] == "OR")
    #print(s[9] == "AND")
    #print(s[9] == "OR")
    #print(s[10] == "AND")
    #print(s[10] == "OR")
    #print(s[11] == "AND")
    #print(s[11] == "OR")
    #print(s[12] == "AND")
    #print(s[12] == "OR")
    #print(s[13] == "AND")
    #print(s[13] == "OR")
    #print(s[14] == "AND")
    #print(s[14] == "OR")
    #print(s[15] == "AND")
    #print(s[15] == "OR")
    #print(s[16] == "AND")
    #print(s[16] == "OR")
    #print(s[17] == "AND")
    #print(s[17] == "OR")
    #print(s[18] == "AND")
    #print(s[18] == "OR")
    #print(s[19] == "AND")
    #print(s[19] == "OR")
    #print(s[20] == "AND")
    #print(s[20] == "OR")
    #print(s[
