def main():
    N = int(input())
    #print(N)
    #print(type(N))
    #S = []
    #P = []
    #for i in range(N):
    #    (S_i, P_i) = input().split()
    #    S.append(S_i)
    #    P.append(int(P_i))
    #print(S)
    #print(P)
    #print(type(S))
    #print(type(P))
    #print(type(S[0]))
    #print(type(P[0]))
    #print(type(S[0][0]))
    #print(type(P[0][0]))
    #print(type(P[0][1]))
    #print(type(P[0][2]))
    #print(type(P[0][3]))
    #print(type(P[0][4]))
    #print(type(P[0][5]))
    #print(type(P[0][6]))
    #print(type(P[0][7]))
    #print(type(P[0][8]))
    #print(type(P[0][9]))
    #print(type(P[0][10]))
    #print(type(P[0][11]))
    #print(type(P[0][12]))
    #print(type(P[0][13]))
    #print(type(P[0][14]))
    #print(type(P[0][15]))
    #print(type(P[0][16]))
    #print(type(P[0][17]))
    #print(type(P[0][18]))
    #print(type(P[0][19]))
    #print(type(P[0][20]))
    #print(type(P[0][21]))
    #print(type(P[0][22]))
    #print(type(P[0][23]))
    #print(type(P[0][24]))
    #print(type(P[0][25]))
    #print(type(P[0][26]))
    #print(type(P[0][27]))
    #print(type(P[0][28]))
    #print(type(P[0][29]))
    #print(type(P[0][30]))
    #print(type(P[0][31]))
    #print(type(P[0][32]))
    #print(type(P[0][33]))
    #print(type(P[0][34]))
    #print(type(P[0][35]))
    #print(type(P[0][36]))
    #print(type(P[0][37]))
    #print

if __name__ == '__main__':
    main()