def main():
    N, K = map(int, input().split())
    c = list(map(int, input().split()))
    # print(N, K, c)
    # print(type(N), type(K), type(c))
    # print(len(c))
    # print(c[0])
    # print(c[1])
    # print(c[2])
    # print(c[3])
    # print(c[4])
    # print(c[5])
    # print(c[6])
    # print(c[7])
    # print(c[8])
    # print(c[9])
    # print(c[10])
    # print(c[11])
    # print(c[12])
    # print(c[13])
    # print(c[14])
    # print(c[15])
    # print(c[16])
    # print(c[17])
    # print(c[18])
    # print(c[19])
    # print(c[20])
    # print(c[21])
    # print(c[22])
    # print(c[23])
    # print(c[24])
    # print(c[25])
    # print(c[26])
    # print(c[27])
    # print(c[28])
    # print(c[29])
    # print(c[30])
    # print(c[31])
    # print(c[32])
    # print(c[33])
    # print(c[34])
    # print(c[35])
    # print(c[36])
    # print(c[37])
    # print(c[38])
    # print(c[39])
    # print(c[40])
    # print(c[41])
    # print(c[42])
    # print(c[43])
    # print(c[44])
    # print(c[45])
    # print(c[46])
    # print(c[47])
    # print(c[48])
    # print(c[49])
    # print(c[50])
    # print(c[51])
    # print(c[52])
    # print(c[53])
    # print(c[54])
    # print(c[55])
    # print(c[56])
    # print(c[57])
    # print(c[58])
    # print(c[59])
    # print(c[60])
    # print(c[61])
    # print(c[62])
    # print(c[63])

if __name__ == '__main__':
    main()