def main():
    N = int(input())
    T = []
    K = []
    A = []
    for i in range(N):
        T_i, K_i, *A_i = map(int, input().split())
        T.append(T_i)
        K.append(K_i)
        A.append(A_i)
    # print(N)
    # print(T)
    # print(K)
    # print(A)
    # print(T[1])
    # print(K[1])
    # print(A[1])
    # print(len(A[1]))
    # print(A[1][0])
    # print(A[1][0])
    # print(A[1][1])
    # print(A[1][2])
    # print(A[1][3])
    # print(A[1][0] < 1)
    # print(A[1][1] < 1)
    # print(A[1][2] < 1)
    # print(A[1][3] < 1)
    # print(A[1][0] < 2)
    # print(A[1][1] < 2)
    # print(A[1][2] < 2)
    # print(A[1][3] < 2)
    # print(A[1][0] < 3)
    # print(A[1][1] < 3)
    # print(A[1][2] < 3)
    # print(A[1][3] < 3)
    # print(A[1][0] < 4)
    # print(A[1][1] < 4)
    # print(A[1][2] < 4)
    # print(A[1][3] < 4)
    # print(A[1][0] < 5)
    # print(A[1][1] < 5)
    # print(A[1][2] < 5)
    # print(A[1][3] < 5)
    # print(A[1][0] < 6)
    # print(A[1][1] < 6)
    # print(A[1][2] < 6)
    # print(A[1][3] < 6)
    # print(A[1][0] < 7)
    # print(A[1][1] < 7)
    # print(A[

if __name__ == '__main__':
    main()