def solve():
    N, K = map(int, input().split())
    A = list(map(int, input().split()))
    # print(N, K, A)
    # print(A[0])
    # print(A[0] + A[1])
    # print(A[0] + A[1] + A[2])
    # print(A[0] + A[1] + A[2] + A[3])
    # print(A[0] + A[1] + A[2] + A[3] + A[4])
    # print(A[0] + A[1] + A[2] + A[3] + A[4] + A[5])
    # print(A[1])
    # print(A[1] + A[2])
    # print(A[1] + A[2] + A[3])
    # print(A[1] + A[2] + A[3] + A[4])
    # print(A[1] + A[2] + A[3] + A[4] + A[5])
    # print(A[2])
    # print(A[2] + A[3])
    # print(A[2] + A[3] + A[4])
    # print(A[2] + A[3] + A[4] + A[5])
    # print(A[3])
    # print(A[3] + A[4])
    # print(A[3] + A[4] + A[5])
    # print(A[4])
    # print(A[4] + A[5])
    # print(A[5])
    # print(A[0] - K)
    # print(A[0] + A[1] - K)
    # print(A[0] + A[1] + A[2] - K)
    # print(A[0] + A[1] + A[2] + A[3] - K)
    # print(A[0] + A[1] + A[2] + A[3] + A[4] - K)
    # print(A[0] + A[1] + A[2] + A[3] + A[4] + A[5] - K)
    # print(A[1] - K

if __name__ == '__main__':
    solve()