def main():
    import sys
    import collections
    N = int(sys.stdin.readline())
    X = []
    Y = []
    for i in range(N):
        x,y = map(int, sys.stdin.readline().split())
        X.append(x)
        Y.append(y)
    #print(N)
    #print(X)
    #print(Y)
    #print(X[0])
    #print(Y[0])
    #print(X[1])
    #print(Y[1])
    #print("X[0]=",X[0])
    #print("Y[0]=",Y[0])
    #print("X[1]=",X[1])
    #print("Y[1]=",Y[1])
    #print("X[2]=",X[2])
    #print("Y[2]=",Y[2])
    #print("X[3]=",X[3])
    #print("Y[3]=",Y[3])
    #print("X[4]=",X[4])
    #print("Y[4]=",Y[4])
    #print("X[5]=",X[5])
    #print("Y[5]=",Y[5])
    #print("X[6]=",X[6])
    #print("Y[6]=",Y[6])
    #print("X[7]=",X[7])
    #print("Y[7]=",Y[7])
    #print("X[8]=",X[8])
    #print("Y[8]=",Y[8])
    #print("X[9]=",X[9])
    #print("Y[9]=",Y[9])
    #print("X[10]=",X[10])
    #print("Y[10]=",Y[10])
    #print("X[11]=",X[11])
    #print("Y[11]=",Y[11])
    #print("X[12]=",X[12])
    #print("Y[12]=",Y[12])
    #print("X[13]=",X[13])
    #print("Y[13]=",Y[13])
    #print("X[14]=",X[14])
    #print("Y[14]=",Y[14])
    #print("X[15]=",X[

if __name__ == '__main__':
    main()