def main():
    N = int(input())
    x = []
    y = []
    for i in range(N):
        x_i, y_i = map(int, input().split())
        x.append(x_i)
        y.append(y_i)
    #print(x)
    #print(y)
    #print(N)
    #print(len(x))
    #print(len(y))
    #print(len(x) == N)
    #print(len(y) == N)
    #print(len(x) == len(y))
    #print(len(x) == len(y) == N)
    #print(len(x) == len(y) == N == True)
    #print(len(x) == len(y) == N == True == True)
    #print(len(x) == len(y) == N == True == True == True)
    #print(len(x) == len(y) == N == True == True == True == True)
    #print(len(x) == len(y) == N == True == True == True == True == True)
    #print(len(x) == len(y) == N == True == True == True == True == True == True)
    #print(len(x) == len(y) == N == True == True == True == True == True == True == True)
    #print(len(x) == len(y) == N == True == True == True == True == True == True == True == True)
    #print(len(x) == len(y) == N == True == True == True == True == True == True == True == True == True)
    #print(len(x) == len(y) == N == True == True == True == True == True == True == True == True == True == True)
    #print(len(x) == len(y) == N == True == True == True == True == True == True == True == True == True == True == True)
    #print(len(x) == len(y) == N == True == True == True == True == True == True == True == True == True == True == True == True)
    #print(len(x) == len(y) == N == True == True == True == True == True == True == True == True == True == True == True == True == True)
    #print(len(x) == len(y) == N == True == True == True == True == True == True == True == True == True == True
