def main():
    H, W, rs, cs = map(int, input().split())
    N = int(input())
    rcs = [list(map(int, input().split())) for _ in range(N)]
    Q = int(input())
    dl = [list(map(str, input().split())) for _ in range(Q)]
    rcs.sort(key=lambda x: x[0])
    rcs.sort(key=lambda x: x[1])
    rcs.sort(key=lambda x: x[0] + x[1])
    rcs.sort(key=lambda x: x[0] - x[1])
    rcs.sort(key=lambda x: x[1] - x[0])
    rcs.sort(key=lambda x: x[0] + x[1])
    rcs.sort(key=lambda x: x[0] - x[1])
    rcs.sort(key=lambda x: x[1] - x[0])
    rcs.sort(key=lambda x: x[0] + x[1])
    rcs.sort(key=lambda x: x[1] - x[0])
    rcs.sort(key=lambda x: x[0] + x[1])
    rcs.sort(key=lambda x: x[1] - x[0])
    rcs.sort(key=lambda x: x[0] + x[1])
    rcs.sort(key=lambda x: x[1] - x[0])
    rcs.sort(key=lambda x: x[0] + x[1])
    rcs.sort(key=lambda x: x[1] - x[0])
    rcs.sort(key=lambda x: x[0] + x[1])
    rcs.sort(key=lambda x: x[1] - x[0])
    rcs.sort(key=lambda x: x[0] + x[1])
    rcs.sort(key=lambda x: x[1] - x[0])
    rcs.sort(key=lambda x: x[0] + x[1])
    rcs.sort(key=lambda x: x[1] - x[0])
    print(H, W, rs, cs)
    print(N)
    print(rcs)
    print(Q)
    print(dl)
    return
main()
