def solve():
    # n = int(input())
    # a = list(map(int, input().split()))
    s = int(input())
    # s = input()
    # h, w = map(int, input().split())
    # a = [list(map(int, input().split())) for _ in range(h)]
    # b = [int(input()) for _ in range(n)]
    # print(s)
    # print(len(s))
    # print(s[0])
    # print(s[1])
    # print(s[2])
    # print(s[3])
    # print(s[4])
    # print(s[5])
    # print(s[6])
    # print(s[7])
    # print(s[8])
    # print(s[9])
    # print(s[10])
    # print(s[11])
    # print(s[12])
    # print(s[13])
    # print(s[14])
    # print(s[15])
    # print(s[16])
    # print(s[17])
    # print(s[18])
    # print(s[19])
    # print(s[20])
    # print(s[21])
    # print(s[22])
    # print(s[23])
    # print(s[24])
    # print(s[25])
    # print(s[26])
    # print(s[27])
    # print(s[28])
    # print(s[29])
    # print(s[30])
    # print(s[31])
    # print(s[32])
    # print(s[33])
    # print(s[34])
    # print(s[35])
    # print(s[36])
    # print(s[37])
    # print(s[38])
    # print(s[39])
    # print(s[40])
    # print(s[41])
    # print(s[42])
    # print(s[43])
    # print(s[44])
    # print(s[45])
    # print(s[46])
    # print(s[47])
    # print(s[48])
    # print(s[49])
    # print(s[50])
    # print(s[51])
    # print(s[52])
    # print(s[53])
    # print(s[54])
    # print(s[55])
    # print(s[56])
    # print(s[57])
    # print(s
