def main():
    from sys import stdin
    #n = int(input())
    #a, b = map(int, input().split())
    #s = input()
    #a = list(map(int, input().split()))
    n, t = map(int, stdin.readline().split())
    #a = [int(input()) for _ in range(n)]
    #a = [list(map(int, input().split())) for _ in range(n)]
    #a = [stdin.readline().strip() for _ in range(n)]
    #a = stdin.readlines()
    #a = [int(s) for s in stdin.readlines()]
    #a = [stdin.readline().strip() for _ in range(n)]
    #a = [int(stdin.readline()) for _ in range(n)]
    #a = [list(map(int, stdin.readline().split())) for _ in range(n)]
    #a = [stdin.readline().strip() for _ in range(n)]
    #a = [list(map(int, stdin.readline().split())) for _ in range(n)]
    #a = [list(map(int, stdin.readline().split())) for _ in range(n)]
    #a = stdin.read().splitlines()
    #a = [int(s) for s in stdin.read().splitlines()]
    #a = [stdin.readline().strip() for _ in range(n)]
    #a = [int(stdin.readline()) for _ in range(n)]
    #a = [list(map(int, stdin.readline().split())) for _ in range(n)]
    #a = [stdin.readline().strip() for _ in range(n)]
    #a = [list(map(int, stdin.readline().split())) for _ in range(n)]
    #a = [list(map(int, stdin.readline().split())) for _ in range(n)]
    #a = stdin.read().splitlines()
    #a = [int(s) for s in stdin.read().splitlines()]
    #a = [stdin.readline().strip() for _ in range(n)]
    #a = [int(stdin.readline()) for _ in range(n)]
    #a = [list(map(int, stdin.readline().split())) for _ in range(n)]
    #a = [stdin.readline().strip() for _ in range(n)]
    a = [list(map(int, stdin.readline().split())) for _ in range(n)]
    #a = [list(map(int, stdin.readline().split())) for _ in
