def main():
    #n = int(input())
    #a = list(map(int, input().split()))
    #s = input()
    #h = [int(input()) for i in range(n)]
    n = 4
    h = [1, 2, 2, 1]
    #h = [int(input()) for i in range(n)]
    #a = list(map(int, input().split()))
    #s = input()
    #n = int(input())
    #a = list(map(int, input().split()))
    #s = input()
    #h = [int(input()) for i in range(n)]
    #n = int(input())
    #a = list(map(int, input().split()))
    #s = input()
    #h = [int(input()) for i in range(n)]
    #n = int(input())
    #a = list(map(int, input().split()))
    #s = input()
    #h = [int(input()) for i in range(n)]
    #n = int(input())
    #a = list(map(int, input().split()))
    #s = input()
    #h = [int(input()) for i in range(n)]
    #n = int(input())
    #a = list(map(int, input().split()))
    #s = input()
    #h = [int(input()) for i in range(n)]
    #n =
