def main():
    N, M = map(int, input().split())
    A = []
    for i in range(M):
        A.append(list(map(int, input().split()))[1:])
    
    #print(A)
    #print(len(A))
    #print(A[0])
    #print(len(A[0]))
    #print(A[0][0])
    #print(A[0][1])
    #print(A[1][0])
    #print(A[1][1])
    #print(len(A[0]) + len(A[1]))
    #print(N)
    #print(A[0][0])
    #print(A[1][0])
    #print(A[0][1])
    #print(A[1][1])
    #print(A[0][0])
    #print(A[1][1])
    #print(A[0][1])
    #print(A[1][0])
    #print(A[0][0])
    #print(A[1][0])
    #print(A[0][1])
    #print(A[1][1])
    #print(A[0][0])
    #print(A[1][1])
    #print(A[0][1])
    #print(A[1][0])
    #print(A[0][0])
    #print(A[1][0])
    #print(A[0][1])
    #print(A[1][1])
    #print(A[0][0])
    #print(A[1][1])
    #print(A[0][1])
    #print(A[1][0])
    #print(A[0][0])
    #print(A[1][0])
    #print(A[0][1])
    #print(A[1][1])
    #print(A[0][0])
    #print(A[1][1])
    #print(A[0][1])
    #print(A[1][0])
    #print(A[0][0])
    #print(A[1][0])
    #print(A[0][1])
    #print(A[1][1])
    #print(A[0][0])
    #print(A[1][1])
    #print(A[0][1])
    #print(A[1][0])
    #print(A[0][0])
    #print(A[1][0])
