def main():
    N, T = map(int, input().split())
    A = list(map(int, input().split()))
    #print(N, T)
    #print(A)
    sum_A = sum(A)
    #print(sum_A)
    #print(T % sum_A)
    #print(T // sum_A)
    #print(T // sum_A * sum_A)
    #print(T - T // sum_A * sum_A)
    #print(T - T // sum_A * sum_A)
    #print(sum(A[:2]))
    #print(sum(A[:3]))
    #print(sum(A[:4]))
    #print(sum(A[:5]))
    #print(sum(A[:6]))
    #print(sum(A[:7]))
    #print(sum(A[:8]))
    #print(sum(A[:9]))
    #print(sum(A[:10]))
    #print(sum(A[:11]))
    #print(sum(A[:12]))
    #print(sum(A[:13]))
    #print(sum(A[:14]))
    #print(sum(A[:15]))
    #print(sum(A[:16]))
    #print(sum(A[:17]))
    #print(sum(A[:18]))
    #print(sum(A[:19]))
    #print(sum(A[:20]))
    #print(sum(A[:21]))
    #print(sum(A[:22]))
    #print(sum(A[:23]))
    #print(sum(A[:24]))
    #print(sum(A[:25]))
    #print(sum(A[:26]))
    #print(sum(A[:27]))
    #print(sum(A[:28]))
    #print(sum(A[:29]))
    #print(sum(A[:30]))
    #print(sum(A[:31]))
    #print(sum(A[:32]))
    #print(sum(A[:33]))
    #print(sum(A[:34]))
    #print(sum(A[:35]))
    #print(sum(A[:36]))
    #print(sum(A[:37]))
    #print(sum(A[:38]))
    #print(sum(A[:39]))
    #print(sum(A[:40]))
    #print(sum(A[:41]))
    #print(sum(A[:42]))
    #print(sum(A[:43]))
    #print(sum(A[:44]))
    #print(sum(A[:45]))
    #print(sum(A[:46]))
    #print(sum(A[:47]))
    #print(sum(A[:48]))
    #print(sum(A[:49]))
    #print(sum(A[:50]))
    #print(sum(A
