def main():
    N = int(input())
    sx, sy, tx, ty = map(int, input().split())
    circles = [list(map(int, input().split())) for _ in range(N)]
    #print(circles)
    #print(sx, sy, tx, ty)
    #print(circles[1][0], circles[1][1], circles[1][2])
    #print(circles[2][0], circles[2][1], circles[2][2])
    #print(circles[3][0], circles[3][1], circles[3][2])
    #print(sx, sy)
    #print(tx, ty)
    #print(circles)
    #print(circles[0])
    #print(circles[1])
    #print(circles[2])
    #print(circles[3])
    #print(circles[0][0], circles[0][1], circles[0][2])
    #print(circles[1][0], circles[1][1], circles[1][2])
    #print(circles[2][0], circles[2][1], circles[2][2])
    #print(circles[3][0], circles[3][1], circles[3][2])
    #print(circles[0][0], circles[0][1], circles[0][2])
    #print(circles[1][0], circles[1][1], circles[1][2])
    #print(circles[2][0], circles[2][1], circles[2][2])
    #print(circles[3][0], circles[3][1], circles[3][2])
    print("Yes")

if __name__ == '__main__':
    main()