def main():
    N, M = map(int, input().split())
    P = [0]*M
    Y = [0]*M
    for i in range(M):
        P[i], Y[i] = map(int, input().split())
    # sort by P, Y
    P_sorted = sorted(range(M), key=lambda k: P[k])
    P_sorted2 = sorted(range(M), key=lambda k: Y[k])
    #print(P_sorted)
    #print(P_sorted2)
    #print(P)
    #print(Y)
    #print(P[P_sorted[0]])
    #print(Y[P_sorted2[0]])
    #print(P[P_sorted[1]])
    #print(Y[P_sorted2[1]])
    #print(P[P_sorted[2]])
    #print(Y[P_sorted2[2]])
    #print(P[P_sorted[3]])
    #print(Y[P_sorted2[3]])
    #print(P[P_sorted[4]])
    #print(Y[P_sorted2[4]])
    #print(P[P_sorted[5]])
    #print(Y[P_sorted2[5]])
    #print(P[P_sorted[6]])
    #print(Y[P_sorted2[6]])
    #print(P[P_sorted[7]])
    #print(Y[P_sorted2[7]])
    #print(P[P_sorted[8]])
    #print(Y[P_sorted2[8]])
    #print(P[P_sorted[9]])
    #print(Y[P_sorted2[9]])
    #print(P[P_sorted[10]])
    #print(Y[P_sorted2[10]])
    #print(P[P_sorted[11]])
    #print(Y[P_sorted2[11]])
    #print(P[P_sorted[12]])
    #print(Y[P_sorted2[12]])
    #print(P[P_sorted[13]])
    #print(Y[P_sorted2[13]])
    #print(P[P_sorted[14]])
    #print(Y[P_sorted2[14]])
    #print(P[P_sorted[15]])
    #print(Y[P_sorted2[15]])
    #print(P[P_sorted[16]])
    #print(Y[P_sorted2[16]])
    #print(P[P_sorted[17]])
    #print(Y[P_sorted2[17]])
    #print(P[P_sorted[18]])
    #print(Y[P_sorted2[18]])
    #print(P[P_sorted[19]])
    #print(Y[P_sorted2[19]])
    #print(P[P_sorted

if __name__ == '__main__':
    main()