def main():
    N,M = map(int,input().split())
    P = [0]*M
    Y = [0]*M
    for i in range(M):
        P[i], Y[i] = map(int,input().split())
    P = [p-1 for p in P]
    #print(P)
    #print(Y)
    #print(N,M)
    #print(P)
    #print(Y)
    Y_sorted = sorted(Y)
    #print(Y_sorted)
    P_sorted = sorted(P)
    #print(P_sorted)
    P_sorted = sorted(P_sorted)
    #print(P_sorted)
    Y_sorted = sorted(Y_sorted)
    #print(Y_sorted)
    #print(P_sorted)
    #print(Y_sorted)
    P_sorted = sorted(P_sorted)
    #print(P_sorted)
    Y_sorted = sorted(Y_sorted)
    #print(Y_sorted)
    #print(P_sorted)
    #print(Y_sorted)
    P_sorted = sorted(P_sorted)
    #print(P_sorted)
    Y_sorted = sorted(Y_sorted)
    #print(Y_sorted)
    #print(P_sorted)
    #print(Y_sorted)
    P_sorted = sorted(P_sorted)
    #print(P_sorted)
    Y_sorted = sorted(Y_sorted)
    #print(Y_sorted)
    #print(P_sorted)
    #print(Y_sorted)
    P_sorted = sorted(P_sorted)
    #print(P_sorted)
    Y_sorted = sorted(Y_sorted)
    #print(Y_sorted)
    #print(P_sorted)
    #print(Y_sorted)
    P_sorted = sorted(P_sorted)
    #print(P_sorted)
    Y_sorted = sorted(Y_sorted)
    #print(Y_sorted)
    #print(P_sorted)
    #print(Y_sorted)
    P_sorted = sorted(P_sorted)
    #print(P_sorted)
    Y_sorted = sorted(Y_sorted)
    #print(Y_sorted)
    #print(P_sorted)
    #print(Y_sorted)
    P_sorted = sorted(P_sorted)
    #print(P_sorted)
    Y_sorted = sorted(Y_sorted)
    #print(Y_sorted)
    #print(P_sorted)
    #print(Y_sorted)
    P_sorted = sorted(P_sorted)
    #print(P_sorted)
    Y_sorted = sorted(Y_sorted)
    #print(Y_sorted)
    #print(P_sorted)
    #print(Y_sorted)
    P_sorted = sorted(P_sorted)
    #print(P_sorted)
    Y_sorted = sorted(Y_sorted)
    #print(Y_sorted

if __name__ == '__main__':
    main()