def main():
    S = input()
    K = int(input())
    S = S.replace("1", "a")
    S = S.replace("2", "bb")
    S = S.replace("3", "ccc")
    S = S.replace("4", "dddd")
    S = S.replace("5", "eeeee")
    S = S.replace("6", "ffffff")
    S = S.replace("7", "ggggggg")
    S = S.replace("8", "hhhhhhhh")
    S = S.replace("9", "iiiiiiiii")
    S = S.replace("0", "jjjjjjjjjj")
    S = S.replace("a", "1")
    S = S.replace("b", "2")
    S = S.replace("c", "3")
    S = S.replace("d", "4")
    S = S.replace("e", "5")
    S = S.replace("f", "6")
    S = S.replace("g", "7")
    S = S.replace("h", "8")
    S = S.replace("i", "9")
    S = S.replace("j", "0")
    print(S[K-1])

if __name__ == '__main__':
    main()