def main():
    N = int(input())
    AB = []
    for i in range(N-1):
        AB.append(list(map(int,input().split())))
    #print(N,AB)
    #print("----------")
    #print(AB[0][0],AB[0][1])
    #print(AB[1][0],AB[1][1])
    #print(AB[2][0],AB[2][1])
    #print(AB[3][0],AB[3][1])
    #print("----------")
    #print(AB[0][0],AB[0][1])
    #print(AB[0][1],AB[1][0])
    #print(AB[1][0],AB[1][1])
    #print(AB[1][1],AB[2][0])
    #print(AB[2][0],AB[2][1])
    #print(AB[2][1],AB[3][0])
    #print(AB[3][0],AB[3][1])
    #print("----------")
    #print(AB[0][0],AB[0][1])
    #print(AB[0][1],AB[1][0])
    #print(AB[1][0],AB[1][1])
    #print(AB[1][1],AB[2][0])
    #print(AB[2][0],AB[2][1])
    #print(AB[2][1],AB[3][0])
    #print(AB[3][0],AB[3][1])
    #print("----------")
    #print(AB[0][0],AB[0][1])
    #print(AB[0][1],AB[1][0])
    #print(AB[1][0],AB[1][1])
    #print(AB[1][1],AB[2][0])
    #print(AB[2][0],AB[2][1])
    #print(AB[2][1],AB[3][0])
    #print(AB[3][0],AB[3][1])
    #print("----------")
    #print(AB[0][0],AB[0][1])
    #print(AB[0][1],AB[1][0])

if __name__ == '__main__':
    main()