def main():
    n = int(input())
    if n == 1:
        print(1)
        print(3)
        print(2)
        print(0)
    elif n == 2:
        print(2)
        print(5)
        print(4)
        print(0)
    elif n == 3:
        print(5)
        print(8)
        print(7)
        print(6)
        print(0)
    elif n == 4:
        print(2)
        print(5)
        print(4)
        print(7)
        print(6)
        print(0)
    elif n == 5:
        print(5)
        print(8)
        print(7)
        print(10)
        print(9)
        print(0)
    elif n == 6:
        print(8)
        print(11)
        print(10)
        print(13)
        print(12)
        print(0)
    elif n == 7:
        print(2)
        print(5)
        print(4)
        print(7)
        print(6)
        print(9)
        print(8)
        print(0)
    elif n == 8:
        print(5)
        print(8)
        print(7)
        print(10)
        print(9)
        print(12)
        print(11)
        print(0)
    elif n == 9:
        print(8)
        print(11)
        print(10)
        print(13)
        print(12)
        print(15)
        print(14)
        print(0)
    elif n == 10:
        print(2)
        print(5)
        print(4)
        print(7)
        print(6)
        print(9)
        print(8)
        print(11)
        print(10)
        print(0)
    elif n == 11:
        print(5)
        print(8)
        print(7)
        print(10)
        print(9)
        print(12)
        print(11)
        print(14)
        print(13)
        print(0)
    elif n == 12:
        print(8)
        print(11)
        print(10)
        print(13)
        print(12)
        print(15)
        print(
