def main():
    N = int(input())
    # if N == 1:
    #     print(1)
    #     print(2)
    #     print(3)
    #     exit()
    # if N == 2:
    #     print(2)
    #     print(1)
    #     print(4)
    #     print(3)
    #     print(5)
    #     exit()
    # if N == 3:
    #     print(2)
    #     print(1)
    #     print(4)
    #     print(3)
    #     print(6)
    #     print(5)
    #     print(7)
    #     exit()
    # if N == 4:
    #     print(2)
    #     print(1)
    #     print(4)
    #     print(3)
    #     print(6)
    #     print(5)
    #     print(8)
    #     print(7)
    #     print(9)
    #     print(10)
    #     exit()
    # if N == 5:
    #     print(2)
    #     print(1)
    #     print(4)
    #     print(3)
    #     print(6)
    #     print(5)
    #     print(8)
    #     print(7)
    #     print(10)
    #     print(9)
    #     print(11)
    #     print(12)
    #     exit()
    # if N == 6:
    #     print(2)
    #     print(1)
    #     print(4)
    #     print(3)
    #     print(6)
    #     print(5)
    #     print(8)
    #     print(7)
    #     print(10)
    #     print(9)
    #     print(12)
    #     print(11)
    #     print(13)
    #     print(14)
    #     exit()
    # if N == 7:
    #     print(2)
    #     print(1)
    #     print(4)
    #     print(3)
    #     print(6)
    #     print(5)
    #     print(8)
