def main():
    n,x,y = map(int,input().split())
    u = [0]*(n-1)
    v = [0]*(n-1)
    for i in range(n-1):
        u[i],v[i] = map(int,input().split())
    # print(n,x,y,u,v)
    # print(type(n),type(x),type(y),type(u),type(v))
    # print(len(u),len(v))
    # print(u)
    # print(v)
    # print(u[0])
    # print(v[0])
    # print(u[1])
    # print(v[1])
    # print(u[2])
    # print(v[2])
    # print(u[3])
    # print(v[3])
    # print(u[4])
    # print(v[4])
    # print(u[5])
    # print(v[5])
    # print(u[6])
    # print(v[6])
    # print(u[7])
    # print(v[7])
    # print(u[8])
    # print(v[8])
    # print(u[9])
    # print(v[9])
    # print(u[10])
    # print(v[10])
    # print(u[11])
    # print(v[11])
    # print(u[12])
    # print(v[12])
    # print(u[13])
    # print(v[13])
    # print(u[14])
    # print(v[14])
    # print(u[15])
    # print(v[15])
    # print(u[16])
    # print(v[16])
    # print(u[17])
    # print(v[17])
    # print(u[18])
    # print(v[18])
    # print(u[19])
    # print(v[19])
    # print(u[20])
    # print(v[20])
    # print(u[21])
    # print(v[21])
    # print(u[22])
    # print(v[22])
    # print(u[23])
    # print(v[23])
    # print(u[24])
    # print(v[24])
    # print(u[25])
    # print(v[25])
    # print(u[26])
    # print(v[26])
    # print(u[27])
    # print(v[27])
    # print(u[28

if __name__ == '__main__':
    main()