def main():
    N = int(input())
    S = input()
    W = list(map(int, input().split()))
    #print(N)
    #print(S)
    #print(W)
    #print("len(S)=",len(S))
    #print("len(W)=",len(W))
    if len(S) != N:
        print("len(S) != N")
    if len(W) != N:
        print("len(W) != N")
    if len(S) != len(W):
        print("len(S) != len(W)")
    #print("S=",S)
    #print("W=",W)
    #print("S[0]=",S[0])
    #print("W[0]=",W[0])
    #print("S[1]=",S[1])
    #print("W[1]=",W[1])
    #print("S[2]=",S[2])
    #print("W[2]=",W[2])
    #print("S[3]=",S[3])
    #print("W[3]=",W[3])
    #print("S[4]=",S[4])
    #print("W[4]=",W[4])
    #print("S[5]=",S[5])
    #print("W[5]=",W[5])
    #print("S[6]=",S[6])
    #print("W[6]=",W[6])
    #print("S[7]=",S[7])
    #print("W[7]=",W[7])
    #print("S[8]=",S[8])
    #print("W[8]=",W[8])
    #print("S[9]=",S[9])
    #print("W[9]=",W[9])
    #print("S[10]=",S[10])
    #print("W[10]=",W[10])
    #print("S[11]=",S[11])
    #print("W[11]=",W[11])
    #print("S[12]=",S[12])
    #print("W[12]=",W[12])
    #print("S[13]=",S[13])
    #print("W[13]=",W[13])
    #print("S[

if __name__ == '__main__':
    main()