def main():
    n = int(input())
    s = []
    for i in range(n):
        s.append(input())
    #print(s)
    #print(s.count('newfile'))
    #print(s.count('newfolder'))
    #print(s.count('newfile')+s.count('newfolder'))
    #print(s.count('newfile')+s.count('newfolder')+1)
    #print(s.count('newfile')+s.count('newfolder')+2)
    #print(s.count('newfile')+s.count('newfolder')+3)
    #print(s.count('newfile')+s.count('newfolder')+4)
    #print(s.count('newfile')+s.count('newfolder')+5)
    #print(s.count('newfile')+s.count('newfolder')+6)
    #print(s.count('newfile')+s.count('newfolder')+7)
    #print(s.count('newfile')+s.count('newfolder')+8)
    #print(s.count('newfile')+s.count('newfolder')+9)
    #print(s.count('newfile')+s.count('newfolder')+10)
    #print(s.count('newfile')+s.count('newfolder')+11)
    #print(s.count('newfile')+s.count('newfolder')+12)
    #print(s.count('newfile')+s.count('newfolder')+13)
    #print(s.count('newfile')+s.count('newfolder')+14)
    #print(s.count('newfile')+s.count('newfolder')+15)
    #print(s.count('newfile')+s.count('newfolder')+16)
    #print(s.count('newfile')+s.count('newfolder')+17)
    #print(s.count('newfile')+s.count('newfolder')+18)
    #print(s.count('newfile')+s.count('newfolder')+19)
    #print(s.count('newfile')+s.count('newfolder')+20)
    #print(s.count('newfile')+s.count('newfolder')+21)
    #print(s.count('newfile')+s.count('newfolder')+22)
    #print(s.count('newfile')+s.count('newfolder')+23)
    #print(s.count('newfile')+s.count('newfolder')+24)
    #print(s.count('newfile')+s.count('newfolder')+25)
    #print(s.count('newfile')+s.count('new
