def main():
    S = input()
    #print(S)
    #print(type(S))
    #print(len(S))
    #print(S[0])
    #print(S[1])
    #print(S[2])
    #print(S[3])
    #print(S[4])
    #print(S[5])
    #print(S[6])
    #print(S[7])
    #print(S[8])
    #print(S[9])
    #print(S[0] == "o")
    #print(S[1] == "o")
    #print(S[2] == "o")
    #print(S[3] == "o")
    #print(S[4] == "o")
    #print(S[5] == "o")
    #print(S[6] == "o")
    #print(S[7] == "o")
    #print(S[8] == "o")
    #print(S[9] == "o")
    #print(S[0] == "x")
    #print(S[1] == "x")
    #print(S[2] == "x")
    #print(S[3] == "x")
    #print(S[4] == "x")
    #print(S[5] == "x")
    #print(S[6] == "x")
    #print(S[7] == "x")
    #print(S[8] == "x")
    #print(S[9] == "x")
    #print(S[0] == "?")
    #print(S[1] == "?")
    #print(S[2] == "?")
    #print(S[3] == "?")
    #print(S[4] == "?")
    #print(S[5] == "?")
    #print(S[6] == "?")
    #print(S[7] == "?")
    #print(S[8] == "?")
    #print(S[9] == "?")
    #print(S[0] == "o" or S[0] == "?")
    #print(S[1] == "o" or S[1] == "?")
    #print(S[2] == "o" or S[2] == "?")
    #print(S[3] == "o" or S[3] == "?")
    #print(S[4] == "o

if __name__ == '__main__':
    main()