def solve():
    K = int(input())
    S = input()
    T = input()
    #print(K, S, T)
    #print(type(K), type(S), type(T))
    #print(len(S), len(T))
    #print(S[0:4], S[4], T[0:4], T[4])
    #print(S[0:4] == T[0:4])
    #print(S[0:4] == T[0:4] and S[4] == '#' and T[4] == '#')
    #print(S[0:4] == T[0:4] and S[4] == '#' and T[4] == '#')
    #print(S[0:4] == T[0:4] and S[4] == '#' and T[4] == '#')
    #print(S[0:4] == T[0:4] and S[4] == '#' and T[4] == '#')
    #print(S[0:4] == T[0:4] and S[4] == '#' and T[4] == '#')
    #print(S[0:4] == T[0:4] and S[4] == '#' and T[4] == '#')
    #print(S[0:4] == T[0:4] and S[4] == '#' and T[4] == '#')
    #print(S[0:4] == T[0:4] and S[4] == '#' and T[4] == '#')
    #print(S[0:4] == T[0:4] and S[4] == '#' and T[4] == '#')
    #print(S[0:4] == T[0:4] and S[4] == '#' and T[4] == '#')
    #print(S[0:4] == T[0:4] and S[4] == '#' and T[4] == '#')
    #print(S[0:4] == T[0:4] and S[4] == '#' and T[4] == '#')
    #print(S[0:4] == T[0:4] and S[4] == '#' and T[4] == '#')
    #print(S[0:4] ==
