def main():
    N, M = map(int, input().split())
    k = [0] * M
    a = [[0] * M for i in range(N)]
    for i in range(M):
        k[i] = int(input())
        a[i] = list(map(int, input().split()))
    # print(N, M, k, a)
    # print('---')
    # print(a[0][0])
    # print(a[0][1])
    # print(a[1][0])
    # print(a[1][1])
    # print('---')
    # print(a[0][0])
    # print(a[1][0])
    # print(a[0][1])
    # print(a[1][1])
    # print('---')
    # print(a[0][0])
    # print(a[1][1])
    # print(a[0][1])
    # print(a[1][0])
    # print('---')
    # print(a[0][1])
    # print(a[1][0])
    # print(a[0][0])
    # print(a[1][1])
    # print('---')
    # print(a[0][1])
    # print(a[1][1])
    # print(a[0][0])
    # print(a[1][0])
    # print('---')
    # print(a[1][0])
    # print(a[1][1])
    # print(a[0][0])
    # print(a[0][1])
    # print('---')
    # print(a[1][1])
    # print(a[1][0])
    # print(a[0][1])
    # print(a[0][0])
    # print('---')
    # print(a[1][1])
    # print(a[0][0])
    # print(a[0][1])
    # print(a[1][0])
    # print('---')
    # print(a[1][1])
    # print(a[0][1])
    # print(a[0][0])
    # print(a[1][1])
    # print('---')
    # print(a[1][1])
    # print(a[0][1])
    # print(a[1][0])
    # print(a[0][0])
    # print('
