def main():
    N = int(input())
    A = []
    for i in range(0,N):
        A.append([int(x) for x in input().split()])
    #print(A)
    #print(len(A))
    #print(len(A[0]))
    #print(A[0][2])
    #print(A[0][3])
    #print(A[0][4])
    #print(A[1][2])
    #print(A[1][3])
    #print(A[1][4])
    #print(A[2][3])
    #print(A[2][4])
    #print(A[3][4])
    #print(A[1][0])
    #print(A[2][0])
    #print(A[3][0])
    #print(A[4][0])
    #print(A[2][1])
    #print(A[3][1])
    #print(A[4][1])
    #print(A[3][2])
    #print(A[4][2])
    #print(A[4][3])
    #print(A[0][1])
    #print(A[0][2])
    #print(A[0][3])
    #print(A[0][4])
    #print(A[1][2])
    #print(A[1][3])
    #print(A[1][4])
    #print(A[2][3])
    #print(A[2][4])
    #print(A[3][4])
    #print(A[1][0])
    #print(A[2][0])
    #print(A[3][0])
    #print(A[4][0])
    #print(A[2][1])
    #print(A[3][1])
    #print(A[4][1])
    #print(A[3][2])
    #print(A[4][2])
    #print(A[4][3])
    #print(A[0][1])
    #print(A[0][2])
    #print(A[0][3])
    #print(A[0][4])
    #print(A[1][2])
    #print(A[1][3])
    #print(A[1][4])
    #print(A[2][3])
    #print(A[2][4])
    #print(A[3][4])
    #print(A[
