def main():
    N, M = map(int, input().split())
    A = list(map(int, input().split()))
    A.sort()
    #print(A)
    #print(A[0])
    #print(A[N-1])
    #print(A[N-1]//A[0])
    #print(A[N-1]%A[0])
    #print(A[N-1]//A[0] + 1)
    #print(A[N-1]//A[0] - 1)
    #print(A[N-1]//A[0] - 2)
    #print(A[N-1]//A[0] - 3)
    #print(A[N-1]//A[0] - 4)
    #print(A[N-1]//A[0] - 5)
    #print(A[N-1]//A[0] - 6)
    #print(A[N-1]//A[0] - 7)
    #print(A[N-1]//A[0] - 8)
    #print(A[N-1]//A[0] - 9)
    #print(A[N-1]//A[0] - 10)
    #print(A[N-1]//A[0] - 11)
    #print(A[N-1]//A[0] - 12)
    #print(A[N-1]//A[0] - 13)
    #print(A[N-1]//A[0] - 14)
    #print(A[N-1]//A[0] - 15)
    #print(A[N-1]//A[0] - 16)
    #print(A[N-1]//A[0] - 17)
    #print(A[N-1]//A[0] - 18)
    #print(A[N-1]//A[0] - 19)
    #print(A[N-1]//A[0] - 20)
    #print(A[N-1]//A[0] - 21)
    #print(A[N-1]//A[0] - 22)
    #print(A[N-1]//A[0] - 23)
    #print(A[N-1]//A[0] - 24)

if __name__ == '__main__':
    main()