def main():
    H, W = map(int, input().split())
    C = []
    for i in range(H):
        C.append(input())
    # print(C)
    # print(C[0][0])
    # print(C[0][1])
    # print(C[1][0])
    # print(C[1][1])
    # print(C[2][0])
    # print(C[2][1])
    # print(C[3][0])
    # print(C[3][1])
    # print(C[4][0])
    # print(C[4][1])
    # print(C[0][1])
    # print(C[1][0])
    # print(C[1][1])
    # print(C[2][0])
    # print(C[2][1])
    # print(C[3][0])
    # print(C[3][1])
    # print(C[4][0])
    # print(C[4][1])
    # print(C[0][1])
    # print(C[1][0])
    # print(C[1][1])
    # print(C[2][0])
    # print(C[2][1])
    # print(C[3][0])
    # print(C[3][1])
    # print(C[4][0])
    # print(C[4][1])
    # print(C[0][1])
    # print(C[1][0])
    # print(C[1][1])
    # print(C[2][0])
    # print(C[2][1])
    # print(C[3][0])
    # print(C[3][1])
    # print(C[4][0])
    # print(C[4][1])
    # print(C[0][1])
    # print(C[1][0])
    # print(C[1][1])
    # print(C[2][0])
    # print(C[2][1])
    # print(C[3][0])
    # print(C[3][1])
    # print(C[4][0])
    # print(C[4][1])
    # print(C[0][1])
    # print(C[1][0])
    # print(C[1][1])
    # print(C[2][0])
    # print(C[2][1])
    # print(C[3

if __name__ == '__main__':
    main()