def main():
    N, X = map(int, input().split())
    A = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
    #print(N, X)
    #print(A)
    #print(A[0])
    #print(A[25])
    #print(A[26])
    #print(len(A))
    #print(len(A) * N)
    #print(A[0] * N)
    #print(A[1] * N)
    #print(A[2] * N)
    #print(A[3] * N)
    #print(A[4] * N)
    #print(A[5] * N)
    #print(A[6] * N)
    #print(A[7] * N)
    #print(A[8] * N)
    #print(A[9] * N)
    #print(A[10] * N)
    #print(A[11] * N)
    #print(A[12] * N)
    #print(A[13] * N)
    #print(A[14] * N)
    #print(A[15] * N)
    #print(A[16] * N)
    #print(A[17] * N)
    #print(A[18] * N)
    #print(A[19] * N)
    #print(A[20] * N)
    #print(A[21] * N)
    #print(A[22] * N)
    #print(A[23] * N)
    #print(A[24] * N)
    #print(A[25] * N)
    #print(A[0] * N + A[1] * N)
    #print(A[0] * N + A[1] * N + A[2] * N)
    #print(A[0] * N + A[1] * N + A[2] * N + A[3] * N)
    #print(A[0] * N + A[1] * N + A[2] * N + A[3] * N + A[4] * N)
    #print(A[0] * N + A[1] * N + A[2] * N + A[3] * N + A[4] * N + A[5] * N)
    #print(A[0] * N + A[1] * N +

if __name__ == '__main__':
    main()