def main():
    N, M = map(int, input().split())
    k = [0] * M
    a = [[] for _ in range(M)]
    for i in range(M):
        k[i] = int(input())
        a[i] = list(map(int, input().split()))
    #print(k)
    #print(a)
    #print(N, M)
    #print(k)
    #print(a)
    #print(a[0][0])
    #print(a[1][1])
    #print(a[0][0] == a[1][1])
    #print(a[0][0] == a[1][0])
    #print(a[0][1] == a[1][0])
    #print(a[0][1] == a[1][1])
    #print(k)
    #print(a)
    #print(N, M)
    #print(k)
    #print(a)
    #print(a[0][0])
    #print(a[1][1])
    #print(a[0][0] == a[1][1])
    #print(a[0][0] == a[1][0])
    #print(a[0][1] == a[1][0])
    #print(a[0][1] == a[1][1])
    #print(k)
    #print(a)
    #print(N, M)
    #print(k)
    #print(a)
    #print(a[0][0])
    #print(a[1][1])
    #print(a[0][0] == a[1][1])
    #print(a[0][0] == a[1][0])
    #print(a[0][1] == a[1][0])
    #print(a[0][1] == a[1][1])
    #print(k)
    #print(a)
    #print(N, M)
    #print(k)
    #print(a)
    #print(a[0][0])
    #print(a[1][1])
    #print(a[0][0] == a[1][1])
    #print(a[0][0] == a[1][0])
    #print(a[0][1] == a[1][0])
    #print(a[0][1] == a[1][1])
    #print
