def main():
    N, C = map(int, input().split())
    A = [0] * N
    B = [0] * N
    C = [0] * N
    for i in range(N):
        A[i], B[i], C[i] = map(int, input().split())
    #print(A)
    #print(B)
    #print(C)
    #print(N, C)
    #print(A)
    #print(B)
    #print(C)
    #print(A)
    #print(B)
    #print(C)
    #print(N, C)
    #print(A)
    #print(B)
    #print(C)
    #print(A)
    #print(B)
    #print(C)
    #print(N, C)
    #print(A)
    #print(B)
    #print(C)
    #print(A)
    #print(B)
    #print(C)
    #print(N, C)
    #print(A)
    #print(B)
    #print(C)
    #print(A)
    #print(B)
    #print(C)
    #print(N, C)
    #print(A)
    #print(B)
    #print(C)
    #print(A)
    #print(B)
    #print(C)
    #print(N, C)
    #print(A)
    #print(B)
    #print(C)
    #print(A)
    #print(B)
    #print(C)
    #print(N, C)
    #print(A)
    #print(B)
    #print(C)
    #print(A)
    #print(B)
    #print(C)
    #print(N, C)
    #print(A)
    #print(B)
    #print(C)
    #print(A)
    #print(B)
    #print(C)
    #print(N, C)
    #print(A)
    #print(B)
    #print(C)
    #print(A)
    #print(B)
    #print(C)
    #print(N, C)
    #print(A)
    #print(B)
    #print(C)
    #print(A)
    #print(B)
    #print(C)
    #print(N, C)
    #print(A)
    #print(B)
    #print(C)
    #print(A)
    #print(B)
    #print(C)
    #print(N, C)
    #print(A)

if __name__ == '__main__':
    main()