def main():
    N, M, T = map(int, input().split())
    A = list(map(int, input().split()))
    X = [0] * M
    Y = [0] * M
    for i in range(M):
        X[i], Y[i] = map(int, input().split())
    #print(N, M, T)
    #print(A)
    #print(X)
    #print(Y)
    #print("------------")
    #print(A[0])
    #print("------------")
    #print(A[1])
    #print("------------")
    #print(A[2])
    #print("------------")
    #print(A[3])
    #print("------------")
    #print(A[4])
    #print("------------")
    #print(A[5])
    #print("------------")
    #print(A[6])
    #print("------------")
    #print(A[7])
    #print("------------")
    #print(A[8])
    #print("------------")
    #print(A[9])
    #print("------------")
    #print(A[10])
    #print("------------")
    #print(A[11])
    #print("------------")
    #print(A[12])
    #print("------------")
    #print(A[13])
    #print("------------")
    #print(A[14])
    #print("------------")
    #print(A[15])
    #print("------------")
    #print(A[16])
    #print("------------")
    #print(A[17])
    #print("------------")
    #print(A[18])
    #print("------------")
    #print(A[19])
    #print("------------")
    #print(A[20])
    #print("------------")
    #print(A[21])
    #print("------------")
    #print(A[22])
    #print("------------")
    #print(A[23])
    #print("------------")
    #print(A[24])
    #print("------------")
    #print(A[25])
    #print("------------")
    #print(A[26])
    #print("------------")
    #print(A[27])
    #print("------------")
    #print(A[28])
    #print("------------")
    #print(A[29])
    #print("------------")
    #print(A[30])
    #print("------------")

if __name__ == '__main__':
    main()