def solve():
    N, M = map(int, input().split())
    A, B = [], []
    for i in range(M):
        a, b = map(int, input().split())
        A.append(a)
        B.append(b)
    print(A, B)
    # A, B = zip(*sorted(zip(A, B), key=lambda x: x[1]))
    # print(A, B)
    # print(list(zip(A, B)))
    # print(sorted(list(zip(A, B)), key=lambda x: x[1]))
    # print(sorted(list(zip(A, B)), key=lambda x: x[1])[0][0])
    # print(sorted(list(zip(A, B)), key=lambda x: x[1])[0][1])
    # print(sorted(list(zip(A, B)), key=lambda x: x[1])[0][0])
    # print(sorted(list(zip(A, B)), key=lambda x: x[1])[0][1])
    # print(sorted(list(zip(A, B)), key=lambda x: x[1])[0][0])
    # print(sorted(list(zip(A, B)), key=lambda x: x[1])[0][1])
    # print(sorted(list(zip(A, B)), key=lambda x: x[1])[0][0])
    # print(sorted(list(zip(A, B)), key=lambda x: x[1])[0][1])
    # print(sorted(list(zip(A, B)), key=lambda x: x[1])[0][0])
    # print(sorted(list(zip(A, B)), key=lambda x: x[1])[0][1])
    # print(sorted(list(zip(A, B)), key=lambda x: x[1])[0][0])
    # print(sorted(list(zip(A, B)), key=lambda x: x[1])[0][1])
    # print(sorted(list(zip(A, B)), key=lambda x: x[1])[0][0])
    # print(sorted(list(zip(A, B)), key=lambda x: x[1])[0][1])
    # print(sorted(list(zip(A, B)), key=lambda x: x[1])[0][0])
    # print(sorted(list(zip(A, B)), key=lambda x: x[1])[0][1])
    # print(sorted(list(zip(A, B)), key=lambda x: x[1])[0][0])
    # print(sorted(list(zip(A, B)), key=lambda x:
