def main():
    H, W = map(int, input().split())
    #C = [list(map(str, input().split())) for _ in range(H)]
    C = [list(map(str, input())) for _ in range(H)]
    #print(C)
    #print(C[0][0])
    #print(C[0][1])
    #print(C[0][2])
    #print(C[0][3])
    #print(C[0][4])
    #print(C[1][0])
    #print(C[1][1])
    #print(C[1][2])
    #print(C[1][3])
    #print(C[1][4])
    #print(C[2][0])
    #print(C[2][1])
    #print(C[2][2])
    #print(C[2][3])
    #print(C[2][4])
    #print(C[3][0])
    #print(C[3][1])
    #print(C[3][2])
    #print(C[3][3])
    #print(C[3][4])
    #print(C[4][0])
    #print(C[4][1])
    #print(C[4][2])
    #print(C[4][3])
    #print(C[4][4])
    #print(C[0][0] == ".")
    #print(C[0][0] == "#")
    #print(C[1][0] == ".")
    #print(C[1][0] == "#")
    #print(C[2][0] == ".")
    #print(C[2][0] == "#")
    #print(C[3][0] == ".")
    #print(C[3][0] == "#")
    #print(C[4][0] == ".")
    #print(C[4][0] == "#")
    #print(C[0][1] == ".")
    #print(C[0][1] == "#")
    #print(C[1][1] == ".")
    #print(C[1][1] == "#")
    #print(C[2][1] == ".")
    #print(C[2][1] == "#")
    #print(C[3][1] == ".")
    #print(C[3][1] == "#")
    #print(C[

if __name__ == '__main__':
    main()