def main():
    n,q = map(int,input().split())
    ab = [list(map(int,input().split())) for i in range(n-1)]
    px = [list(map(int,input().split())) for i in range(q)]
    #print(n,q,ab,px)
    #print()
    #print(parent)
    #print()
    #print(ans)
    #print()
    #print(visited)
    #print()
    #print(visited2)
    #print(ans)
    #print()
    #print(visited)
    #print()
    #print(visited2)
    #print(ans)
    #print()
    #print(visited)
    #print()
    #print(visited2)
    #print(ans)
    #print()
    #print(visited)
    #print()
    #print(visited2)
    #print(ans)
    #print()
    #print(visited)
    #print()
    #print(visited2)
    #print(ans)
    #print()
    #print(visited)
    #print()
    #print(visited2)
    #print(ans)
    #print()
    #print(visited)
    #print()
    #print(visited2)
    #print()
    #print(ans)
    #print()
    #print(visited)
    #print()
    #print(visited2)
    #print()
    #print(ans)
    #print()
    #print(visited)
    #print()
    #print(visited2)
    #print()
    #print(ans)
    #print()
    #print(visited)
    #print()
    #print(visited2)
    #print()
    #print(ans)
    #print()
    #print(visited)
    #print()
    #print(visited2)
    #print()
    #print(ans)
    #print()
    #print(visited)
    #print()
    #print(visited2)
    #print()
    #print(ans)
    #print()
    #print(visited)
    #print()
    #print(visited2)
    #print()
    #print(ans)
    #print()
    #print(visited)
    #print()
    #print(visited2)
    #print()
    #print()
    ans = [0 for i in range(n)]
    visited = [0 for i in range(n)]
    visited2 = [0 for

if __name__ == '__main__':
    main()