def main():
    N, Q = map(int, input().split())
    S = input()
    #print(N, Q, S)
    #print(type(N), type(Q), type(S))
    #print(S[0:2])
    #print(S[0:2].count('AC'))
    #print(S[1:3].count('AC'))
    #print(S[2:4].count('AC'))
    #print(S[3:5].count('AC'))
    #print(S[4:6].count('AC'))
    #print(S[5:7].count('AC'))
    #print(S[6:8].count('AC'))
    #print(S[7:9].count('AC'))
    #print(S[8:10].count('AC'))
    #print(S[9:11].count('AC'))
    #print(S[10:12].count('AC'))
    #print(S[11:13].count('AC'))
    #print(S[12:14].count('AC'))
    #print(S[13:15].count('AC'))
    #print(S[14:16].count('AC'))
    #print(S[15:17].count('AC'))
    #print(S[16:18].count('AC'))
    #print(S[17:19].count('AC'))
    #print(S[18:20].count('AC'))
    #print(S[19:21].count('AC'))
    #print(S[20:22].count('AC'))
    #print(S[21:23].count('AC'))
    #print(S[22:24].count('AC'))
    #print(S[23:25].count('AC'))
    #print(S[24:26].count('AC'))
    #print(S[25:27].count('AC'))
    #print(S[26:28].count('AC'))
    #print(S[27:29].count('AC'))
    #print(S[28:30].count('AC'))
    #print(S[29:31].count('AC'))
    #print(S[30:32].count('AC'))
    #print(S[31:33].count('AC'))
    #print(S[32:34].count('AC'))
    #print(S[33:35].count('AC'))
    #print(S[34:36].
