def main():
    A, B, C = map(int, input().split())
    #print(A, B, C)
    #print("A+B+C=", A+B+C)
    #print("A/(A+B+C)=", A/(A+B+C))
    #print("B/(A+B+C)=", B/(A+B+C))
    #print("C/(A+B+C)=", C/(A+B+C))
    #print("A/(A+B+C)*A/(A+B+C)=", A/(A+B+C)*A/(A+B+C))
    #print("A/(A+B+C)*B/(A+B+C)=", A/(A+B+C)*B/(A+B+C))
    #print("A/(A+B+C)*C/(A+B+C)=", A/(A+B+C)*C/(A+B+C))
    #print("B/(A+B+C)*A/(A+B+C)=", B/(A+B+C)*A/(A+B+C))
    #print("B/(A+B+C)*B/(A+B+C)=", B/(A+B+C)*B/(A+B+C))
    #print("B/(A+B+C)*C/(A+B+C)=", B/(A+B+C)*C/(A+B+C))
    #print("C/(A+B+C)*A/(A+B+C)=", C/(A+B+C)*A/(A+B+C))
    #print("C/(A+B+C)*B/(A+B+C)=", C/(A+B+C)*B/(A+B+C))
    #print("C/(A+B+C)*C/(A+B+C)=", C/(A+B+C)*C/(A+B+C))
    #print("A/(A+B+C)*A/(A+B+C)*A/(A+B+C)=", A/(A+B+C)*A/(A+B+C)*A/(A+B+C))
    #print("A/(A+B+C)*A/(A+B+C)*B/(A+B+C)=", A/(A+B+C)*A/(A+B+C)*B/(A+B+C))
    #print("A/(A+B+C)*A/(A+B+C)*C/(A+B+C)=", A/(A+B+C)*A/(A+B+C)*C/(A+B+C))
    #print("A/(A+B+C)*B/(A+B+C)*A/(A+B+C)=", A/(A+B+C
