def main():
    N, K = map(int, input().split())
    A = list(map(int, input().split()))
    #print(N, K, A)
    
    #f(X) = (X XOR A_1) + (X XOR A_2) + ... + (X XOR A_N)
    #f(X) = X + (A_1 XOR A_2) + (A_1 XOR A_3) + (A_2 XOR A_3) + ...
    #f(X) = X + (A_1 XOR A_2 XOR A_3) + (A_1 XOR A_2 XOR A_4) + (A_1 XOR A_3 XOR A_4) + ...
    #f(X) = X + (A_1 XOR A_2 XOR A_3 XOR A_4 XOR A_5 XOR A_6 XOR A_7 XOR A_8 XOR ...) + ...
    #f(X) = X + (A_1 XOR A_2 XOR A_3 XOR A_4 XOR A_5 XOR A_6 XOR A_7 XOR A_8 XOR ...) + ...
    #f(X) = X + (A_1 XOR A_2 XOR A_3 XOR A_4 XOR A_5 XOR A_6 XOR A_7 XOR A_8 XOR ...) + ...
    #f(X) = X + (A_1 XOR A_2 XOR A_3 XOR A_4 XOR A_5 XOR A_6 XOR A_7 XOR A_8 XOR ...) + ...
    #f(X) = X + (A_1 XOR A_2 XOR A_3 XOR A_4 XOR A_5 XOR A_6 XOR A_7 XOR A_8 XOR ...) + ...
    #f(X) = X + (A_1 XOR A_2 XOR A_3 XOR A_4 XOR A_5 XOR A_6 XOR A_7 XOR A_8 XOR ...) + ...
    #f(X) = X + (A_1 XOR A_2 XOR A_3 XOR A_4 XOR A_5 XOR A_6 XOR A_7 XOR A_8 XOR ...) + ...
    #f(X) = X + (A_1 XOR A_2 XOR A_3 XOR A_4 XOR A_5 XOR A_6 XOR A_7 XOR
