def main():
    K = int(input())
    #print("K:{}".format(K))
    #print("type K:{}".format(type(K)))
    #print("K-1:{}".format(K-1))
    #print("type K-1:{}".format(type(K-1)))
    #print("K-1:{}".format(K-1))
    #print("type K-1:{}".format(type(K-1)))
    #print("K-1%9:{}".format(K-1%9))
    #print("type K-1%9:{}".format(type(K-1%9)))
    #print("K-1//9:{}".format(K-1//9))
    #print("type K-1//9:{}".format(type(K-1//9)))
    #print("K-1%9+1:{}".format(K-1%9+1))
    #print("type K-1%9+1:{}".format(type(K-1%9+1)))
    #print("K-1//9+1:{}".format(K-1//9+1))
    #print("type K-1//9+1:{}".format(type(K-1//9+1)))
    #print("K-1%9-1:{}".format(K-1%9-1))
    #print("type K-1%9-1:{}".format(type(K-1%9-1)))
    #print("K-1//9:{}".format(K-1//9))
    #print("type K-1//9:{}".format(type(K-1//9)))
    #print("K-1%9:{}".format(K-1%9))
    #print("type K-1%9:{}".format(type(K-1%9)))
    #print("K-1//9-1:{}".format(K-1//9-1))
    #print("type K-1//9-1:{}".format(type(K-1//9-1)))
    #print("K-1%9+1:{}".format(K-1%9+1))
    #print("type K-1%9+1:{}".format(type(K-1%9+1)))
    #print("K-1//9+1:{}".format(K-1//9+1))
    #print("type K
