def main():
    # 读取数据
    line = input()
    N, M = line.split()
    N = int(N)
    M = int(M)
    #print(N, M)
    #print(type(N), type(M))
    #print(type(line))
    #print(line)
    #print(line.split())
    #print(type(line.split()))
    #print(type(line.split()[0]))
    #print(type(line.split()[1]))
    #print(int(line.split()[0]), int(line.split()[1]))
    #print(type(int(line.split()[0])), type(int(line.split()[1])))
    #print(type(line.split()[0]), type(line.split()[1]))
    #创建一个N行M列的数组，初始值为0
    foods = [[0 for i in range(M)] for j in range(N)]
    #print(foods)
    #print(type(foods))
    #print(foods[0])
    #print(type(foods[0]))
    #print(foods[0][0])
    #print(type(foods[0][0]))
    #print(foods[0][1])
    #print(type(foods[0][1]))
    #print(foods[0][2])
    #print(type(foods[0][2]))
    #print(foods[0][3])
    #print(type(foods[0][3]))
    #print(foods[0][4])
    #print(type(foods[0][4]))
    #print(foods[1])
    #print(type(foods[1]))
    #print(foods[1][0])
    #print(type(foods[1][0]))
    #print(foods[1][1])
    #print(type(foods[1][1]))
    #print(foods[1][2])
    #print(type(foods[1][2]))
    #print(foods[1][3])
    #print(type(foods[1][3]))
    #print(foods[1][4])
    #print(type(foods[1][4]))
    #print(foods[2])
    #print(type(foods[2]))
    #print(foods[2][0])
    #print(type(foods[2][0]))
    #print(foods[2][1])
    #print(type(foods[2][1]))
    #print(foods[2][2])

if __name__ == '__main__':
    main()