def main():
    N = int(input())
    A = list(map(int, input().split()))
    B = list(map(int, input().split()))
    #print(N)
    #print(A)
    #print(B)
    #print(A[0])
    #print(B[0])
    #print(A[0] == B[0])
    #print(A[0] == B[1])
    #print(A[1] == B[0])
    #print(A[1] == B[1])
    #print(A[1] == B[2])
    #print(A[2] == B[1])
    #print(A[2] == B[2])
    #print(A[2] == B[3])
    #print(A[3] == B[2])
    #print(A[3] == B[3])
    #print(A[3] == B[4])
    #print(A[4] == B[3])
    #print(A[4] == B[4])
    #print(A[4] == B[5])
    #print(A[5] == B[4])
    #print(A[5] == B[5])
    #print(A[5] == B[6])
    #print(A[6] == B[5])
    #print(A[6] == B[6])
    #print(A[6] == B[7])
    #print(A[7] == B[6])
    #print(A[7] == B[7])
    #print(A[7] == B[8])
    #print(A[8] == B[7])
    #print(A[8] == B[8])
    #print(A[8] == B[9])
    #print(A[9] == B[8])
    #print(A[9] == B[9])
    #print(A[9] == B[10])
    #print(A[10] == B[9])
    #print(A[10] == B[10])
    #print(A[10] == B[11])
    #print(A[11] == B[10])
    #print(A[11] == B[11])
    #print(A[11] == B[12])
    #print(A[12] == B[11])
    #print(A[12] == B

if __name__ == '__main__':
    main()