def main():
    n, k = map(int, input().split())
    p = list(map(int, input().split()))
    # print(n, k)
    # print(p)
    # print(p.index(1))
    # print(p.index(2))
    # print(p.index(3))
    # print(p.index(4))
    # print(p.index(5))
    # print(p.index(6))
    # print(p.index(7))
    # print(p.index(8))
    # print(p.index(9))
    # print(p.index(10))
    # print(p.index(11))
    # print(p.index(12))
    # print(p.index(13))
    # print(p.index(14))
    # print(p.index(15))
    # print(p.index(16))
    # print(p.index(17))
    # print(p.index(18))
    # print(p.index(19))
    # print(p.index(20))
    # print(p.index(21))
    # print(p.index(22))
    # print(p.index(23))
    # print(p.index(24))
    # print(p.index(25))
    # print(p.index(26))
    # print(p.index(27))
    # print(p.index(28))
    # print(p.index(29))
    # print(p.index(30))
    # print(p.index(31))
    # print(p.index(32))
    # print(p.index(33))
    # print(p.index(34))
    # print(p.index(35))
    # print(p.index(36))
    # print(p.index(37))
    # print(p.index(38))
    # print(p.index(39))
    # print(p.index(40))
    # print(p.index(41))
    # print(p.index(42))
    # print(p.index(43))
    # print(p.index(44))
    # print(p.index(45))
    # print(p.index(46))
    # print(p.index(47))
    # print(p.index(48))
    # print(p.index(49))
    # print(p.index(50))
    # print(p.index(51))
    # print(p.index(52))
    # print(p.index(53))
    # print(p.index(54))
    # print(p.index(55))
    # print(p.index(56))
    # print(p.index(57))
    # print(p.index(58

if __name__ == '__main__':
    main()