def main():
    # Q = int(input())
    # q = []
    # for i in range(Q):
    #     q.append(input())
    # print(q)
    # print(q[0])
    # print(q[0].split(' ')[0])
    # print(q[0].split(' ')[1])
    # print(q[0].split(' ')[2])
    # print(q[1])
    # print(q[1].split(' ')[0])
    # print(q[1].split(' ')[1])
    # print(q[1].split(' ')[2])
    # print(q[2])
    # print(q[2].split(' ')[0])
    # print(q[2].split(' ')[1])
    # print(q[2].split(' ')[2])
    # print(q[3])
    # print(q[3].split(' ')[0])
    # print(q[3].split(' ')[1])
    # print(q[3].split(' ')[2])
    # print(q[4])
    # print(q[4].split(' ')[0])
    # print(q[4].split(' ')[1])
    # print(q[4].split(' ')[2])
    # print(q[5])
    # print(q[5].split(' ')[0])
    # print(q[5].split(' ')[1])
    # print(q[5].split(' ')[2])
    # print(q[6])
    # print(q[6].split(' ')[0])
    # print(q[6].split(' ')[1])
    # print(q[6].split(' ')[2])
    # print(q[7])
    # print(q[7].split(' ')[0])
    # print(q[7].split(' ')[1])
    # print(q[7].split(' ')[2])
    # print(q[8])
    # print(q[8].split(' ')[0])
    # print(q[8].split(' ')[1])
    # print(q[8].split(' ')[2])
    q = ['1 3', '1 2', '3', '1 2', '1 7', '3', '2 2 3', '3']
    # q = ['1 10000', '1 1000', '2 100 3', '1 10']
    S = []
    for i in range(len(q)):
