def main():
    n, m, x = map(int, input().split())
    c = []
    a = []
    for i in range(n):
        c.append(list(map(int, input().split())))
    for i in range(n):
        a.append(c[i][1:])
    #print(a)
    #print(c)
    #print(n, m, x)
    #print(a[0][0])
    #print(a[0][1])
    #print(a[1][0])
    #print(a[1][1])
    #print(a[2][0])
    #print(a[2][1])
    #print(c[0][0])
    #print(c[0][1])
    #print(c[1][0])
    #print(c[1][1])
    #print(c[2][0])
    #print(c[2][1])
    #print(a[0][0])
    #print(a[0][1])
    #print(a[0][2])
    #print(a[1][0])
    #print(a[1][1])
    #print(a[1][2])
    #print(a[2][0])
    #print(a[2][1])
    #print(a[2][2])
    #print(a[3][0])
    #print(a[3][1])
    #print(a[3][2])
    #print(a[4][0])
    #print(a[4][1])
    #print(a[4][2])
    #print(a[5][0])
    #print(a[5][1])
    #print(a[5][2])
    #print(a[6][0])
    #print(a[6][1])
    #print(a[6][2])
    #print(a[7][0])
    #print(a[7][1])
    #print(a[7][2])
    #print(a[0][0] + a[1][0] + a[2][0] + a[3][0] + a[4][0] + a[5][0] + a[6][0] + a[7][0])
    #print(a[0][1] + a[1][1] + a[2][1] + a[3][1] + a[4][1] + a[5][
