def main():
    import sys
    input = sys.stdin.readline
    H, W = map(int, input().split())
    Ch, Cw = map(int, input().split())
    Dh, Dw = map(int, input().split())
    S = [list(input().rstrip()) for _ in range(H)]
    #print(H, W, Ch, Cw, Dh, Dw, S)
    #for i in range(H):
    #    print(S[i])
    #print("start")
    #print("H", H)
    #print("W", W)
    #print("Ch", Ch)
    #print("Cw", Cw)
    #print("Dh", Dh)
    #print("Dw", Dw)
    #print("S", S)
    #print("S[0]", S[0])
    #print("S[1]", S[1])
    #print("S[2]", S[2])
    #print("S[3]", S[3])
    #print("start")
    #print("H", H)
    #print("W", W)
    #print("Ch", Ch)
    #print("Cw", Cw)
    #print("Dh", Dh)
    #print("Dw", Dw)
    #print("S", S)
    #print("S[0]", S[0])
    #print("S[1]", S[1])
    #print("S[2]", S[2])
    #print("S[3]", S[3])
    #print("start")
    #print("H", H)
    #print("W", W)
    #print("Ch", Ch)
    #print("Cw", Cw)
    #print("Dh", Dh)
    #print("Dw", Dw)
    #print("S", S)
    #print("S[0]", S[0])
    #print("S[1]", S[1])
    #print("S[2]", S[2])
    #print("S[3]", S[3])
    #print("start")
    #print("H", H)
    #print("W", W)
    #print("Ch", Ch)
    #print("Cw", Cw)
    #print("Dh", Dh)
    #print("Dw", Dw)
    #

if __name__ == '__main__':
    main()