def main():
    input_lines = input()
    input_lines = input_lines.split()
    N = int(input_lines[0])
    T = [0] * N
    X = [0] * N
    A = [0] * N
    for i in range(N):
        input_lines = input()
        input_lines = input_lines.split()
        T[i] = int(input_lines[0])
        X[i] = int(input_lines[1])
        A[i] = int(input_lines[2])
    T.insert(0, 0)
    X.insert(0, 0)
    A.insert(0, 0)
    #print(T)
    #print(X)
    #print(A)
    #print(N)
    #print(T[1])
    #print(X[1])
    #print(A[1])
    #print(T[2])
    #print(X[2])
    #print(A[2])
    #print(T[3])
    #print(X[3])
    #print(A[3])
    #print(T[4])
    #print(X[4])
    #print(A[4])
    #print(T[5])
    #print(X[5])
    #print(A[5])
    #print(T[6])
    #print(X[6])
    #print(A[6])
    #print(T[7])
    #print(X[7])
    #print(A[7])
    #print(T[8])
    #print(X[8])
    #print(A[8])
    #print(T[9])
    #print(X[9])
    #print(A[9])
    #print(T[10])
    #print(X[10])
    #print(A[10])
    #print(T[11])
    #print(X[11])
    #print(A[11])
    #print(T[12])
    #print(X[12])
    #print(A[12])
    #print(T[13])
    #print(X[13])
    #print(A[13])
    #print(T[14])
    #print(X[14])
    #print(A[14])
    #print(T[15])
    #print(X[15])
    #print(A[15])
    #print(T[16])
    #print(X[16])
    #print(A[16])
    #print(T[17])
    #print(X

if __name__ == '__main__':
    main()