def main():
    n,m,q = map(int,input().split())
    abcd = []
    for i in range(q):
        abcd.append(list(map(int,input().split())))
    # print(abcd)
    # print(n,m,q)
    # print(abcd)
    # print(abcd[0][0])
    # print(abcd[0][1])
    # print(abcd[0][2])
    # print(abcd[0][3])
    # print(abcd[1][0])
    # print(abcd[1][1])
    # print(abcd[1][2])
    # print(abcd[1][3])
    # print(abcd[2][0])
    # print(abcd[2][1])
    # print(abcd[2][2])
    # print(abcd[2][3])
    # print(abcd[3][0])
    # print(abcd[3][1])
    # print(abcd[3][2])
    # print(abcd[3][3])
    # print(abcd[4][0])
    # print(abcd[4][1])
    # print(abcd[4][2])
    # print(abcd[4][3])
    # print(abcd[5][0])
    # print(abcd[5][1])
    # print(abcd[5][2])
    # print(abcd[5][3])
    # print(abcd[6][0])
    # print(abcd[6][1])
    # print(abcd[6][2])
    # print(abcd[6][3])
    # print(abcd[7][0])
    # print(abcd[7][1])
    # print(abcd[7][2])
    # print(abcd[7][3])
    # print(abcd[8][0])
    # print(abcd[8][1])
    # print(abcd[8][2])
    # print(abcd[8][3])
    # print(abcd[9][0])
    # print(abcd[9][1])
    # print(abcd[9][2])
    # print(abcd[9][3])
    # print(abcd[10][0])
    # print(abcd[10][1])
    # print(abcd[10][2])
    # print(abcd[10][3])
    # print(abcd

if __name__ == '__main__':
    main()