def main():
    N = int(input())
    A = list(map(int,input().split()))
    B = list(map(int,input().split()))
    C = list(map(int,input().split()))
    #print(N,A,B,C)
    #print(A[0])
    #print(B[C[0]-1])
    #print(B[0])
    #print(C[0])
    #print(A[0]==B[C[0]-1])
    #print(A[0]==B[0])
    #print(A[0]==B[C[0]-1])
    #print(A[0]==B[0])
    #print(A[1]==B[C[1]-1])
    #print(A[1]==B[1])
    #print(A[1]==B[C[1]-1])
    #print(A[1]==B[1])
    #print(A[2]==B[C[2]-1])
    #print(A[2]==B[2])
    #print(A[2]==B[C[2]-1])
    #print(A[2]==B[2])
    #print(A[0]==B[C[0]-1])
    #print(A[0]==B[0])
    #print(A[0]==B[C[0]-1])
    #print(A[0]==B[0])
    #print(A[1]==B[C[1]-1])
    #print(A[1]==B[1])
    #print(A[1]==B[C[1]-1])
    #print(A[1]==B[1])
    #print(A[2]==B[C[2]-1])
    #print(A[2]==B[2])
    #print(A[2]==B[C[2]-1])
    #print(A[2]==B[2])
    #print(A[0]==B[C[0]-1])
    #print(A[0]==B[0])
    #print(A[0]==B[C[0]-1])
    #print(A[0]==B[0])
    #print(A[1]==B[C[1]-1])
    #print(A[1]==B[1])
    #print(A[1]==B[C[1]-1])
    #print(A[1]==B[1])
    #print(A[2]==B[C[2]-1])
    #print(A[2]==B[

if __name__ == '__main__':
    main()