def main():
    print("问题陈述")
    print("给你一个整数N，求满足以下条件的长度为N的字符串的数量，模数为10^9+7：")
    print("该字符串不包含除A、C、G和T以外的其他字符。")
    print("字符串中不包含AGC这个子串。")
    print("上述条件不能通过交换一次相邻的两个字符被违反。")
    print("注释")
    print("字符串T的子串是指从T的开头和结尾去除零个或多个字符后得到的字符串。")
    print("例如，ATCODER的子串包括TCO、AT、CODER、ATCODER和（空字符串），但不包括AC。")
    print("限制条件")
    print("3 ≦ N ≦ 100")
    print("输入")
    print("输入是由标准输入法提供的，格式如下：")
    print("N")
    print("输出")
    print("打印满足以下条件的长度为N的字符串的数量，模数为10^9+7。")
    print("输入样本 1")
    print("3")
    print("样本输出 1")
    print("61")
    print("有4^3=64个长度为3的字符串不包含A、C、G和T以外的字符，其中只有AGC、ACG和GAC违反条件，所以答案是64-3=61。")
    print("输入样本2")
    print("4")
    print("样本输出2")
    print("230")
    print("采样输入3")
    print("100")
    print("样品输出3")
    print("388130742")
    print("一定要打印出10^9+7的模数的字符串数量。")
    print("#############################################################")
    print("请输入N的值:")
    N = int(input())
    print("请输入N个字符:")
    S = input()
    print("请输入要排除的字符串:")
    NG = input()
    print("请输入要排除的字符串:")
    NG

if __name__ == '__main__':
    main()