def solve():
    N = int(input())
    A = list(map(int, input().split()))
    #print(N)
    #print(A)
    #print(len(A))
    #print(A[2])
    #print(A[1])
    #print(A[0])
    #print(A[2] >= A[1])
    #print(A[1] >= A[0])
    #print(A[2] >= A[0])
    #print(A[3] >= A[2])
    #print(A[4] >= A[3])
    #print(A[4] >= A[2])
    #print(A[3] >= A[1])
    #print(A[2] >= A[0])
    #print(A[1] >= A[0])
    #print(A[4] >= A[3])
    #print(A[3] >= A[2])
    #print(A[2] >= A[1])
    #print(A[1] >= A[0])
    #print(A[4] >= A[2])
    #print(A[3] >= A[1])
    #print(A[2] >= A[0])
    #print(A[4] >= A[1])
    #print(A[3] >= A[0])
    #print(A[4] >= A[0])
    #print(A[0] >= A[0])
    #print(A[1] >= A[1])
    #print(A[2] >= A[2])
    #print(A[3] >= A[3])
    #print(A[4] >= A[4])
    #print(A[0] >= A[1])
    #print(A[0] >= A[2])
    #print(A[0] >= A[3])
    #print(A[0] >= A[4])
    #print(A[1] >= A[2])
    #print(A[1] >= A[3])
    #print(A[1] >= A[4])
    #print(A[2] >= A[3])
    #print(A[2] >= A[4])
    #print(A[3] >= A[4])
    #print(A[0] >= A[0])
    #print(A[1] >= A[1])
    #print(A[2] >= A[2])
