def solution():
    H, W = map(int, input().split())
    S = [input() for i in range(H)]
    #print(S)
    #print(len(S[0]))
    #print(S[0][0])
    #print(S[0][1])
    #print(S[0][2])
    #print(S[0][3])
    #for i in range(H):
    #    for j in range(W):
    #        print(S[i][j], end='')
    #    print()
    #print(S[1][1])
    #print(S[1][2])
    #print(S[1][3])
    #print(S[1][4])
    #print(S[2][1])
    #print(S[2][2])
    #print(S[2][3])
    #print(S[2][4])
    #print(S[3][1])
    #print(S[3][2])
    #print(S[3][3])
    #print(S[3][4])
    #print(S[4][1])
    #print(S[4][2])
    #print(S[4][3])
    #print(S[4][4])
    #print(S[5][1])
    #print(S[5][2])
    #print(S[5][3])
    #print(S[5][4])
    #print(S[6][1])
    #print(S[6][2])
    #print(S[6][3])
    #print(S[6][4])
    #print(S[7][1])
    #print(S[7][2])
    #print(S[7][3])
    #print(S[7][4])
    #print(S[8][1])
    #print(S[8][2])
    #print(S[8][3])
    #print(S[8][4])
    #print(S[9][1])
    #print(S[9][2])
    #print(S[9][3])
    #print(S[9][4])
    #print(S[10][1])
    #print(S[10][2])
    #print(S[10][3])
    #print(S[10][4])
    #print(S[11][1])
    #print(S[11][2])
    #print(S[11][3])
    #print(S[
