def main():
    k = int(input())
    s = input()
    t = input()
    s1 = s[:4]
    s2 = s[4]
    t1 = t[:4]
    t2 = t[4]
    s1 = list(s1)
    t1 = list(t1)
    s1.sort()
    t1.sort()
    s1 = ''.join(s1)
    t1 = ''.join(t1)
    s1 = int(s1)
    t1 = int(t1)
    s1 = s1 * 10 + int(s2)
    t1 = t1 * 10 + int(t2)
    #print(s1)
    #print(t1)
    #print(s1 > t1)
    #print(s1 < t1)
    #print(s1 == t1)
    #print(s1 != t1)
    #print(s1 >= t1)
    #print(s1 <= t1)
    #print(s1 > t1)
    #print(s1 < t1)
    #print(s1 == t1)
    #print(s1 != t1)
    #print(s1 >= t1)
    #print(s1 <= t1)
    #print(s1 > t1)
    #print(s1 < t1)
    #print(s1 == t1)
    #print(s1 != t1)
    #print(s1 >= t1)
    #print(s1 <= t1)
    #print(s1 > t1)
    #print(s1 < t1)
    #print(s1 == t1)
    #print(s1 != t1)
    #print(s1 >= t1)
    #print(s1 <= t1)
    #print(s1 > t1)
    #print(s1 < t1)
    #print(s1 == t1)
    #print(s1 != t1)
    #print(s1 >= t1)
    #print(s1 <= t1)
    #print(s1 > t1)
    #print(s1 < t1)
    #print(s1 == t1)
    #print(s1 != t1)
    #print(s1 >= t1)
    #print(s1 <= t1)
    #print(s1 > t1)
    #print(s1 < t1)
    #print(s1 == t1

if __name__ == '__main__':
    main()