def main():
    N, L, R = map(int, input().split())
    A = list(map(int, input().split()))
    #print(N, L, R)
    #print(A)
    #print(A[0])
    #print(A[1])
    #print(A[2])
    #print(A[3])
    #print(A[4])
    #print(A[5])
    #print(A[6])
    #print(A[7])
    #print(A[8])
    #print(A[9])
    #print(A[10])
    #print(A[0] + A[1] + A[2] + A[3] + A[4] + A[5] + A[6] + A[7] + A[8] + A[9] + A[10])
    #print(sum(A))
    #print(A[0:1])
    #print(A[0:2])
    #print(A[0:3])
    #print(A[0:4])
    #print(A[0:5])
    #print(A[0:6])
    #print(A[0:7])
    #print(A[0:8])
    #print(A[0:9])
    #print(A[0:10])
    #print(A[0:11])
    #print(A[1:2])
    #print(A[1:3])
    #print(A[1:4])
    #print(A[1:5])
    #print(A[1:6])
    #print(A[1:7])
    #print(A[1:8])
    #print(A[1:9])
    #print(A[1:10])
    #print(A[1:11])
    #print(A[2:3])
    #print(A[2:4])
    #print(A[2:5])
    #print(A[2:6])
    #print(A[2:7])
    #print(A[2:8])
    #print(A[2:9])
    #print(A[2:10])
    #print(A[2:11])
    #print(A[3:4])
    #print(A[3:5])
    #print(A[3:6])
    #print(A[3:7])
    #print(A[3:8])
    #print(A
