def main():
    n = int(input())
    x = []
    y = []
    for i in range(n):
        x1, y1 = map(int, input().split())
        x.append(x1)
        y.append(y1)
    #print(x)
    #print(y)
    #print("----------")
    #print(x[0])
    #print(y[0])
    #print("----------")
    #print(x[1])
    #print(y[1])
    #print("----------")
    #print(x[2])
    #print(y[2])
    #print("----------")
    #print(x[0], y[0])
    #print(x[1], y[1])
    #print(x[2], y[2])
    #print("----------")
    #print(x[0], y[0])
    #print(x[1], y[1])
    #print(x[2], y[2])
    #print("----------")
    #print(x[0], y[0])
    #print(x[1], y[1])
    #print(x[2], y[2])
    #print("----------")
    #print(x[0], y[0])
    #print(x[1], y[1])
    #print(x[2], y[2])
    #print("----------")
    #print(x[0], y[0])
    #print(x[1], y[1])
    #print(x[2], y[2])
    #print("----------")
    #print(x[0], y[0])
    #print(x[1], y[1])
    #print(x[2], y[2])
    #print("----------")
    #print(x[0], y[0])
    #print(x[1], y[1])
    #print(x[2], y[2])
    #print("----------")
    #print(x[0], y[0])
    #print(x[1], y[1])
    #print(x[2], y[2])
    #print("----------")
    m = 0
    d = []
    w = []
    for i in range(n):
        d.append(0)
        w.append("")
    #print(d)
    #print(w)
    #print("----------")
    #print(d[0])
    #print(w[0])
    #
