def main():
    N, M = map(int, input().split())
    #print(N, M)
    #print(type(N), type(M))
    s = []
    c = []
    for i in range(M):
        s_i, c_i = map(int, input().split())
        s.append(s_i)
        c.append(c_i)
    #print(s, c)
    #print(type(s), type(c))
    #print(len(s), len(c))
    #print(type(s[0]), type(c[0]))
    #print(type(s[1]), type(c[1]))
    #print(type(s[2]), type(c[2]))
    #print(type(s[3]), type(c[3]))
    #print(type(s[4]), type(c[4]))
    #print(type(s[5]), type(c[5]))
    #print(type(s[6]), type(c[6]))
    #print(type(s[7]), type(c[7]))
    #print(type(s[8]), type(c[8]))
    #print(type(s[9]), type(c[9]))
    #print(type(s[10]), type(c[10]))
    #print(type(s[11]), type(c[11]))
    #print(type(s[12]), type(c[12]))
    #print(type(s[13]), type(c[13]))
    #print(type(s[14]), type(c[14]))
    #print(type(s[15]), type(c[15]))
    #print(type(s[16]), type(c[16]))
    #print(type(s[17]), type(c[17]))
    #print(type(s[18]), type(c[18]))
    #print(type(s[19]), type(c[19]))
    #print(type(s[20]), type(c[20]))
    #print(type(s[21]), type(c[21]))
    #print(type(s[22]), type(c[22]))
    #print(type(s[23]), type(c[23]))
    #print(type(s[24]), type(c[24]))
    #print(type(s[25]), type(c[25]))
    #print(type(s[26]), type(c[26]))
    #print(type(s[27]), type(c[27]))
    #print(type(s[28]), type(c[28]))
    #print(type(s[29]), type(c[29]))
    #print(type(s[30]), type(c[30]))
