def main():
    N = int(input())
    A = list(map(int,input().split()))
    A.sort()
    #print(A)
    #print(A[0])
    #print(A[1])
    #print(A[2])
    #print(A[3])
    #print(A[4])
    #print(A[5])
    #print(A[6])
    #print(A[7])
    #print(A[8])
    #print(A[9])
    for K in range(N):
        #print(K)
        #print(A[K])
        #print(A[K+1])
        #print(A[K+2])
        #print(A[K+3])
        #print(A[K+4])
        #print(A[K+5])
        #print(A[K+6])
        #print(A[K+7])
        #print(A[K+8])
        #print(A[K+9])
        #print(A[K+10])
        print(len(set(A[K:])))

if __name__ == '__main__':
    main()