def main():
    N,X,Y = map(int,input().split())
    edge = [[] for i in range(N+1)]
    for i in range(N-1):
        u,v = map(int,input().split())
        edge[u].append(v)
        edge[v].append(u)
    #print(edge)
    #print("X=",X,"Y=",Y)
    #print("N=",N)
    #print("N-1=",N-1)
    #print("edge=",edge)
    #print(len(edge))
    #print(len(edge[1]))
    #print(len(edge[2]))
    #print(len(edge[3]))
    #print(len(edge[4]))
    #print(len(edge[5]))
    #print(len(edge[6]))
    #print("edge[1]=",edge[1])
    #print("edge[2]=",edge[2])
    #print("edge[3]=",edge[3])
    #print("edge[4]=",edge[4])
    #print("edge[5]=",edge[5])
    #print("edge[6]=",edge[6])
    #print("edge[1][0]=",edge[1][0])
    #print("edge[1][1]=",edge[1][1])
    #print("edge[1][2]=",edge[1][2])
    #print("edge[2][0]=",edge[2][0])
    #print("edge[2][1]=",edge[2][1])
    #print("edge[3][0]=",edge[3][0])
    #print("edge[3][1]=",edge[3][1])
    #print("edge[4][0]=",edge[4][0])
    #print("edge[5][0]=",edge[5][0])
    #print("edge[6][0]=",edge[6][0])
    #print("edge[1][0]=",edge[1][0])
    #print("edge[1][1]=",edge[1][1])
    #print("edge[1][2]=",edge[1][2])
    #print("edge[2][0]=",edge[2][0])
    #print("edge[2][1]=",edge[2][1])
    #print("edge[3][0]
