def main():
    print('输入样本1')
    print('5')
    print('1 2')
    print('1 3')
    print('1 9')
    print('2 9')
    print('3 9')
    print('3 9 2 4 5 6 7 8')
    print('样本输出1')
    print('5')
    print('下面的程序通过五次操作完成了这个谜题。')
    print('将棋子2从顶点9移到顶点1。')
    print('将棋子3从顶点2移到顶点9。')
    print('将棋子2从顶点1移到顶点2。')
    print('将棋子1从顶点3移到顶点1。')
    print('将棋子3从顶点9移到顶点3。')
    print('另一方面，我们不可能在少于五次的操作中完成这个拼图。因此，我们应该打印5。')
    print('请注意，给定的图形可能是不相连的。')
    print('输入样本 2')
    print('5')
    print('1 2')
    print('1 3')
    print('1 9')
    print('2 9')
    print('3 9')
    print('1 2 3 4 5 6 7 8')
    print('样本输出2')
    print('0')
    print('这个拼图从一开始就已经完成了。')
    print('因此，完成该拼图所需的最少操作数为0。')
    print('输入样本3')
    print('12')
    print('8 5')
    print('9 6')
    print('4 5')
    print('4 1')
    print('2 5')
    print('8 9')
    print('2 1')
    print('3 6')
    print('8 7')
    print('6 5')
    print('7 4')
    print('2 3')
    print('1 2 3 4 5 6 8 7')
    print('

if __name__ == '__main__':
    main()