def main():
    n = int(input())
    t = []
    a = []
    for i in range(n):
        t_i, k_i, *a_i = map(int, input().split())
        t.append(t_i)
        a.append(a_i)
    #print(t)
    #print(a)
    #print(t[0])
    #print(a[0])
    #print(a[0][0])
    #print(a[0][1])
    #print(a[0][2])
    #print(a[0][3])
    #print(a[0][4])
    #print(a[0][5])
    #print(t[1])
    #print(a[1])
    #print(a[1][0])
    #print(a[1][1])
    #print(a[1][2])
    #print(a[1][3])
    #print(a[1][4])
    #print(a[1][5])
    #print(t[2])
    #print(a[2])
    #print(a[2][0])
    #print(a[2][1])
    #print(a[2][2])
    #print(a[2][3])
    #print(a[2][4])
    #print(a[2][5])
    #print(t[3])
    #print(a[3])
    #print(a[3][0])
    #print(a[3][1])
    #print(a[3][2])
    #print(a[3][3])
    #print(a[3][4])
    #print(a[3][5])
    #print(t[4])
    #print(a[4])
    #print(a[4][0])
    #print(a[4][1])
    #print(a[4][2])
    #print(a[4][3])
    #print(a[4][4])
    #print(a[4][5])
    #print(t[5])
    #print(a[5])
    #print(a[5][0])
    #print(a[5][1])
    #print(a[5][2])
    #print(a[5][3])
    #print(a[5][4])
    #print(a[5][5])
    #print(t[6])
    #print(a[6])
    #print(a[6][0])
    #print(a[6
