def main():
    N, M = map(int, input().split())
    bridge = [list(map(int, input().split())) for _ in range(M)]
    bridge = bridge[::-1]
    #print(bridge)
    #print(N, M)
    #print(bridge)
    #print(bridge[0][0])
    #print(bridge[0][1])
    #print(bridge[1][0])
    #print(bridge[1][1])
    #print(bridge[2][0])
    #print(bridge[2][1])
    #print(bridge[3][0])
    #print(bridge[3][1])
    #print(bridge[4][0])
    #print(bridge[4][1])
    #print(bridge[5][0])
    #print(bridge[5][1])
    #print(bridge[6][0])
    #print(bridge[6][1])
    #print(bridge[7][0])
    #print(bridge[7][1])
    #print(bridge[8][0])
    #print(bridge[8][1])
    #print(bridge[9][0])
    #print(bridge[9][1])
    
    #print(bridge[0][0])
    #print(bridge[0][1])
    #print(bridge[1][0])
    #print(bridge[1][1])
    #print(bridge[2][0])
    #print(bridge[2][1])
    #print(bridge[3][0])
    #print(bridge[3][1])
    #print(bridge[4][0])
    #print(bridge[4][1])
    #print(bridge[5][0])
    #print(bridge[5][1])
    #print(bridge[6][0])
    #print(bridge[6][1])
    #print(bridge[7][0])
    #print(bridge[7][1])
    #print(bridge[8][0])
    #print(bridge[8][1])
    #print(bridge[9][0])
    #print(bridge[9][1])
    
    #print(bridge[0][0])
    #print(bridge[0][1])
    #print(bridge[1][0])
    #print(bridge[1][1])
