def main():
    H, W = map(int, input().split())
    A = [list(input()) for _ in range(H)]
    #print(A)
    #print(H, W)
    #print(A)
    #print(A[0])
    #print(A[1])
    #print(A[2])
    #print(A[3])
    
    #print(A[0][0])
    #print(A[0][1])
    #print(A[0][2])
    #print(A[0][3])
    #print(A[0][4])
    #print(A[0][5])
    
    #print(A[1][0])
    #print(A[1][1])
    #print(A[1][2])
    #print(A[1][3])
    #print(A[1][4])
    #print(A[1][5])
    
    #print(A[2][0])
    #print(A[2][1])
    #print(A[2][2])
    #print(A[2][3])
    #print(A[2][4])
    #print(A[2][5])
    
    #print(A[3][0])
    #print(A[3][1])
    #print(A[3][2])
    #print(A[3][3])
    #print(A[3][4])
    #print(A[3][5])
    
    #print(A[4][0])
    #print(A[4][1])
    #print(A[4][2])
    #print(A[4][3])
    #print(A[4][4])
    #print(A[4][5])
    
    #print(A[5][0])
    #print(A[5][1])
    #print(A[5][2])
    #print(A[5][3])
    #print(A[5][4])
    #print(A[5][5])
    
    #print(A[6][0])
    #print(A[6][1])
    #print(A[6][2])
    #print(A[6][3])
    #print(A[6][4])
    #print(A[6][5])
    
    #print(A[7][0])
    #print(A[7][1])
    #print(A[7][2])
    #print(A[7][3])
    #print(A[7
