def main():
    N, K = map(int, input().split())
    Sushi = []
    for _ in range(N):
        t, d = map(int, input().split())
        Sushi.append((d, t))
    Sushi.sort(reverse=True)
    #print(Sushi)
    #print(K)
    #print(N)
    #print(Sushi[0][0])
    #print(Sushi[0][1])
    #print(Sushi[1][0])
    #print(Sushi[1][1])
    #print(Sushi[2][0])
    #print(Sushi[2][1])
    #print(Sushi[3][0])
    #print(Sushi[3][1])
    #print(Sushi[4][0])
    #print(Sushi[4][1])
    #print(Sushi[5][0])
    #print(Sushi[5][1])
    #print(Sushi[6][0])
    #print(Sushi[6][1])
    #print(Sushi[7][0])
    #print(Sushi[7][1])
    #print(Sushi[8][0])
    #print(Sushi[8][1])
    #print(Sushi[9][0])
    #print(Sushi[9][1])
    #print(Sushi[10][0])
    #print(Sushi[10][1])
    #print(Sushi[11][0])
    #print(Sushi[11][1])
    #print(Sushi[12][0])
    #print(Sushi[12][1])
    #print(Sushi[13][0])
    #print(Sushi[13][1])
    #print(Sushi[14][0])
    #print(Sushi[14][1])
    #print(Sushi[15][0])
    #print(Sushi[15][1])
    #print(Sushi[16][0])
    #print(Sushi[16][1])
    #print(Sushi[17][0])
    #print(Sushi[17][1])
    #print(Sushi[18][0])
    #print(Sushi[18][1])
    #print(Sushi[19][0])
    #print(Sushi[19][1])
    #print(Sushi[20][0])
    #print(Sushi[20][1])
    #print(Sushi[21][0])
