def main():
    N, M = map(int, input().split())
    #print(N, M)
    #print(type(N), type(M))
    road = []
    for i in range(M):
        road.append(list(map(int, input().split())))
    #print(road)
    #print(type(road))
    #print(road[0][0])
    #print(road[0][1])
    #print(road[1][0])
    #print(road[1][1])
    #print(road[2][0])
    #print(road[2][1])
    #print(road[3][0])
    #print(road[3][1])
    #print(road[4][0])
    #print(road[4][1])
    #print(road[5][0])
    #print(road[5][1])
    #print(road[6][0])
    #print(road[6][1])
    #print(road[7][0])
    #print(road[7][1])
    #print(road[8][0])
    #print(road[8][1])
    #print(road[9][0])
    #print(road[9][1])
    #print(road[10][0])
    #print(road[10][1])
    #print(road[11][0])
    #print(road[11][1])
    #print(road[12][0])
    #print(road[12][1])
    #print(road[13][0])
    #print(road[13][1])
    #print(road[14][0])
    #print(road[14][1])
    #print(road[15][0])
    #print(road[15][1])
    #print(road[16][0])
    #print(road[16][1])
    #print(road[17][0])
    #print(road[17][1])
    #print(road[18][0])
    #print(road[18][1])
    #print(road[19][0])
    #print(road[19][1])
    #print(road[20][0])
    #print(road[20][1])
    #print(road[21][0])
    #print(road

if __name__ == '__main__':
    main()