def main():
    N, K = map(int, input().split())
    c = list(map(int, input().split()))
    #print(N, K)
    #print(c)
    #print(len(c))
    #print(c[0:3])
    #print(c[1:4])
    #print(c[2:5])
    #print(c[3:6])
    #print(c[4:7])
    #print(c[5:8])
    #print(c[6:9])
    #print(c[0:6])
    #print(c[1:7])
    #print(c[2:8])
    #print(c[3:9])
    #print(c[4:10])
    #print(c[0:7])
    #print(c[1:8])
    #print(c[2:9])
    #print(c[3:10])
    #print(c[0:8])
    #print(c[1:9])
    #print(c[2:10])
    #print(c[0:9])
    #print(c[1:10])
    #print(c[0:10])
    #print(c[0:N-K+1])
    #print(c[1:N-K+2])
    #print(c[2:N-K+3])
    #print(c[3:N-K+4])
    #print(c[4:N-K+5])
    #print(c[5:N-K+6])
    #print(c[6:N-K+7])
    #print(c[7:N-K+8])
    #print(c[8:N-K+9])
    #print(c[9:N-K+10])
    #print(c[0:N-K+1])
    #print(c[1:N-K+2])
    #print(c[2:N-K+3])
    #print(c[3:N-K+4])
    #print(c[4:N-K+5])
    #print(c[5:N-K+6])
    #print(c[6:N-K+7])
    #print(c[7:N-K+8])
    #print(c[8:N-K+9])
    #print(c[9:N-K+10])
    #print(c[0:N-K+1])
    #print(c[1:N-K+2])
    #print(c[2:N-K+3])
    #print(c[3

if __name__ == '__main__':
    main()