def main():
    N, A, B = map(int, input().split())
    S = input()
    S = list(S)
    S.reverse()
    S = ''.join(S)
    #print(N, A, B, S)
    #print(S[0])
    #print(S[1])
    #print(S[-1])
    #print(S[-2])
    #print(S)
    #print(S[0])
    #print(S[1])
    #print(S[-1])
    #print(S[-2])
    #print(S[0])
    #print(S[-1])
    #print(S[0] == S[-1])
    #print(S[1])
    #print(S[-2])
    #print(S[1] == S[-2])
    #print(S[0])
    #print(S[-1])
    #print(S[0] == S[-1])
    #print(S[1])
    #print(S[-2])
    #print(S[1] == S[-2])
    #print(S[0])
    #print(S[-1])
    #print(S[0] == S[-1])
    #print(S[1])
    #print(S[-2])
    #print(S[1] == S[-2])
    #print(S[0])
    #print(S[-1])
    #print(S[0] == S[-1])
    #print(S[1])
    #print(S[-2])
    #print(S[1] == S[-2])
    #print(S[0])
    #print(S[-1])
    #print(S[0] == S[-1])
    #print(S[1])
    #print(S[-2])
    #print(S[1] == S[-2])
    #print(S[0])
    #print(S[-1])
    #print(S[0] == S[-1])
    #print(S[1])
    #print(S[-2])
    #print(S[1] == S[-2])
    #print(S[0])
    #print(S[-1])
    #print(S[0] == S[-1])
    #print(S[1])
    #print(S[-2])
    #print(S[1] == S[-2])
    #print(S[0])
    #print(S[-1])
    #print(S[0] == S[-1])
