def main():
    N, M = map(int, input().split())
    A = []
    B = []
    for i in range(M):
        a,b = map(int, input().split())
        A.append(a)
        B.append(b)
    #print(A)
    #print(B)
    #print("A[0] = " + str(A[0]))
    #print("B[0] = " + str(B[0]))
    #print("A[1] = " + str(A[1]))
    #print("B[1] = " + str(B[1]))
    #print("A[2] = " + str(A[2]))
    #print("B[2] = " + str(B[2]))
    #print("A[3] = " + str(A[3]))
    #print("B[3] = " + str(B[3]))
    #print("A[4] = " + str(A[4]))
    #print("B[4] = " + str(B[4]))
    #print("A[5] = " + str(A[5]))
    #print("B[5] = " + str(B[5]))
    #print("A[6] = " + str(A[6]))
    #print("B[6] = " + str(B[6]))
    #print("A[7] = " + str(A[7]))
    #print("B[7] = " + str(B[7]))
    #print("A[8] = " + str(A[8]))
    #print("B[8] = " + str(B[8]))
    #print("A[9] = " + str(A[9]))
    #print("B[9] = " + str(B[9]))
    #print("A[10] = " + str(A[10]))
    #print("B[10] = " + str(B[10]))
    #print("A[11] = " + str(A[11]))
    #print("B[11] = " + str(B[11]))
    #print("A[12] = " + str(A[12]))
    #print("B[12] = " + str(B[12]))
    #print("A[13] = " + str(A[13]))
    #print("B[13]

if __name__ == '__main__':
    main()