def main():
    h, w = map(int, input().split())
    a = [list(input()) for _ in range(h)] # 2次元配列の入力の受け取り
    #print(a)
    #print(a[0][0])
    #print(a[0][0])
    #print(a[0][1])
    #print(a[0][2])
    #print(a[0][3])
    #print(a[0][4])
    #print(a[1][0])
    #print(a[1][1])
    #print(a[1][2])
    #print(a[1][3])
    #print(a[1][4])
    #print(a[2][0])
    #print(a[2][1])
    #print(a[2][2])
    #print(a[2][3])
    #print(a[2][4])
    #print(a[3][0])
    #print(a[3][1])
    #print(a[3][2])
    #print(a[3][3])
    #print(a[3][4])
    #print(a[4][0])
    #print(a[4][1])
    #print(a[4][2])
    #print(a[4][3])
    #print(a[4][4])
    #print("a[0][0] = " + a[0][0])
    #print("a[0][1] = " + a[0][1])
    #print("a[0][2] = " + a[0][2])
    #print("a[0][3] = " + a[0][3])
    #print("a[0][4] = " + a[0][4])
    #print("a[1][0] = " + a[1][0])
    #print("a[1][1] = " + a[1][1])
    #print("a[1][2] = " + a[1][2])
    #print("a[1][3] = " + a[1][3])
    #print("a[1][4] = " + a[1][4])
    #print("a[2][0] = " + a[2][0])
    #print("a[2][

if __name__ == '__main__':
    main()