def main():
    H, W = map(int, input().split())
    S = [input() for _ in range(H)]
    #print(H, W)
    #print(S)
    #print(S[0][0])
    #print(S[0][1])
    #print(S[1][0])
    #print(S[1][1])
    #print(S[1][2])
    #print(S[2][1])
    #print(S[2][2])
    #print(S[0][0] == '.')
    #print(S[0][1] == '.')
    #print(S[1][0] == '.')
    #print(S[1][1] == '.')
    #print(S[1][2] == '.')
    #print(S[2][1] == '.')
    #print(S[2][2] == '.')
    #print(S[0][0] == '.' and S[0][1] == '.' and S[1][0] == '.' and S[1][1] == '.' and S[1][2] == '.' and S[2][1] == '.' and S[2][2] == '.')
    #print(S[0][0] == '.' and S[0][1] == '.' and S[1][0] == '.' and S[1][1] == '.' and S[1][2] == '.' and S[2][1] == '.' and S[2][2] == '.')
    #print(S[1][1] == '.' and S[1][2] == '.' and S[2][1] == '.' and S[2][2] == '.')
    #print(S[0][0] == '.' and S[0][1] == '.' and S[1][0] == '.' and S[1][1] == '.' and S[1][2] == '.' and S[2][1] == '.' and S[2][2] == '.' and S[2][3] == '.')
    #print(S[0][0] == '.' and S[0][1] == '.' and S[1][0] == '.' and S[1][1] == '.' and S[1][2] == '.' and S[2][1] == '.' and S[2][2] == '.' and S[2
