def main():
    N, M = map(int, input().split())
    k = []
    a = []
    for i in range(M):
        k.append(int(input()))
        a.append(list(map(int, input().split())))
    #print(N, M, k, a)
    #print(len(a))
    #print(len(a[0]))
    #print(a[0][0])
    #print(a[0][1])
    #print(a[1][0])
    #print(a[1][1])
    #print(len(a[0]))
    #print(len(a[1]))
    #print(len(a[2]))
    #print(len(a[3]))
    #print(len(a[4]))
    #print(len(a[5]))
    #print(len(a[6]))
    #print(len(a[7]))
    #print(len(a[8]))
    #print(len(a[9]))
    #print(len(a[10]))
    #print(len(a[11]))
    #print(len(a[12]))
    #print(len(a[13]))
    #print(len(a[14]))
    #print(len(a[15]))
    #print(len(a[16]))
    #print(len(a[17]))
    #print(len(a[18]))
    #print(len(a[19]))
    #print(len(a[20]))
    #print(len(a[21]))
    #print(len(a[22]))
    #print(len(a[23]))
    #print(len(a[24]))
    #print(len(a[25]))
    #print(len(a[26]))
    #print(len(a[27]))
    #print(len(a[28]))
    #print(len(a[29]))
    #print(len(a[30]))
    #print(len(a[31]))
    #print(len(a[32]))
    #print(len(a[33]))
    #print(len(a[34]))
    #print(len(a[35]))
    #print(len(a[36]))
    #print(len(a[37]))
    #print(len(a[38]))
    #print(len(a[39]))
    #print(len(a[40]))
    #print(len(a[41]))
    #print(len(a[42]))
    #print(len(a[43]))
    #print(len(a[44]))
    #print(len(a[45]))
    #print(len(a[46]))
    #print(len(a[47]))
    #print(len(a[48]))
