def main():
    N, M = map(int, input().split())
    prime = prime_factorization(M)
    if prime == None:
        print(1)
        return
    #print(prime)
    #print(len(prime))
    #print(prime[0][1])
    #print(prime[1][1])
    #print(prime[2][1])
    #print(prime[3][1])
    #print(prime[4][1])
    #print(prime[5][1])
    #print(prime[6][1])
    #print(prime[7][1])
    #print(prime[8][1])
    #print(prime[9][1])
    #print(prime[10][1])
    #print(prime[11][1])
    #print(prime[12][1])
    #print(prime[13][1])
    #print(prime[14][1])
    #print(prime[15][1])
    #print(prime[16][1])
    #print(prime[17][1])
    #print(prime[18][1])
    #print(prime[19][1])
    #print(prime[20][1])
    #print(prime[21][1])
    #print(prime[22][1])
    #print(prime[23][1])
    #print(prime[24][1])
    #print(prime[25][1])
    #print(prime[26][1])
    #print(prime[27][1])
    #print(prime[28][1])
    #print(prime[29][1])
    #print(prime[30][1])
    #print(prime[31][1])
    #print(prime[32][1])
    #print(prime[33][1])
    #print(prime[34][1])
    #print(prime[35][1])
    #print(prime[36][1])
    #print(prime[37][1])
    #print(prime[38][1])
    #print(prime[39][1])
    #print(prime[40][1])
    #print(prime[41][1])
    #print(prime[42][1])
    #print(prime[43][1])
    #print(prime[44][1])

if __name__ == '__main__':
    main()