def main():
    line = input()
    #line = "ooo??? xxxx"
    print(line)
    #print(line[0])
    #print(line[1])
    #print(line[2])
    #print(line[3])
    #print(line[4])
    #print(line[5])
    #print(line[6])
    #print(line[7])
    #print(line[8])
    #print(line[9])
    #print(line[10])
    #print(len(line))
    #print(line.count("o"))
    #print(line.count("x"))
    #print(line.count("?"))
    #print(line.count("o") + line.count("?"))
    #print(line.count("x") + line.count("?"))
    #print(line.count("o") + line.count("?") == 4)
    #print(line.count("x") + line.count("?") == 4)
    #print(line.count("o") + line.count("?") == 3)
    #print(line.count("x") + line.count("?") == 3)
    #print(line.count("o") + line.count("?") == 2)
    #print(line.count("x") + line.count("?") == 2)
    #print(line.count("o") + line.count("?") == 1)
    #print(line.count("x") + line.count("?") == 1)
    #print(line.count("o") + line.count("?") == 0)
    #print(line.count("x") + line.count("?") == 0)
    #print(line.count("o") + line.count("?") == 4 and line.count("x") + line.count("?") == 0)
    #print(line.count("x") + line.count("?") == 4 and line.count("o") + line.count("?") == 0)
    #print(line.count("o") + line.count("?") == 3 and line.count("x") + line.count("?") == 1)
    #print(line.count("x") + line.count("?") == 3 and line.count("o") + line.count("?") == 1)
    #print(line.count("o") + line.count("?") == 2 and line.count("x") + line.count("?") == 2)
    #print(line.count("x") + line.count("?") == 2 and line.count("o") +
