def solve(n, q, a, xk):
    #print("n: {}, q: {}, a: {}, xk: {}".format(n, q, a, xk))
    #print("a: {}".format(a))
    #print("xk: {}".format(xk))
    #print("xk[0]: {}".format(xk[0]))
    #print("xk[0][0]: {}".format(xk[0][0]))
    #print("xk[0][1]: {}".format(xk[0][1]))
    #print("xk[1]: {}".format(xk[1]))
    #print("xk[1][0]: {}".format(xk[1][0]))
    #print("xk[1][1]: {}".format(xk[1][1]))
    #print("xk[2]: {}".format(xk[2]))
    #print("xk[2][0]: {}".format(xk[2][0]))
    #print("xk[2][1]: {}".format(xk[2][1]))
    #print("xk[3]: {}".format(xk[3]))
    #print("xk[3][0]: {}".format(xk[3][0]))
    #print("xk[3][1]: {}".format(xk[3][1]))
    #print("xk[4]: {}".format(xk[4]))
    #print("xk[4][0]: {}".format(xk[4][0]))
    #print("xk[4][1]: {}".format(xk[4][1]))
    #print("xk[5]: {}".format(xk[5]))
    #print("xk[5][0]: {}".format(xk[5][0]))
    #print("xk[5][1]: {}".format(xk[5][1]))
    #print("xk[6]: {}".format(xk[6]))
    #print("xk[6][0]: {}".format(xk[6][0]))
    #print("xk[6][1]: {}".format(xk[6][1]))
    #print("xk[7]: {}".format(xk[7]))
    #print("xk[7][0]: {}".format(xk[7][0]))
    #print("xk[7][1]: {}".format

if __name__ == '__main__':
    solve()