def main():
    N = int(input())
    S = []
    for i in range(N):
        t, x, a = map(int, input().split())
        S.append([t, x, a])
    S.sort()
    #print(S)
    #print(S[0][0])
    #print(S[1][0])
    #print(S[2][0])
    #print(S[3][0])
    #print(S[4][0])
    #print(S[5][0])
    #print(S[6][0])
    #print(S[7][0])
    #print(S[8][0])
    #print(S[9][0])
    #print(S[0][1])
    #print(S[1][1])
    #print(S[2][1])
    #print(S[3][1])
    #print(S[4][1])
    #print(S[5][1])
    #print(S[6][1])
    #print(S[7][1])
    #print(S[8][1])
    #print(S[9][1])
    #print(S[0][2])
    #print(S[1][2])
    #print(S[2][2])
    #print(S[3][2])
    #print(S[4][2])
    #print(S[5][2])
    #print(S[6][2])
    #print(S[7][2])
    #print(S[8][2])
    #print(S[9][2])
    #print(S[0][0])
    #print(S[1][0])
    #print(S[2][0])
    #print(S[3][0])
    #print(S[4][0])
    #print(S[5][0])
    #print(S[6][0])
    #print(S[7][0])
    #print(S[8][0])
    #print(S[9][0])
    #print(S[0][1])
    #print(S[1][1])
    #print(S[2][1])
    #print(S[3][1])
    #print(S[4][1])
    #print(S[5][1])
    #print(S[6][1])
    #print(S[7][1])
    #print(S[8][1])
    #print(S[9][

if __name__ == '__main__':
    main()