def find_missing_digit(string):
    #converting string to set
    string_set = set(string)
    #converting set to list
    string_list = list(string_set)
    #converting list to int
    string_int_list = [int(i) for i in string_list]
    #sorting list
    string_int_list.sort()
    #print(string_int_list)
    #converting list to string
    string_int_list = [str(i) for i in string_int_list]
    #converting list to string
    string_int = ''.join(string_int_list)
    #print(string_int)
    #converting string to int
    string_int = int(string_int)
    #print(string_int)
    #print(type(string_int))
    #print(type(string_int_list))
    #print(type(string_list))
    #print(type(string_set))
    #print(type(string))
    #print(string)
    #print(string_set)
    #print(string_list)
    #print(string_int_list)
    #print(string_int)
    #print(type(string_int))
    #print(type(string_int_list))
    #print(type(string_list))
    #print(type(string_set))
    #print(type(string))
    #print(string)
    #print(string_set)
    #print(string_list)
    #print(string_int_list)
    #print(string_int)
    #print(type(string_int))
    #print(type(string_int_list))
    #print(type(string_list))
    #print(type(string_set))
    #print(type(string))
    #print(string)
    #print(string_set)
    #print(string_list)
    #print(string_int_list)
    #print(string_int)
    #print(type(string_int))
    #print(type(string_int_list))
    #print(type(string_list))
    #print(type(string_set))
    #print(type(string))
    #print(string)
    #print(string_set)
    #print(string_list)
    #print(string_int_list)
    #print(string_int)
    #print(type(string_int))
    #print(type(string_int_list))
    #print(type(string_list))
    #print(type(string_set))
    #print(type(string))
    #print(string)
    #print(string_set)
    #print(string_list)
    #print(string_int_list)
    #print(string_int)
    #print(type(string_int))
    #print(type(string_int_list))
    #print(type(string_list))
    #print(type(string_set

if __name__ == '__main__':
    find_missing_digit()