def main():
    S = input()
    N = len(S)
    S = S[::-1]
    # T = [0] * (N + 1)
    # for i in range(N):
    #     T[i + 1] = (T[i] + int(S[i]) * pow(10, i, 2019)) % 2019
    # print(T)
    # print(S)
    # print(N)
    # print(S[0])
    # print(int(S[0]))
    # print(pow(10, 0, 2019))
    # print(int(S[0]) * pow(10, 0, 2019))
    # print(T[1])
    # print(T[2])
    # print(T[3])
    # print(T[4])
    # print(T[5])
    # print(T[6])
    # print(T[7])
    # print(T[8])
    # print(T[9])
    # print(T[10])
    # print(T[11])
    # print(T[12])
    # print(T[13])
    # print(T[14])
    # print(T[15])
    # print(T[16])
    # print(T[17])
    # print(T[18])
    # print(T[19])
    # print(T[20])
    # print(T[21])
    # print(T[22])
    # print(T[23])
    # print(T[24])
    # print(T[25])
    # print(T[26])
    # print(T[27])
    # print(T[28])
    # print(T[29])
    # print(T[30])
    # print(T[31])
    # print(T[32])
    # print(T[33])
    # print(T[34])
    # print(T[35])
    # print(T[36])
    # print(T[37])
    # print(T[38])
    # print(T[39])
    # print(T[40])
    # print(T[41])
    # print(T[42])
    # print(T[43])
    # print(T[44])
    # print(T[45])
    # print(T[46])
    # print(T[47])
    # print(T[48])
    # print(T[49])
    # print(T[50])
    # print(T[51])
    #
