def main():
    n = int(input())
    p = list(map(int, input().split()))
    q = list(map(int, input().split()))
    p = list(p)
    q = list(q)
    p = [i-1 for i in p]
    q = [i-1 for i in q]
    # print(p)
    # print(q)
    # print(n)
    # print(p)
    # print(q)
    # print(p.index(0))
    # print(q.index(0))
    # print(p.index(1))
    # print(q.index(1))
    # print(p.index(2))
    # print(q.index(2))
    # print(p.index(3))
    # print(q.index(3))
    # print(p.index(4))
    # print(q.index(4))
    # print(p.index(5))
    # print(q.index(5))
    # print(p.index(6))
    # print(q.index(6))
    # print(p.index(7))
    # print(q.index(7))
    # print(p.index(8))
    # print(q.index(8))
    # print(p.index(0))
    # print(q.index(0))
    # print(p.index(1))
    # print(q.index(1))
    # print(p.index(2))
    # print(q.index(2))
    # print(p.index(3))
    # print(q.index(3))
    # print(p.index(4))
    # print(q.index(4))
    # print(p.index(5))
    # print(q.index(5))
    # print(p.index(6))
    # print(q.index(6))
    # print(p.index(7))
    # print(q.index(7))
    # print(p.index(8))
    # print(q.index(8))
    # print(p.index(0))
    # print(q.index(0))
    # print(p.index(1))
    # print(q.index(1))
    # print(p.index(2))
    # print(q.index(2))
    # print(p.index(3))
    # print(q.index(3))
    # print(p.index(4))
    # print(q.index(4))
    # print(p.index(5))
    # print(q.index(5))
    # print(p.index(6))
    # print(q.index(6))
    # print(p.index(7))
