def main():
    n,m,q = map(int,input().split())
    l = [0]*m
    r = [0]*m
    for i in range(m):
        l[i],r[i] = map(int,input().split())
    p = [0]*q
    q = [0]*q
    for i in range(q):
        p[i],q[i] = map(int,input().split())
    # print(n,m,q)
    # print(l,r)
    # print(p,q)
    # print("debug1")
    # print(n,m,q)
    # print(l,r)
    # print(p,q)
    # print("debug2")
    # print(n,m,q)
    # print(l,r)
    # print(p,q)
    # print("debug3")
    # print(n,m,q)
    # print(l,r)
    # print(p,q)
    # print("debug4")
    # print(n,m,q)
    # print(l,r)
    # print(p,q)
    # print("debug5")
    # print(n,m,q)
    # print(l,r)
    # print(p,q)
    # print("debug6")
    # print(n,m,q)
    # print(l,r)
    # print(p,q)
    # print("debug7")
    # print(n,m,q)
    # print(l,r)
    # print(p,q)
    # print("debug8")
    # print(n,m,q)
    # print(l,r)
    # print(p,q)
    # print("debug9")
    # print(n,m,q)
    # print(l,r)
    # print(p,q)
    # print("debug10")
    # print(n,m,q)
    # print(l,r)
    # print(p,q)
    # print("debug11")
    # print(n,m,q)
    # print(l,r)
    # print(p,q)
    # print("debug12")
    # print(n,m,q)
    # print(l,r)
    # print(p,q)
    # print("debug13")
    # print(n,m,q)
    # print(l,r)
    # print(p,q)
    # print("debug14")
    # print(n,m,q)
    # print(l,r)
    # print(p,q)
    # print("debug15")
    # print(n,m,q)
    # print(l,r)
    # print(p,q)
    # print("
