def main():
    h, w = map(int, input().split())
    s = [input() for _ in range(h)]
    #print(h, w)
    #print(s)
    #print(s[0][2])
    #print(s[0][0])
    #print(s[0][1])
    #print(s[0][2])
    #print(s[0][3])
    #print(s[0][4])
    #print(s[1][0])
    #print(s[1][1])
    #print(s[1][2])
    #print(s[1][3])
    #print(s[1][4])
    #print(s[2][0])
    #print(s[2][1])
    #print(s[2][2])
    #print(s[2][3])
    #print(s[2][4])
    #print(s[3][0])
    #print(s[3][1])
    #print(s[3][2])
    #print(s[3][3])
    #print(s[3][4])
    #print(s[4][0])
    #print(s[4][1])
    #print(s[4][2])
    #print(s[4][3])
    #print(s[4][4])
    #print(s[0][2])
    #print(s[1][2])
    #print(s[2][2])
    #print(s[3][2])
    #print(s[4][2])
    #print(s[0][0])
    #print(s[1][0])
    #print(s[2][0])
    #print(s[3][0])
    #print(s[4][0])
    #print(s[0][1])
    #print(s[1][1])
    #print(s[2][1])
    #print(s[3][1])
    #print(s[4][1])
    #print(s[0][2])
    #print(s[1][2])
    #print(s[2][2])
    #print(s[3][2])
    #print(s[4][2])
    #print(s[0][3])
    #print(s[1][3])
    #print(s[2][3])
    #print(s[3][3])
    #print(s[4][3])
    #print

if __name__ == '__main__':
    main()