def main():
    print("问题274：")
    print("问题陈述")
    print("给你一个长度为N的序列A=（A_1, A_2, ..., A_N），由正整数和整数x和y组成。")
    print("请判断在xy坐标平面上放置N+1个点p_1, p_2, ..., p_N, p_{N+1}是否能满足以下所有条件。(允许在同一坐标上放置两个或多个点)。")
    print("p_1 = (0, 0).")
    print("p_2 = (A_1, 0).")
    print("p_{N+1}=（x，y）。")
    print("点p_i和p_{i+1}之间的距离是A_i。(1 ≦ i ≦ N)")
    print("线段p_i p_{i+1}和p_{i+1} p_{i+2}形成一个90度角。(1 ≦ i ≦ N - 1)")
    print("限制条件")
    print("2 ≦ N ≦ 10^3")
    print("1 ≦ A_i ≦ 10")
    print("|x|, |y| ≦ 10^4")
    print("输入的所有数值都是整数。")
    print("输入")
    print("输入是由标准输入给出的，格式如下：")
    print("N x y")
    print("A_1 A_2 ...A_N")
    print("输出")
    print("如果可以放置p_1, p_2, ..., p_N, p_{N+1}来满足问题陈述中的所有条件，打印Yes；否则，打印No。")
    print("输入样本 1")
    print("3 -1 1")
    print("2 1 3")
    print("样本输出1")
    print("Yes")
    print("下图显示了一个安置，其中p_1=（0，0），p_2=（2，0），p_3=（2，1），p_4=
