def main():
    h, w = map(int, input().split())
    a = [list(input()) for i in range(h)]
    #print(a)
    #print(a[0][0])
    #print(a[0][1])
    #print(a[1][0])
    #print(a[1][1])
    #print(a[0][0] == '+')
    #print(a[0][0] == '-')
    #print(a[1][0] == '+')
    #print(a[1][0] == '-')
    #print(a[0][1] == '+')
    #print(a[0][1] == '-')
    #print(a[1][1] == '+')
    #print(a[1][1] == '-')
    #print(a[0][0] == '+')
    #print(a[0][0] == '-')
    #print(a[1][0] == '+')
    #print(a[1][0] == '-')
    #print(a[0][1] == '+')
    #print(a[0][1] == '-')
    #print(a[1][1] == '+')
    #print(a[1][1] == '-')
    #print(a[0][0] == '+')
    #print(a[0][0] == '-')
    #print(a[1][0] == '+')
    #print(a[1][0] == '-')
    #print(a[0][1] == '+')
    #print(a[0][1] == '-')
    #print(a[1][1] == '+')
    #print(a[1][1] == '-')
    #print(a[0][0] == '+')
    #print(a[0][0] == '-')
    #print(a[1][0] == '+')
    #print(a[1][0] == '-')
    #print(a[0][1] == '+')
    #print(a[0][1] == '-')
    #print(a[1][1] == '+')
    #print(a[1][1] == '-')
    #print(a[0][0] == '+')
    #print(a[0][0] == '-')
    #print(a[1][0] == '+')
    #print(a[1][0] == '-')
    #print(a[0][1] == '+')
    #print(a[
