def solve(N, S, W):
    # N = int(input())
    # S = input()
    # W = list(map(int, input().split()))
    # print(N, S, W)
    # print("N =", N)
    # print("S =", S)
    # print("W =", W)
    # print("")
    # S = "10101"
    # W = [60, 45, 30, 40, 80]
    # N = len(S)
    # S = "000"
    # W = [1, 2, 3]
    # N = len(S)
    # S = "10101"
    # W = [60, 50, 50, 50, 60]
    # N = len(S)
    # print("N =", N)
    # print("S =", S)
    # print("W =", W)
    # print("")
    # print("S =", S)
    # print("W =", W)
    # print("N =", N)
    # print("S =", S)
    # print("W =", W)
    # print("")
    # print("S =", S)
    # print("W =", W)
    # print("N =", N)
    # print("S =", S)
    # print("W =", W)
    # print("")
    # print("S =", S)
    # print("W =", W)
    # print("N =", N)
    # print("S =", S)
    # print("W =", W)
    # print("")
    # print("S =", S)
    # print("W =", W)
    # print("N =", N)
    # print("S =", S)
    # print("W =", W)
    # print("")
    # print("S =", S)
    # print("W =", W)
    # print("N =", N)
    # print("S =", S)
    # print("W =", W)
    # print("")
    # print("S =", S)
    # print("W =", W)
    # print("N =", N)
    # print("S =", S)
    # print("W =", W)
    # print("")
    # print("S =", S)
    # print("W =", W)
    # print("N =", N)
    # print("S =", S)
    # print("
