def solve(H, W, S):
    # print(H, W, S)
    # print(type(H), type(W), type(S))
    # print(S[0])
    # print(type(S[0]))
    # print(S[0][0])
    # print(type(S[0][0]))
    # print(S[0][0] == '#')
    # print(S[0][0] == '.')
    # print(S[0][1] == '#')
    # print(S[0][1] == '.')
    # print(S[1][0] == '#')
    # print(S[1][0] == '.')
    # print(S[1][1] == '#')
    # print(S[1][1] == '.')
    # print(S[0][0] == '#')
    # print(S[0][0] == '.')
    # print(S[0][1] == '#')
    # print(S[0][1] == '.')
    # print(S[1][0] == '#')
    # print(S[1][0] == '.')
    # print(S[1][1] == '#')
    # print(S[1][1] == '.')
    # print(S[0][0] == '#')
    # print(S[0][0] == '.')
    # print(S[0][1] == '#')
    # print(S[0][1] == '.')
    # print(S[1][0] == '#')
    # print(S[1][0] == '.')
    # print(S[1][1] == '#')
    # print(S[1][1] == '.')
    # print(S[0][0] == '#')
    # print(S[0][0] == '.')
    # print(S[0][1] == '#')
    # print(S[0][1] == '.')
    # print(S[1][0] == '#')
    # print(S[1][0] == '.')
    # print(S[1][1] == '#')
    # print(S[1][1] == '.')
    # print(S[0][0] == '#')
    # print(S[0][0] == '.')
    # print(S[0][1] == '#')
    # print(S[0][1] == '.')
    # print(S[1
