def main():
    N = int(input())
    T = []
    X = []
    A = []
    for i in range(N):
        t, x, a = map(int, input().split())
        T.append(t)
        X.append(x)
        A.append(a)
    # print(T, X, A)
    # print(N)
    # print(T[0], X[0], A[0])
    # print(T[1], X[1], A[1])
    # print(T[2], X[2], A[2])
    # print(T[3], X[3], A[3])
    # print(T[4], X[4], A[4])
    # print(T[5], X[5], A[5])
    # print(T[6], X[6], A[6])
    # print(T[7], X[7], A[7])
    # print(T[8], X[8], A[8])
    # print(T[9], X[9], A[9])
    # for i in range(N):
    #     print(T[i], X[i], A[i])
    # print(N)
    # print(T[0], X[0], A[0])
    # print(T[1], X[1], A[1])
    # print(T[2], X[2], A[2])
    # print(T[3], X[3], A[3])
    # print(T[4], X[4], A[4])
    # print(T[5], X[5], A[5])
    # print(T[6], X[6], A[6])
    # print(T[7], X[7], A[7])
    # print(T[8], X[8], A[8])
    # print(T[9], X[9], A[9])
    # print(N)
    # print(T[0], X[0], A[0])
    # print(T[1], X[1], A[1])
    # print(T[2], X[2], A[2])
    # print(T[3], X[3], A[3])
    # print(T[4], X[4], A[4])
    # print(T[5], X[5], A[5])
    # print(T[6], X[
