def main():
    N = int(input())
    A = list(map(int, input().split()))
    #print(N)
    #print(A)
    A.sort()
    #print(A)
    #print(len(A))
    #print(len(set(A)))
    #print(A)
    #print(set(A))
    #print(len(set(A))-1)
    #print(len(A)-1)
    #print(len(A)-len(set(A)))
    #print(len(A)-len(set(A))-1)
    #print(len(A)-len(set(A))+1)
    #print(len(A)-len(set(A))+2)
    #print(len(A)-len(set(A))+3)
    #print(len(A)-len(set(A))+4)
    #print(len(A)-len(set(A))+5)
    #print(len(A)-len(set(A))+6)
    #print(len(A)-len(set(A))+7)
    #print(len(A)-len(set(A))+8)
    #print(len(A)-len(set(A))+9)
    #print(len(A)-len(set(A))+10)
    #print(len(A)-len(set(A))+11)
    #print(len(A)-len(set(A))+12)
    #print(len(A)-len(set(A))+13)
    #print(len(A)-len(set(A))+14)
    #print(len(A)-len(set(A))+15)
    #print(len(A)-len(set(A))+16)
    #print(len(A)-len(set(A))+17)
    #print(len(A)-len(set(A))+18)
    #print(len(A)-len(set(A))+19)
    #print(len(A)-len(set(A))+20)
    #print(len(A)-len(set(A))+21)
    #print(len(A)-len(set(A))+22)
    #print(len(A)-len(set(A))+23)
    #print(len(A)-len(set(A))+24)
    #print(len(A)-len(set(A))+25)
    #print(len(A)-len(set(A))+26)
    #print(len(A)-len(set(A))+27)
    #print(len(A)-len(set(A))+28)
    #print(len(A)-len(set(A))+29)
    #print(len(A)-len(set(A))+30)
    #print(len(A)-len(set(A))+31)
    #print(len(A)-len(set(A))+32)
    #print(len(A)-len(set(A))+33)
    #print

if __name__ == '__main__':
    main()