def main():
    H, W = map(int, input().split())
    S = []
    for i in range(H):
        S.append(input())
    # print(S)
    # print(S[1][2])
    # print(S[1][2] == '#')
    # print(S[1][2] == '.')
    # print(S[1][2] == '#')
    # print(S[1][2] == '.')
    # print(S[1][2] == '#')
    # print(S[1][2] == '.')
    # print(S[1][2] == '#')
    # print(S[1][2] == '.')
    # print(S[1][2] == '#')
    # print(S[1][2] == '.')
    # print(S[1][2] == '#')
    # print(S[1][2] == '.')
    # print(S[1][2] == '#')
    # print(S[1][2] == '.')
    # print(S[1][2] == '#')
    # print(S[1][2] == '.')
    # print(S[1][2] == '#')
    # print(S[1][2] == '.')
    # print(S[1][2] == '#')
    # print(S[1][2] == '.')
    # print(S[1][2] == '#')
    # print(S[1][2] == '.')
    # print(S[1][2] == '#')
    # print(S[1][2] == '.')
    # print(S[1][2] == '#')
    # print(S[1][2] == '.')
    # print(S[1][2] == '#')
    # print(S[1][2] == '.')
    # print(S[1][2] == '#')
    # print(S[1][2] == '.')
    # print(S[1][2] == '#')
    # print(S[1][2] == '.')
    # print(S[1][2] == '#')
    # print(S[1][2] == '.')
    # print(S[1][2] == '#')
    # print(S[1][2] == '.')
    # print(S[1][2] == '#')
    # print(S[1][2] == '.')
