def main():
    #n = int(input())
    #a = list(map(int, input().split()))
    #b = list(map(int, input().split()))
    #c = list(map(int, input().split()))
    n = int(input())
    x = []
    y = []
    p = []
    for i in range(n):
        a = list(map(int, input().split()))
        x.append(a[0])
        y.append(a[1])
        p.append(a[2])
    #print(x)
    #print(y)
    #print(p)
    #print(len(x))
    #print(len(y))
    #print(len(p))
    #print(x[0])
    #print(y[0])
    #print(p[0])
    #print(x[1])
    #print(y[1])
    #print(p[1])
    #print(x[2])
    #print(y[2])
    #print(p[2])
    #print(x[3])
    #print(y[3])
    #print(p[3])
    #print(x[4])
    #print(y[4])
    #print(p[4])
    #print(x[5])
    #print(y[5])
    #print(p[5])
    #print(x[6])
    #print(y[6])
    #print(p[6])
    #print(x[7])
    #print(y[7])
    #print(p[7])
    #print(x[8])
    #print(y[8])
    #print(p[8])
    #print(x[9])
    #print(y[9])
    #print(p[9])
    #print(x[10])
    #print(y[10])
    #print(p[10])
    #print(x[11])
    #print(y[11])
    #print(p[11])
    #print(x[12])
    #print(y[12])
    #print(p[12])
    #print(x[13])
    #print(y[13])
    #print(p[13])
    #print(x[14])
    #print(y[14])
    #print(p[14])
    #print(x[15])
    #print(y[15])
    #print(p[15])
    #print(x[16])
    #print(y[16])
    #print(p[16])
    #print(x[17])

if __name__ == '__main__':
    main()