def main():
    N = int(input())
    #N = 5
    #u = [2, 2, 1, 3]
    #v = [5, 3, 3, 4]
    #w = [2, 10, 8, 2]
    u = []
    v = []
    w = []
    for i in range(N - 1):
        u_i, v_i, w_i = map(int, input().split())
        #u_i, v_i, w_i = u[i], v[i], w[i]
        u.append(u_i)
        v.append(v_i)
        w.append(w_i)
    #print(u)
    #print(v)
    #print(w)
    #print(N)
    #print(u)
    #print(v)
    #print(w)
    #print(u[0])
    #print(v[0])
    #print(w[0])
    #print(u[1])
    #print(v[1])
    #print(w[1])
    #print(u[2])
    #print(v[2])
    #print(w[2])
    #print(u[3])
    #print(v[3])
    #print(w[3])
    #print(N)
    #print(u)
    #print(v)
    #print(w)
    #print(u[0])
    #print(v[0])
    #print(w[0])
    #print(u[1])
    #print(v[1])
    #print(w[1])
    #print(u[2])
    #print(v[2])
    #print(w[2])
    #print(u[3])
    #print(v[3])
    #print(w[3])
    #print(u[4])
    #print(v[4])
    #print(w[4])
    #print(u[5])
    #print(v[5])
    #print(w[5])
    #print(u[6])
    #print(v[6])
    #print(w[6])
    #print(u[7])
    #print(v[7])
    #print(w[7])
    #print(u[8])
    #print(v[8])
    #print(w[8])
    #print(u[9])
    #print(v[9])
    #print(w[9])
    #print(u[10])
    #print(v
