def main():
    import sys
    import math
    import itertools
    N = int(sys.stdin.readline())
    xy = [list(map(int, sys.stdin.readline().split())) for _ in range(N)]
    #print(xy)
    #print(len(xy))
    #print(xy[0][0])
    #print(xy[0][1])
    #print(xy[1][0])
    #print(xy[1][1])
    #print(xy[2][0])
    #print(xy[2][1])
    #print(xy[3][0])
    #print(xy[3][1])
    #print(xy[4][0])
    #print(xy[4][1])
    #print(xy[5][0])
    #print(xy[5][1])
    #print(xy[6][0])
    #print(xy[6][1])
    #print(xy[7][0])
    #print(xy[7][1])
    #print(xy[8][0])
    #print(xy[8][1])
    #print(xy[9][0])
    #print(xy[9][1])
    #print(xy[10][0])
    #print(xy[10][1])
    #print(xy[11][0])
    #print(xy[11][1])
    #print(xy[12][0])
    #print(xy[12][1])
    #print(xy[13][0])
    #print(xy[13][1])
    #print(xy[14][0])
    #print(xy[14][1])
    #print(xy[15][0])
    #print(xy[15][1])
    #print(xy[16][0])
    #print(xy[16][1])
    #print(xy[17][0])
    #print(xy[17][1])
    #print(xy[18][0])
    #print(xy[18][1])
    #print(xy[19][0])
    #print(xy[19][1])
    #print(xy[20][0])
    #print(xy[20][1])
    #print(xy[21][0])
    #print(xy[21][1])
    #print(xy[22][0])
    #print(xy[22][1])
    #print(xy[23][0])
    #print(xy[23][1])
    #print(xy[24][0])
    #print(xy[24

if __name__ == '__main__':
    main()