def get_problem_index(problem_id):
    #print("Problem ID: ", problem_id)
    #print("Problem ID length: ", len(problem_id))
    #print("Problem ID[0]: ", problem_id[0])
    #print("Problem ID[1]: ", problem_id[1])
    #print("Problem ID[2]: ", problem_id[2])
    #print("Problem ID[3]: ", problem_id[3])
    #print("Problem ID[4]: ", problem_id[4])
    #print("Problem ID[5]: ", problem_id[5])
    #print("Problem ID[6]: ", problem_id[6])
    #print("Problem ID[7]: ", problem_id[7])
    #print("Problem ID[8]: ", problem_id[8])
    #print("Problem ID[9]: ", problem_id[9])
    #print("Problem ID[10]: ", problem_id[10])
    #print("Problem ID[11]: ", problem_id[11])
    #print("Problem ID[12]: ", problem_id[12])
    #print("Problem ID[13]: ", problem_id[13])
    #print("Problem ID[14]: ", problem_id[14])
    #print("Problem ID[15]: ", problem_id[15])
    #print("Problem ID[16]: ", problem_id[16])
    #print("Problem ID[17]: ", problem_id[17])
    #print("Problem ID[18]: ", problem_id[18])
    #print("Problem ID[19]: ", problem_id[19])
    #print("Problem ID[20]: ", problem_id[20])
    #print("Problem ID[21]: ", problem_id[21])
    #print("Problem ID[22]: ", problem_id[22])
    #print("Problem ID[23]: ", problem_id[23])
    #print("Problem ID[24]: ", problem_id[24])
    #print("Problem ID[25]: ", problem_id[25])
    #print("Problem ID[26]: ", problem_id[26])
    #print("Problem ID[27]: ", problem_id[27])
    #print("Problem ID[28]: ", problem_id[28])
    #print("Problem ID[29]: ", problem_id[29])
    #print("Problem ID[30]: ", problem_id[30])
    #print("Problem
