def main():
    n, k = map(int, input().split())
    a = list(map(int, input().split()))
    # a = [int(input()) for i in range(n)]
    # a = [list(map(int, input().split())) for i in range(n)]
    # a = [input() for i in range(n)]
    # a = [list(input()) for i in range(n)]
    # a = [str(input()) for i in range(n)]
    # a = [list(map(str, input().split())) for i in range(n)]
    # a = [list(input().split()) for i in range(n)]
    # a = [list(map(int, input().split())) for i in range(n)]
    # a = [list(map(str, input().split())) for i in range(n)]
    # a = [int(input()) for i in range(n)]
    # a = [list(map(int, input().split())) for i in range(n)]
    # a = [input() for i in range(n)]
    # a = [list(input()) for i in range(n)]
    # a = [str(input()) for i in range(n)]
    # a = [list(map(str, input().split())) for i in range(n)]
    # a = [list(input().split()) for i in range(n)]
    # a = [list(map(int, input().split())) for i in range(n)]
    # a = [list(map(str, input().split())) for i in range(n)]
    # a = [int(input()) for i in range(n)]
    # a = [list(map(int, input().split())) for i in range(n)]
    # a = [input() for i in range(n)]
    # a = [list(input()) for i in range(n)]
    # a = [str(input()) for i in range(n)]
    # a = [list(map(str, input().split())) for i in range(n)]
    # a = [list(input().split()) for i in range(n)]
    # a = [list(map(int, input().split())) for i in range(n)]
    # a = [list(map(str, input().split())) for i in range(n)]
    # a = [int(input()) for i in range(n)]
    # a = [list(map(int, input().split())) for i in range(n)]

if __name__ == '__main__':
    main()