def main():
    N, M = map(int, input().split())
    K = []
    A = []
    for i in range(N):
        k, *a = map(int, input().split())
        K.append(k)
        A.append(a)
    #print(N, M)
    #print(K)
    #print(A)
    #print(len(A))
    #print(len(A[0]))
    #print(A[0][0])
    #print(len(A[1]))
    #print(A[1][1])
    #print(A[1][2])
    #print(len(A[2]))
    #print(A[2][0])
    #print(A[2][1])
    #print(len(A[3]))
    #print(A[3][0])
    #print(A[3][1])
    #print(A[3][2])
    #print(len(A[4]))
    #print(A[4][0])
    #print(A[4][1])
    #print(A[4][2])
    #print(A[4][3])
    #print(len(A[5]))
    #print(A[5][0])
    #print(A[5][1])
    #print(A[5][2])
    #print(A[5][3])
    #print(A[5][4])
    #print(len(A[6]))
    #print(A[6][0])
    #print(A[6][1])
    #print(A[6][2])
    #print(A[6][3])
    #print(A[6][4])
    #print(A[6][5])
    #print(len(A[7]))
    #print(A[7][0])
    #print(A[7][1])
    #print(A[7][2])
    #print(A[7][3])
    #print(A[7][4])
    #print(A[7][5])
    #print(A[7][6])
    #print(len(A[8]))
    #print(A[8][0])
    #print(A[8][1])
    #print(A[8][2])
    #print(A[8][3])
    #print(A[8][4])
    #print(A[8][5])
    #print(A[8][6])
    #print(A[8][7])
    #print(len(A[9]))
    #print

if __name__ == '__main__':
    main()