def main():
    N, M = map(int, input().split())
    A = [0 for i in range(M)]
    B = [0 for i in range(M)]
    for i in range(M):
        A[i], B[i] = map(int, input().split())
    #print("N = ", N)
    #print("M = ", M)
    #print("A = ", A)
    #print("B = ", B)
    if M == 0:
        print(3**N)
        return
    #print("A = ", A)
    #print("B = ", B)
    #print("M = ", M)
    #print("N = ", N)
    #print("A = ", A)
    #print("B = ", B)
    #print("M = ", M)
    #print("N = ", N)
    #print("A = ", A)
    #print("B = ", B)
    #print("M = ", M)
    #print("N = ", N)
    #print("A = ", A)
    #print("B = ", B)
    #print("M = ", M)
    #print("N = ", N)
    #print("A = ", A)
    #print("B = ", B)
    #print("M = ", M)
    #print("N = ", N)
    #print("A = ", A)
    #print("B = ", B)
    #print("M = ", M)
    #print("N = ", N)
    #print("A = ", A)
    #print("B = ", B)
    #print("M = ", M)
    #print("N = ", N)
    #print("A = ", A)
    #print("B = ", B)
    #print("M = ", M)
    #print("N = ", N)
    #print("A = ", A)
    #print("B = ", B)
    #print("M = ", M)
    #print("N = ", N)
    #print("A = ", A)
    #print("B = ", B)
    #print("M = ", M)
    #print("N = ", N)
    #print("A = ", A)
    #print("B = ", B)
    #print("M = ", M)
    #

if __name__ == '__main__':
    main()