def main():
    N, M = map(int, input().split())
    # print(N, M)
    A = []
    B = []
    for i in range(N):
        a, b = map(int, input().split())
        A.append(a)
        B.append(b)
    # print(A, B)
    # print('------')
    # print(sorted(B))
    # print('------')
    # print(sorted(B, reverse=True))
    # print('------')
    # print(sorted(zip(B, A)))
    # print('------')
    # print(sorted(zip(B, A), reverse=True))
    # print('------')
    # print(sorted(zip(B, A), reverse=True)[:M])
    # print('------')
    # print(sorted(zip(B, A), reverse=True)[:M][0])
    # print('------')
    # print(sorted(zip(B, A), reverse=True)[:M][0][0])
    # print('------')
    # print(sorted(zip(B, A), reverse=True)[:M][0][1])
    # print('------')
    # print(sorted(zip(B, A), reverse=True)[:M][0][0] * sorted(zip(B, A), reverse=True)[:M][0][1])
    # print('------')
    # print(sum([sorted(zip(B, A), reverse=True)[:M][i][0] * sorted(zip(B, A), reverse=True)[:M][i][1] for i in range(M)]))
    # print('------')
    print(sum([sorted(zip(B, A), reverse=True)[:M][i][0] * sorted(zip(B, A), reverse=True)[:M][i][1] for i in range(M)]))

if __name__ == '__main__':
    main()