def main():
    N, M = map(int, input().split())
    K = []
    A = []
    for i in range(N):
        k, *a = map(int, input().split())
        K.append(k)
        A.append(a)
    # print(K, A)
    # print(A[0][0])
    # print(A[1][0])
    # print(A[2][0])
    # print(A[3][0])
    # print(A[4][0])
    # print(A[0][1])
    # print(A[1][1])
    # print(A[2][1])
    # print(A[3][1])
    # print(A[4][1])
    # print(A[0][2])
    # print(A[1][2])
    # print(A[2][2])
    # print(A[3][2])
    # print(A[4][2])
    # print(A[0][3])
    # print(A[1][3])
    # print(A[2][3])
    # print(A[3][3])
    # print(A[4][3])
    # print(A[0][4])
    # print(A[1][4])
    # print(A[2][4])
    # print(A[3][4])
    # print(A[4][4])
    # print(A[0][5])
    # print(A[1][5])
    # print(A[2][5])
    # print(A[3][5])
    # print(A[4][5])
    # print(A[0][6])
    # print(A[1][6])
    # print(A[2][6])
    # print(A[3][6])
    # print(A[4][6])
    # print(A[0][7])
    # print(A[1][7])
    # print(A[2][7])
    # print(A[3][7])
    # print(A[4][7])
    # print(A[0][8])
    # print(A[1][8])
    # print(A[2][8])
    # print(A[3][8])
    # print(A[4][8])
    # print(A[0][9])
    # print(A[1][9])
    # print(A[2][9])
    # print(A[3][9])
