def main():
    H, W = map(int, input().split())
    S = [input() for _ in range(H)]
    #print(H, W)
    #print(S)
    #print()
    #print()
    #print("start")
    #print("S[0][0] = ", S[0][0])
    #print("S[0][1] = ", S[0][1])
    #print("S[0][2] = ", S[0][2])
    #print("S[0][3] = ", S[0][3])
    #print("S[0][4] = ", S[0][4])
    #print("S[1][0] = ", S[1][0])
    #print("S[1][1] = ", S[1][1])
    #print("S[1][2] = ", S[1][2])
    #print("S[1][3] = ", S[1][3])
    #print("S[1][4] = ", S[1][4])
    #print("S[2][0] = ", S[2][0])
    #print("S[2][1] = ", S[2][1])
    #print("S[2][2] = ", S[2][2])
    #print("S[2][3] = ", S[2][3])
    #print("S[2][4] = ", S[2][4])
    #print("S[3][0] = ", S[3][0])
    #print("S[3][1] = ", S[3][1])
    #print("S[3][2] = ", S[3][2])
    #print("S[3][3] = ", S[3][3])
    #print("S[3][4] = ", S[3][4])
    #print("S[4][0] = ", S[4][0])
    #print("S[4][1] = ", S[4][1])
    #print("S[4][2] = ", S[4][2])
    #print("S[4][3] = ", S[4][3])
    #print("S[4][4] = ", S[4][
