def main():
    from sys import stdin
    from collections import Counter
    from itertools import product
    from functools import reduce
    from operator import mul
    from math import factorial
    from math import log10
    from math import pow
    from math import floor
    from math import ceil
    from math import gcd
    from math import sqrt
    from math import pi
    from math import inf
    from math import e
    from bisect import bisect_left
    from bisect import bisect_right
    from bisect import insort_left
    from bisect import insort_right
    from heapq import heappush
    from heapq import heappop
    from heapq import heapify
    from heapq import heappushpop
    from heapq import heapreplace
    from heapq import merge
    from random import randint
    from random import shuffle
    from random import sample
    from random import choice
    from random import choices
    from random import randrange
    from random import random
    from random import triangular
    from random import uniform
    from random import gauss
    from random import betavariate
    from random import expovariate
    from random import gammavariate
    from random import lognormvariate
    from random import normalvariate
    from random import vonmisesvariate
    from random import paretovariate
    from random import weibullvariate
    from decimal import Decimal
    from decimal import getcontext
    from decimal import ROUND_CEILING
    from decimal import ROUND_DOWN
    from decimal import ROUND_FLOOR
    from decimal import ROUND_HALF_DOWN
    from decimal import ROUND_HALF_EVEN
    from decimal import ROUND_HALF_UP
    from decimal import ROUND_UP
    from decimal import ROUND_05UP
    from typing import Any
    from typing import Union
    from typing import NoReturn
    from typing import Optional
    from typing import List
    from typing import Tuple
    from typing import Callable
    from typing import Iterable
    from typing import Iterator
    from typing import Sequence
    from typing import Mapping
    from typing import MutableSequence
    from typing import MutableMapping
    from typing import Counter as CounterType
    from typing import Set
    from typing import MutableSet
    from typing import Dict
    from typing import DefaultDict
    from
