def main():
    n, c = map(int, input().split())
    d = []
    for i in range(c):
        d.append(list(map(int, input().split())))
    color = []
    for i in range(n):
        color.append(list(map(int, input().split())))
    # print(d)
    # print(color)
    # print(n, c)
    # print(color[0][0])
    # print((1+1)%3)
    # print(color[0][1])
    # print((1+2)%3)
    # print(color[0][2])
    # print((1+3)%3)
    # print(color[0][3])
    # print((1+4)%3)
    # print(color[1][0])
    # print((2+1)%3)
    # print(color[1][1])
    # print((2+2)%3)
    # print(color[1][2])
    # print((2+3)%3)
    # print(color[1][3])
    # print((2+4)%3)
    # print(color[2][0])
    # print((3+1)%3)
    # print(color[2][1])
    # print((3+2)%3)
    # print(color[2][2])
    # print((3+3)%3)
    # print(color[2][3])
    # print((3+4)%3)
    # print(color[3][0])
    # print((4+1)%3)
    # print(color[3][1])
    # print((4+2)%3)
    # print(color[3][2])
    # print((4+3)%3)
    # print(color[3][3])
    # print((4+4)%3)
    # print(color[4][0])
    # print((5+1)%3)
    # print(color[4][1])
    # print((5+2)%3)
    # print(color[4][2])
    # print((5+3)%3)
    # print(color[4][3])
    # print((5+4)%3)
    # print(color[5][0])
    # print((6+1)%3)
    # print(color[5][1])
    # print((6+2)%3)
    # print(color[5][
