def main():
    N = int(input())
    T = []
    A = []
    for i in range(N):
        Ti, Ki, *Ai = map(int, input().split())
        T.append(Ti)
        A.append(Ai)
    #print(N)
    #print(T)
    #print(A)
    #print(T[0])
    #print(A[0])
    #print(T[1])
    #print(A[1])
    #print(T[2])
    #print(A[2])
    #print(T[3])
    #print(A[3])
    #print(T[4])
    #print(A[4])
    #print(T[5])
    #print(A[5])
    #print(T[6])
    #print(A[6])
    #print(T[7])
    #print(A[7])
    #print(T[8])
    #print(A[8])
    #print(T[9])
    #print(A[9])
    #print(T[10])
    #print(A[10])
    #print(T[11])
    #print(A[11])
    #print(T[12])
    #print(A[12])
    #print(T[13])
    #print(A[13])
    #print(T[14])
    #print(A[14])
    #print(T[15])
    #print(A[15])
    #print(T[16])
    #print(A[16])
    #print(T[17])
    #print(A[17])
    #print(T[18])
    #print(A[18])
    #print(T[19])
    #print(A[19])
    #print(T[20])
    #print(A[20])
    #print(T[21])
    #print(A[21])
    #print(T[22])
    #print(A[22])
    #print(T[23])
    #print(A[23])
    #print(T[24])
    #print(A[24])
    #print(T[25])
    #print(A[25])
    #print(T[26])
    #print(A[26])
    #print(T[27])
    #print(A[27])
    #print(T[28])
    #print(A[28])
    #print(T[29])
    #print(A[29])
    #print(T[30])
    #print(A[30])

if __name__ == '__main__':
    main()