def main():
    n, w = map(int, input().split())
    cheese = []
    for i in range(n):
        cheese.append(list(map(int, input().split())))
    cheese.sort(key=lambda x: x[0])
    cheese.reverse()
    # print(cheese)
    # print('-----------------------')
    # cheese.sort(key=lambda x: x[1])
    # cheese.reverse()
    # print(cheese)
    # print('-----------------------')
    # cheese.sort(key=lambda x: x[0]/x[1])
    # cheese.reverse()
    # print(cheese)
    # print('-----------------------')
    # cheese.sort(key=lambda x: x[1]/x[0])
    # cheese.reverse()
    # print(cheese)
    # print('-----------------------')
    # cheese.sort(key=lambda x: x[0]*x[1])
    # cheese.reverse()
    # print(cheese)
    # print('-----------------------')
    # cheese.sort(key=lambda x: x[1]*x[0])
    # cheese.reverse()
    # print(cheese)
    # print('-----------------------')
    # cheese.sort(key=lambda x: x[0]/x[1]*x[1])
    # cheese.reverse()
    # print(cheese)
    # print('-----------------------')
    # cheese.sort(key=lambda x: x[1]/x[0]*x[0])
    # cheese.reverse()
    # print(cheese)
    # print('-----------------------')
    # cheese.sort(key=lambda x: x[0]/x[1]*x[0])
    # cheese.reverse()
    # print(cheese)
    # print('-----------------------')
    # cheese.sort(key=lambda x: x[1]/x[0]*x[1])
    # cheese.reverse()
    # print(cheese)
    # print('-----------------------')
    # cheese.sort(key=lambda x: x[0]/x[1]*x[1]/x[0])
    # cheese.reverse()
    # print(cheese)
    # print('-----------------------')
    # cheese.sort(key=lambda x: x[1]/x[0]*x[0]/x[1])
    # cheese.reverse()
    # print(cheese)
    # print('-----------------------')
    # cheese.sort(key=lambda x: x[0]/x[1]*x[1]/x[

if __name__ == '__main__':
    main()