def main():
    N, M = map(int, input().split())
    #print(N, M)
    #print(type(N), type(M))
    #print((N, M))
    #print(type((N, M)))
    #print((N, M)[0])
    #print((N, M)[1])
    #print(type((N, M)[0]), type((N, M)[1]))
    #print((N, M)[0], (N, M)[1])
    #print((N, M)[0] * (N, M)[1])
    #print(type((N, M)[0] * (N, M)[1]))
    #print((N, M)[0] * (N, M)[1] * (N, M)[1])
    #print(type((N, M)[0] * (N, M)[1] * (N, M)[1]))
    #print((N, M)[0] * (N, M)[1] * (N, M)[1] * (N, M)[1])
    #print(type((N, M)[0] * (N, M)[1] * (N, M)[1] * (N, M)[1]))
    #print((N, M)[0] * (N, M)[1] * (N, M)[1] * (N, M)[1] * (N, M)[1])
    #print(type((N, M)[0]
