def main():
    S = input()
    #S = "redocta"
    #S = "catredo"
    #S = "atcoder"
    Slist = list(S)
    #print(Slist)
    #print("".join(Slist))
    #print(Slist.index("a"))
    #print(Slist.index("c"))
    #print(Slist.index("o"))
    #print(Slist.index("r"))
    #print(Slist.index("t"))
    #print(Slist.index("d"))
    #print(Slist.index("e"))
    #print(Slist.count("a"))
    #print(Slist.count("c"))
    #print(Slist.count("o"))
    #print(Slist.count("r"))
    #print(Slist.count("t"))
    #print(Slist.count("d"))
    #print(Slist.count("e"))
    #print(Slist.index("a"))
    #print(Slist.index("c"))
    #print(Slist.index("o"))
    #print(Slist.index("r"))
    #print(Slist.index("t"))
    #print(Slist.index("d"))
    #print(Slist.index("e"))
    #print("".join(Slist))
    #print(Slist.index("a"))
    #print(Slist.index("c"))
    #print(Slist.index("o"))
    #print(Slist.index("r"))
    #print(Slist.index("t"))
    #print(Slist.index("d"))
    #print(Slist.index("e"))
    #print("".join(Slist))
    #print(Slist.index("a"))
    #print(Slist.index("c"))
    #print(Slist.index("o"))
    #print(Slist.index("r"))
    #print(Slist.index("t"))
    #print(Slist.index("d"))
    #print(Slist.index("e"))
    #print("".join(Slist))
    #print(Slist.index("a"))
    #print(Slist.index("c"))
    #print(Slist.index("o"))
    #print(Slist.index("r"))
    #print(Slist.index("t"))
    #print(Slist.index("d"))
    #print(Slist.index("e"))
    #print("".join(Slist))
    #print(Slist.index("a"))
    #print(Slist.index("c"))
    #print(Slist.index("o"))
    #print(Slist

if __name__ == '__main__':
    main()