def main():
  # N = int(input())
  # A = list(map(int, input().split()))
  # A, B, C = map(int, input().split())
  # S = input()
  # N, K = map(int, input().split())
  # S = input()
  # A = list(map(int, input().split()))
  # A = [list(map(int, input().split())) for _ in range(N)]
  Q = int(input())
  # Q = N
  # A = list(map(int, input().split()))
  # A = [list(map(int, input().split())) for _ in range(N)]
  # A = [list(map(int, input().split())) for _ in range(N)]
  # A = [int(input()) for _ in range(N)]
  # A = [list(map(int, input().split())) for _ in range(N)]
  # A = [list(map(int, input().split())) for _ in range(N)]
  # A = [list(map(int, input().split())) for _ in range(N)]
  # N = int(input())
  # A = list(map(int, input().split()))
  # A, B, C = map(int, input().split())
  # S = input()
  # N, K = map(int, input().split())
  # S = input()
  # A = list(map(int, input().split()))
  # A = [list(map(int, input().split())) for _ in range(N)]
  # Q = int(input())
  # A = [list(map(int, input().split())) for _ in range(N)]
  # A = [int(input()) for _ in range(N)]
  # A = [list(map(int, input().split())) for _ in range(N)]
  # A = [int(input()) for _ in range(N)]
  # A = [list(map(int, input().split())) for _ in range(N)]
  # A = [int(input()) for _ in range(N)]
  # A = [list(map(int, input().split())) for _ in range(N)]
  # A = [list(map(int, input().split())) for _ in range(N)]
  # B = [list(map(int, input().split())) for _ in range(N)]
  # A = [int(input()) for _ in range(N)]
  # B = [int(input
