def main():
    N, K = map(int, input().split())
    R, S, P = map(int, input().split())
    T = input()
    # print(N, K, R, S, P, T)
    # print(T[0:K])
    # print(T[K:N])
    # print(T[N - K:N])
    # print(T[0:N - K])
    # print(T[K:N - K])
    # print(T[0:K] + T[N - K:N])
    # print(T[0:N - K] + T[K:N])
    # print(T[K:N] + T[0:K])
    # print(T[N - K:N] + T[0:N - K])
    # print(T[0:N - K] + T[K:N] + T[0:K])
    # print(T[K:N] + T[0:K] + T[N - K:N])
    # print(T[N - K:N] + T[0:N - K] + T[K:N])
    # print(T[0:K] + T[N - K:N] + T[K:N])
    # print(T[0:N - K] + T[K:N] + T[N - K:N])
    # print(T[K:N] + T[N - K:N] + T[0:K])
    # print(T[N - K:N] + T[0:K] + T[K:N])
    # print(T[0:K] + T[N - K:N] + T[K:N] + T[0:N - K])
    # print(T[0:N - K] + T[K:N] + T[N - K:N] + T[0:K])
    # print(T[K:N] + T[0:K] + T[N - K:N] + T[0:N - K])
    # print(T[N - K:N] + T[0:K] + T[K:N] + T[0:N - K])
    # print(T[0:N - K] + T[K:N] + T[N - K:N] + T[0:K] + T[K:N])
    # print(T[K:N] + T[0:K] + T[N - K:N] + T[0:N - K] + T[K:N])
    # print(T[N - K:N] + T[

if __name__ == '__main__':
    main()