def main():
    N, M = map(int, input().split())
    k = [0] * M
    a = [[] for _ in range(M)]
    for i in range(M):
        k[i] = int(input())
        a[i] = list(map(int, input().split()))
    #print(N, M)
    #print(k)
    #print(a)
    #print("")
    #print("start")
    #print("")
    #print("a")
    #print(a)
    #print("")
    #print("a[0]")
    #print(a[0])
    #print("")
    #print("a[0][0]")
    #print(a[0][0])
    #print("")
    #print("a[0][0]-1")
    #print(a[0][0]-1)
    #print("")
    #print("a[0][0]-1+N")
    #print(a[0][0]-1+N)
    #print("")
    #print("a[0][0]-1+N*2")
    #print(a[0][0]-1+N*2)
    #print("")
    #print("a[0][0]-1+N*3")
    #print(a[0][0]-1+N*3)
    #print("")
    #print("a[0][0]-1+N*4")
    #print(a[0][0]-1+N*4)
    #print("")
    #print("a[0][0]-1+N*5")
    #print(a[0][0]-1+N*5)
    #print("")
    #print("a[0][0]-1+N*6")
    #print(a[0][0]-1+N*6)
    #print("")
    #print("a[0][0]-1+N*7")
    #print(a[0][0]-1+N*7)
    #print("")
    #print("a[0][0]-1+N*8")
    #print(a[0][0]-1+N*8)
    #print("")
    #print("a[0][0]-1+N*9")
    #print(a[0][0]-1+N*9)
    #print("")
    #print("a[0][0]-1+N*10")
