def main():
    N, M = map(int, input().split())
    k = [0] * M
    a = [[0] * N for _ in range(M)]
    for i in range(M):
        k[i] = int(input())
        a[i] = list(map(int, input().split()))
    #print(N, M)
    #print(k)
    #print(a)
    #print(a[0][0])
    #print(a[1][0])
    #print(a[1][1])
    #print(a[2][0])
    #print(a[2][1])
    #print(a[2][2])
    #print(a[3][0])
    #print(a[3][1])
    #print(a[3][2])
    #print(a[3][3])
    #print(a[4][0])
    #print(a[4][1])
    #print(a[4][2])
    #print(a[4][3])
    #print(a[4][4])
    #print(a[5][0])
    #print(a[5][1])
    #print(a[5][2])
    #print(a[5][3])
    #print(a[5][4])
    #print(a[5][5])
    #print(a[6][0])
    #print(a[6][1])
    #print(a[6][2])
    #print(a[6][3])
    #print(a[6][4])
    #print(a[6][5])
    #print(a[6][6])
    #print(a[7][0])
    #print(a[7][1])
    #print(a[7][2])
    #print(a[7][3])
    #print(a[7][4])
    #print(a[7][5])
    #print(a[7][6])
    #print(a[7][7])
    #print(a[8][0])
    #print(a[8][1])
    #print(a[8][2])
    #print(a[8][3])
    #print(a[8][4])
    #print(a[8][5])
    #print(a[8][6])
    #print(a[8][7])
    #print(a[8][8])
    #print(a[9][0])
    #print(a
