def main():
    N, M = map(int, input().split())
    H = list(map(int, input().split()))
    A = []
    B = []
    for i in range(M):
        a, b = map(int, input().split())
        A.append(a)
        B.append(b)
    #print(N, M, H, A, B)
    #print(N, M, H, A, B)
    #print('N = ', N)
    #print('M = ', M)
    #print('H = ', H)
    #print('A = ', A)
    #print('B = ', B)
    #print('len(H) = ', len(H))
    #print('len(A) = ', len(A))
    #print('len(B) = ', len(B))
    #print('len(H) = ', len(H))
    #print('len(A) = ', len(A))
    #print('len(B) = ', len(B))
    #print('len(H) = ', len(H))
    #print('len(A) = ', len(A))
    #print('len(B) = ', len(B))
    #print('len(H) = ', len(H))
    #print('len(A) = ', len(A))
    #print('len(B) = ', len(B))
    #print('len(H) = ', len(H))
    #print('len(A) = ', len(A))
    #print('len(B) = ', len(B))
    #print('len(H) = ', len(H))
    #print('len(A) = ', len(A))
    #print('len(B) = ', len(B))
    #print('len(H) = ', len(H))
    #print('len(A) = ', len(A))
    #print('len(B) = ', len(B))
    #print('len(H) = ', len(H))
    #print('len(A) = ', len(A))
    #print('len(B) = ', len(B))
    #print('len(H) = ', len(H))
    #print('len(A) = ', len(A))
    #print('len(B) = ', len(B))
    #print('len(H) = ', len(H))
    #print('len(A) = ', len(A))
    #print('len(B) = ', len(B))
    #print('len(H)
