def main():
    S = input()
    Q = int(input())
    t_k = [list(map(int, input().split())) for _ in range(Q)]
    #print(S, Q, t_k)
    #print(S[0], S[1], S[2])
    #print(S[3], S[4], S[5])
    #print(S[6], S[7], S[8])
    #print(S[9], S[10], S[11])
    #print(S[12], S[13], S[14])
    #S = input()
    #Q = int(input())
    #t_k = [list(map(int, input().split())) for _ in range(Q)]
    #print(S, Q, t_k)
    #print(S[0], S[1], S[2])
    #print(S[3], S[4], S[5])
    #print(S[6], S[7], S[8])
    #print(S[9], S[10], S[11])
    #print(S[12], S[13], S[14])
    #print(S[0], S[1], S[2])
    #print(S[3], S[4], S[5])
    #print(S[6], S[7], S[8])
    #print(S[9], S[10], S[11])
    #print(S[12], S[13], S[14])
    #print(S[0], S[1], S[2])
    #print(S[3], S[4], S[5])
    #print(S[6], S[7], S[8])
    #print(S[9], S[10], S[11])
    #print(S[12], S[13], S[14])
    #print(S[0], S[1], S[2])
    #print(S[3], S[4], S[5])
    #print(S[6], S[7], S[8])
    #print(S[9], S[10], S[11])
    #print(S[12], S[13], S[14])
    #print(S[0], S[1], S[2])
    #print(S[3], S[4], S[5])
    #print(S[6], S[7
