def main():
    N,X,Y = map(int,input().split())
    edges = []
    for i in range(N-1):
        edges.append(list(map(int,input().split())))
    #print(edges)
    #print(N,X,Y)
    #print(edges)
    graph = [[0 for i in range(N)] for j in range(N)]
    #print(graph)
    for edge in edges:
        graph[edge[0]-1][edge[1]-1] = 1
        graph[edge[1]-1][edge[0]-1] = 1
    #print(graph)
    #print(graph)
    #print(graph[1])
    #print(graph[2])
    #print(graph[3])
    #print(graph[4])
    #print(graph[5])
    #print(graph[6])
    #print(graph[7])
    #print(graph[8])
    #print(graph[9])
    #print(graph[10])
    #print(graph[11])
    #print(graph[12])
    #print(graph[13])
    #print(graph[14])
    #print(graph[15])
    #print(graph[16])
    #print(graph[17])
    #print(graph[18])
    #print(graph[19])
    #print(graph[20])
    #print(graph[21])
    #print(graph[22])
    #print(graph[23])
    #print(graph[24])
    #print(graph[25])
    #print(graph[26])
    #print(graph[27])
    #print(graph[28])
    #print(graph[29])
    #print(graph[30])
    #print(graph[31])
    #print(graph[32])
    #print(graph[33])
    #print(graph[34])
    #print(graph[35])
    #print(graph[36])
    #print(graph[37])
    #print(graph[38])
    #print(graph[39])
    #print(graph[40])
    #print(graph[41])
    #print(graph[42])
    #print(graph[43])
    #print(graph[44])
    #print(graph[45])
    #print(graph[46])
    #print(graph[47])
    #print(graph[48])
    #print(graph[49])
    #print(graph[50])
    #print(graph[51])
    #print(graph[52])
    #print(graph[53])
    #
