def problem_statement():
    print("How many triples of non-negative integers (a, b, c) satisfy a+b+c ≦ S and a × b × c ≦ T?")
    print("Constraints")
    print("0 ≦ S ≦ 100")
    print("0 ≦ T ≦ 10000")
    print("S and T are integers.")
    print("Input")
    print("Input is given from Standard Input in the following format:")
    print("S T")
    print("Output")
    print("Print the number of triples of non-negative integers (a,b,c) satisfying the conditions.")
    print("Sample Input 1")
    print("1 0")
    print("Sample Output 1")
    print("4")
    print("The triples (a,b,c) satisfying the conditions are (0,0,0), (0,0,1), (0,1,0), and (1,0,0) ― there are four of them.")
    print("Sample Input 2")
    print("2 5")
    print("Sample Output 2")
    print("10")
    print("Sample Input 3")
    print("10 10")
    print("Sample Output 3")
    print("213")
    print("Sample Input 4")
    print("30 100")
    print("Sample Output 4")
    print("2471")
