def main():
    s = input()
    #print(s)
    #print(len(s))
    s_len = len(s)
    #print(s_len)
    #print(s[0])
    #print(s[1])
    #print(s[2])
    #print(s[s_len - 1])
    #print(s[s_len - 2])
    #print(s[s_len - 3])
    #print(s[s_len - 4])
    #print(s[s_len - 5])
    #print(s[s_len - 6])
    #print(s[s_len - 7])
    #print(s[s_len - 8])
    #print(s[s_len - 9])
    #print(s[s_len - 10])
    #print(s[s_len - 11])
    #print(s[s_len - 12])
    #print(s[s_len - 13])
    #print(s[s_len - 14])
    #print(s[s_len - 15])
    #print(s[s_len - 16])
    #print(s[s_len - 17])
    #print(s[s_len - 18])
    #print(s[s_len - 19])
    #print(s[s_len - 20])
    #print(s[s_len - 21])
    #print(s[s_len - 22])
    #print(s[s_len - 23])
    #print(s[s_len - 24])
    #print(s[s_len - 25])
    #print(s[s_len - 26])
    #print(s[s_len - 27])
    #print(s[s_len - 28])
    #print(s[s_len - 29])
    #print(s[s_len - 30])
    #print(s[s_len - 31])
    #print(s[s_len - 32])
    #print(s[s_len - 33])
    #print(s[s_len - 34])
    #print(s[s_len - 35])
    #print(s[s_len - 36])
    #print(s[s_len - 37])
    #print(s[s_len - 38])
    #print(s[s_len - 39])
    #print(s[s_len - 40])
    #print(s[s_len - 41])
    #print(s[s_len - 42])
    #print(s[s_len - 43])
    #print(s[s_len - 44])
    #print(s[s_len -

if __name__ == '__main__':
    main()