def main():
    #n = int(input())
    #a, b = map(int, input().split())
    n, m = map(int, input().split())
    #s = input()
    #s = input().split()
    #a = list(map(int, input().split()))
    #a = [int(input()) for i in range(n)]
    #a = [list(map(int, input().split())) for i in range(n)]
    #a = [input() for i in range(n)]
    #a = [input().split() for i in range(n)]
    #a = [list(map(int, input().split())) for i in range(n)]
    #a = [[int(input()) for i in range(n)] for j in range(n)]
    #a = [[int(input()) for i in range(m)] for j in range(n)]
    #a = [[input() for i in range(n)] for j in range(n)]
    #a = [[input().split() for i in range(n)] for j in range(n)]
    #a = [[list(map(int, input().split())) for i in range(m)] for j in range(n)]
    #a = [list(map(int, input().split())) for i in range(m)]
    #a = [list(map(int, input().split())) for i in range(n)]
    #a = [list(map(int, input().split())) for i in range(h)]
    #a = [list(map(int, input().split())) for i in range(h)]
    #a = [list(map(int, input().split())) for i in range(h)]
    #a = [input() for i in range(n)]
    #a = [input().split() for i in range(n)]
    #a = [list(map(int, input().split())) for i in range(n)]
    #a = [int(input()) for i in range(n)]
    #a = [input() for i in range(n)]
    #a = [input().split() for i in range(n)]
    #a = [list(map(int, input().split())) for i in range(n)]
    #a = [[int(input()) for i in range(n)] for j in range(n)]
    #a = [[input() for i in range(n)] for j in range(n)]
    #a = [[input().split() for i in range
