def main():
    n, k = map(int, input().split())
    tds = []
    for i in range(n):
        tds.append(list(map(int, input().split())))
    tds.sort(key=lambda x: x[1], reverse=True)
    print(tds)
    tds.sort(key=lambda x: x[0])
    print(tds)
    tds.sort(key=lambda x: x[1], reverse=True)
    print(tds)
    tds.sort(key=lambda x: x[0])
    print(tds)
    tds.sort(key=lambda x: x[1], reverse=True)
    print(tds)
    tds.sort(key=lambda x: x[0])
    print(tds)
    tds.sort(key=lambda x: x[1], reverse=True)
    print(tds)
    tds.sort(key=lambda x: x[0])
    print(tds)
    tds.sort(key=lambda x: x[1], reverse=True)
    print(tds)
    tds.sort(key=lambda x: x[0])
    print(tds)
    tds.sort(key=lambda x: x[1], reverse=True)
    print(tds)
    tds.sort(key=lambda x: x[0])
    print(tds)
    tds.sort(key=lambda x: x[1], reverse=True)
    print(tds)
    tds.sort(key=lambda x: x[0])
    print(tds)
    tds.sort(key=lambda x: x[1], reverse=True)
    print(tds)
    tds.sort(key=lambda x: x[0])
    print(tds)
    tds.sort(key=lambda x: x[1], reverse=True)
    print(tds)
    tds.sort(key=lambda x: x[0])
    print(tds)
