def main():
    N, M = map(int, input().split())
    #print(N, M)
    #print(type(N), type(M))
    k = []
    s = []
    p = []
    for i in range(M):
        k.append(list(map(int, input().split())))
        #print(k)
        s.append(list(map(int, input().split())))
        #print(s)
    p = list(map(int, input().split()))
    #print(p)
    #print(type(k), type(s), type(p))
    #print(k[0][0])
    #print(s[0][0])
    #print(p[0])
    #print(len(k))
    #print(len(s))
    #print(len(p))
    #print(k[0][0])
    #print(s[0][0])
    #print(p[0])
    #print(k[0][1])
    #print(s[0][1])
    #print(k[1][0])
    #print(s[1][0])
    #print(p[1])
    #print(k[1][1])
    #print(s[1][1])
    #print(k[1][2])
    #print(s[1][2])
    #print(k[2][0])
    #print(s[2][0])
    #print(p[2])
    #print(k[2][1])
    #print(s[2][1])
    #print(k[2][2])
    #print(s[2][2])
    #print(k[2][3])
    #print(s[2][3])
    #print(k[2][4])
    #print(s[2][4])
    #print(k[3][0])
    #print(s[3][0])
    #print(p[3])
    #print(k[3][1])
    #print(s[3][1])
    #print(k[3][2])
    #print(s[3][2])
    #print(k[4][0])
    #print(s[4][0])
    #print(p[4])
    #print(k[4][1])
    #print(s[4][1])
    #print(k[4][2])
    #print(s[4][2])
    #print(k[4][3])
    #print(s[4][3])
    #print(k[4][

if __name__ == '__main__':
    main()