def main():
    N, C = map(int, input().split())
    abcs = [list(map(int, input().split())) for _ in range(N)]
    abcs.sort()
    #print(abcs)
    #print(N, C)
    #print(abcs)
    #print(abcs[0][0])
    #print(abcs[0][1])
    #print(abcs[0][2])
    #print(abcs[1][0])
    #print(abcs[1][1])
    #print(abcs[1][2])
    #print(abcs[2][0])
    #print(abcs[2][1])
    #print(abcs[2][2])
    #print(abcs[3][0])
    #print(abcs[3][1])
    #print(abcs[3][2])
    #print(abcs[4][0])
    #print(abcs[4][1])
    #print(abcs[4][2])
    #print(abcs[5][0])
    #print(abcs[5][1])
    #print(abcs[5][2])
    #print(abcs[6][0])
    #print(abcs[6][1])
    #print(abcs[6][2])
    #print(abcs[7][0])
    #print(abcs[7][1])
    #print(abcs[7][2])
    #print(abcs[8][0])
    #print(abcs[8][1])
    #print(abcs[8][2])
    #print(abcs[9][0])
    #print(abcs[9][1])
    #print(abcs[9][2])
    #print(abcs[10][0])
    #print(abcs[10][1])
    #print(abcs[10][2])
    #print(abcs[11][0])
    #print(abcs[11][1])
    #print(abcs[11][2])
    #print(abcs[12][0])
    #print(abcs[12][1])
    #print(abcs[12][2])
    #print(abcs[13][0])
    #print(abcs[13][1])
    #print(abcs[13][2])
    #print(abcs[14][0])
    #print(abcs[14][1])
    #print

if __name__ == '__main__':
    main()