def solve():
    N,C = map(int, input().split())
    lst = []
    for i in range(N):
        lst.append(list(map(int, input().split())))
    print(lst)
    print(N,C)
    print(lst[0][0])
    print(lst[0][1])
    print(lst[0][2])
    print(lst[1][0])
    print(lst[1][1])
    print(lst[1][2])
    print(lst[2][0])
    print(lst[2][1])
    print(lst[2][2])
    print(lst[3][0])
    print(lst[3][1])
    print(lst[3][2])
    print(lst[4][0])
    print(lst[4][1])
    print(lst[4][2])
    print(lst[0][0])
    print(lst[0][1])
    print(lst[0][2])
    print(lst[1][0])
    print(lst[1][1])
    print(lst[1][2])
    print(lst[2][0])
    print(lst[2][1])
    print(lst[2][2])
    print(lst[3][0])
    print(lst[3][1])
    print(lst[3][2])
    print(lst[4][0])
    print(lst[4][1])
    print(lst[4][2])
    print(lst[0][0])
    print(lst[0][1])
    print(lst[0][2])
    print(lst[1][0])
    print(lst[1][1])
    print(lst[1][2])
    print(lst[2][0])
    print(lst[2][1])
    print(lst[2][2])
    print(lst[3][0])
    print(lst[3][1])
    print(lst[3][2])
    print(lst[4][0])
    print(lst[4][1])
    print(lst[4][2])
    print(lst[0][0])
    print(lst[0][1])
    print(lst[0][2])
    print(lst[1][0])
    print(lst[1][1])
    print(lst[1][2])
    print(lst[2][0])
    print(lst[2][1])
    print(lst[2][2])
    print(lst[3][0])
    print(lst[3][1])
    print(lst[3][2])

if __name__ == '__main__':
    solve()