def main():
    n = int(input())
    s = []
    for i in range(n):
        s.append(list(map(int,input().split())))
    # print(s)
    # s.sort(key=lambda x:x[0])
    # print(s)
    # s.sort(key=lambda x:x[1])
    # print(s)
    # s.sort(key=lambda x:x[2])
    # print(s)
    # s.sort(key=lambda x:x[0],reverse=True)
    # print(s)
    # s.sort(key=lambda x:x[1],reverse=True)
    # print(s)
    s.sort(key=lambda x:x[2],reverse=True)
    # print(s)
    # s.sort(key=lambda x:x[0],reverse=True)
    # print(s)
    # s.sort(key=lambda x:x[1],reverse=True)
    # print(s)
    # s.sort(key=lambda x:x[2],reverse=True)
    # print(s)
    # s.sort(key=lambda x:x[0])
    # print(s)
    # s.sort(key=lambda x:x[1])
    # print(s)
    # s.sort(key=lambda x:x[2])
    # print(s)
    # s.sort(key=lambda x:x[0],reverse=True)
    # print(s)
    # s.sort(key=lambda x:x[1],reverse=True)
    # print(s)
    # s.sort(key=lambda x:x[2],reverse=True)
    # print(s)
    # s.sort(key=lambda x:x[0])
    # print(s)
    # s.sort(key=lambda x:x[1])
    # print(s)
    # s.sort(key=lambda x:x[2])
    # print(s)
    # s.sort(key=lambda x:x[0],reverse=True)
    # print(s)
    # s.sort(key=lambda x:x[1],reverse=True)
    # print(s)
    # s.sort(key=lambda x:x[2],reverse=True)
    # print(s)
    # s.sort(key=lambda x:x[0])
    # print(s)
    # s.sort(key=lambda x:x[1])
    # print(s)
    # s.sort(key=lambda x:x[2])
    # print(s)
    # s.sort(key=lambda x:x[0],reverse=True)
    # print(s)
    # s.sort(key=lambda x:x[1],reverse=True)
    # print(s)
    # s.sort(key=lambda x:x[

if __name__ == '__main__':
    main()