def main():
    n = int(input())
    snuke = []
    for i in range(n):
        t, x, a = map(int, input().split())
        snuke.append([t, x, a])
    snuke.sort()
    #print(snuke)
    #t, x, a = map(int, input().split())
    #snuke.append([t, x, a])
    #snuke.sort()
    #print(snuke)
    #print(snuke[0][0], snuke[0][1], snuke[0][2])
    #print(snuke[1][0], snuke[1][1], snuke[1][2])
    #print(snuke[2][0], snuke[2][1], snuke[2][2])
    #print(snuke[3][0], snuke[3][1], snuke[3][2])
    #print(snuke[4][0], snuke[4][1], snuke[4][2])
    #print(snuke[5][0], snuke[5][1], snuke[5][2])
    #print(snuke[6][0], snuke[6][1], snuke[6][2])
    #print(snuke[7][0], snuke[7][1], snuke[7][2])
    #print(snuke[8][0], snuke[8][1], snuke[8][2])
    #print(snuke[9][0], snuke[9][1], snuke[9][2])
    #print(snuke[10][0], snuke[10][1], snuke[10][2])
    #print(snuke[11][0], snuke[11][1], snuke[11][2])
    #print(snuke[12][0], snuke[12][1], snuke[12][2])
    #print(snuke[13][0], snuke[13][1], snuke[13][2])
    #print(snuke[14][0], snuke[14][1], snuke[14][2])
    #print(snuke[15][0], snuke[15][1], snuke[15][2])

if __name__ == '__main__':
    main()