def solve():
    N,L,R = map(int,input().split())
    A = list(map(int,input().split()))
    #print(A)
    #print(N,L,R)
    #print(A[0],A[1],A[2],A[3],A[4])
    #print(A[N-1],A[N-2],A[N-3],A[N-4],A[N-5])
    #print(A[0],A[1],A[2],A[3],A[4])
    #print(A[N-1],A[N-2],A[N-3],A[N-4],A[N-5])
    #print(A[0],A[1],A[2],A[3],A[4])
    #print(A[N-1],A[N-2],A[N-3],A[N-4],A[N-5])
    #print(A[0],A[1],A[2],A[3],A[4])
    #print(A[N-1],A[N-2],A[N-3],A[N-4],A[N-5])
    #print(A[0],A[1],A[2],A[3],A[4])
    #print(A[N-1],A[N-2],A[N-3],A[N-4],A[N-5])
    #print(A[0],A[1],A[2],A[3],A[4])
    #print(A[N-1],A[N-2],A[N-3],A[N-4],A[N-5])
    #print(A[0],A[1],A[2],A[3],A[4])
    #print(A[N-1],A[N-2],A[N-3],A[N-4],A[N-5])
    #print(A[0],A[1],A[2],A[3],A[4])
    #print(A[N-1],A[N-2],A[N-3],A[N-4],A[N-5])
    #print(A[0],A[1],A[2],A[3],A[4])
    #print(A[N-1],A[N-2],A[N-3],A[N-4],A[N-5])
    #print(A[0

if __name__ == '__main__':
    solve()