def main():
    k = int(input())
    s = input()
    t = input()
    s = s[:4]
    t = t[:4]
    #print(s)
    #print(t)
    #print(k)
    #print(type(k))
    #print(type(s))
    #print(type(t))
    #print(type(int(s)))
    #print(type(int(t)))
    #print(int(s))
    #print(int(t))
    #print(type(s[0]))
    #print(type(t[0]))
    #print(type(s[1]))
    #print(type(t[1]))
    #print(type(s[2]))
    #print(type(t[2]))
    #print(type(s[3]))
    #print(type(t[3]))
    #print(type(s[4]))
    #print(type(t[4]))
    #print(s[0])
    #print(t[0])
    #print(s[1])
    #print(t[1])
    #print(s[2])
    #print(t[2])
    #print(s[3])
    #print(t[3])
    #print(s[4])
    #print(t[4])
    #print(s[0] == t[0])
    #print(s[1] == t[1])
    #print(s[2] == t[2])
    #print(s[3] == t[3])
    #print(s[4] == t[4])
    #print(s[0] == t[0] and s[1] == t[1] and s[2] == t[2] and s[3] == t[3] and s[4] == t[4])
    #print(int(s[0]) + int(s[1]) + int(s[2]) + int(s[3]) + int(s[4]))
    #print(int(t[0]) + int(t[1]) + int(t[2]) + int(t[3]) + int(t[4]))
    #print(int(s[0]) + int(s[1]) + int(s[2]) + int(s[3]) + int(s[4]) > int(t[0]) + int(t[1]) + int(t[2]) + int(t[3]) + int(t[4]))
    #print(int(s[0]) + int(s[1]) + int(s[2]) +

if __name__ == '__main__':
    main()