def main():
    K = int(input())
    S = input()
    T = input()
    #print(K, S, T)
    #print(type(K), type(S), type(T))
    #print(len(S), len(T))
    #print(S[0:4], S[4])
    #print(T[0:4], T[4])
    #print(S[0:4].count('1'))
    #print(S[0:4].count('2'))
    #print(S[0:4].count('3'))
    #print(S[0:4].count('4'))
    #print(S[0:4].count('5'))
    #print(S[0:4].count('6'))
    #print(S[0:4].count('7'))
    #print(S[0:4].count('8'))
    #print(S[0:4].count('9'))
    #print(S[0:4].count('1') + S[0:4].count('2') + S[0:4].count('3') + S[0:4].count('4') + S[0:4].count('5') + S[0:4].count('6') + S[0:4].count('7') + S[0:4].count('8') + S[0:4].count('9'))
    #print(T[0:4].count('1'))
    #print(T[0:4].count('2'))
    #print(T[0:4].count('3'))
    #print(T[0:4].count('4'))
    #print(T[0:4].count('5'))
    #print(T[0:4].count('6'))
    #print(T[0:4].count('7'))
    #print(T[0:4].count('8'))
    #print(T[0:4].count('9'))
    #print(T[0:4].count('1') + T[0:4].count('2') + T[0:4].count('3') + T[0:4].count('4') + T[0:4].count('5') + T[0:4].count('6') + T[0:4].count('7') + T[0:4].count('8') +

if __name__ == '__main__':
    main()