def main():
    # 读入数据
    N, C = map(int, input().split())
    #print(N, C)
    #print(type(N), type(C))
    #print(type(N) == int, type(C) == int)
    #print(type(N) == float, type(C) == float)
    #print(type(N) == str, type(C) == str)
    #print(type(N) == bool, type(C) == bool)
    #print(type(N) == list, type(C) == list)
    #print(type(N) == tuple, type(C) == tuple)
    #print(type(N) == set, type(C) == set)
    #print(type(N) == dict, type(C) == dict)
    #print(type(N) == complex, type(C) == complex)
    #print(type(N) == object, type(C) == object)
    #print(type(N) == frozenset, type(C) == frozenset)
    #print(type(N) == bytes, type(C) == bytes)
    #print(type(N) == bytearray, type(C) == bytearray)
    #print(type(N) == memoryview, type(C) == memoryview)
    #print(type(N) == str, type(C) == int)
    #print(type(N) == int, type(C) == str)
    #print(type(N) == str, type(C) == float)
    #print(type(N) == float, type(C) == str)
    #print(type(N) == str, type(C) == bool)
    #print(type(N) == bool, type(C) == str)
    #print(type(N) == str, type(C) == list)
    #print(type(N) == list, type(C) == str)
    #print(type(N) == str, type(C) == tuple)
    #print(type(N) == tuple, type(C) == str)
    #print(type(N) == str, type(C) == set)
    #print(type(N) == set, type(C) == str)
    #print(type(N) == str, type(C) == dict)
    #print(type(N) == dict, type(C) == str)
    #print(type(N) == str, type(C) == complex)
    #print(type(N) == complex, type(C) == str)
    #print(type(N) ==
