def coin(n,m,X,C,Y):
    #n次抛硬币，m种连胜奖金
    #X为n次抛硬币的结果
    #C为连胜奖金的条件
    #Y为连胜奖金的金额
    #X=[2,7,1,8,2,8]
    #C=[2,3,5]
    #Y=[10,1,5]
    #n=6
    #m=3
    #print(X)
    #print(C)
    #print(Y)
    #print(n,m)
    X=[int(i) for i in X]
    C=[int(i) for i in C]
    Y=[int(i) for i in Y]
    #print(X)
    #print(C)
    #print(Y)
    #print(n,m)
    #print(X[0])
    #print(C[0])
    #print(Y[0])
    #print(X[1])
    #print(C[1])
    #print(Y[1])
    #print(X[2])
    #print(C[2])
    #print(Y[2])
    #print(n,m)
    #print(X)
    #print(C)
    #print(Y)
    #print(n,m)
    #print(X[0])
    #print(C[0])
    #print(Y[0])
    #print(X[1])
    #print(C[1])
    #print(Y[1])
    #print(X[2])
    #print(C[2])
    #print(Y[2])
    #print(n,m)
    #print(X)
    #print(C)
    #print(Y)
    #print(n,m)
    #print(X[0])
    #print(C[0])
    #print(Y[0])
    #print(X[1])
    #print(C[1])
    #print(Y[1])
    #print(X[2])
    #print(C[2])
    #print(Y[2])
    #print(n,m)
    #print(X)
    #print(C)
    #print(Y)
    #print(n,m)
    #print(X[0])
    #print(C[0])
    #print(Y[0])
    #print(X[1])
    #print(C[1])
    #print(Y
