def dfs(v, p):
    global ans
    ans.append(v)
    for u in G[v]:
        if u != p:
            dfs(u, v)
            ans.append(v)
            #print(ans)
            #print("v=%d"%v)
            #print("u=%d"%u)
            #print("p=%d"%p)
            #print("G[v]=")
            #print(G[v])
            #print("G[u]=")
            #print(G[u])
            #print("G[p]=")
            #print(G[p])
            #print("ans=")
            #print(ans)
            #print("ans[-1]=")
            #print(ans[-1])
            #print("ans[-2]=")
            #print(ans[-2])
            #print("ans[-3]=")
            #print(ans[-3])
            #print("ans[-4]=")
            #print(ans[-4])
            #print("ans[-5]=")
            #print(ans[-5])
            #print("ans[-6]=")
            #print(ans[-6])
            #print("ans[-7]=")
            #print(ans[-7])
            #print("ans[-8]=")
            #print(ans[-8])
            #print("ans[-9]=")
            #print(ans[-9])
            #print("ans[-10]=")
            #print(ans[-10])
            #print("ans[-11]=")
            #print(ans[-11])
            #print("ans[-12]=")
            #print(ans[-12])
            #print("ans[-13]=")
            #print(ans[-13])
            #print("ans[-14]=")
            #print(ans[-14])
            #print("ans[-15]=")
            #print(ans[-15])
            #print("ans[-16]=")
            #print(ans[-16])
            #print("ans[-17]=")
            #print(ans[-17])
            #print("ans[-18]=")
            #print(ans[-18])
            #print("ans[-19]=")
            #print(ans[-19])
            #print("ans[-20]=")
            #print(ans[-20])
            #print("ans[-21]=")
            #print(ans[-21])
            #print("ans[-22]=")
            #print(ans[-22])
            #print("ans[-23]=")
            #print(ans[-23])
            #print("ans

if __name__ == '__main__':
    dfs()