def main():
    N, K = map(int, input().split())
    A = list(map(int, input().split()))
    #print(N, K)
    #print(A)
    #print(N % A[0])
    #print(N % A[1])
    #print(N % A[2])
    #print(N % A[3])
    #print(N % A[4])
    #print(N % A[5])
    #print(N % A[6])
    #print(N % A[7])
    #print(N % A[8])
    #print(N % A[9])
    #print(N % A[10])
    #print(N % A[11])
    #print(N % A[12])
    #print(N % A[13])
    #print(N % A[14])
    #print(N % A[15])
    #print(N % A[16])
    #print(N % A[17])
    #print(N % A[18])
    #print(N % A[19])
    #print(N % A[20])
    #print(N % A[21])
    #print(N % A[22])
    #print(N % A[23])
    #print(N % A[24])
    #print(N % A[25])
    #print(N % A[26])
    #print(N % A[27])
    #print(N % A[28])
    #print(N % A[29])
    #print(N % A[30])
    #print(N % A[31])
    #print(N % A[32])
    #print(N % A[33])
    #print(N % A[34])
    #print(N % A[35])
    #print(N % A[36])
    #print(N % A[37])
    #print(N % A[38])
    #print(N % A[39])
    #print(N % A[40])
    #print(N % A[41])
    #print(N % A[42])
    #print(N % A[43])
    #print(N % A[44])
    #print(N % A[45])
    #print(N % A[46])
    #print(N % A[47])
    #print(N % A[48])
    #print(N % A[49])
    #print(N % A[50])
    #print(N
