def main():
    N, Q = map(int, input().split())
    S = input()
    #print(N, Q, S)
    #print(len(S))
    #print(S[0])
    #print(S[0:1])
    #print(S[0:2])
    #print(S[0:3])
    #print(S[0:4])
    #print(S[0:5])
    #print(S[0:6])
    #print(S[0:7])
    #print(S[0:8])
    #print(S[0:9])
    #print(S[1:2])
    #print(S[1:3])
    #print(S[1:4])
    #print(S[1:5])
    #print(S[1:6])
    #print(S[1:7])
    #print(S[1:8])
    #print(S[1:9])
    #print(S[2:3])
    #print(S[2:4])
    #print(S[2:5])
    #print(S[2:6])
    #print(S[2:7])
    #print(S[2:8])
    #print(S[2:9])
    #print(S[3:4])
    #print(S[3:5])
    #print(S[3:6])
    #print(S[3:7])
    #print(S[3:8])
    #print(S[3:9])
    #print(S[4:5])
    #print(S[4:6])
    #print(S[4:7])
    #print(S[4:8])
    #print(S[4:9])
    #print(S[5:6])
    #print(S[5:7])
    #print(S[5:8])
    #print(S[5:9])
    #print(S[6:7])
    #print(S[6:8])
    #print(S[6:9])
    #print(S[7:8])
    #print(S[7:9])
    #print(S[8:9])
    #print(S[0:1])
    #print(S[1:2])
    #print(S[2:3])
    #print(S[3:4])
    #print(S[4:5])
    #print(S[5:6])

if __name__ == '__main__':
    main()