def resolve():
    # N, M = map(int, input().split())
    # AB = []
    # for _ in range(M):
    #     AB.append(list(map(int, input().split())))
    N, M = 4, 5
    AB = [[2, 4], [1, 2], [2, 3], [1, 3], [3, 4]]
    print(AB)
    # AB = sorted(AB, key=lambda x: x[1])
    # print(AB)
    # AB = sorted(AB, key=lambda x: x[0])
    # print(AB)
    # AB = sorted(AB, key=lambda x: x[1])
    # print(AB)
    # AB = sorted(AB, key=lambda x: x[0])
    # print(AB)
    # AB = sorted(AB, key=lambda x: x[1])
    # print(AB)
    # AB = sorted(AB, key=lambda x: x[0])
    # print(AB)
    # AB = sorted(AB, key=lambda x: x[1])
    # print(AB)
    # AB = sorted(AB, key=lambda x: x[0])
    # print(AB)
    # AB = sorted(AB, key=lambda x: x[1])
    # print(AB)
    # AB = sorted(AB, key=lambda x: x[0])
    # print(AB)
    # AB = sorted(AB, key=lambda x: x[1])
    # print(AB)
    # AB = sorted(AB, key=lambda x: x[0])
    # print(AB)
    # AB = sorted(AB, key=lambda x: x[1])
    # print(AB)
    # AB = sorted(AB, key=lambda x: x[0])
    # print(AB)
    # AB = sorted(AB, key=lambda x: x[1])
    # print(AB)
    # AB = sorted(AB, key=lambda x: x[1])
    # print(AB)
    # AB = sorted(AB, key=lambda x: x[0])
    # print(AB)
    # print(AB)
    # print(sorted(AB, key=lambda x: x[0]))
    # print(sorted(AB, key=lambda x: x[1]))
