def main():
    print('请输入K值：')
    k = int(input())
    print('k =',k)
    print('请输入N值：')
    n = int(input())
    print('n =',n)
    print('请输入M值：')
    m = int(input())
    print('m =',m)
    print('请输入P值：')
    p = int(input())
    print('p =',p)
    print('请输入Q值：')
    q = int(input())
    print('q =',q)
    print('请输入R值：')
    r = int(input())
    print('r =',r)
    print('请输入S值：')
    s = int(input())
    print('s =',s)
    print('请输入T值：')
    t = int(input())
    print('t =',t)
    print('请输入U值：')
    u = int(input())
    print('u =',u)
    print('请输入V值：')
    v = int(input())
    print('v =',v)
    print('请输入W值：')
    w = int(input())
    print('w =',w)
    print('请输入X值：')
    x = int(input())
    print('x =',x)
    print('请输入Y值：')
    y = int(input())
    print('y =',y)
    print('请输入Z值：')
    z = int(input())
    print('z =',z)
    print('请输入A值：')
    a = int(input())
    print('a =',a)
    print('请输入B值：')
    b = int(input())
    print('b =',b)
    print('请输入C值：')
    c = int(input())
    print('c =',c)
    print('请输入D值：')
    d = int(input())
    print('d =',d)
    print('请输入E值：')
    e = int(input())
    print('e =',e)
    print('请输入F值：')
    f = int(input())
    print('f =',f)
    print('请输入G值：')
    g = int(input())
    print('g =',g)
    print('请输入H值：')
    h = int(input())
    print('h =',h)
    print('请输入I值：')
    i = int(input())
