def main():
    n = int(input())
    edges = []
    for _ in range(n-1):
        edges.append(list(map(int, input().split())))
    #print(edges)
    #print(edges[0][0])
    #print(edges[0][1])
    #print(edges[0][0] == 1)
    #print(edges[0][1] == 1)
    #print(edges[0][0] == 2)
    #print(edges[0][1] == 2)
    #print(edges[0][0] == 3)
    #print(edges[0][1] == 3)
    #print(edges[0][0] == 4)
    #print(edges[0][1] == 4)
    #print(edges[0][0] == 5)
    #print(edges[0][1] == 5)
    #print(edges[0][0] == 6)
    #print(edges[0][1] == 6)
    #print(edges[0][0] == 7)
    #print(edges[0][1] == 7)
    #print(edges[0][0] == 8)
    #print(edges[0][1] == 8)
    #print(edges[0][0] == 9)
    #print(edges[0][1] == 9)
    #print(edges[0][0] == 10)
    #print(edges[0][1] == 10)
    #print(edges[0][0] == 11)
    #print(edges[0][1] == 11)
    #print(edges[0][0] == 12)
    #print(edges[0][1] == 12)
    #print(edges[0][0] == 13)
    #print(edges[0][1] == 13)
    #print(edges[0][0] == 14)
    #print(edges[0][1] == 14)
    #print(edges[0][0] == 15)
    #print(edges[0][1] == 15)
    #print(edges[0][0] == 16)
    #print(edges[0][1] == 16)
    #print(edges[0][0] == 17)
    #print(edges[0][1] == 17)
    #print

if __name__ == '__main__':
    main()