def main():
    N, K, Q = map(int, input().split())
    A = list(map(int, input().split()))
    L = list(map(int, input().split()))
    #print("N: {0}, K: {1}, Q: {2}".format(N, K, Q))
    #print("A: {0}".format(A))
    #print("L: {0}".format(L))
    #print("N: {0}, K: {1}, Q: {2}".format(N, K, Q))
    #print("A: {0}".format(A))
    #print("L: {0}".format(L))
    #print("N: {0}, K: {1}, Q: {2}".format(N, K, Q))
    #print("A: {0}".format(A))
    #print("L: {0}".format(L))
    #print("N: {0}, K: {1}, Q: {2}".format(N, K, Q))
    #print("A: {0}".format(A))
    #print("L: {0}".format(L))
    #print("N: {0}, K: {1}, Q: {2}".format(N, K, Q))
    #print("A: {0}".format(A))
    #print("L: {0}".format(L))
    #print("N: {0}, K: {1}, Q: {2}".format(N, K, Q))
    #print("A: {0}".format(A))
    #print("L: {0}".format(L))
    #print("N: {0}, K: {1}, Q: {2}".format(N, K, Q))
    #print("A: {0}".format(A))
    #print("L: {0}".format(L))
    #print("N: {0}, K: {1}, Q: {2}".format(N, K, Q))
    #print("A: {0}".format(A))
    #print("L: {0}".format(L))
    #print("N: {0}, K: {1}, Q: {2}".format(N, K, Q))
    #print("A: {0}".format(A))
    #print("L: {0}".format(L))
    #print("N: {0}, K: {
