def main():
    n, k = map(int, input().split())
    a = list(map(int, input().split()))
    xy = []
    for i in range(n):
        xy.append(list(map(int, input().split())))
    ans = 0
    # print(n, k)
    # print(a)
    # print(xy)
    # print(xy[0])
    # print(xy[0][0])
    # print(xy[0][1])
    # print(xy[1][0])
    # print(xy[1][1])
    # print(xy[2][0])
    # print(xy[2][1])
    # print(xy[3][0])
    # print(xy[3][1])
    # print(xy[4][0])
    # print(xy[4][1])
    # print(xy[5][0])
    # print(xy[5][1])
    # print(xy[6][0])
    # print(xy[6][1])
    # print(xy[7][0])
    # print(xy[7][1])
    # print(xy[8][0])
    # print(xy[8][1])
    # print(xy[9][0])
    # print(xy[9][1])
    # print(xy[10][0])
    # print(xy[10][1])
    # print(xy[11][0])
    # print(xy[11][1])
    # print(xy[12][0])
    # print(xy[12][1])
    # print(xy[13][0])
    # print(xy[13][1])
    # print(xy[14][0])
    # print(xy[14][1])
    # print(xy[15][0])
    # print(xy[15][1])
    # print(xy[16][0])
    # print(xy[16][1])
    # print(xy[17][0])
    # print(xy[17][1])
    # print(xy[18][0])
    # print(xy[18][1])
    # print(xy[19][0])
    # print(xy[19][1])
    # print(xy[20][0])
    # print(xy[20][1])
    # print(xy[21][0])
    # print(xy[21][1])
    # print(xy[22][0])
    # print(xy[22][1])
    # print(xy[23][0])
